### ISSUE TITLE
[SINHALA] Link to USE documentation is broken

### ISSUE THREAD

**Issue by pathumego** [MicrosoftDocs/typography-issues#100]
Link to USE spec the introduction is broken &lt;https://docs.microsoft.com/en-us/typography/OpenTypeDev/USE/&gt;
Should direct to https://docs.microsoft.com/en-us/typography/script-development/use instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b600ff4-6e07-bce1-ac22-14bbecfa9ea4
* Version Independent ID: f9de5cd2-043e-5e2b-33d7-7c27b10f2928
* Content: [Creating and Supporting OpenType Fonts for Sinhala Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/sinhala)
* Content Source: [typographydocs/script-development/sinhala.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/sinhala.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment]
Closing as Fixed.
