### ISSUE TITLE
Duda fuente gabriola

### ISSUE THREAD

**Issue by josquinet** [MicrosoftDocs/typography-issues#1004]
---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para learn.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 1265e0b5-5b81-c5e5-7d24-fc9d79aecbe4
* Version Independent ID: 98675a4c-4f0f-cd2f-be9e-297aecd1d15b
* Content: [Gabriola font family - Typography](https://learn.microsoft.com/es-es/typography/font-list/gabriola#products-that-supply-this-font)
* Content Source: [typographydocs/font-list/gabriola.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/gabriola.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
This is not possible at present, but we (Tiro Typeworks, the designers of Gabriola) hope to be able to offer such licenses in future.

Esto no es posible en la actualidad, pero nosotros (Tiro Typeworks, los diseñadores de Gabriola) esperamos poder ofrecer dichas licencias en el futuro.

**Comment by alib-ms** [comment]
Gabriola font is only available with Microsoft products and services such as Windows and Office applications.
