### ISSUE TITLE
Rockwell Nova For Some Reason Doesn’t Have OpenType Features In The Pan-European Supplemental Fonts

### ISSUE THREAD

**Issue by Sayhone721** [MicrosoftDocs/typography-issues#1006]
For example, the kerning.
![image](https://user-images.githubusercontent.com/92538982/212705547-d50a319f-e671-426f-baea-33db7c37af20.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b5dc8876-0b02-839f-f13c-ab7d19824443
* Version Independent ID: 8f21fec9-ed92-3eda-a6d7-78e1f1112499
* Content: [Rockwell Nova font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/rockwell-nova)
* Content Source: [typographydocs/font-list/rockwell-nova.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/rockwell-nova.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Thank you for reporting this issue. I will have this issue corrected in the upcoming release.

**Comment by alib-ms** [comment]
Fixed, the picture below shows kerning improvements in two weights. However, similar improvements are made to all the weights of the family. 
![image](https://user-images.githubusercontent.com/36778811/216684019-06a86bec-bafb-4773-9ed2-fbf538e663f0.png)

We have also updated the currency symbol range. The picture below shows improvements for various currency symbols previously shown via font fallback.  
![image](https://user-images.githubusercontent.com/36778811/216684418-1dcf5b83-5f3d-45ab-9df6-3a7493b149be.png)

Updated fonts will be available with the next Windows feature update.

**Comment by Sayhone721** [comment]
This has nothing to do with Rockwell Nova, but the original Rockwell isn't on my system. Same with other fonts like Berlin Sans, Stencil, ITC Snap, Garamond, and Century Gothic. I had to do an operation reinstall so that's why they used to be here, but not anymore. What should I do?

**Comment by alib-ms** [comment]
If you encounter any unexpected missing fonts, please utilize the Windows Feedback Hub tool to report the issue.
