### ISSUE TITLE
Feature tags are interpreted as HTML tags

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#101]
Feature tags are sometimes written with angle brackets instead of quotation marks, so they are interpreted as HTML tags and are not visible. For example, this page says “Only one glyph per cluster can be reordered using .” where it should say “Only one glyph per cluster can be reordered using 'pref'.”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 194a6d3c-4137-46e9-3a4b-44b990200986
* Version Independent ID: a0c8e788-5228-aa28-670e-3ba1ac3faecd
* Content: [Creating and supporting OpenType fonts for the Universal Shaping Engine - Typography](https://docs.microsoft.com/en-us/typography/script-development/use)
* Content Source: [typographydocs/script-development/use.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/use.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment]
Closing as Fixed.
