### ISSUE TITLE
Lcaron/lcaron in Arial Unicode is the wrong form

### ISSUE THREAD

**Issue by vennjadin** [MicrosoftDocs/typography-issues#1010]
<img width="1624" alt="Screenshot 2023-02-03 at 12 22 30" src="https://user-images.githubusercontent.com/94799122/216591399-776f1674-01b3-4fa5-90ef-fd53e16af1e3.png">

https://www.setuptype.com/x/cod/letters/lcaron

The Lcaron characters uses the wrong form. See link for correct one.

**Comment by alib-ms** [comment]
The Arial Unicode MS font does not ship with Microsoft products anymore.  You probably want to reach out to Monotype, the distributor of this font, to get this issue addressed.
