### ISSUE TITLE
Friendly name: Flattened ascent forms

### ISSUE THREAD

**Issue by schriftgestalt** [MicrosoftDocs/typography-issues#1013]
From the description of the feature, to me "Flattened a**c**cent forms" would makes more sense. Because the accents are flattened, not the ascenders.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb16259e-1f7c-4e96-02b8-f692eb3e77e7
* Version Independent ID: eab1b2c5-0209-ccdf-b898-bbc5b5dbbe0f
* Content: [Registered features, f-j (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/features_fj)
* Content Source: [typographydocs/opentype/spec/features_fj.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_fj.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
Agreed. That looks like a typo.

**Comment by khaledhosny** [comment]
In case anyone couldn’t see it like me, the current text says ”ascent” with an “s” instead of ”accent”.

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
