### ISSUE TITLE
Minor word duplication

### ISSUE THREAD

**Issue by mekkablue** [MicrosoftDocs/typography-issues#1014]
In the **usWinAscent** description, there is a sentence that starts like:

> **Also**, this clipping behavior **also** interacts...

One ‘also’ is superfluous, I think.

---
#### Document details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ae9457c-0d3d-c137-588b-81d54a086f07
* Version Independent ID: 658c6d22-b9d1-1007-9cdb-6898911c9c75
* Content: [OS/2 - OS/2 and Windows metrics table (OpenType 1.9) - Typography](https://learn.microsoft.com/en-gb/typography/opentype/spec/os2)
* Content Source: [typographydocs/opentype/spec/os2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/os2.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.
