### ISSUE TITLE
Nobody answers for the vendor ID registration

### ISSUE THREAD

**Issue by ToSupply** [MicrosoftDocs/typography-issues#1018]
Hi,

We’re trying to register our type foundry vendor ID but nobody answers to the mail address indicated address: mstwsite@microsoft.com.

Oddly, we got one answer to a question but then the communication stopped.
We tried with 2 of our mail adresses and it’s been a week with no answer.
Our requested ID doesn’t appear on the vendors page even tough all informations have been provided.

Could you provide a workaround?
Thanks in advance for your help.
Best

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0a1c6588-f887-46ea-8f19-aed067e6c0d5
* Version Independent ID: 76804d51-3c1a-761f-48ea-b6e176aaf286
* Content: [Register as a font vendor - Typography](https://learn.microsoft.com/en-us/typography/vendors/register)
* Content Source: [typographydocs/vendors/register.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/vendors/register.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Hi

Sorry about this. What is your vendor ID request so I can check on my end.

**Comment by ToSupply** [comment]
Hi,
Thank you very much for your answer!

Vendor ID
ToSp

Foundry Name
ToSupply

E-mail Address
***@***.*** ***@***.***>

Website
www.t-o.supply <http://www.t-o.supply/>

Let me know if you need anything else.
Best


ToStudio
ch	Sébeillon 1, 1004 Lausanne
+41	79 583 69 23
www.	t-o.studio
 <https://t-o.studio/>

**Comment by alib-ms** [comment]
Got it. I am checking will get it done.

**Comment by ToSupply** [comment]
Thanks
