### ISSUE TITLE
One of the OpenType cmap table format 4 examples appears to have an errant value

### ISSUE THREAD

**Issue by rsheeter** [MicrosoftDocs/typography-issues#1019]
In https://learn.microsoft.com/en-us/typography/opentype/spec/cmap#format-4-segment-mapping-to-delta-values the following example is given:

| Field | Value |
| -- | -- |
| segCountX2: | 8 | 
| searchRange: | 8 |
| entrySelector: | 4 |
| rangeShift: | 0 |   |
| endCode: | 20 90 480 0xffff |
| reservedPad: | 0 | 
| startCode: | 10 30 153 0xffff |
| idDelta: | -9 -18 -80 1 | 
| idRangeOffset: | 0 0 0 0 |

The computation of entrySelector is noted to be "Log2 of the maximum power of 2 less than or equal to segCount (log2(searchRange/2), which is equal to floor(log2(segCount)))". That seems to give me 2, not 4.

Context: https://github.com/googlefonts/fontations/pull/275#discussion_r1135360353

**Comment by PeterConstable** [comment]
That's a **very** old typo, dating at least to the TrueType 1.66 spec.

**Comment by Lorp** [comment]
![image](https://github.com/MicrosoftDocs/typography-issues/assets/587440/daee17da-4289-488b-b500-e12065e7e5ab)

Microsoft Corporation Version 1.00

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
