### ISSUE TITLE
Contourless glyphs with instructions

### ISSUE THREAD

**Issue by apodtele** [MicrosoftDocs/typography-issues#1020]
The [specs](https://learn.microsoft.com/en-us/typography/opentype/spec/glyf#simple-glyph-description) are very clear that zero contours are legal. It is obvious that such glyphs cannot have any `endPtsOfContours`, `flags`, or `Coordinates`. What about `instructions` though? It seems to be legal to instruct contourless glyphs. I do not have examples however. All data are usually omitted.

*The question really is whether `instructionLength` is a required, optional, or illegal field in the contourless glyphs?*

The composite contourless glyphs might be instructed too but that is umambiguously specified by `WE_HAVE_INSTRUCTIONS`. Could one instruct phantom points in contourless glyphs? Or what would be other purposes? These are separate questions.

**Comment by PeterCon** [comment]
It wouldn't have occurred to me that anyone might interpret the spec as implying that the `instructionLength` field is either optional or illegal in _any_ case.

**Comment by PeterCon** [comment]
I would think

>If a glyph has zero contours, it need not have any glyph data.

means that there's _no_ glyph data, not even the glyph header values (hence in loca the offset for this glyph and for the next glyph are the same).

But if there is _any_ glyph data (the loca offset for the next glyph is grearter than the offset for this glyph), then I would interpret either Apple's spec or the OT spec as implying that there must be a minimum of 12 bytes of data: the header fields, plus the `instructionLength` field.

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
