### ISSUE TITLE
Berlin Sans Isn't On My Windows 11 Computer

### ISSUE THREAD

**Issue by Sayhone721** [MicrosoftDocs/typography-issues#1021]
![Screenshot (1)](https://user-images.githubusercontent.com/92538982/226076329-b990329d-0482-4a5b-974e-f3b3d44dc64b.png)
There's also some other fonts that aren't on there like Arial Rounded, Gill Sans, Rockwell, Stancil, Broadway, and Agency FB. What is going on?! I also found out that most of those fonts are standard fonts. Why is Microsoft removing standard fonts on some computers?

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ea00eecc-6816-77be-6d53-a910e47d279e
* Version Independent ID: df6b0b98-073d-84bc-0f94-8e579aa0ebbb
* Content: [Berlin Sans FB font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/berlin-sans-fb)
* Content Source: [typographydocs/font-list/berlin-sans-fb.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/berlin-sans-fb.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
This font ships with Office. As noted on the [Berlin Sans FB font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/berlin-sans-fb) page
"This typeface is available within Office applications. For more information visit this [page.](https://support.office.com/en-us/article/cloud-fonts-in-office-f7b009fe-037f-45ed-a556-b5fe6ede6adb)"

**Comment by Sayhone721** [comment]
I think the reason why I don't have it is because I don't have Office applications.

**Comment by kenmcd** [comment]
> I think the reason why I don't have it is because I don't have the Windows 365 subscription. But they used to be in my system, (I had to do an operating reinstall), and I don't think I used to have the subscription _before_ the OS reinstall, so I don't know why I don't have them this time.

The fonts are installed into the Windows Fonts folder when Office 2007, 2010, 2013, 2016, 2019, etc. is installed.
Don't need an M365 subscription to install.

Always back-up your fonts folders before re-installing the OS.

**Comment by Sayhone721** [comment]
I didn't know I had to back up those fonts. I never had to deal with this before.

**Comment by Sayhone721** [comment]
And I have Microsoft Office (365) on my computer.

**Comment by kenmcd** [comment]
> And I have Microsoft Office (365) on my computer.

When I installed Office 365 on a Windows 11 system, those fonts were installed in the main Windows Fonts folder.
C:\Windows\Fonts\   

Files are:
- BRLNSB.TTF
- BRLNSDB.TTF
- BRLNSR.TTF

**Comment by Sayhone721** [comment]
That is weird. How come *I* don't have them?

**Comment by FontBoss** [comment]
aka.ms/officefonts lists the fonts that are available within Office apps. I realize that's not helpful if you want to use the fonts outside Office. 

The actual fonts installed locally can vary depending on the Office components installed and language options. My guess is that this one only gets installed with Publisher.

**Comment by Sayhone721** [comment]
What is Publisher?

**Comment by alib-ms** [comment]
https://www.microsoft.com/en-us/microsoft-365/publisher

**Comment by Sayhone721** [comment]
I don't remember having that.

**Comment by Sayhone721** [comment]
And I never had Office components.

**Comment by Sayhone721** [comment]
@alib-ms, this is off topic, but is sending system fonts via email, installing them on a computer, and then using them illegal? I was trying to search that on Google, but it didn't say anything.

**Comment by Sayhone721** [comment]
@kenmcd, is it illegal to send system fonts with email, and using them? If it isn't, can you send me the system fonts?

**Comment by tiroj** [comment]
Fonts are distributed and used under license. Fonts bundled with Microsoft products such as Window and Office etc. or made available through the MS cloud service are distributed and used under the licenses for those products and services. Among other things, these licenses prohibit redistribution and modification of the fonts. You can’t send someone the fonts via email or any other channel because that would constitute redistribution, and you do not have a distribution license.

**Comment by Sayhone721** [comment]
@tiroj, thanks for explaining. I was thinking that too, but I just wanted to make sure I was right.

**Comment by Sayhone721** [comment]
Apparently, the reason why I don't have those Office fonts is because when you wipe out your computer, those fonts wouldn't get installed.

**Comment by alib-ms** [comment]
If you encounter any unexpected missing fonts, please utilize the Windows Feedback Hub tool to report the issue.
