### ISSUE TITLE
ClearType RWGB pixel layout support

### ISSUE THREAD

**Issue by keppycs** [MicrosoftDocs/typography-issues#1022]
LG's new OLED panel (LW270AHQ-ERG1) uses an RWGB pixel layout, instead of a standard RGB one. ClearType doesn't work well with this new sub pixel layout.

Sorry if I'm posting this in the wrong place. Windows Support sent me here.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bf2300b8-71e0-a6fe-b12f-f47b2b9564c1
* Version Independent ID: e771c103-3be0-7747-0084-be7bdef7bf63
* Content: [Microsoft ClearType - Typography](https://learn.microsoft.com/en-us/typography/cleartype/)
* Content Source: [typographydocs/cleartype/index.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/cleartype/index.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Hi,

AFAIK, we don’t support nor test any other pixel layouts.

**Comment by PeterCon** [comment]
This issue has to do with text display issues in features in Windows, not the fonts themselves. Such feedback should be submitted via the [Windows Feedback Hub app](https://support.microsoft.com/en-us/windows/send-feedback-to-microsoft-with-the-feedback-hub-app-f59187f8-8739-22d6-ba93-f66612949332).
