### ISSUE TITLE
Font infringement

### ISSUE THREAD

**Issue by yarrrrrrrrrrrrra** [MicrosoftDocs/typography-issues#1023]
[ I bought Microsoft 365 for business in China, and I assume that I can use the Microsoft provided fonts for commercial use.  However, while I was using the Microsoft Yahei on commerical outputs, I received a lawyer letter from Founder, claiming that my use of their fonts has constituted infringement and additional payment is required. How come? Please explain! ]

---
#### 文档详细信息

⚠ *请勿编辑此部分。 learn.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 887c10e0-63c5-06d9-38fc-3c844c0d308d
* Version Independent ID: fbc7a8c5-a8bd-611d-0758-1b56e5d5a03a
* Content: [Microsoft YaHei font family - Typography](https://learn.microsoft.com/zh-cn/typography/font-list/microsoft-yahei)
* Content Source: [typographydocs/font-list/microsoft-yahei.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/microsoft-yahei.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Hi,

We created a FAQ to help our customers understand usage of fonts shipped with Windows and redistribution rights. 
[Font redistribution FAQ - Typography | Microsoft Learn](https://learn.microsoft.com/en-us/typography/fonts/font-faq)

**Comment by yarrrrrrrrrrrrra** [comment]
> 
Hi,

Microsoft Yahei did not specifically licensed for non-commercial use, but I still got the lawyer letter from its designer Founder claiming that I infringed their copyright. I was quiet confusing.
![image](https://user-images.githubusercontent.com/128477207/226782449-3c3daa1f-9439-423a-9354-decc281dfde2.png)

**Comment by alib-ms** [comment]
Windows 11 [EULA](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.microsoft.com%2Fen-us%2FUseTerms%2FOEM%2FWindows%2F11%2FUseTerms_OEM_Windows_11_English.htm&data=05%7C01%7Calib%40microsoft.com%7Ca8980e5ec08740caf7e308db62313b2e%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638211735829097090%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FHBg9H1WpkrHUWutQmxbjPI7L8wi3XVKgskLEh%2FerDY%3D&reserved=0) is posted here. 

PS: I'm not an attorney, therefore, can't offer legal advice.
