### ISSUE TITLE
Full list of symbols please

### ISSUE THREAD

**Issue by valterekholm** [MicrosoftDocs/typography-issues#1024]
Hello. I need a table/list with all symbols in this font, so I can copy some funny symbols from it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: a897815e-652e-d4ae-8f3d-979ee1ec0fcb
* Version Independent ID: 575e9a80-3e10-d850-eea7-d3c921779f82
* Content: [Segoe UI Emoji font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/segoe-ui-emoji)
* Content Source: [typographydocs/font-list/Segoe-UI-Emoji.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/Segoe-UI-Emoji.md)
* Product: **typography**
* GitHub Login: @alib
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
You can use the Character Map app in Windows to see characters supported in a font. (This app has a limitation in that it only supports Unicode code points U+0000 to U+FFFF.) There are other tools you can find online for displaying all of the characters supported in a font, such as [BabelMap](https://www.babelstone.co.uk/Software/BabelMap.html) or [ViewGlyph](https://www.bing.com/ck/a?!&&p=c66251e40c8c5293JmltdHM9MTY4MTA4NDgwMCZpZ3VpZD0wZDQxMmZhNS1jMDhkLTZmZjItMWY0YS0zZDY5YzEzNzZlNzUmaW5zaWQ9NTE4OQ&ptn=3&hsh=3&fclid=0d412fa5-c08d-6ff2-1f4a-3d69c1376e75&psq=viewglyph&u=a1aHR0cHM6Ly9zY3JpcHRzLnNpbC5vcmcvY21zL3NjcmlwdHMvcGFnZS5waHA_c2l0ZV9pZD1ucnNpJmlkPVZpZXdHbHlwaF9ob21l&ntb=1).

**Comment by myfonj** [comment]
Good tools for inspecting font features and glyph support are currently also web apps as:
- https://wakamaifondue.com/
- https://fontdrop.info/

**Comment by kenmcd** [comment]
**Microsoft Segoe UI Emoji - all - Emojipedia**
https://emojipedia.org/microsoft/show_all/#more
