### ISSUE TITLE
Font typography is very hard locate appropriate symbols for math and othersciences.

### ISSUE THREAD

**Issue by innovatejb** [MicrosoftDocs/typography-issues#1025]
Typography is extremely hard to use. if you are looking for a particular symbol. The entire symbol set of a font should be easily accessible.  I spent far too much time hunting for appropriate math symbols.  The math symbols were inadequate for anyone doing scientific work.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 229b25bf-55be-c1cf-1c5c-199b58ffc496
* Version Independent ID: 73018ddd-a37b-7abc-5ccf-cef0663aa721
* Content: [Symbol font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/symbol?source=recommendations)
* Content Source: [typographydocs/font-list/symbol.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/symbol.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by MurraySargent** [comment]
The old symbol font shouldn't be used for math. All of its symbols and many, many more are in Unicode. The Cambria Math font has most of the Unicode math symbols as does Segoe UI Symbol. For documentation, see [Unicode Technical Report #25](https://unicode.org/reports/tr25/tr25-13.pdf). You can also search for symbols on the web by name. For example, search for Unicode integral symbol.

**Comment by alib-ms** [comment]
Please use the "Feedback Hub" app in Windows to help us improve customer experience.
