### ISSUE TITLE
Mistake for font name of "Korean Supplemental Fonts"

### ISSUE THREAD

**Issue by whaoran** [MicrosoftDocs/typography-issues#1026]
Please help double check the column "File Name" and "Version" for these four Korean fonts: Batang, Dotum, Gulim and Gungsuh.
Some obvious mistakes can be found here.
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 258ad530-9159-5b54-6252-e4bd8ec33e4b
* Version Independent ID: 079dca33-ba4b-7349-4a91-0a99ecdf3d2c
* Content: [Font List Windows 11 - Typography](https://learn.microsoft.com/en-us/typography/fonts/windows_11_font_list)
* Content Source: [typographydocs/fonts/Windows_11_Font_List.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/fonts/Windows_11_Font_List.md)
* Product: **typography**
* GitHub Login: @alib
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Thank you will do.

**Comment by alib-ms** [comment]
Hi, Can you please help me understand, what seems to be the issue?

**Comment by kenmcd** [comment]
Probably does not understand that multiple TTF fonts can be in one TTC file.
And thus thinks the file names are wrong.
All looks correct to me.

**Comment by alib-ms** [comment]
Thank you [kenmcd](https://github.com/kenmcd) for confirming all looks good.
