### ISSUE TITLE
Stylistic sets are not GSUB-exclusive

### ISSUE THREAD

**Issue by khaledhosny** [MicrosoftDocs/typography-issues#1028]
The text of the feature registry of stylistic set features makes repeated mentions of GSUB table and gives the impression that stylistic set are only for glyph substitutions and not for positioning. Fonts do exist in the wild that have GPOS stylistic sets, and testing shows that layout engines correctly apply them. Many applications does not seem to process featureParams for GPOS stylistic sets and may be the text of the feature registry has something to do with it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c3b75f69-8bb1-88e5-05b9-035c9f3ec528
* Version Independent ID: 9a9af849-512e-5dfd-b9a6-c05480f34f01
* Content: [Registered features, p-t (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/features_pt#ssxx)
* Content Source: [typographydocs/opentype/spec/features_pt.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_pt.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by colinmford** [comment]
Seconded; while the recommended use of a stylistic set might be GSUB 1, I don't think the registry should be as prescriptive for GSUB as it is here. 

For example:
>The featureParamsOffset field of the Feature Table of these GSUB features may be set to 0, or to an offset to a Feature Parameters table comprising two successive uint16 values, as follows:

The inclusion of "GSUB features" there seems overly prescriptive, probably leading application developers to think featureParams should apply _only_ to GSUB features, when I see no reason it could not apply to GPOS as well.

**Comment by tiroj** [comment]
I would love to completely overhaul the entire feature registry and change the way features are described and information presented. The concept of ‘GSUB features’ and ‘GPOS features’ that the registry appears to promote misrepresents the font format architecture, and—in the absence of an OTL implementation spec—has led developers to make restrictive assumptions about what lookup types can be included in particular features. The features should instead be described in terms of their typographic functionality, expected default state, processing order if relavent, and implementation left to the font developer. At most, the feature descriptions could provide examples of common implementations, while making it clear that _any_ lookup type or combination of lookup types may be used in any feature.

**Comment by PeterConstable** [comment]
The descriptions can reflect how the parties that registered the features anticipated them being used. That said, it makes sense not to restrict how features can be used provided the generalization is consistent with the original idea.

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by tiroj** [comment]
In addition to making clear that ssXX features may involve GPOS instead of or in addition to GSUB, I recommend adding something to the UI suggestion field to emphasise that it should be possible to apply more than one ssXX feature at a time to text. This has been a big problem with MS Office’s implementation, which treat ssXX features as exclusive, allowing only one at a time to be activated:
<img width="589" alt="image" src="https://github.com/MicrosoftDocs/typography-issues/assets/5614500/3d799714-23ea-450b-85a9-9684e82d9f77">

Different ssXX features mat affect different groups of glyphs, so being able to turn on more than one at a time is important.

**Comment by Lorp** [comment]
Perhaps Microsoft is worried about the implications of arbitrary combinations of ss01 to ss20 potentially leading to 2^20 possibilities for what happens to a glyph.

**Comment by PeterConstable** [comment]
I doubt that. More likely that whoever designed the UI assumed these features are complementary, which isn't unreasonable if one assumes the features have font-wide effect rather than partitioning the glyph set.

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for further revisions addressing comments from @tiroj about UI .

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
