### ISSUE TITLE
[glyf] No handedness or grid alignment information is mentioned

### ISSUE THREAD

**Issue by shi-yan** [MicrosoftDocs/typography-issues#1029]
I think this document has important pieces of information missing.

First, regarding the handedness of the contour lines, should clockwise or counter-clockwise be treated as positive (not holes)? or this is not defined by the font at all and any orientations can be used?

(so far, I have seen inconsistent orientations used in TTF and OTF files ). This information is important for triangulation algorithms if I need to render text as geometry objects.

Second, the (x_min, y_min) is usually not the origin (0,0), what should be used for glyph layout/ alignment? the minimum bounding box calculated using the control points? the global bounding box? or the origin? 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b2a9a6a1-a9b9-0864-8982-322da821389e
* Version Independent ID: a42612e3-dc1d-f980-fe4a-4880d1fd0086
* Content: [glyf - Glyf data table (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/glyf)
* Content Source: [typographydocs/opentype/spec/glyf.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/glyf.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
While it isn't stated in the glyf chapter, it is implicit in the [discussion of the scan converter in the TrueType Fundamentals chapter](https://learn.microsoft.com/en-us/typography/opentype/spec/ttch01#the-scan-converter).

>A point is considered to be an interior point of a glyph if it has a non-zero winding number. The winding number is itself determined by drawing a ray from the point in question toward infinity. (The direction in which the ray points in unimportant.) Starting with a count of zero, we subtract one each time a glyph contour crosses the ray from right to left or bottom to top. Such a crossing is termed an on transition. We add one each time a contour of the glyph crossed the ray from left to right or top to bottom. Such a crossing is termed an off transition. If the final count is non-zero, the point is an interior point.

The glyf chapter could provide a cross-reference to that.

**Comment by PeterCon** [comment]
The 'glyf' chapter already has an opening paragraph that mentions rasterization with a link to the TrueType Fundamentals chapter. So nothing new needs to be added in that regard.

Regarding xMin, yMin versus the origin and glyph placement, this is also partially discussed in the TrueType Fundamentals chapter, though a complete understanding also requires reading a description of head.flags bit 1, lsb values in hmtx, and phantom points. Further clarification could be added in the TrueType Fundamentals chapter.

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions to the TrueType Fundamentals chapter addressing this issue.

**Comment by PeterConstable** [comment]
Somewhat related: #353

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
