### ISSUE TITLE
Segoe UI not in Word for Mac ver 16.17

### ISSUE THREAD

**Issue by jkemnitz** [MicrosoftDocs/typography-issues#103]
I transfer files between my PC and Mac but it is so frustrating that the Segoe UI font is not there in the Mac version and I keep having to deal with the substitution process.  Can I get the font, PLEASE?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3c2a6fb-3005-b23b-bc83-f8046b852851
* Version Independent ID: f5d0fbf0-990b-7b3d-0c4a-bd4b51c8532e
* Content: [Segoe UI font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/segoe-ui)
* Content Source: [typographydocs/font-list/segoe-ui.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/segoe-ui.md)
* Product: **windows**
* GitHub Login: @nihar
* Microsoft Alias: **mihar**

**Comment by FontBoss** [comment]
Hi, you don't mention what kind of files, assuming documents you can embed Segoe UI in your Word and PowerPoint files, or into PDFs. You'll need a recent version of Mac Office. We're currently exploring additional options for Office. Also certain styles of Segoe UI are available for developers and designers here - https://docs.microsoft.com/en-us/windows/uwp/design/downloads/#fonts (read the license for usage restrictions) - Thanks, Si (Program Manager, Office Design)

**Comment by MichaelGrigoryan25** [comment]
I would suggest installing it with this.
[Segoe UI.zip](https://github.com/MicrosoftDocs/typography-issues/files/4533060/Segoe.UI.zip)
Hope it helps

**Comment by alib-ms** [comment]
The Office Cloud Font Service now offers the Segoe UI font.
