### ISSUE TITLE
ISO-639 mga (Middle Irish) and ghc (Hiberno-Scottish Gaelic)

### ISSUE THREAD

**Issue by silmeth** [MicrosoftDocs/typography-issues#1031]
Those codes are not associated with any language system.

`mga` is ISO-639-2 code for Middle Irish (Gaelic dialects of ~900–1200, the stage after Old Irish – sharing its written tradition, some Old Irish texts being preserved in Middle Irish manuscripts), `ghc` is an ISO-639-3 code for “Hiberno-Scottish Gaelic” which is a name given by Ethnologue to Classical Gaelic or Classical Irish – the standardized language of Gaelic poetry of ~1200–1750.¹

So it would make sense to me to:
* add `mga` to `SGA` (Old Irish) Language System Tag,
* add `ghc` to `IRT` (Irish Traditional) system,
* **or** add separate Language Systems for those stages of Irish/Gaelic.

Lack of association for those codes causes texts using the insular (“Gaelic”) type in HTML elements marked with `lang="mga"` or `lang="ghc"` to render incorrectly using Junicode 2 font, see https://github.com/psb1558/Junicode-font/issues/170

----
¹ [Ethnologue 15, p. 565](https://archive.org/details/ethnologuelangua0000unse_g7e1/page/564/mode/):
> **Gaelic, Hiberno-Scottish** (Gaoidhealg, Hiberno-Scottish Classical Common Gaelic) [ghc] Extinct. Ireland and Scotland. *Class:* Indo-European, Celtic, Insular, Goidelic. *Lg Dev:* Roman script. Bible: 1690. *Other:* Archaic literary language based on 12th century Irish, formerly used by professional classes in Ireland until the 17th century and Scotland until the 18th century. vso.

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
