### ISSUE TITLE
Where is the download link for the font?

### ISSUE THREAD

**Issue by Choosechee** [MicrosoftDocs/typography-issues#1032]
I want to download the font, but there's no link to get it.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f1360cc-06aa-3a93-dae0-69bbae45cac3
* Version Independent ID: 41421a84-cd8c-6536-9e5f-c964eddd3a9d
* Content: [LCD font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/lcd)
* Content Source: [typographydocs/font-list/lcd.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/lcd.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
HI [Choosechee](https://github.com/Choosechee), The fonts we offer are exclusively provided with our shipped products. However, it appears that the specific font you are interested in is not included in our current product lineup. Fortunately, you can obtain a license for this font through the link provided on this page [LCD font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/lcd).

**Comment by kenmcd** [comment]
Only place I have found this font is in:
**Microsoft Flight Simulator X Demo**     
(from 2006)

**Comment by alib-ms** [comment]
much thanks!
