### ISSUE TITLE
Unclear behavior if anchor offset is NULL in GPOS Lookup Type 3.1 

### ISSUE THREAD

**Issue by waruyama** [MicrosoftDocs/typography-issues#1034]
In chapter "GPOS — Glyph Positioning Table" under "Cursive Attachment Positioning Format1: Cursive attachment" there is written:

*To position glyphs using the CursivePosFormat1 subtable, a text-processing client aligns the ExitAnchor point of a glyph with the EntryAnchor point of the following glyph. If no corresponding anchor point exists, either the EntryAnchor or ExitAnchor offset may be NULL.*

In case any of the anchor offsets is NULL, it is unclear what is the expected behavior should be. I think there are two options:

1. No positioning will be applied
2. Coordinates of the anchor are zero.

I have actually encountered such a case and it seems to me that omitting positioning of any of the anchor offsets is NULL is the correct behavior.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3f748ff4-44a6-6395-e0ce-d249b8c9541b
* Version Independent ID: b80d0359-5657-632b-29e8-142c06902001
* Content: [GPOS — Glyph Positioning Table (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/gpos)
* Content Source: [typographydocs/opentype/spec/gpos.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gpos.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
If either entryAnchorOffset or exitAnchorOffset is NULL, then no positioning is applied. This could be clarified.

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
