### ISSUE TITLE
[OpenType] Language System Tag for Kadiweu

### ISSUE THREAD

**Issue by moyogo** [MicrosoftDocs/typography-issues#1035]
Kadiwéu [[kbc](https://iso639-3.sil.org/code/kbc)] uses a letter G with a median stroke. Because there is no specific character for G with a median stroke, if Ǥ U+1E14 and in particular ǥ U+1E15 are used their shapes in Kadiwéu should be different than their default shape in most fonts which most often have the stroke on the bottom right of the G and through the descender of the g.

Please consider adding the following Language System Tag:
Language System | Language System Tag | Corresponding ISO 639 ID (if applicable)
-- | -- | --
Kadiwéu |  'KBC ' | [kbc](https://iso639-3.sil.org/code/kbc)

References:
- Glyn Griffiths, [_Dicionário da língua Kadiwéu: Kadiwéu - Português Português - Kadiwéu_](https://www.sil.org/resources/archives/17004) , 1st ed. , 2002 , Linguistics
- G. José da Silva et al. *Dinatitalo Okomag̶a G̶obagatedi – livro de neoalfabetização*, Mato Grosso do Sul, Secretaria de Estado da Educação, 2005
  <img width="298" alt="Screenshot 2023-05-04 at 12 12 35" src="https://user-images.githubusercontent.com/1923747/236175795-050f4184-3406-4658-ab12-03ca3be7e94b.png">

- Miriam Moreira Alves, Verno José Gustavo Weiss, [_Pequeno Dicionario Kadiwéu-Português (Mini Vocabulário Kadiwéu-Portugês)_](http://biblioteca.funai.gov.br/media/pdf/Folheto72/FO-CX-72-4598-2013.PDF), Associação de Educação Católica AEC/MS, 2000

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
