### ISSUE TITLE
[OpenType] Language System Tags for Embera languages and Pilaga

### ISSUE THREAD

**Issue by moyogo** [MicrosoftDocs/typography-issues#1036]
At least two Emberá languages, Northern Emberá [[emp](https://iso639-3.sil.org/code/emp)], Emberá Chamí [[cmi](https://iso639-3.sil.org/code/cmi)], use the letters B with a median stroke and D with a median stroke in some orthographies, and Pilagá [[plg](https://iso639-3.sil.org/code/plg)] uses the letter B with a media stroke.
There is already a recently encoded Ꟈ U+A7C7 and ꟈ U+A7C8 that may be used instead of Đ U+0110 and đ U+0111, but there is no specific character for B with median stroke, if or Ƀ U+0243 and ƀ U+0180 or Đ U+0110 and đ U+0111 or Ƀ U+0243 and ƀ U+0180 are used their shapes in these two Emberá languages should be different than their default shape in pretty much all modern fonts which have a short stroke on the bottom right or bottom right of the capitals and through the ascender of the small letters, whereas the letters in Emberá orthographies have a long stroke or even a diagonal stroke through the capitals B and D and a median stroke through the small letters b and d and the letters in Pilagá orthogaphy have a long stroke through the capital B and a median stroke through the small letter b.

The Language System Tag 'PLG ' is already defined for "Palaung", Pilagá could use 'PLG0'.

Please consider adding the following Language System Tags:
Language System | Language System Tag | Corresponding ISO 639 ID (if applicable)
-- | -- | --
Emberá-Chamí |  'CMI ' | [cmi](https://iso639-3.sil.org/code/cmi)
Northern Emberá |  'EMP ' | [emp](https://iso639-3.sil.org/code/emp)
Pilagá | 'PLG0' | [plg](https://iso639-3.sil.org/code/plg)

Other [Emberá languages](https://en.wikipedia.org/wiki/Ember%C3%A1_languages) could also have Language System Tags:
Language System | Language System Tag | Corresponding ISO 639 ID (if applicable)
-- | -- | --
Emberá-Baudó | 'BDC ' | [bdc](https://iso639-3.sil.org/code/bdc)
Emberá-Catío |  'CTO ' | [cto](https://iso639-3.sil.org/code/cto)
Epena | 'SJA ' | [sja](https://iso639-3.sil.org/code/sja)
Emberá-Tadó |  'TDC ' | [tdc](https://iso639-3.sil.org/code/tdc)

References:
- "Alfabeto pilagá", _Lengua pilagá_, http://lenguapilaga.com.ar/web/alfabeto-pilaga/
- _Dadyi Beꟈeada Ƀʌꟈia, Guía para docentes_, República de Panamá, Ministerio de Educación - Dirección General de Educación, Unidad de Coordinación Técnica para la Ejecución de Programas Especiales en las Áreas Indígenas, Segundo Proyecto de Educación Básica / Banco Mundial, 2006, http://consulta.meduca.gob.pa/files/centroseducativos/etextos/GuiaLibroTexto_embera.pdf
- Asamblea Nacional, República de Panamá, "Ley 88 de 22 de noviembre de 2010 que recononce las lenguas y los alfabetos de los pueblos indígenas de Panamá y dicta normas para la Educación Intercultural Bilingüe", _Gaceta Oficial Digital_, no 26669-A,‎ 26 noviembre 2010, https://www.gacetaoficial.gob.pa/pdfTemp/26669_A/GacetaNo_26669a_20101126.pdf
- Comité de educación bilingüe ẽbẽra bed̶ea chamí, _Ẽbẽra bed̶ead̶e b̶ʉd̶ai kuitáduru_, karta A, Ediciones Manantial, Fundación Semillas, 2021, https://www.sil.org/resources/archives/93708

**Comment by PeterConstable** [comment]
If different languages use the same typographic convention, is it better to have distinct language system tags for each, or one that reflects the convention shared across multiple languages?

**Comment by moyogo** [comment]
Within the Chocó languages using letters with stroke overlay, the Northern Emberá and Emberá-Chamí conventions might be different.

The Northern Emberá Bible translation published in Panama uses diagonal strokes on the capitals but *Dadyi Beꟈeada Ƀʌꟈia, Guía para docentes* uses horizontal strokes. The official alphabet published Gaceta Oficial did not show the capitals.

The Comité de educación bilingüe ẽbẽra bed̶ea chamí’s syllabary uses the capital Ƀ as is instead of a B with a long stroke.

It would be good to have more reference documents in both but this is difficult.

Pilagá is not related to Chocó languages.

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
