### ISSUE TITLE
Minion Web is listed with the "A" Fonts

### ISSUE THREAD

**Issue by Mick536** [MicrosoftDocs/typography-issues#1038]
Minion Web is listed with the "A" Fonts

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: ab667f80-7df3-bafa-0877-51e7af198d44
* Version Independent ID: cfd7b5d4-d79a-36d2-049e-a5d6fff1c270
* Content: [Font library - Typography](https://learn.microsoft.com/en-us/typography/font-list/)
* Content Source: [typographydocs/font-list/index.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/index.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Got it. Will fix.

**Comment by alib-ms** [comment]
thank you for letting us know, fixed!
