### ISSUE TITLE
Typo 1st Para, line 2

### ISSUE THREAD

**Issue by Mick536** [MicrosoftDocs/typography-issues#1040]
Typo: "by Microsoft?s Vincent Connare"

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1c140347-62bf-eac2-b6cb-934b334295e8
* Version Independent ID: 626ccba1-4ab9-8a36-cf0f-154ef8855a2d
* Content: [Trebuchet MS font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/trebuchet-ms)
* Content Source: [typographydocs/font-list/trebuchet-ms.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/trebuchet-ms.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
thank you for letting us know, fixed!
