### ISSUE TITLE
OS/2.strikeoutSize and post.underlineThickness: note about common practice

### ISSUE THREAD

**Issue by mekkablue** [MicrosoftDocs/typography-issues#1041]
I suggest adding a note saying that it is common practice to keep the strikeout and underline sizes the *same* throughout a family in order to avoid different thicknesses of connecting strokes in situations where different styles are used on the same line (e.g., a bold word in a regular text).

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para learn.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 1ae9457c-0d3d-c137-588b-81d54a086f07
* Version Independent ID: 658c6d22-b9d1-1007-9cdb-6898911c9c75
* Content: [OS/2 - OS/2 and Windows metrics table (OpenType 1.9) - Typography](https://learn.microsoft.com/es-mx/typography/opentype/spec/os2)
* Content Source: [typographydocs/opentype/spec/os2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/os2.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by BoldMonday** [comment]
Is this relevant information for a technical spec? Whether underlines are the same thickness across all weights is an aesthetic choice.

What might be a common practice now can change in the future.

**Comment by mekkablue** [comment]
Good point, but that is more an issue of how we formulate it. What about warning of potentially unwanted behaviour:

> If you do not keep the strikeout and underline sizes the same throughout a family, a text rendering will likely display different thicknesses of connecting strokes in situations where different styles are used on the same line (e.g., a bold word in a regular text).

**Comment by ryanbugden** [comment]
My two cents: I could see a possibility where someone might intentionally want varying thicknesses. I think your cautionary statement would be a great flag for a QA tool like Font Bakery (I think it might already be in there).

**Comment by PeterCon** [comment]
Noting common font design practice could be useful in the spec if it could help software developers avoid creating issues. If it's a matter of avoiding problems in how fonts interact with applications, then that suggests the need for a recommendation. This doesn't strike me as either of those. This is aesthestic guidance, and there are lots of other aspects of aesthetic guidance that could be called out. I'm not inclined to have much of that in the spec, unless it's something not obvious that can lead to pretty bad results.
