### ISSUE TITLE
vedic, sanskrit Typeface

### ISSUE THREAD

**Issue by fontdesigner** [MicrosoftDocs/typography-issues#1043]
[Enter feedback here]

https://www.linkedin.com/feed/update/urn:li:activity:7065738556928892928/
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1198929e-67b2-8442-c623-7e1325712c6a
* Version Independent ID: 47fa7093-96e1-effa-2157-f07d00e2d7c4
* Content: [Sanskrit Text font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/sanskrit-text)
* Content Source: [typographydocs/font-list/Sanskrit-Text.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/Sanskrit-Text.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **alib**

**Comment by fontdesigner** [comment]
https://www.linkedin.com/feed/update/urn:li:activity:7065738556928892928/

**Comment by fitojb** [comment]
What is exactly it that you’re requesting Microsoft Typography do?

**Comment by alib-ms** [comment]
No actionable feedback.
