### ISSUE TITLE
Will it support CJK Unified Ideographs Extension B

### ISSUE THREAD

**Issue by asd223100** [MicrosoftDocs/typography-issues#1044]
As tittle, I found it can not support CJK Unified Ideographs Extension B
Have a plan for support?

---
#### 文件的詳細資料

⚠ *請勿編輯此部分。 learn.microsoft.com 必要 ➟ 連結 GitHub 問題。*

* ID: 964ad563-4fea-7efb-332d-994c620a2e97
* Version Independent ID: 9fdd074e-2f69-e569-2398-3883097a67c9
* Content: [Microsoft JhengHei font family - Typography](https://learn.microsoft.com/zh-hk/typography/font-list/microsoft-jhenghei)
* Content Source: [typographydocs/font-list/microsoft-jhenghei.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/microsoft-jhenghei.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Microsoft JhengHei is designed to cater to the needs of Traditional Chinese language support and it does not support extension ranges. For Traditional Chinese Extension B coverage please use MingLiU-Ext B or MingLiU_HKSCS-Ext B.
