### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by MONTAHADOHAN** [MicrosoftDocs/typography-issues#1046]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c6183f33-6bd9-d594-abb1-55d7a7e7a429
* Version Independent ID: 58b29f6a-b523-b47a-611d-1b9f936bbc22
* Content: [Arial Rounded MT font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/arial-rounded-mt)
* Content Source: [typographydocs/font-list/arial-rounded-mt.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/arial-rounded-mt.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
No actionable feedback.
