### ISSUE TITLE
Bahnschrift font for commercial use

### ISSUE THREAD

**Issue by asdasdqeeeqwe** [MicrosoftDocs/typography-issues#1047]
Hello, 

i would like to use Bahnschrift commercially, e.g. as the primary font for our webshop. 

According to the following paragraph, I am  unable to do this, see the section in **bold**. Unfortunately, the Bahnschrift cannot be licensed neither via fonts.com nor webtype.com. 

CSS lets a web page creator specify a prioritized list of fonts (commonly known as a “font stack”) that a web content rendering engine, such as those used by a web browser, should use to render the text of a web page if they are available on the device on which the rendering engine is running. Web content publishers are free to specify Windows supplied fonts in their font stacks. In fact, as a web page creator you don’t even need to be a Windows licensee to include a Windows font name in a CSS font stack, as the “use” of the font occurs on the Windows device, not on your web server.

Web fonts are fonts that are hosted on a web server. You do not have rights to:

**copy fonts from a Windows installation to a web server, a process known as web font “self-hosting”.
convert the font to the formats typically associated with web fonts, such as the WOFF or WOFF2 format.
Many Windows fonts are available for web use through Monotype’s Fonts.com web font service, some are also available via Type Network’s WebType.com. Other Windows fonts may be available from their original creator.
[Enter feedback here]**

According to another [source](https://answers.microsoft.com/de-de/windows/forum/all/schriften-legal-kommerziell-nutzen/18d00dc1-8f0d-4f39-ba65-faff89c0caaf), in german, Bahnschrift can be licensed through https://www.microsoft.com/typography/fonts/. The link unfortunately does not work for me and different people who tried it on my behalf. 

Does anybody know, if Bahnschrift can be licensed for commercial use and where? 

Thank you very much for your help!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1ea5ad39-ec78-af12-1479-e3def2c62723
* Version Independent ID: 4c9dbe2a-0d30-42fe-34be-38053fcf5c4e
* Content: [Font redistribution FAQ - Typography](https://learn.microsoft.com/en-us/typography/fonts/font-faq)
* Content Source: [typographydocs/fonts/font-faq.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/fonts/font-faq.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Hi,

Bahnschrift is a Microsoft font, and it can be licensed through our external licensing partner, Monotype, contact there is Sutter, Jacqueline [jaki@monotype.com](mailto:jaki@monotype.com).

Thanks,
Ali
