### ISSUE TITLE
What do head.created and head.modified mean?

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#1049]
It is unclear what the created and modified fields are for. Do they refer to creation and modification times of a particular font file (which would usually be around the same value) or of the font (which could be a project with multiple versions spanning many years) or of something else?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f3ee780c-6509-ae67-2223-7c0468dc745c
* Version Independent ID: 907dff3d-e18f-e9c9-3ff6-7cf7f05aa7be
* Content: [head - Font header table (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/head)
* Content Source: [typographydocs/opentype/spec/head.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/head.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
I don't know that there's one right answer.
