### ISSUE TITLE
Input range explanation in chaining contextual subtables

### ISSUE THREAD

**Issue by mta452** [MicrosoftDocs/typography-issues#105]
The spec says, `Please note that (just like in the ContextPosFormat1 subtable) these lookups are required to operate within the range of text from the covered glyph to the end of the input sequence.`

What would be the applicable range, if the specified lookup depends on previous glyphs? Consider the following scenario as an example.

**Glyph String:** `b₃ b₂ b₁ g₁ g₂ l₁ l₂ l₃`
**Backtrack Sequence:** `b₃ b₂ b₁`
**Input Sequence:** `g₁ g₂`
**Lookahead Sequence:** `l₁ l₂ l₃`

Assume that the lookup record specifies a mark-to-base positioning with mark glyph being `g₁` and base glyph being `b₁`. `g₁` lies in the input sequence, while `b₁` lies in the backtrack sequence. Now technically, `g₁` is the glyph on which lookup is applied but `b₁` is its necessity. So the question is, which operations are bound to the input range? Is matching of previous and next glyphs also bounded?

Maybe the spec can shed more light on it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f748ff4-44a6-6395-e0ce-d249b8c9541b
* Version Independent ID: b80d0359-5657-632b-29e8-142c06902001
* Content: [GPOS — Glyph Positioning Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/gpos)
* Content Source: [typographydocs/opentype/spec/gpos.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gpos.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
@mta452 The sequenceIndex in the lookup record is, as defined, within the Input Sequence; and that glyph will be treated as the first glyph in the sequence acted on by the nested lookup (or the only glyph, in the case of GPOS type 1). 

In your example, the lookup record references a type 4 (mark-to-base) lookup for `g1`. That nested lookup would be acting on the sequence `g1 g2`. That means that `g1` would need to be treated as though a base in the type 4 lookup. But if that glyph is not, in fact, a base (as classified in GDEF), then that would seem like not-well-formed data. The spec currently doesn't say explicitly what should happen in such a case, and I could imagine different implementations might end up doing different things. (If I were implementing, I'd probably treated it like a no-op.)

What's not clear to me is what, if anything, should be clarified in the spec. It seems that your question is whether the nested type 4 lookup could position `g1` from the input sequence onto `b1` in the backtrack sequence. If that's the question, is the answer ("no") not clear in the spec? If not, where do you think it should have been clarified?

**Comment by PeterCon** [comment]
@mta452 : I'm wondering if you're monitoring and could provide clarification on this. Thanks.

**Comment by behdad** [comment]
I believe this requirement shall be relaxed and removed.

**Comment by mta452** [comment]
@PeterCon I had initially implemented the input range boundary for nested lookups but [Urdu Typesetting](https://docs.microsoft.com/en-us/typography/font-list/urdu-typesetting) caused issues with this.

**Comment by PeterCon** [comment]
The intent of the spec has always been (though maybe this isn't sufficiently clear) that backtrack and lookahead sequences are only for added context when matching in the parent lookup, and that nested lookups can only act starting at the first glyph of the input sequence. Nested lookups don't re-process glyphs earlier in the sequence that were already processed by the parent lookup. 

Part of the confusion seems to relate to assuming that the base glyph for the mark-to-base lookup should be in the backtrack sequence. That's incorrect: the base glyph b1 should be in the coverage table of the m2b lookup; when nested within a type 8 parent lookup, b1 should be in the coverage of that lookup and the first glyph in the input sequence.

**Comment by PeterCon** [comment]
This may be the same issue as #184 .

**Comment by mta452** [comment]
Yes, it seems to be the same issue.

**Comment by PeterCon** [comment]
I close this and continue tracking #184.

But I think there may be a bit of a difference between the question in that issue and yours, and I'll reiterate part of my earlier comment:

>Part of the confusion seems to relate to assuming that the base glyph for the mark-to-base lookup should be in the backtrack sequence. That's incorrect: the base glyph b1 should be in the coverage table of the m2b lookup; when nested within a type 8 parent lookup, b1 should be in the coverage of that lookup and the first glyph in the input sequence.

IOW, instead of this:

Glyph String: b₃ b₂ b₁ g₁ g₂ l₁ l₂ l₃
Backtrack Sequence: `b₃ b₂ b₁`
Input Sequence: g₁ g₂
Lookahead Sequence: l₁ l₂ l₃

you could have this:

Backtrack Sequence: `b₃ b₂`
Input Sequence: `b₁` g₁ g₂

and the nested lookup should have `b₁` in its coverage table and act on b₁ g₁ g₂.
