### ISSUE TITLE
Description for underlinePosition is unclear

### ISSUE THREAD

**Issue by ryanbugden** [MicrosoftDocs/typography-issues#1050]
Hello, I and some others have been doing a bit of work to (attempt to) help sync up underline and strikethrough behavior across the web and apps. In reading the OT spec, I was finding some of the wording unclear, in particular the description for `underlinePosition`. I have a suggestion for clarification below and would appreciate any consideration.

### underlinePosition: Current Description

> This is the suggested distance of the top of the underline from the baseline (negative values indicate below baseline).
> The PostScript definition of this FontInfo dictionary key (the y coordinate of the center of the stroke) is not used for historical reasons. The value of the PostScript key may be calculated by subtracting half the underlineThickness from the value of this field.

### Issues With the Description

1. “is not used for historical reasons”. could mean:
a. Is not used at all, and that's because of various historical reasons
or
b. is not used for historical reasons; it's used for other reasons
2. With “is not used for historical reasons”, it’s slightly unclear if it’s:
a. font-maker-centric: "is not the methodology you should use when coming up with this value"
or
b. app/interpreter-centric: "is not the methodology you should use when interpreting whatever value is here"
3. It mentions a calculation to get a value for the `cff` table, but AFDKO works in the opposite direction (e.g. taking the UFO font info key, interpreting it to mean the value destined for `cff` table, and calculating a new value [`cff`’s underlinePosition + underlineThickness / 2] for the `post` table)

### underlinePosition: Suggested Description

> Suggested y-coordinate of the top of the underline, relative to the baseline (negative values indicate that the underline is below the baseline). For historical reasons, the PostScript definition of this FontInfo dictionary key (the y-coordinate of the center of the stroke) is not used for the `post` table.

A less vague description than "for historical reasons" would also be welcome, from someone who knows more about this than I.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c682af48-1252-0ffc-c6d7-c73130b2a690
* Version Independent ID: ed9e6d48-434b-ab0c-2fdf-e2700cde9cb2
* Content: [post — PostScript Table (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/post)
* Content Source: [typographydocs/opentype/spec/post.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/post.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by dscorbett** [comment]
I recommend against removing the explanation of the relationship between post.underlinePosition and CFF.UnderlinePosition. It makes the document less clear for no benefit. The formula could be rearranged to match how some tools approach it, but it shouldn’t be deleted.

The note in [the CFF2 document](https://learn.microsoft.com/en-us/typography/opentype/spec/cff2) that UnderlinePosition is “Equivalent to the underlinePosition field in the 'post' table” should be corrected to take the thickness into account.

**Comment by ryanbugden** [comment]
Good point @dscorbett . How about something like this (trying to be super clear)?
> Suggested y-coordinate of the top of the underline, relative to the baseline (negative values indicate that the underline is below the baseline). 

>The PostScript definition of this FontInfo dictionary key (the y-coordinate of the center of the stroke) is not used for the `post` table; it's historically used for the `cff` table. The value of the `post` `underlinePosition` key may be calculated by adding half of the `underlineThickness` to the value of the `cff` `underlinePosition` key.

**Comment by dscorbett** [comment]
That is clear and correct.

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue. 

Note that Appendix D (which had the "equivalent to" wording) will be removed in OT 1.9.1, so that part of the suggestion is moot.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
