### ISSUE TITLE
{'style': 'italic', 'font': ['times', 'verdana', 'caslon']}

### ISSUE THREAD

**Issue by Omshukla07** [MicrosoftDocs/typography-issues#1051]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9307bce0-42fe-44fe-e4ef-08905c80c82e
* Version Independent ID: 795973a5-be24-c2ee-48de-2d0421dcdbad
* Content: [Verdana font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/verdana)
* Content Source: [typographydocs/font-list/verdana.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/verdana.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Can you please clarify?

**Comment by alib-ms** [comment]
Not sure if there is an actionable item here.
