### ISSUE TITLE
Error in example description for input/backtrack/lookahead sequences

### ISSUE THREAD

**Issue by Guldoman** [MicrosoftDocs/typography-issues#1052]
Under the illustration that clarifies the ordering of glyph arrays for input, backtrack and lookahead sequences:
```
the backtrack sequence would comprise glyphs IDs for “dbca” in that order;
```
is specifying the wrong order and should read `dcba`.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb42967-20ca-9270-4572-65315127fcc5
* Version Independent ID: 1fa413f1-71cf-ac2a-0999-70dd5d8ac4cd
* Content: [OpenType layout common table formats (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/chapter2#chained-sequence-context-format-1-simple-glyph-contexts)
* Content Source: [typographydocs/opentype/spec/chapter2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/chapter2.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
See [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.
