### ISSUE TITLE
flac feature name

### ISSUE THREAD

**Issue by tiroj** [MicrosoftDocs/typography-issues#1054]
Currently reads:

_Friendly name: Flattened ascent forms_

Should be:

_Friendly name: Flattened **accent** forms_

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fb16259e-1f7c-4e96-02b8-f692eb3e77e7
* Version Independent ID: eab1b2c5-0209-ccdf-b898-bbc5b5dbbe0f
* Content: [Registered features, f-j (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/features_fj)
* Content Source: [typographydocs/opentype/spec/features_fj.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_fj.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
Or, indeed

_Friendly name: Flattened Accent Forms_

for consistency in capitalisation with other feature names.

**Comment by khaledhosny** [comment]
Already reported in https://github.com/MicrosoftDocs/typography-issues/issues/1013

**Comment by PeterCon** [comment]
Duplicate, so closing.
