### ISSUE TITLE
Microsoft Typography

### ISSUE THREAD

**Issue by timoteo011** [MicrosoftDocs/typography-issues#1059]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b6087ef7-c445-bfa5-940f-de2990bc4069
* Version Independent ID: e581c6e1-b37a-a979-5dc3-5dfa73428201
* Content: [Monotype.com font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/monotype.com)
* Content Source: [typographydocs/font-list/monotype.com.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/monotype.com.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
No actionable feedback, so closing.
