### ISSUE TITLE
We want to buy font copyright issues

### ISSUE THREAD

**Issue by summerjkl** [MicrosoftDocs/typography-issues#1063]
Hello：
  I am an game artist worker in China,Our game want to buy the Candara font ,but we don't know who is the the font author.
we need your help.We would like to know from your company which company designed this font, what is the process of purchase.
Looking forward to receiving your reply。
Thankyou very much!

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 16cfaf7b-bd22-3364-f9e0-0c93cfbf001c
* Version Independent ID: 123e5b62-3c9f-df67-f7f1-3e0a61c2c73f
* Content: [Candara font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/candara)
* Content Source: [typographydocs/font-list/candara.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/candara.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by kenmcd** [comment]
The Candara font designer is Gary Munch.
http://www.munchfonts.com/
His website points to two places to buy the fonts.
https://www.linotype.com/431783/candara-family.html

https://www.fonts.com/font/microsoft-corporation/candara

**Comment by PeterCon** [comment]
The [Candara page](https://learn.microsoft.com/en-us/typography/font-list/candara) provides a link for acquiring a font license.
