### ISSUE TITLE
[OpenType] Language System Tags for orthographies using ı U+0131

### ISSUE THREAD

**Issue by moyogo** [MicrosoftDocs/typography-issues#1065]
Khinalug [ISO 639-3: [kjj](https://iso639-3.sil.org/code/kjj)], Udi [[udi](https://iso639-3.sil.org/code/udi)] and Talysh [[tly](https://iso639-3.sil.org/code/tly)] in Azerbaijan use alphabets similar to Azerbaijani.

Like Azerbaijani 'AZE ' [aze], Crimean Tatar 'CRT ' [crh], Gagauz 'GAG ' [gag], Kazakh 'KAZ ' [kaz], Khorasani Turkic 'KMZ ' [kmz], Krymchak 'JCT ' [jct], Tatar 'TAT ' [tat], Turkish 'TRK ' [tur], Zazaki 'ZZA ' [zza] which may need special features in fonts to prevent ı U+0131 LATIN SMALL LETTER DOTLESS I from looking like i U+0069 LATIN SMALL LETTER I in some contexts, for example if a ligature fi is formed.

Language System | Language System Tag | Corresponding ISO 639 IDs or other information
--|--|--
Khinalug | 'KJJ ' | kjj
Talysh | 'TLY ' | tly
Udi | 'UDI ' | udi

See:
- https://en.wikipedia.org/wiki/Khinalug_language
- https://en.wikipedia.org/wiki/Talysh_language and https://incubator.wikimedia.org/wiki/Wp/tly/Sərlohə or https://unicode.org/udhr//d/udhr_tly.txt
- https://en.wikipedia.org/wiki/Udi_language

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
