### ISSUE TITLE
ocr b with greek characters 

### ISSUE THREAD

**Issue by alexdimi13** [MicrosoftDocs/typography-issues#107]
i want to ask you if there is an ocrb font which includes greek symbols.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 226f0a72-7853-9054-ae87-b977a36d49b3
* Version Independent ID: 5c168b3b-23e8-c215-7adc-e608991cb1ff
* Content: [OCR-B-Digits font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/ocr-b-digits)
* Content Source: [typographydocs/font-list/ocr-b-digits.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/ocr-b-digits.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alib-ms** [comment]
For this question, Myfonts.com may be a more suitable source. It's worth noting that the OCRB included with Microsoft Office only supports the Basic Latin Character set AFAIK.
