### ISSUE TITLE
Comic_Sans_MS21x29_Italic

### ISSUE THREAD

**Issue by PeroPapic** [MicrosoftDocs/typography-issues#1074]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 98c6db8c-d347-baa2-ca72-68f05976e119
* Version Independent ID: f64621c7-8259-8529-4416-e8fa24528433
* Content: [Comic Sans MS font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/comic-sans-ms)
* Content Source: [typographydocs/font-list/comic-sans-ms.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/comic-sans-ms.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Missing details, no actionable item.
