### ISSUE TITLE
谭新作业

### ISSUE THREAD

**Issue by jingxiaotan** [MicrosoftDocs/typography-issues#1075]
wo ni  ta  de  zhe zhe na na zai zai jiu jia jian he nan xiu yv yv ya yue yuan wen wang yan chuntian xiatian qiutian dongtian chifan shuijiao 
我  你  他  的 这    着  那 哪 在  再  就 加  减  和  难   修  鱼 雨 鸭 月     圆    问     忘     眼      春天     夏天     秋天     冬天       吃饭     睡觉
limian waimian zheli zhengzai zhende jiade  xuexiao shenme rongyi mashang xvduo youqu yinggai yinwei suoyi xvyao bixv jiuyao 
里面     外面     这里    正在       真的    假的    学校       什么     容易      马上       许多   有趣    应该     因为   所以   需要 必须  就要
xiexieni biekeqi duibuqi maiguanxi laibuji shengdanjie wanshengjie tangangqin dalanqiu tizuqiu shengrijuhui yuelaiyuehao sihaiweijia
谢谢你  别客气  对不起     没关系   来不及    圣诞节         万圣节          弹钢琴       打篮球   踢足球   生日聚会       越来越好     四海为家
wanshuiqianshan
      万水千山

**Comment by PeterCon** [comment]
No actionable feedback, so closing.
