### ISSUE TITLE
Calibri version in Windows 11 font list page is wrong

### ISSUE THREAD

**Issue by VentusUta** [MicrosoftDocs/typography-issues#1076]
The Calibri version in font list page is 6.23, but 6.26 in Windows 11.

![image](https://github.com/MicrosoftDocs/typography-issues/assets/135337676/bab6f627-511d-4879-98db-f8eec5457d3a)

![image](https://github.com/MicrosoftDocs/typography-issues/assets/135337676/d419d479-6d7d-4b36-bb07-00ccb888cb7f)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 258ad530-9159-5b54-6252-e4bd8ec33e4b
* Version Independent ID: 079dca33-ba4b-7349-4a91-0a99ecdf3d2c
* Content: [Font List Windows 11 - Typography](https://learn.microsoft.com/en-us/typography/fonts/windows_11_font_list)
* Content Source: [typographydocs/fonts/Windows_11_Font_List.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/fonts/Windows_11_Font_List.md)
* Product: **typography**
* GitHub Login: @alib
* Microsoft Alias: **alib**

**Comment by vyaraatanasova219-hue** [comment]
Calibri 6.26 is not a problem. It is the official release from its designer, with 88 additional glyphs.
