### ISSUE TITLE
yahei

### ISSUE THREAD

**Issue by maihepireti** [MicrosoftDocs/typography-issues#1081]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 887c10e0-63c5-06d9-38fc-3c844c0d308d
* Version Independent ID: fbc7a8c5-a8bd-611d-0758-1b56e5d5a03a
* Content: [Microsoft YaHei font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/microsoft-yahei)
* Content Source: [typographydocs/font-list/microsoft-yahei.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/microsoft-yahei.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Missing details, no actionable item.
