### ISSUE TITLE
a

### ISSUE THREAD

**Issue by DonDante2246** [MicrosoftDocs/typography-issues#1083]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 658907f3-1fcc-1974-cb37-85abaf188df8
* Version Independent ID: 5acdd46e-1625-a159-a55a-1176ca2d6804
* Content: [Californian FB font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/californian-fb)
* Content Source: [typographydocs/font-list/californian-fb.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/californian-fb.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Missing details, no actionable item.
