### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by oliverexx** [MicrosoftDocs/typography-issues#1085]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 708a0480-1f2b-dd4d-d7ff-15acd53c1427
* Version Independent ID: d8e57159-d71b-3ef0-5b55-e16e369e88d6
* Content: [Perpetua font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/perpetua)
* Content Source: [typographydocs/font-list/perpetua.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/perpetua.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Missing details, no actionable item.
