### ISSUE TITLE
fuenteConsolas

### ISSUE THREAD

**Issue by Marto07** [MicrosoftDocs/typography-issues#1089]
[Escribir comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para learn.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: bebad8df-b4dd-251d-f63c-630239cf0bcd
* Version Independent ID: 81bc3207-d7c1-6b93-bd22-47771348961a
* Content: [Consolas font family - Typography](https://learn.microsoft.com/es-mx/typography/font-list/consolas)
* Content Source: [typographydocs/font-list/consolas.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/consolas.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by fitojb** [comment]
This report does not contain any information... / Este informe no contiene ninguna información...

**Comment by alib-ms** [comment]
Missing details, no actionable item.
