### ISSUE TITLE
VTT resources link is broken

### ISSUE THREAD

**Issue by cjchapman** [MicrosoftDocs/typography-issues#109]
Following the "VTT resources" link above leads to a page with the message "We are sorry, the page you requested cannot be found.".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3adae675-e33d-0a22-98fd-25a77f2b723c
* Version Independent ID: 3dc9a5cc-4380-056c-848d-48567ecca83c
* Content: [Microsoft Visual TrueType (VTT) - Typography](https://docs.microsoft.com/en-us/typography/tools/vtt/)
* Content Source: [typographydocs/tools/vtt/index.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/tools/vtt/index.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by robmck-ms** [comment]
Removed the sentence with the link. 

Commit: MicrosoftDocs/typography@bb123175d68f42d018177d1f84389316f6a0857e
