### ISSUE TITLE
COLR docs should be explicit about how to resolve offsets

### ISSUE THREAD

**Issue by cmyr** [MicrosoftDocs/typography-issues#1090]
In general the docs for OpenType tables are very consistent about explicitly stating what an offset is relative to, e.g. the [GPOS header](https://learn.microsoft.com/en-us/typography/opentype/spec/gpos#gpos-header) states in the description for each offset field in the header that the offset is relative to the beginning of the GPOS table.

COLR does not follow this convention and I think this is an oversight; although the user might reasonably (and correctly) assume that all offsets are relative to the start of the parent table, this pattern is not universally true for all offsets in all tables in the spec, and I think that it is worth being explicit in this case, particularly in the case when offsets occur inside records, and must be resolved against the start of the record's parent table (such as with the BaseGlyphPaintRecord in the [BaseGlyphList table](https://learn.microsoft.com/en-us/typography/opentype/spec/colr#baseglyphlist-layerlist-and-cliplist).

**Comment by PeterCon** [comment]
See <https://learn.microsoft.com/en-us/typography/opentype/spec/colr#colr-formats>:

> All table offsets are from the start of the parent table in which the offset is given, unless otherwise indicated.

Does the point of reference need to be repeated in each table or record?

**Comment by PeterCon** [comment]
The suggestion is reasonable to avoid possible confusion. (Not re-stating a repeated concept each time could, in theory, be sufficient, but when that concept isn't obvious or implicitly understood by all readers, it can leave ambiguity for the reader.)

See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by cmyr** [comment]
Thanks for the fix. The reason this was an issue for me in particular was that I use the descriptions of the tables as the input for a codegen tool, and it uses the docs to generate documentation for the fields, and it is nice in that case for each offset field to document exactly what the offset is relative to, just to avoid confusion. :)

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
