### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by dany1408** [MicrosoftDocs/typography-issues#1092]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 36b9d23a-b110-648e-afab-917f5f511bb4
* Version Independent ID: 8ae47820-ce61-0597-7a94-ac2684867c40
* Content: [Tahoma font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/tahoma)
* Content Source: [typographydocs/font-list/tahoma.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/tahoma.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
No actionable feedback.
