### ISSUE TITLE
[OpenType] Language System Tag for Chimila

### ISSUE THREAD

**Issue by moyogo** [MicrosoftDocs/typography-issues#1093]
The orthography of the Chimila language (also known as Ette Taara) [ISO 639-3: [cbg](https://iso639-3.sil.org/code/cbg)] in Colombia uses a g with mid overlay stroke.
One may use the generic g with stroke characters Ǥ U+‎01E4 LATIN CAPITAL LETTER G WITH STROKE and ǥ U+01E5 LATIN SMALL LETTER G WITH STROKE to represent this Chimila orthography letter.

It would be useful to have a Language System Tag for Chimila to apply substitutions to have  median overlay stroke g shape, for example with the 'locl' feature, when a font’s default Ǥ U+‎01E4 and ǥ U+01E5 have a stroke in a different position, through the vertical stem on G and the descender of g, like those in the Unicode chart and most fonts.

Language System | Language System Tag | Corresponding ISO 639 IDs or other information
--|--|--
Chimila | 'CBG ' | cbg

See:
- https://en.wikipedia.org/wiki/Chimila_language
- [Juan Camilo Niño Vargas & Narciso Puello Saumeth, _Alfabeto Ette: las vocales de la lengua ette_, 2023](https://ediciones.uniandes.edu.co/library/publication/alfabeto-ette-gaagekragga-ette-taara-consonantes)

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
