### ISSUE TITLE
Arial Unicode

### ISSUE THREAD

**Issue by rufina12** [MicrosoftDocs/typography-issues#1095]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: e542900f-429c-499a-be33-06ed008076fc
* Version Independent ID: b7e1af17-8a49-ab34-9dc4-686adc66a357
* Content: [Arial Unicode MS font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/arial-unicode-ms)
* Content Source: [typographydocs/font-list/arial-unicode-ms.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/arial-unicode-ms.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by kenmcd** [comment]
Previously Arial Unicode MS v1.01 Regular was included with MS Office.
The last version which did include it was Office 2013.
It is no longer include with Office.

You can still get the fonts directly from Monotype.
Regular and Bold are available.
The current version is v1.80.
https://catalog.monotype.com/family/monotype/arial-unicode

Also, macOS still includes Arial Unicode MS v1.01 Regular.

**Comment by PeterCon** [comment]
No actionable feedback was provided. If the intent was to ask where to obtain Arial Unicode MS, then kenmcd has provided that info. Closing.
