### ISSUE TITLE
Add DFKai-SB to word online

### ISSUE THREAD

**Issue by starheart9310** [MicrosoftDocs/typography-issues#1098]
[Enter feedback here]
DFKai-SB, a commonly used fonts in Taiwan and HongKong, is missing in Taiwan.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0000d5f9-43ff-36cf-48ff-453699c439e7
* Version Independent ID: ca3d353c-221b-6e5c-09c2-df8afd86ff57
* Content: [DFKai-SB font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/dfkai-sb)
* Content Source: [typographydocs/font-list/dfkai-sb.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/dfkai-sb.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
This issue is duplicated in #1099, which provides a bit more information. Closing this issue.
