### ISSUE TITLE
Typo: "U+FEEO"

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#11]
In the glossary, “U+FEEO” should be “U+FEE0”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2296e659-a278-4505-3dbe-54e2f8e51a54
* Version Independent ID: 5af9216e-b435-4a4c-3c5a-94756409f8f5
* Content: [Developing OpenType Fonts for Arabic Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/arabic)
* Content Source: [typographydocs/script-development/arabic.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/arabic.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
Done!
