### ISSUE TITLE
xlink:href doesn't work

### ISSUE THREAD

**Issue by hyvyys** [MicrosoftDocs/typography-issues#110]
SVG 2 removed the need for the xlink namespace, so instead of xlink:href you should use href.
Indeed, &lt;use xlink:href="#i-base" /&gt; does not work for Firefox, &lt;use href="#i-base" /&gt; does. However, for Edge neither works. Am I missing something?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7982ac71-0e79-40ed-11ce-1a42674ad14f
* Version Independent ID: b3d4ac02-0d14-a9fd-b76e-9883796a0309
* Content: [svg - Scalable vector graphics table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/svg)
* Content Source: [typographydocs/opentype/spec/svg.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/svg.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by hyvyys** [comment]
Okay, I see I forgot to add the directive: xmlns:xlink="http://www.w3.org/1999/xlink". Anyway, shouldn't Edge implement just href?

**Comment by PeterCon** [comment]
The SVG version used is SVG 1.1, not SVG 2. See https://docs.microsoft.com/en-us/typography/opentype/spec/svg#svg-documents
