### ISSUE TITLE
Use of font for a LOGO

### ISSUE THREAD

**Issue by khumaer** [MicrosoftDocs/typography-issues#1107]
Kindly let me know how to license this font , As in in the absence of any information on the internet, I am using this font for a logo of one of my commercial project. Please do revert back if you need me to comply to any of your policies or licenses.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c490c23e-efc8-1728-619c-11e70ba5657d
* Version Independent ID: b4f7ab40-a11e-d9b6-c8d1-1a824dceb204
* Content: [Poor Richard font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/poor-richard)
* Content Source: [typographydocs/font-list/poor-richard.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/poor-richard.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
The utilization of fonts for creating logos is addressed in our [FAQ](https://learn.microsoft.com/en-us/typography/fonts/font-faq). However, it's worth noting that Poor Richard font hasn't been included in any Microsoft product in the last decade or so, to the best of my knowledge.

**Comment by khumaer** [comment]
Thanks for your revert. :)

**Comment by kenmcd** [comment]
> However, it's worth noting that Poor Richard font hasn't been included in any Microsoft product in the last decade or so, to the best of my knowledge.

Included in all Office 2007 thru Office 2019.
Probably in Office 2021 too but I have not checked the 2021 fonts yet.
