### ISSUE TITLE
イムティアズ

### ISSUE THREAD

**Issue by imtiazzzzzzzzzz** [MicrosoftDocs/typography-issues#1108]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0cb76e8c-e435-4fa5-5e35-8c6d6933bf5e
* Version Independent ID: 9b6131d9-e155-1b16-28cf-40c0b4b9d710
* Content: [MS Mincho font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/ms-mincho)
* Content Source: [typographydocs/font-list/ms-mincho.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/ms-mincho.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by imtiazzzzzzzzzz** [comment]
イムティアズ

**Comment by PeterCon** [comment]
No actionable feedback, so closing.
