### ISSUE TITLE
Incorrect "dlng"/"slng" metadata in "Ebrima" font (TTF, v5.18)

### ISSUE THREAD

**Issue by verdy-p** [MicrosoftDocs/typography-issues#1112]
[Enter feedback here]

Incorrect `dlng` metadata in "Ebrima" font (TTF, v5.18) - The value incorrectly contains script codes surrounded by single quotes and separated by semi-colons; there should be no quotation marks, and language/script tags in TTF fonts may only be separated by a comma (optionally followed by a space).
This is visible in Windows 11: Settings>Fonts

It shows untranslated tags in the selector with these quotes; and when we select the Ebrima font to show its properties, we see:

**Design language** : 'Adlm'; 'Bamu'; 'Ethi'; 'Nkoo'; 'Osma'; 'Tfng', 'Vaii'

Also web browsers or application are not able to select that font or use it to render those scripts with that font (which is then unusable in many cases. "Ebrima" is the only font distributed with Windows that support these scripts, so these scripts have NO valid fallbacks from any other primary font, unless the font is selected explicitly in primary position.
The fix is simple: changed a single metadata tag value to drop the quotes and spaces and replace the semicolon by a comma.

![image](https://github.com/MicrosoftDocs/typography-issues/assets/1387035/404656de-23ab-4383-8613-3107b38a51b4)

![image](https://github.com/MicrosoftDocs/typography-issues/assets/1387035/5c5e3ddd-8929-4665-a753-058b2b615652)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4330d906-d846-18e0-4e9e-962484418bf5
* Version Independent ID: e94109ae-c2ff-4bac-c611-9f34c7589242
* Content: [Ebrima font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/ebrima)
* Content Source: [typographydocs/font-list/ebrima.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/ebrima.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Fixed! 
![image](https://github.com/MicrosoftDocs/typography-issues/assets/36778811/a10e9c1b-8aa0-4977-a4ab-69f1309083af)

**Comment by alib-ms** [comment]
Also,
![image](https://github.com/MicrosoftDocs/typography-issues/assets/36778811/b2c5e6ff-0352-4507-99db-9ebd980b2c0d)

**Comment by verdy-p** [comment]
Thanks to Microsoft for the 5.19 update of Ebrima after my indirect report here. This confirms the interest of Microsoft (and probable pending changes in Google Chrome, Chrome and Edge, as well as WebView used in many apps on Windows, and Android, including for their UI; Now we wait to see if this works also in MS Office, LibreOffice, and other browsers, including on Apple platforms, and other platforms using Harfbuzz or other text redering engines)

**Comment by verdy-p** [comment]
Note that `dlng`/`slng` metadata are already full part of the ISO/IEC 14496-22:2019 standard (Open Font Format, see section 5.7.6.2 Metadata Tags), whose specifications are also available to everyone at no cost (including its 2020-06 amendment).
However the metadata tags are not deprecating the language/script tags used in features tables (see section 6.4).

I think that the ISO standard should indicate how its own "registry" for language&script tags in feature tables is normative, and how it should be extended. This registry was created prior to the 1st release of ISO 15924.

For new scripts they should use 4 letters only like in ISO 15924, but they were registered in lowercase. And it will remain exceptions for scripts whose support in Opentype features was changed in incompatible way using different algorithms needing different feature tables (like 'bng2' vs. legacy 'beng', 'dev2' vs. legacy 'deva', 'gur2' vs. legacy 'guru', 'knd2' vs. legacy 'knda', 'mlm2' vs. legacy 'mlym', 'ory2' vs. legacy 'orya', 'tml2' vs. legacy 'taml') or specific ('DFLT').

For new languages, all should use 3-letters codes (in uppercase) from ISO 639-2/T or ISO 639-3 followed by one SPACE in feature language tags. But here also there are legacy exceptions in the registry.

This standard ISO registry should be impoved by listing only known legacy exceptions, and otherwise should explicit the format (letter case) and their source, with a rationale if there's a need of somethinh different (in my opinion there should be only one registry, this should be in the IANA registry with some change in BCP 47 to explain more specific uses in standard font formats, including OpenType, SVG). This would ease the convergence. But before that happens, the ISO OpenType standard should include some additional rules and explain the rationale for the existing content, and how to "extend" it for supporting languages or scripts not listed in the ISO 14496-22 document.

**Comment by PeterCon** [comment]
@verdy-p you said,
>Microsoft OpenType specifications even forget to mention the existence of the ISO/IEC standard

See <https://learn.microsoft.com/en-us/typography/opentype/spec/>: this is stated clearly on that page.

**Comment by PeterCon** [comment]
Font issue is fixed, so closing.
