### ISSUE TITLE
shruti font

### ISSUE THREAD

**Issue by Abcd-22** [MicrosoftDocs/typography-issues#1113]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: bbd56be7-c6ab-9f22-6681-5f0cddb93f21
* Version Independent ID: e8da8464-a392-0d7a-7f04-849eb54b5c84
* Content: [Shruti font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/shruti)
* Content Source: [typographydocs/font-list/shruti.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/shruti.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
No actionable feedback, so closing.
