### ISSUE TITLE
[OpenType] Additional Language System Tags for Tifinagh

### ISSUE THREAD

**Issue by jcoblentz** [MicrosoftDocs/typography-issues#1118]
The current OpenType tag designation of [Tamashek](https://iso639-3.sil.org/code/tmh) is a macrolanguage covering multiple ISO 639 language tags:
| Language system | Language System Tag | Corresponding ISO 639 IDs or other information |
| ------------------- | ------------------------ | ----------------------------------------------------- |
|Tamashek              | 'TMH '                          | taq, thv, thz, tmh, ttq

I have language data with character variants from languages taq, thv and ttq. It would be useful to have additional Language System Tags created for these microlanguages to apply substitutions for these variants.
| Language system      | Language System Tag | Corresponding ISO 639 IDs or other information |
| ----------------------- | ------------------------ | ----------------------------------------------------- |
|Tamasheq                   | 'TAQ '                          | [taq](https://iso639-3.sil.org/code/taq)                 |
|Tahaggart Tamahaq    | 'THV '                          | [thv](https://iso639-3.sil.org/code/thv)                 |
|Tayart Tamajeq            | 'THZ '                          | [thz](https://iso639-3.sil.org/code/thz)                 |
|Tawallammat Tamajaq | 'TTQ '                          | [ttq](https://iso639-3.sil.org/code/ttq)                 |

Thanks.

**Comment by moyogo** [comment]
There isn’t a 1-to-1 mapping between the different styles of Tifinagh used in Tamashek languages and their ISO 639 languages IDs.
It may be useful to have tags for the various styles rather than the various languages or dialects with ISO 639 language tags. For example Tamasheq, Tamahaq, Tayart Tamajeq or Tawallammat Tamajaq can be written with APT style or SIL styles in Niger. There are also several styles like Ahaggar, Ghat, Air, Azawagh, Adghagh that can be used in multiple of these variants.

**Comment by bobh0303** [comment]
> It may be useful to have tags for the various styles rather than ...

By this are you meaning Stylistic Sets and Character Variants?

**Comment by bobh0303** [comment]
I'll agree that there are some style variations that do not tightly correspond to language, and for these the Stylist Sets or Character Variants are fine. 

But there _are_ some style preferences that have very high correspondence to language, and I'd rather enable use of css language tagging to achieve the desired rendering than force users to use a string of ssxx or cvxx features to get what they desire.

What is the downside of adding these Language System Tags?

**Comment by moyogo** [comment]
I thought specific Language System Tags for the different variants, but that’s not going to happen in implementations.
The Language System Tags and character variants/stylitics sets you’re proposing is much more pratical.

**Comment by PeterConstable** [comment]
IIUC, it sounds like moyogo is coming around to agree with the proposed tags.

**Comment by PeterConstable** [comment]
It would be helpful to have a bit more info: Among those four languages, are there differences in typographic conventions? Or do these as a group have a shared convention that differs from other languages using the same script(s)?

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by bobh0303** [comment]
> See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

First of all, thanks for the draft.   I assume the asterisks (for new entries) will be added later...?

**Comment by PeterCon** [comment]
> I assume the asterisks (for new entries) will be added later...?
Oh, I hadn't thought about updating the current OT 1.9 page as well as the new page for OT 1.9.1 (which I'm trying to complete quickly).

**Comment by bobh0303** [comment]
I don't understand your comment. At any rate, I was looking at the [1.9.1 alpha Language System Tags](https://learn.microsoft.com/en-us/typography/opentype/otspec191alpha/languagetags) and there are no asterisks indicating the new language system tags you've so kindly added.

**Comment by PeterConstable** [comment]
Right: If new tags are requested and added to a current, already-published version, they'll get marked with an asterisk. If OT 1.9.1 was not nearly done, these would have been added to the current version, OT 1.9, and marked.

(For a moment, I thought somehow there was some extraneous _markdown_ markup appearing in the page.)

**Comment by jcoblentz** [comment]
> It would be helpful to have a bit more info

Three languages (`taq`, `thv` and `ttq`) have some unique typographic conventions and I expect to have different OT rules for them. I do not have research data on `thz` but there could be variations there also.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.

**Comment by bobh0303** [comment]
Thanks for your work on this, Peter!
