### ISSUE TITLE
A possible typo in JSTF Example 3.

### ISSUE THREAD

**Issue by mpsuzuki** [MicrosoftDocs/typography-issues#1119]
In https://learn.microsoft.com/en-us/typography/opentype/spec/jstf

![image](https://github.com/MicrosoftDocs/typography-issues/assets/2202675/b84758a7-a741-4519-8075-e13ed2720ed0)

The 3rd column at the 6th row of the table "Example 3" notes "hrinkageDisableGPOS".
Comparing with the 17th row, I'm afraid that it could be a typo of "gposShrinkageDisableOffset".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b691a267-906d-cafb-2f9e-4dadc8691427
* Version Independent ID: 41170219-4e78-137d-9382-2d06039a4e8c
* Content: [JSTF — Justification Table (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/jstf)
* Content Source: [typographydocs/opentype/spec/jstf.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/jstf.md)
* Service: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Thanks for reporting. See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
