### ISSUE TITLE
vmtx: missing CFF2 reference and CharString capitalization

### ISSUE THREAD

**Issue by takaakifuji** [MicrosoftDocs/typography-issues#1120]
> **VORG** (1.9.1 Alpha)
> https://learn.microsoft.com/en-us/typography/opentype/otspec191alpha/delta/vorg_delta.html
> ...from the CFF ~charstring~**or CFF2 CharString** data

> **vmtx** (1.9.1 Alpha)
> https://learn.microsoft.com/en-us/typography/opentype/otspec191alpha/delta/vmtx_delta.html
> ...from the charstring data in the Compact Font Format ('CFF ') table

`vmtx` mentions `CFF` but not `CFF2`, which doesn't look consistent with the recent update for VORG.

And I also expect UpperCamelCase should be used for CharString throughout the whole text according to [the changelog](https://learn.microsoft.com/en-us/typography/opentype/spec/cff2#appendix-e-changes-since-earlier-versions).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 9897b8d3-432b-39ff-3659-92e55bccc17c
* Version Independent ID: d36a164b-a7b9-4ea2-b169-339e372778e7
* Content: [vmtx — Vertical metrics table (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/vmtx)
* Content Source: [typographydocs/opentype/spec/vmtx.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/vmtx.md)
* Service: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterConstable** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by takaakifuji** [comment]
Looks good to me and thank you for the fix!

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
