### ISSUE TITLE
persian

### ISSUE THREAD

**Issue by Feri222** [MicrosoftDocs/typography-issues#1122]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 258ad530-9159-5b54-6252-e4bd8ec33e4b
* Version Independent ID: 079dca33-ba4b-7349-4a91-0a99ecdf3d2c
* Content: [Font List Windows 11 - Typography](https://learn.microsoft.com/en-us/typography/fonts/windows_11_font_list)
* Content Source: [typographydocs/fonts/Windows_11_Font_List.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/fonts/Windows_11_Font_List.md)
* Service: **typography**
* GitHub Login: @alib
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
No actionable feedback. Can you please let us know what you have in mind regarding Persian.

**Comment by alib-ms** [comment]
Since no actionable feedback has been provided, we are closing the matter.
