### ISSUE TITLE
hol

### ISSUE THREAD

**Issue by ALGUIENJAJAJA** [MicrosoftDocs/typography-issues#1125]
[Escriba sus comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para learn.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: b622840f-b223-4564-f395-8aa80746d23a
* Version Independent ID: 7d8c73fa-be2a-da32-ba98-73d257ea329d
* Content: [OCR A Extended font family - Typography](https://learn.microsoft.com/es-es/typography/font-list/ocr-a-extended)
* Content Source: [typographydocs/font-list/ocr-a-extended.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/ocr-a-extended.md)
* Service: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
What do you mean by "hol"?

**Comment by PeterCon** [comment]
No actionable feedback, so closing.
