### ISSUE TITLE
font

### ISSUE THREAD

**Issue by nathany1162** [MicrosoftDocs/typography-issues#1126]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: fa1b9863-e776-5559-5f25-708b42f5f811
* Version Independent ID: 088ef267-df50-aed8-7024-d3364bd4e486
* Content: [Forte font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/forte)
* Content Source: [typographydocs/font-list/forte.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/forte.md)
* Service: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Since no actionable feedback has been provided, we are closing the feedback.
