### ISSUE TITLE
So why explaining but not having the option to download?? Does not make sense

### ISSUE THREAD

**Issue by Nice2Work** [MicrosoftDocs/typography-issues#1127]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0a71d777-d3f8-95ea-ca5b-5ca9bc78a244
* Version Independent ID: bc946b1e-158f-73f0-7215-c7015663b811
* Content: [Webdings font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/webdings)
* Content Source: [typographydocs/font-list/webdings.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/webdings.md)
* Service: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Microsoft fonts come bundled with Microsoft products, and we've created informational pages for numerous fonts included in Windows and other Microsoft products. These pages offer information about fonts not available elsewhere. Currently, the option to download a font file independently from the product is not available.

Thanks,
