### ISSUE TITLE
text segeon us

### ISSUE THREAD

**Issue by Mehrob007** [MicrosoftDocs/typography-issues#1128]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d3c2a6fb-3005-b23b-bc83-f8046b852851
* Version Independent ID: f5d0fbf0-990b-7b3d-0c4a-bd4b51c8532e
* Content: [Segoe UI font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/segoe-ui)
* Content Source: [typographydocs/font-list/segoe-ui.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/segoe-ui.md)
* Service: **typography**
* GitHub Login: @nihar
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Dear [Mehrob007](https://github.com/Mehrob007), Can you please share actionable feedback.

**Comment by PeterCon** [comment]
No actionable feedback, so closing.
