### ISSUE TITLE
[vhea] table with MVAR tags mentions fields for vhea version 1.0, but not corresponding fields for vhea version 1.1.

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#1130]
In the table in the **'vhea' Table and OpenType Font Variations** section, change "ascent" to "ascent, vertTypoAscender"; similarly for descent and linegap.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 312f3284-9ca3-b310-e0e7-d2912d674f88
* Version Independent ID: 81687336-c575-3041-f241-b7ff15b49965
* Content: [vhea — Vertical header table (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/vhea)
* Content Source: [typographydocs/opentype/spec/vhea.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/vhea.md)
* Service: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
