### ISSUE TITLE
[COLR] sweep gradients: angles from x-axis, not y-axis

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#1132]
In the [description of sweep gradients](https://learn.microsoft.com/en-us/typography/opentype/spec/colr#sweep-gradients), it says, "angles are expressed in counter-clockwise degrees from the direction of the positive **x-axis**" (emphasis added). But, in the section on the corresponding Paint table formats, [Formats 8 and 9](Angles are expressed in counter-clockwise degrees from the direction of the y-axis in the design grid.), it says, "Angles are expressed in counter-clockwise degrees from the direction of the **y-axis**". The latter should say "x-axis".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be879f46-c026-4a9d-1156-a3c98ae8f429
* Version Independent ID: 28be1ce2-e487-b652-632f-e4dc5bb17f42
* Content: [COLR - Color Table (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/colr)
* Content Source: [typographydocs/opentype/spec/colr.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/colr.md)
* Service: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
This warrants an erratum for OT 1.9.

**Comment by PeterCon** [comment]
[Erratum posted for OT 1.9](https://learn.microsoft.com/en-us/typography/opentype/spec/errata), with description of [Paint(Var)SweepGradient](https://learn.microsoft.com/en-us/typography/opentype/spec/colr#formats-8-and-9-paintsweepgradient-paintvarsweepgradient) corrected.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.

**Comment by hanriya9-cmd** [comment]
https://github.com/MicrosoftDocs/typography-issues/issues/1240

**Comment by hanriya9-cmd** [comment]
opinionhttps://_a.me/YaKH/Music is emotion.Our playlist #17https://pin.it/7CFVW1s
