### ISSUE TITLE
[MATH] Clarify spaceAfterScript in relation to pre-scripts

### ISSUE THREAD

**Issue by khaledhosny** [MicrosoftDocs/typography-issues#1135]
The description for `spaceAfterScript` has:
> Extra white space to be added after each subscript and superscript.

But there is no mention of how this is applied to prescripts, and implementations seem to be interpreting it differently: https://github.com/w3c/mathml-core/issues/217

Testing shows that Microsoft Word inserts the space **before** prescripts, which makes sense, so the spec should mention this.

![image](https://github.com/MicrosoftDocs/typography-issues/assets/93914/042da885-6704-40e8-81ae-0c23ce8d92ab)
(Testing in Microsoft Word with large `spaceAfterScript` value)

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f0076fd2-52b0-2989-3142-fd9e456b9514
* Version Independent ID: 4aef8fa3-2ad3-7933-5a77-0a7473e66112
* Content: [MATH - The mathematical typesetting table (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/math#mathglyphinfo-table)
* Content Source: [typographydocs/opentype/spec/math.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/math.md)
* Service: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Thanks for pointing this out. I got confirmation of the behaviour from Office.

**Comment by PeterCon** [comment]
Draft change for OT 1.9.1:

>Extra white space to be added after each subscript and superscript<ins> that occurs after a baseline element, and before each subscript and superscript that occurs before a baseline element</ins>. Suggested: 0.5 pt for a 12 pt font. (Note that, in some math layout implementations, a constant value, such as 0.5 pt, may be used for all text sizes. Some implementations may use a constant ratio of text size, such as 1/24 of em.)

See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by khaledhosny** [comment]
Looks good, thanks!

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
