### ISSUE TITLE
Registering font vendor ID

### ISSUE THREAD

**Issue by sanga-yoon** [MicrosoftDocs/typography-issues#1138]
I’ve sent two e-mail requests for registering the font vendor ID, but I didn't get any response. I’ve recently discovered that another vendor had the same problem and contacted the team through a GitHub issue. Is there a way to inform the relevant team that I sent a request?

**Comment by alib-ms** [comment]
Can you please let me know the vendor id you requested?

**Comment by sanga-yoon** [comment]
@alib-ms 
Thank you for your reply.
My font vendor ID was successfully registered yesterday; I will close this issue.
