### ISSUE TITLE
Times New Roman Special G1

### ISSUE THREAD

**Issue by Incangans** [MicrosoftDocs/typography-issues#1139]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0913b362-cbde-1c03-069c-db3f8900e8d3
* Version Independent ID: 8edc0f0e-b179-c9ac-6e2f-6e666dc03495
* Content: [Times New Roman Special font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/times-new-roman-special)
* Content Source: [typographydocs/font-list/times-new-roman-special.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/times-new-roman-special.md)
* Service: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
No actionable feedback, so closing.
