### ISSUE TITLE
[OpenType] Additional Language System Tag for Judeo-Tat

### ISSUE THREAD

**Issue by moyogo** [MicrosoftDocs/typography-issues#1143]
Judeo-Tat (also called Juhuri) [ISO 639-3: [jdt](https://iso639-3.sil.org/code/jdt)] uses Latin or Cyrillic scripts as writing systems.

It would be useful to have a Language System Tag for Judeo-Tat as follows:
| Language System | Language System Tag | Corresponding ISO 639 IDs or other information
| --------------- | ------------------- | ----------------------------------------------
| Judeo-Tat       | 'JDT '              | [jdt](https://iso639-3.sil.org/code/jdt)

In Latin script, when the character Ħ ‎0126 LATIN CAPITAL LETTER H WITH STROKE is used it most often has a vertical stroke through the middle bar of the H instead of a horizontal stroke through the top half of the H.
<img width="257" alt="Screenshot 2024-03-16 at 22 59 28" src="https://github.com/MicrosoftDocs/typography-issues/assets/1923747/863e3c4e-add2-4db6-ae35-ac157522bece">

In Cyrillic script, when the character Ћ ‎040B CYRILLIC CAPITAL LETTER TSHE is used it sometimes has a horizontal bar through the left vertical stem instead of at the top of the left vertical stem.

<img width="250" alt="Screenshot 2024-03-16 at 22 59 41" src="https://github.com/MicrosoftDocs/typography-issues/assets/1923747/149ce7d4-51a4-4616-93f7-06b026667eea">

References:
- Lorna A. Priest, *Request to document glyph variants*, L2/08-034R, 2008-04-18, https://www.unicode.org/L2/L2008/08034r-var-glyphs.pdf
- Я. М. Агарунов, М. Я. Агарунов, *Татско (Еврейско) - Русский Словарь*, Москва: Еврейский университет в Москве, 1997
- Я. М. Агарунов, М. Я. Агарунов, *Большой словарь языка джуури*, Абилов, Баку: Зейналов и сыновья, 2010
- Я. Машияхов, *Дэдэj*, СТМЭГИ, 2017
- М. Нафталиев, *Еврейско (джуури)-русский словарь*, СТМЭГИ, 2016

**Comment by moyogo** [comment]
@tiroj  L2/08-034R is the closest thing to it.

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
