### ISSUE TITLE
The apostrophe shows as a question mark

### ISSUE THREAD

**Issue by bobjansen** [MicrosoftDocs/typography-issues#1146]
The apostrophe shows as a question mark.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: f22b266b-5792-ffe5-451a-e7e1723a625b
* Version Independent ID: 180d504e-a389-bbbe-e318-d0b45bc8ca50
* Content: [Palatino Linotype font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/palatino-linotype)
* Content Source: [typographydocs/font-list/palatino-linotype.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/palatino-linotype.md)
* Service: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Thank you for the feedback. 
Fixed!
