### ISSUE TITLE
Sonar Bangla

### ISSUE THREAD

**Issue by nutan987654** [MicrosoftDocs/typography-issues#1149]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 1fee2063-26af-c7d8-c17f-d2e839c7ab55
* Version Independent ID: eddd8e49-0169-d57f-7db1-6c343fa12c03
* Content: [Shonar Bangla font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/shonar-bangla)
* Content Source: [typographydocs/font-list/shonar-bangla.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/shonar-bangla.md)
* Service: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
No actionable feedback. Closing.
