### ISSUE TITLE
Versions of Calibri

### ISSUE THREAD

**Issue by rillig** [MicrosoftDocs/typography-issues#115]
This article says that the Calibri version is 5.7x, while the Windows 10 version is already at 6.21. This is inconsistent.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c7cadc-6eb0-3a3a-b325-de0aa45e4852
* Version Independent ID: 65e39cbd-0456-87d9-2446-d46dd39dce71
* Content: [Calibri font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/calibri)
* Content Source: [typographydocs/font-list/calibri.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/calibri.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alib-ms** [comment]
Fixed.

**Comment by rillig** [comment]
Not quite. I have installed Windows 11, which is documented to have Calibri 6.23, but in fact I have Calibri 6.26. The Windows 11 page says:
> This is a list of fonts that shipped with Windows 11. Your versions numbers may be different if you did not apply Windows updates.

I did apply all updates, so the documentation should match reality.

**Comment by alib-ms** [comment]
To ensure that our fonts meet customer needs and comply with the Unicode standard, we frequently update them. As a result, I think I should update the webpage to let end-users know that they will have either the version mentioned below or a newer one.

**Comment by alib-ms** [comment]
I can also capture the latest version refresh the page with current version # for each font.
