### ISSUE TITLE
xc

### ISSUE THREAD

**Issue by waledys** [MicrosoftDocs/typography-issues#1151]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c18fbe05-9c0c-0623-36b3-60b60def56ea
* Version Independent ID: 5aa66091-abcf-f128-6e2f-377024e91244
* Content: [Engravers MT font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/engravers-mt#engravers-mt)
* Content Source: [typographydocs/font-list/engravers-mt.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/engravers-mt.md)
* Service: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by waledys** [comment]
x

**Comment by PeterCon** [comment]
No actionable feedback. Closing.
