### ISSUE TITLE
Broadway

### ISSUE THREAD

**Issue by markmcohen** [MicrosoftDocs/typography-issues#1153]
Broadway Font install

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0ddc81be-f3c0-106b-d242-430e04d17184
* Version Independent ID: 984d1db4-610b-15ec-48ae-dc4133083e32
* Content: [Broadway font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/broadway)
* Content Source: [typographydocs/font-list/broadway.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/broadway.md)
* Service: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
No actionable feedback. Closing.
