### ISSUE TITLE
ScriptLangTag Zsye?

### ISSUE THREAD

**Issue by DLasher106** [MicrosoftDocs/typography-issues#1155]
A paragraph in the `ScriptLangTag Values` section:

> On the other hand, “Zmth” (‘Mathematical notation’) and “Zsym” (‘Symbols”) are not used in the Unicode Standard, yet they may be very useful as declarations in font files. (They were, in fact, added to ISO 15924 for use in relation to fonts.)

Should “Zsym” (Symbols (Emoji variant)) be included here?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d8f6ed4e-64e4-2176-f903-c2778419d391
* Version Independent ID: bb311713-0340-4c84-180d-b0016a18fefe
* Content: [meta — Meta table (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/meta)
* Content Source: [typographydocs/opentype/spec/meta.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/meta.md)
* Service: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
I assume you mean "Zsye" rather than "Zsym". I don't know that it's the case that "Zsye" was added to ISO 15924 specifically for use in relation to fonts.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
