### ISSUE TITLE
Misspelled word

### ISSUE THREAD

**Issue by DLasher106** [MicrosoftDocs/typography-issues#1156]
Under `Class ID = 2 Transitional Serifs`, `Subclass ID = 1 : Direct Line`, the word **capitol** should be **capital**.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: d60e5136-3cd3-4046-0e62-e4ae1312bc1a
* Version Independent ID: d60e5136-3cd3-4046-0e62-e4ae1312bc1a
* Content: [IBM Font Family Classifications (OpenType 1.9.1) - Typography](https://learn.microsoft.com/en-us/typography/opentype/otspec191alpha/ibmfc)
* Content Source: [typographydocs/opentype/otspec191alpha/ibmfc.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec191alpha/ibmfc.md)
* Service: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
This dates back to the very first version of the TrueType spec. (Perhaps it might even have originated in IBM documentation.)

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
