### ISSUE TITLE
Language tag request for Khamyang 

### ISSUE THREAD

**Issue by ohbendy** [MicrosoftDocs/typography-issues#1157]
### Description

I wonder if we could register an OpenType language tag for [Khamyang language](https://en.wikipedia.org/wiki/Khamyang_language). I'm currently working on a [font](https://github.com/ohbendy/Phake-Ramayana) where we'd like to implement letterforms that differ from the Tai Phake and Tai Khamti shapes. Maybe `KHY ` or `KHYG` would work? 

### Page URL

https://learn.microsoft.com/en-us/typography/opentype/spec/languagetags

### Content source URL

https://github.com/MicrosoftDocs/typography-issues

**Comment by ohbendy** [comment]
Could we possibly also register an OT language tag for [Geba](https://en.wikipedia.org/wiki/Geba_Karen_language) (ISO 639-3 `kvq`)? We have tags for other Karen languages (S'gaw, Eastern Pwo, Western Pwo, Pa'O, Kayah) and I'd like to be able to control Geba shaping via LOCL rules.

**Comment by PeterCon** [comment]
'KSU ' has been registered for Khamyang. (The ISO 639 ID is used if there's no conflict and no need to distinguish.) 

'KVQ ' has been registered for Geba Karen.
