### ISSUE TITLE
Sitka font family changes for Windows 11

### ISSUE THREAD

**Issue by birdie-github** [MicrosoftDocs/typography-issues#1160]
### Description

Earlier Windows 10/11 releases had these font files for this family:
```
Sitka.ttc:  TrueType font collection data, 2.0, 6 fonts, digitally signed, at 0x30 TrueType Font data, 19 tables, 1st "GDEF"
SitkaB.ttc: TrueType font collection data, 2.0, 6 fonts, digitally signed, at 0x30 TrueType Font data, 19 tables, 1st "GDEF"
SitkaI.ttc: TrueType font collection data, 2.0, 6 fonts, digitally signed, at 0x30 TrueType Font data, 19 tables, 1st "GDEF"
SitkaZ.ttc: TrueType font collection data, 2.0, 6 fonts, digitally signed, at 0x30 TrueType Font data, 19 tables, 1st "GDEF"
3,850,612 B in 4 files
```

Win11_23H2_English_x64v2.iso seems to have dropped them in favour of:
```
SitkaVF.ttf:        TrueType Font data, digitally signed, 26 tables, 1st "DSIG", 78 names, Macintosh, \251 2020 Microsoft Corporation. All Rights Reserved.Sitka TextRegular1.00 b007;MS;SitkaTextVers
SitkaVF-Italic.ttf: TrueType Font data, digitally signed, 26 tables, 1st "DSIG", 90 names, Macintosh, \251 2020 Microsoft Corporation. All Rights Reserved.Sitka TextItalic1.00 b006;MS;SitkaText-Ital
1,076,064 B in 2 files
```

I'd love to get some clarification on that.

### Page URL

https://learn.microsoft.com/en-us/typography/font-list/sitka

### Content source URL

https://learn.microsoft.com/en-us/typography/font-list/sitka

**Comment by tiroj** [comment]
Sitka now ships as a TrueType flavour OpenType variable font. The same range of weights and optical size variants are included as in the previous TrueType Collection files, but now using OT variations technology to store them as deltas of a single outline set, significantly improving the file size efficiency and also enabling things like access to intermediate weights and automatic display of optical size design for the nominal text size.

**Comment by birdie-github** [comment]
@tiroj 

So, SitkaVF.ttf and SitkaVF-Italic.ttf are the right files, correct?

**Comment by kenmcd** [comment]
> So, SitkaVF.ttf and SitkaVF-Italic.ttf are the right files, correct?

Yes.
Below is a brief summary of the new variable fonts vs. the old static fonts.

Windows 10 Static Fonts

![Microsoft-Windows-Fonts-Guide--Sitka-test-from-LO_1-edited](https://github.com/MicrosoftDocs/typography-issues/assets/844920/28916aaf-3b44-4f2a-9dd6-6f26296cead1)


Windows 11 Variable Fonts

![Microsoft-Windows-Fonts-Guide--Sitka-test-from-LO_2-edited](https://github.com/MicrosoftDocs/typography-issues/assets/844920/ea8198ef-a2f5-488a-990a-41d47afe1b7d)
