### ISSUE TITLE
[USE] New InSC value Reordering_Killer

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#1173]
### Description

Unicode 16 has a new property value for the Indic syllabic category: Reordering_Killer.

This value needs to be supported in the USE cluster model.

### Page URL

https://learn.microsoft.com/en-us/typography/script-development/use

### Content source URL

https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/use.md

**Comment by NorbertLindenberg** [comment]
The PR doesn't change the existing overrides, which is good in the sense that the new values in the UCD's InSC don't affect the behavior of the USE in a negative way.

However, better would be to use the new value to recognize that a Batak Consonant-Virama sequence should not be separated from the preceding cluster, the way it's already done in UAX 15 for line breaking. Yet better would be to make the required reordering automatic in the USE. That would make hacks in Batak fonts such as the one described in the Glyph reordering section of [Constructing fonts for the Batak script](https://lontar.eu/en/notes/constructing-fonts-for-batak/index.html#Reordering) unnecessary.

**Comment by xadxura** [comment]
The problem with this structure in Batak is that it creates a general requirement for look-ahead. This is a very specific case which can be accommodated in a font's OT. The goal of USE has always been to provide a general basis for enabling script orthographies and expecting that OT will fill the gap between USE and script-specfic requirements.
