### ISSUE TITLE
[OpenType] Language System Tags for languages using Ŋ with N-shape

### ISSUE THREAD

**Issue by jmcwilliams403** [MicrosoftDocs/typography-issues#1175]
Ume Sámi [ISO 639-3: [sju](https://iso639-3.sil.org/code/sju)] and Pite Sámi [ISO 639-3: [sje](https://iso639-3.sil.org/code/sje)] in Norway and Sweden are two critically endangered languages that make orthographic use of Ŋ/ŋ.

As is customary for Sámi typography, the preferred form for the capital is modeled after the ordinary capital N, like that of Inari Sami 'ISM ' [smn], Lule Sami 'LSM ' [smj], Northern Sami 'NSM ' [sme], and Skolt Sami 'SKS ' [sms], as opposed to the far greater number of African languages that use a form modeled after an enlarged version of the lowercase letter.

Language System | Language System Tag | Corresponding ISO 639 IDs or other information
---|---|---
Ume Sami | 'SJU ' | [sju](https://iso639-3.sil.org/code/sju)
Pite Sami | 'SJE ' | [sje](https://iso639-3.sil.org/code/sje)

See:
* https://en.wikipedia.org/wiki/Eng_(letter)#Appearance
* https://en.wikipedia.org/wiki/Ume_S%C3%A1mi
* https://en.wikipedia.org/wiki/Pite_S%C3%A1mi
* https://en.wikipedia.org/wiki/S%C3%A1mi_languages#Orthographies and https://en.wikipedia.org/wiki/S%C3%A1mi_orthography

**Comment by PeterCon** [comment]
The proposed tags have been added.
