### ISSUE TITLE
Almost duplicate paragraphs

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#118]
There are two similar paragraphs beginning “Users don’t view or print characters” one right after the other.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b15ab9e-86c5-f6e0-0145-f9de77c60141
* Version Independent ID: 0ebe3dec-cc24-b6a4-01b8-73bfdb79a71a
* Content: [Advanced typographic tables - OpenType Layout - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/ttochap1)
* Content Source: [typographydocs/opentype/spec/ttochap1.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/ttochap1.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Thanks for pointing this out. This is an editorial error introduced in version 1.8.3: the first of the two paragraphs in the current text was intended to be a replacement for the second, but the second did not get deleted.

**Comment by PeterCon** [comment]
Fixed.
