### ISSUE TITLE
Typo: "OpenTypeTM"

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#12]
“OpenTypeTM” should be “OpenType™”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c96a4645-95e0-891a-7209-5b940e4fd84e
* Version Independent ID: 3646ed53-e094-d551-9283-2f4293b00b18
* Content: [Microsoft font properties editor - Typography](https://docs.microsoft.com/en-us/typography/tools/font-properties-editor)
* Content Source: [typographydocs/tools/font-properties-editor.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/tools/font-properties-editor.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
Done!
