### ISSUE TITLE
Feature recognition algorithm

### ISSUE THREAD

**Issue by mta452** [MicrosoftDocs/typography-issues#120]
The OpenType spec defines a feature as: `Features define the functionality of an OpenType Layout font and they are named to convey meaning to the text-processing client. Consider a feature named 'liga' to create ligatures. Because of its name, the client knows what the feature does and can decide whether to apply it.`

Regarding implementation, the spec says: `After choosing which features to use, the client assembles all lookups from the selected features. To implement features, a client applies the lookups in the order the lookup definitions occur in the LookupList. As a result, within the GSUB or GPOS table, lookups from several different features may be interleaved during text processing.`

However the spec does not specify which feature a client should recognize from a lookup if it belongs to multiple features being applied simultaneously. Consider two features, `liga` and `dlig` as an example. The `liga` feature contains lookups `1` and `2` while the `dlig` feature contains lookups `2` and `3`. After assembling their lookups, lookup `1` would be associated with `liga` and lookup `3` would be associated with `dlig`.  But there are different ways to recognize lookup `2`.
* Associate it with the first feature being assembled, i.e. `liga`. 
* Associate it with the last feature being assembled, i.e. `dlig`.
* Associate it with all assembled features, i.e. `liga` as well as `dlig`.

It would be really helpful if an algorithm is standardized for this purpose.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb42967-20ca-9270-4572-65315127fcc5
* Version Independent ID: 1fa413f1-71cf-ac2a-0999-70dd5d8ac4cd
* Content: [OpenType layout common table formats - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/chapter2#slTbl_sRec)
* Content Source: [typographydocs/opentype/spec/chapter2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/chapter2.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
"Client" refers to a text layout engine used for presenting text. In layout processing, the engine never needs to derive a feature from a particular lookup. It only processes in the other direction: from features to lookups. 

Features are an activation mechanism: for a given run of text, a feature tag is derived from rich text formatting information or, in some cases (for correct script behaviours) derived from analysis of the Unicode string; and then the corresponding Feature table is used to determine Lookup tables that should be processed for layout of that text run.

The only scenario in which one might want to go from lookups to features would be in a font development tool: knowing the action taken in a given lookup, the tool might be able to determine an appropriate feature tag to associate that lookup with. But in the general case, and in the case of your liga/dlig example, that would be at the font-designers discretion and not something that could be predicted algorithmically. Even if algorithms could be written for some cases, that would be beyond the scope of the OpenType spec.
