### ISSUE TITLE
Examples 7-18

### ISSUE THREAD

**Issue by Gilbertcocteau** [MicrosoftDocs/typography-issues#125]
Have you decided to keep just Examples 1-6? Are the Examples 7-18 gone forever? If they are, text like "Example 7 at the end of this chapter..." should be corrected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f748ff4-44a6-6395-e0ce-d249b8c9541b
* Version Independent ID: b80d0359-5657-632b-29e8-142c06902001
* Content: [GPOS — Glyph Positioning Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/gpos)
* Content Source: [typographydocs/opentype/spec/gpos.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gpos.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
It's not clear how it happened, but the omission wasn't intentional. Thanks for pointing it out.

**Comment by PeterCon** [comment]
Fixed.

**Comment by Gilbertcocteau** [comment]
Thank you for your quick response.
