### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by punchcutter** [MicrosoftDocs/typography-issues#127]
The NOTE at the top of this page points to https://docs.microsoft.com/en-us/typography/OpenTypeDev/USE/intro.md which does not exist. It should point to https://docs.microsoft.com/en-us/typography/script-development/use

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b136ee1d-ce2e-f8cb-47ef-fe1181b73a50
* Version Independent ID: b48c1d37-72b0-7893-d248-2514bf4a7661
* Content: [Creating and Supporting OpenType Fonts for the Javanese Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/javanese)
* Content Source: [typographydocs/script-development/javanese.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/javanese.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment]
Closing as Fixed.
