### ISSUE TITLE
Broken link to USE documentation

### ISSUE THREAD

**Issue by punchcutter** [MicrosoftDocs/typography-issues#128]
Same as on the Tibetan and Javanese pages. Only Tibetan has been fixed so far. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9e7e552c-421e-c810-76c5-fcfa68449999
* Version Independent ID: 86acabea-6d17-87d5-b9e6-03dcf845745a
* Content: [Creating and Supporting OpenType Fonts for the Buginese Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/buginese)
* Content Source: [typographydocs/script-development/buginese.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/buginese.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment]
Closing as Fixed.
