### ISSUE TITLE
Typo: "Mkmk"

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#13]
In the list of positioning features, “Mkmk” should be “mkmk”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afaf5060-fd0d-2b4c-7555-e3d81ccafe24
* Version Independent ID: 06c7f355-4cd9-4d0c-188b-4d65d4a5b406
* Content: [Creating and Supporting OpenType Fonts for Tibetan Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/tibetan)
* Content Source: [typographydocs/script-development/tibetan.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/tibetan.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
Done!
