### ISSUE TITLE
Wrong calculated value in interpolation example

### ISSUE THREAD

**Issue by mta452** [MicrosoftDocs/typography-issues#130]
In the last interpolation example, the result of `0.2 × -135 + 0.7 × -2` is written `-134.8`. The actual value, however, is `-27 + -1.4` = `-28.4` which is correctly depicted in the diagram.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ea55ee-53f0-15da-1819-6dbbd9ae0e51
* Version Independent ID: 5746bf07-2094-52b3-3285-dadc590006c7
* Content: [OpenType Font Variations overview - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otvaroverview#variation-data-tables-and-miscellaneous-requirements)
* Content Source: [typographydocs/opentype/spec/otvaroverview.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otvaroverview.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by alibasi** [comment]
Thank for letting us know. This has been fixed.
