### ISSUE TITLE
I try to solve my problem with trying to find a way to download the "Arial narrow" font

### ISSUE THREAD

**Issue by MovingMazes** [MicrosoftDocs/typography-issues#131]
If, on this page, I use the link : "Arial Narrow", it opens a new page. If then on the new page, i click on the link : 
"Purchase & Download Microsoft fonts for personal, professional or business use on workstations"
then I get an 404
PAGE NOT FOUND
error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ab667f80-7df3-bafa-0877-51e7af198d44
* Version Independent ID: cfd7b5d4-d79a-36d2-049e-a5d6fff1c270
* Content: [Fonts and supported products - Typography](https://docs.microsoft.com/en-us/typography/font-list/#feedback)
* Content Source: [typographydocs/font-list/index.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/index.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alib-ms** [comment]
It appears that the broken links were resolved quite some time ago, but the reported problem was not updated or marked as resolved.
