### ISSUE TITLE
Duplicated words: "anguage tags)." (Tamil)

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#14]
Appendix A ends with “(ie. you must add a space to the three character language tags).anguage tags).”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 29067dd3-10a9-4b1e-63fe-7c26ce6d29f8
* Version Independent ID: 0daa7215-4ccb-7c54-5598-6ac905f75e88
* Content: [| Microsoft Docs](https://docs.microsoft.com/en-us/typography/script-development/tamil)
* Content Source: [typographydocs/script-development/tamil.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/tamil.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
Done!
