### ISSUE TITLE
Squares

### ISSUE THREAD

**Issue by mekkablue** [MicrosoftDocs/typography-issues#140]
&gt; U+25FB	White medium square
&gt; U+25FC	Black medium square
&gt; U+25FD	White medium small square
&gt; U+25FE	Black medium small square
&gt; 
&gt; These glyphs may be used in text as generic bases and so should be enabled in mark positioning lookups supported by the font.

Squares as generic bases for mark positioning? Is this a mistake? Or is there a real-life example for that?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b136ee1d-ce2e-f8cb-47ef-fe1181b73a50
* Version Independent ID: b48c1d37-72b0-7893-d248-2514bf4a7661
* Content: [Creating and Supporting OpenType Fonts for the Javanese Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/javanese)
* Content Source: [typographydocs/script-development/javanese.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/javanese.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment]
Closing as Fixed
