### ISSUE TITLE
Incorrect prefix or description.

### ISSUE THREAD

**Issue by tnake** [MicrosoftDocs/typography-issues#141]
In the section of "Reorder Characters", the prefix of list item is inconsistent with description.
That is in the list item "4. Final reordering:", and list item following that, description of "Reorder reph:".
That description be written the steps number; eg "proceed to step 5.", "found in steps 3 or 4". However, as far as my web browser, their list item prefix show "a.", "b.", and "c.".
While descriptions even now use number characters, the style sheet of such list item is "list-style-type: lower-alpha;". Therefore, I think that such inconsistent is caused.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c1a0129-e23f-c785-89bc-25fb41b378c0
* Version Independent ID: b2a39f6a-94ed-b3ff-effb-17b2cc31b9e1
* Content: [| Microsoft Docs](https://docs.microsoft.com/en-us/typography/script-development/devanagari)
* Content Source: [typographydocs/script-development/devanagari.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/devanagari.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
Thank you for reporting this issue. Fixed!
