### ISSUE TITLE
Incorrect bracket pair.

### ISSUE THREAD

**Issue by tnake** [MicrosoftDocs/typography-issues#142]
The description of above- and below- base marks, the section of Position glyph sequences (GPOS processing), are ending with the closing parenthesis.
However, a matching opened parenthesis does not exist.(perhaps, I guess that such closing parenthesis is needlessness.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c1a0129-e23f-c785-89bc-25fb41b378c0
* Version Independent ID: b2a39f6a-94ed-b3ff-effb-17b2cc31b9e1
* Content: [| Microsoft Docs](https://docs.microsoft.com/en-us/typography/script-development/devanagari)
* Content Source: [typographydocs/script-development/devanagari.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/devanagari.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
Thank you for reporting this issue. Fixed!
