### ISSUE TITLE
why some bytes no comment in table and table?

### ISSUE THREAD

**Issue by ymx9600** [MicrosoftDocs/typography-issues#143]
I find that some bytes is not explanation between  2 tables.
For example,there is 2 bytes that is 00 00 after the cmap table and before the next table.
I want to read data what I want and reset file,but i don't no whether the data is useful.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 86923ff4-2b60-9144-e2b4-77cdb36fd698
* Version Independent ID: ea221e53-f51a-8233-3c0b-d416e5360623
* Content: [cmap - Character To Glyph Index Mapping Table - Typography](https://docs.microsoft.com/zh-cn/typography/opentype/spec/cmap)
* Content Source: [typographydocs/opentype/spec/cmap.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cmap.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by khaledhosny** [comment]
That is padding between the tables and should be ignored, see https://docs.microsoft.com/en-us/typography/opentype/spec/recom#table-alignment-and-length.

**Comment by ymx9600** [comment]
Thank you so much!

At 2018-12-07 01:43:30, "Khaled Hosny" <notifications@github.com> wrote:


That is padding between the tables and should be ignored, see https://docs.microsoft.com/en-us/typography/opentype/spec/recom#table-alignment-and-length.

**Comment by ymx9600** [comment]
I solved the problem a few days ago,but thank you all the same.
There are two font packs in the font file,where the sourceFile.TTF is  the font available that I modified through the tool file,and newTTF.ttf is  I extracted through my program.
Although it can be used,I found that the font and the text couldn't map, and I couldn't find many ways to do that, and I felt like I was at the end of my rope.
I don't no how to deal with the problem and I am very confused,so I need your help.

If possible, could you please look at my newTTF.ttf file and see what's wrong with it?
I need your help truly. Thank you. Thank you so much!





[font file.zip](https://github.com/MicrosoftDocs/typography-issues/files/2656242/font.file.zip)

**Comment by khaledhosny** [comment]
Looks like newTTF.ttf has an invalid cmap table.

**Comment by PeterCon** [comment]
No spec changes required.
