### ISSUE TITLE
How do I host the Sitka font for web?

### ISSUE THREAD

**Issue by rburkey87** [MicrosoftDocs/typography-issues#145]
I'd like to use the Sitka font family for a website, but I can't find a commercial license for it. I see that it says here that we don't have the rights to self-host system fonts. Where can I find a commercial license for it?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ea5ad39-ec78-af12-1479-e3def2c62723
* Version Independent ID: 4c9dbe2a-0d30-42fe-34be-38053fcf5c4e
* Content: [Font redistribution FAQ - Typography](https://docs.microsoft.com/en-us/typography/fonts/font-faq)
* Content Source: [typographydocs/fonts/font-faq.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/fonts/font-faq.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by FontBoss** [comment]
Sitka was commissioned by and is wholly owned by Microsoft. It's not currently available through one of our font licensing partners. I'll check with my colleagues to see if that is likely to change in the near future.

**Comment by rburkey87** [comment]
Thank you!

**Comment by wldl** [comment]
@FontBoss 
Legend say that he is still asking, to this day.

**Comment by dnnsjsk** [comment]
Any news on that matter @FontBoss?

**Comment by christopherritter** [comment]
Checking to see if there has been any activity on this issue @FontBoss ?

**Comment by alib-ms** [comment]
Segoe UI can be acquired from our licensing partner Monotype. [License Microsoft fonts](https://www.fonts.com/content/microsoft-typography) for enterprises, web developers, for hardware & software redistribution or server installations.

**Comment by rburkey87** [comment]
Sitka and Segoe are completely different fonts.

**Comment by alib-ms** [comment]
Sorry, updated my post. Segoe UI can be licensed from Monotype.

**Comment by FontBoss** [comment]
The question is about Sitka.

Best, Si

Sent from Outlook<http://aka.ms/weboutlook>
