### ISSUE TITLE
No single quotation marks

### ISSUE THREAD

**Issue by Gilbertcocteau** [MicrosoftDocs/typography-issues#147]
Shouldn't the baseline tags in the table be enclosed in single quotation marks like you did in the Script tag section?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 388203c1-4a7b-5480-43ae-65983202a5aa
* Version Independent ID: 2bac6e07-a47a-7a2d-6ca5-8b7e01831861
* Content: [Baseline tags - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/baselinetags)
* Content Source: [typographydocs/opentype/spec/baselinetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/baselinetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by v-nihar** [comment]
Closing as Fixed.
