### ISSUE TITLE
U+009D characters.

### ISSUE THREAD

**Issue by tnake** [MicrosoftDocs/typography-issues#149]
In the section of Appendices, a paragraph above the table of registered scripts and language systems tags contains two characters of U+009D, which are immediately following "&#39;dev2&#39;" and "&#39;deva&#39;".
This also had been pointed out at "#19 Extraneous U+009D". However, I think that this was only reflected to page of Bengali script.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c1a0129-e23f-c785-89bc-25fb41b378c0
* Version Independent ID: b2a39f6a-94ed-b3ff-effb-17b2cc31b9e1
* Content: [| Microsoft Docs](https://docs.microsoft.com/en-us/typography/script-development/devanagari)
* Content Source: [typographydocs/script-development/devanagari.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/devanagari.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
Thank you for reporting this issue. Fixed!
