### ISSUE TITLE
Duplicated words: "anguage tags)." (Telugu)

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#15]
Appendix A ends with “(ie. you must add a space to the three character language tags).anguage tags).”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f30d87bb-fd19-2037-05c1-114e61256d65
* Version Independent ID: d008266b-c95a-4aa1-e99a-2de6242169a5
* Content: [| Microsoft Docs](https://docs.microsoft.com/en-us/typography/script-development/telugu)
* Content Source: [typographydocs/script-development/telugu.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/telugu.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment]
Corrected issue.
Commit:
https://github.com/MicrosoftDocs/typography/pull/152/commits/d8d5cea3f251539ad298a4c37a903a36d8cab921

**Comment by alibasi** [comment]
Done!
