### ISSUE TITLE
Link is broken.

### ISSUE THREAD

**Issue by tnake** [MicrosoftDocs/typography-issues#154]
The referred document from link of "Creating and supporting OpenType fonts for Indic Scripts" does not exist.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c7943de-3f8a-35bb-4161-fe81702e3092
* Version Independent ID: 11014449-3ad3-4c87-a71a-c0a0d1e0df63
* Content: [OpenType glyph processing - Typography](https://docs.microsoft.com/en-us/typography/opentype/processing-part1)
* Content Source: [typographydocs/opentype/processing-part1.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/processing-part1.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment]
Closing as Fixed.
