### ISSUE TITLE
Single width cut in and value

### ISSUE THREAD

**Issue by jenskutilek** [MicrosoftDocs/typography-issues#155]
The OT spec says that the single width cut in and values only apply to MIAP and MIRP, but the description of MDRP also mentions single width being applied there.

Also what data type should both values have? In Graphics State summary it says pixels, but in SSW it says FUnits and in SSWCI 1/64th pixel.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8f3ce77-c18f-1036-ccc3-0de8c9354055
* Version Independent ID: 60e1d2a3-664c-ebc9-e6f2-4d7f201c0bed
* Content: [Graphics State Summary - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/tt_graphics_state)
* Content Source: [typographydocs/opentype/spec/tt_graphics_state.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/tt_graphics_state.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **v-nihar**

**Comment by PeterCon** [comment]
Got clarification that single_width_value and single_width_cut_in are used only for MDRP, MIRP (as reflected in Apple's specs). And, that the units for SSW is FUnits, but the interpreter converts into pixels (all pixels amounts on stack are F26Dot6 -- hence the meaning of 1/64ths).

Proposed changes for the next version have been made to clarify all of that.
