### ISSUE TITLE
HTML structure is broken slightly.

### ISSUE THREAD

**Issue by tnake** [MicrosoftDocs/typography-issues#159]
That is in the list of Uniscribe's shaping engines that is in section of "Uniscribe in Detail".
That list is written with ul and li element, but each list item contain the character reference(which is "&amp;lt;"), except that the first of list(Arabic).
So that, incorrect texts are displayed, such as "Hebrew<br/Hebrew, Thaana".
I think that use of character reference is inappropriate for this list. Rather, I think that use of br element is more appropriate.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1486e9b0-3aee-6b3f-d46d-89cbc67a2fd2
* Version Independent ID: 1d50d420-a803-4b12-d2a2-0ce9cd1f2606
* Content: [OpenType glyph processing - Typography](https://docs.microsoft.com/en-us/typography/opentype/processing-part2)
* Content Source: [typographydocs/opentype/processing-part2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/processing-part2.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment]
Closing as Fixed.
