### ISSUE TITLE
App doesn't work

### ISSUE THREAD

**Issue by ekatherina** [MicrosoftDocs/typography-issues#16]
I press "Open" button and choose ttf file, but it doesn't show anything in VOLT UI.

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 95b4f6e6-1a64-7950-5dea-33ebefbd65ca
* Version Independent ID: 0dab74f8-3cb7-2684-81d2-f0473de9e2f8
* Content: [Visual OpenType Layout Tool - Typography](https://docs.microsoft.com/ru-ru/typography/tools/volt/index)
* Content Source: [typographydocs/tools/volt/index.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/tools/volt/index.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment]
Added in training video link, however this issue is for the tool and not the website.

**Comment by najith97** [comment]
Even I face the same problem, what is the solution to it?

**Comment by hyvyys** [comment]
Where in the video is this explained??

**Comment by v-nihar** [comment]
The VOLT video was created for educational purposes. It does not cover all the features of OpenType not it answers all the issues.

A better place would be to post a quest at discussion forum such as [https://typedrawers.com/](https://typedrawers.com/)
