### ISSUE TITLE
Arabic font need improvement

### ISSUE THREAD

**Issue by boutayeb** [MicrosoftDocs/typography-issues#160]
The arabic typography is quite rich and beautiful but the default windows Segoe Arabic does not reflect that at all. It's a tiny font. It's not clear nor beautiful. Even the old version Arial Arabic was much better. Have a look for example at this typface style, really clean https://www.amirifont.org/.

Would mind improve the Arabic typography for the standard Segoe font?

Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3c2a6fb-3005-b23b-bc83-f8046b852851
* Version Independent ID: f5d0fbf0-990b-7b3d-0c4a-bd4b51c8532e
* Content: [Segoe UI font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/segoe-ui)
* Content Source: [typographydocs/font-list/segoe-ui.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/segoe-ui.md)
* Product: **typography**
* GitHub Login: @nihar
* Microsoft Alias: **mihar**

**Comment by boutayeb** [comment]
https://github.com/alif-type/amiri/releases/tag/0.111

**Comment by alib-ms** [comment]
Thank you for your feedback. Arabic in Segoe UI is designed for UI,purposes.  Have you tried Arabic support in Calibri?

**Comment by alib-ms** [comment]
This is feedback for Microsoft software products, not for the content in the Typography site. Please use feedback channels for the products in question, such as the Windows Feedback Hub.
