### ISSUE TITLE
Update Licensing Info Links

### ISSUE THREAD

**Issue by Bosef1** [MicrosoftDocs/typography-issues#161]
The link to fonts.com for licensing the font is incorrect; please have it updated.  In particular,
https://www.fonts.com/family/1283/ocr-b
goes to a 404 page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e88dec4-8d54-3761-586c-1ed0e384a963
* Version Independent ID: 5bb6c90a-fed4-5326-4c05-81b6f9d347d5
* Content: [OCRB font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/ocrb)
* Content Source: [typographydocs/font-list/ocrb.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/ocrb.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
Thank you for reporting this issue. Fixed!
