### ISSUE TITLE
[USE] Missing positional categories for medial consonants

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#162]
The document provides four subclasses for medial consonants: CONS_MED_ABOVE, CONS_MED_BELOW, CONS_MED_PRE, CONS_MED_POST. When mapping from the positional categories defined in the Unicode data to these subclasses, it only provides derivations for the positional categories Top, Bottom, Left, Right. The Unicode 11 data already has Bottom_And_Left for Javanese cakra, and a later version is likely to use Bottom_And_Right for Javanese pengkal.

---
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

ID: 194a6d3c-4137-46e9-3a4b-44b990200986
Version Independent ID: a0c8e788-5228-aa28-670e-3ba1ac3faecd
Content: [Creating and supporting OpenType fonts for the Universal Shaping Engine - Typography](https://docs.microsoft.com/en-us/typography/script-development/use)
Content Source: typographydocs/script-development/use.md
Product: typography

**Comment by xadxura** [comment]
These will be supported via overrides to IPC=Bottom, since, from the cluster model point of view, bottom meets the clustering requirement. Update to specify these overrides in the USE spec in PR.
