### ISSUE TITLE
[USE] No reordered medial consonant in Balinese

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#163]
The document states “Scripts such as Javanese and Balinese reorder a medial consonant to the beginning of a cluster based on context.” While this is true for Javanese cakra, I’m not aware of any medial consonants in Balinese for which this statement is true.

---
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

ID: 194a6d3c-4137-46e9-3a4b-44b990200986
Version Independent ID: a0c8e788-5228-aa28-670e-3ba1ac3faecd
Content: [Creating and supporting OpenType fonts for the Universal Shaping Engine - Typography](https://docs.microsoft.com/en-us/typography/script-development/use)
Content Source: typographydocs/script-development/use.md
Product: typography

**Comment by xadxura** [comment]
Pushed fix.
