### ISSUE TITLE
What is "id=ivsTbl" ?

### ISSUE THREAD

**Issue by tnake** [MicrosoftDocs/typography-issues#165]
In the section of the overview, there is a less mean paragraph which displays '&lt;id=&quot;ivsTbl&quot;&gt;'(which is imediatlly above caption of "Item Variation Store Overview".).
I think that, probably, this paragraph should not be displayed.
Instead, I propse that this is written as '&lt;p&gt;&lt;a id=&quot;ivsTbl&quot;&gt;&lt;/p&gt;' like other similar anchors.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8d3d5b8-059a-613d-8666-80438ebd7aa7
* Version Independent ID: 6a0f2873-97c3-833c-45e4-340ea96667a0
* Content: [GDEF — Glyph Definition Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/gdef)
* Content Source: [typographydocs/opentype/spec/gdef.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gdef.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by v-nihar** [comment]
Closing as Fixed.
