### ISSUE TITLE
Wrong code points for ZWNJ and ZWJ

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#167]
The section “Invalid Combining Marks” mentions the Unicode code points “ZWJ (zero width joiner; U+200C), the ZWNJ (zero width non-joiner; U+200D)”.

In actual Unicode, the code points are assigned differently: U+200C ZERO WIDTH NON-JOINER, U+200D ZERO WIDTH JOINER.

---
Document Details

⚠ Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.

- ID: aad9cb38-9a74-d136-23f6-0fdc5dca33c8
- Version Independent ID: ef6b84e4-d3a7-8c34-78ac-1b5788765fb8
- Content: [Developing OpenType Fonts for Khmer Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/khmer)
- Content Source: typographydocs/script-development/khmer.md
- Product: typography

**Comment by alibasi** [comment]
Thank you for reporting the issue. Fixed!
