### ISSUE TITLE
Incomplete description of 'slng'

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#17]
The description for 'slng' says “Only one instance See below for additional details.” It should be “Only one instance is used. See below for additional details.” as it is for 'dlng'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8f6ed4e-64e4-2176-f903-c2778419d391
* Version Independent ID: bb311713-0340-4c84-180d-b0016a18fefe
* Content: [meta — Meta table specification - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/meta)
* Content Source: [typographydocs/opentype/spec/meta.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/meta.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Fixed for the next version. Thanks!
