### ISSUE TITLE
Is Consolas open source?

### ISSUE THREAD

**Issue by KexyBiscuit** [MicrosoftDocs/typography-issues#173]
I mean, is https://github.com/PiotrGrochowski/Consolas [legitimate](https://github.com/PiotrGrochowski/Consolas/issues/1)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bebad8df-b4dd-251d-f63c-630239cf0bcd
* Version Independent ID: 81bc3207-d7c1-6b93-bd22-47771348961a
* Content: [Consolas font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/consolas)
* Content Source: [typographydocs/font-list/consolas.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/consolas.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by cup** [comment]
https://github.com/MicrosoftDocs/typography-issues/issues/173
https://github.com/PiotrGrochowski/Consolas/issues/1
https://github.com/PiotrGrochowski/Consolas/issues/2

**Comment by alibasi** [comment]
Thank you for your comment.  This issue is currently under review.  Consolas is not an open source font.  Please reference the “[Licensing Info](https://docs.microsoft.com/typography/fonts/font-faq)” section above.

**Comment by PiotrGrochowski** [comment]
The font (DMCA Sans Serif 9.0-20252) is now available at https://typedesign.netlify.com/dmcasansserif.html and it is officially not the same entity as Microsoft Consolas. It is a general-purpose sans-serif monospaced font with 3309 characters and 32 styles.

**Comment by cup** [comment]
@PiotrGrochowski lol

> Repository unavailable due to DMCA takedown.

https://github.com/PiotrGrochowski/Consolas

**Comment by PiotrGrochowski** [comment]
Don&#39;t worry, get the latest version of DMCA Sans Serif at  typedesign.netlify.com typedesign.netlify.com  github.com @PiotrGrochowski  lol  Repository unavailable due to DMCA takedown.  github.com github.com  —  You are receiving this because you were mentioned.  Reply to this email directly,  github.com view it on GitHub , or  github.com mute the thread .

**Comment by PiotrGrochowski** [comment]
that hacker behind MicrosoftDocs you monster

**Comment by PiotrGrochowski** [comment]
this font is now available at https://typedesign.netlify.com/dmcasansserif.html
