### ISSUE TITLE
Add note for Head::flags bit 3

### ISSUE THREAD

**Issue by be5invis** [MicrosoftDocs/typography-issues#175]
I observed that clearing this bit for hinted fonts will lead to incorrect results, especially for fonts intensively used delta hinting.
Per Greg Hitchcock: 
> We strongly recommend for all fonts that are hinted to set the integral PPEM flag.

**Comment by PeterCon** [comment]
Changed for next version:

> <b>Bit 3:</b> Force ppem to integer values for all internal scaler math; may use fractional ppem sizes if this bit is clear<ins>. It is strongly recommended that this be set in hinted fonts.</ins>
