### ISSUE TITLE
[USE] Tibetan scripts were not clustered correctly

### ISSUE THREAD

**Issue by shizhaowu** [MicrosoftDocs/typography-issues#176]
༁ཾཿ
This tibetan scripts cannot be clustered correctly. Possiblely because the last two chars 0xF7E & 0xF7F are both MIs, while two MIs are not valid in the current cluster analysis rule.

**Comment by xadxura** [comment]
Thank you for your feedback. Currently, Unicode does not define a syllbalic category for U+0F01 (༁) in the file [IndicSyllabicCategory.txt](http://www.unicode.org/Public/12.0.0/ucd/IndicSyllabicCategory.txt). As a result, it does not behave as a base that takes Tibetan marks (e.g., U+0F7E). If U+0F01 TIBETAN MARK GTER YIG MGO should combine, please provide documentation showing its combining behaviour to Unicode, [feedback](https://unicode.org/reporting.html)

**Comment by xadxura** [comment]
I did some additional research on this. I'm satisfied this should be added to the ISC overrides list:

0F01         ; Consonant # Lo       TIBETAN MARK GTER YIG MGO TRUNCATED

**Comment by xadxura** [comment]
Pushed fix to https://github.com/microsoft/font-tools/blob/master/USE/IndicSyllabicCategory-Additional.txt
