### ISSUE TITLE
Consonant_Medial inappropriate for Tai Tham

### ISSUE THREAD

**Issue by Richard57** [MicrosoftDocs/typography-issues#181]
The USE assumes that consonants of category Consonant_Medial are not followed by consonants of a different category within the stack.  This is chiefly falsified for Tai Tham because WA and LOW YA do not have medial forms; indeed &lt;SAKOT, WA&gt; and &lt;SAKOT, LOW YA&gt; often function as vowels.  Examples: ᨠᩖ᩠ᩅᩫ 'to fear', ᨷᩕ᩠ᨿᨷ 'to revise', ᨸᩖ᩠ᩅᨠ 'termite', ᩉᩖ᩠ᩅᩣ 'metal'.

The simplest solution is to override their InSC to Consonant_Subjoined. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 194a6d3c-4137-46e9-3a4b-44b990200986
* Version Independent ID: a0c8e788-5228-aa28-670e-3ba1ac3faecd
* Content: [Creating and supporting OpenType fonts for the Universal Shaping Engine - Typography](https://docs.microsoft.com/en-us/typography/script-development/use)
* Content Source: [typographydocs/script-development/use.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/use.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by xadxura** [comment]
Closing this issue while we wait for UTC script adhoc to approve revised details of Tai Tham handling.
