### ISSUE TITLE
Spurious HTML tag in page

### ISSUE THREAD

**Issue by brawer** [MicrosoftDocs/typography-issues#182]
There’s a spurious `&lt;/tr` at the beginning of [section A](https://docs.microsoft.com/en-us/typography/vendors/#a), between the section title and the table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d203fe-edb5-7fd0-88f1-40a688aee010
* Version Independent ID: 42388cb3-6080-2322-5f5f-5111f3b70ffb
* Content: [Registered typography vendors - Typography](https://docs.microsoft.com/en-us/typography/vendors/#a)
* Content Source: [typographydocs/vendors/index.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/vendors/index.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
Thank you for letting us know. Fixed!
