### ISSUE TITLE
"Format 2" at the end of Format 0

### ISSUE THREAD

**Issue by MaddTheSane** [MicrosoftDocs/typography-issues#185]
There is some badly formatted text at the end of the Format 0 section:
> Windows v3.1 does not make use of the 'kern' data other than to expose it to applications through the GetFontData() API.Format 2

It looks like "Format 2" was written twice: Once at the end of Format 0, and again as a section header for Format 2.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7055464b-3647-7ed6-573b-bf2c987bf69a
* Version Independent ID: 0e73b31b-f3f2-2def-be4f-6572b8712695
* Content: [kern - Kerning - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/kern#feedback)
* Content Source: [typographydocs/opentype/spec/kern.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/kern.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by v-nihar** [comment]
Closing as Fixed.
