### ISSUE TITLE
Does final paragraph need?

### ISSUE THREAD

**Issue by tnake** [MicrosoftDocs/typography-issues#186]
I think that it seems that final paragraph is corrupt, and there are duplicate portions too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc38f55-a142-6d66-fc68-1bb6e6e9ed56
* Version Independent ID: 0665d6f2-4150-1977-4fd6-91c50c226ed9
* Content: [OpenType Font Variations Common Table Formats - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otvarcommonformats)
* Content Source: [typographydocs/opentype/spec/otvarcommonformats.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otvarcommonformats.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by v-nihar** [comment]
Closing as Fixed.
