### ISSUE TITLE
Please put a list of all characters?

### ISSUE THREAD

**Issue by tomsku** [MicrosoftDocs/typography-issues#187]
in Cambria Math

---
#### Asiakirjan tiedot

⚠ *Älä muokkaa tätä osiota. Sitä tarvitaan kohteessa docs.microsoft.com GitHub-ongelmien linkityksessä.*

* ID: 69ddf8e0-1be1-8bc6-1ff2-4912f5be3718
* Version Independent ID: 1214071a-614d-ec8d-0227-a5a77eaefce5
* Content: [Cambria Math font family - Typography](https://docs.microsoft.com/fi-fi/typography/font-list/cambria-math)
* Content Source: [typographydocs/font-list/cambria-math.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/cambria-math.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
You can view all the character in the Cambria Math or any other font using the Charmap app.

**Comment by PiotrGrochowski** [comment]
charmap.exe does not show all characters

**Comment by alib-ms** [comment]
Please provide this feedback using the Feedback Hub Windows 10.

**Comment by PiotrGrochowski** [comment]
charmap.exe is a classic Win32 application, I don't think they do that kind of feedback
