### ISSUE TITLE
sbix originOffset clarification

### ISSUE THREAD

**Issue by bungeman** [MicrosoftDocs/typography-issues#191]
Since OpenType is (almost) always y-up I would interpret the documentation of originOffsetY to mean that positive values of originOffsetY will visually push the image down. However, DirectWrite seems to go in the opposite direction (positive values push the bottom of the image up from the baseline). FreeType appears to follow the specification as written (positive values push the bottom of the image down from the baseline). CoreGraphics appears to agree with DirectWrite in direction but not with anyone else for origin (positive values push the bottom of the image up from the bottom of the cbox of the outline from the glyf table, or something like that).

There are similar issues with originOffsetX. From my reading the documentation it isn't clear which way to go. The first sentence implies that positive values should make the image move left, the second sentence implies that positive values should make the image move right. It appears all implementations have positive values move the image to the right, but DirectWrite and FreeType add this value to the original glyph origin where CoreGraphics appears to add the lsb from the hmtx table first (the left of the cbox of the outline from the glyf table).

As a result, if I try to create an sbix glyph with the image origin off both the x and y axis I get different results on all three major implementations. As a result, I would request that there be some clarification of both where the 'origin' is (the original glyph origin on the baseline or the lower left of the cbox from the glyf) and which direction positive values off originOffsetX/Y should visually move the image.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a3b23c7e-abea-878a-d732-ea49acee6426
* Version Independent ID: cf0683db-45b4-d9ff-73d0-5769895dffa5
* Content: [SBIX - Standard Bitmap Graphics Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/sbix)
* Content Source: [typographydocs/opentype/spec/sbix.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/sbix.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by bungeman** [comment]
Attaching an example to illustrate the issue. The test.zip attached has a simple index.html and a planetsbix.ttf with offsets designed around what FreeType currently does (the font has positive values for originOffsetY which it expects to push the image down). The intent is that the planets have their centers on the baseline, and the bottom left rings of Saturn should extend slightly to the left of the advance position (underhang). Viewing this page in Chrome, Edge, and Safari gives three different results for positioning.

Chrome will be using FreeType and works the way one would expect (since the font was designed that way, and was debugged into existence this way using ftview). Safari will draw all of the glyphs more or less on the baseline since the cbox bounds are in the "right" place and the positive originOffsetY is pushing the image up from the bottom of the cbox. Edge draws all of the images way above the baseline since it uses positive values of originOffsetY to move up from the baseline.

Note that on Safari Saturn is much closer to Jupiter (and further from Uranus) than either Chrome or Edge, since Safari is applying both the lsb and the originOffsetX (both of which will move the image to the left).

Also note that DirectWrite itself doesn't appear to force a particular interpretation of these numbers and seems to just report them through DWRITE_GLYPH_IMAGE_DATA. However, the documentation for DWRITE_GLYPH_IMAGE_DATA doesn't make it clear what origin to apply the values to. I'm using Edge as an example since I'm assuming it's the app closest to the DirectWrite team.

[test.zip](https://github.com/MicrosoftDocs/typography-issues/files/2958282/test.zip)

**Comment by bungeman** [comment]
Further note that bits of this confusion are starting to be documented elsewhere. For example https://glyphsapp.com/tutorials/creating-an-apple-color-font in the section "Controlling Width, Scale and Position". The documentation there describes how to make a CoreGraphics flavor sbix glyph with the image off the axes by adjusting the glyf outline and keeping originOffsetX/Y at 0. I'm not sure of the behavior of other font authoring tools.

**Comment by bungeman** [comment]
Just to clarify, Chrome on Linux and Windows will use FreeType here. Chrome on Mac will use CoreGraphics and position the images on the baseline like Safari (note that there may be other visual issues I created this font to demonstrate, such as https://bugs.chromium.org/p/skia/issues/detail?id=7746 ).

**Comment by bungeman** [comment]
A note on the seemingly odd behavior of CoreGraphics of interpreting an originOffsetX/Y of 0 as putting the lower left corner of the sbix image at the lower left of the bbox of the glyph in the 'glyf' table. It appears that CTFontGetBoundingRectsForGlyphs (and all other means of getting bounding rectangles for glyphs through CT/CG) return the bbox of the glyph in the 'glyf' table, ignoring the size or placement of any image from the 'sbix' table and also ignoring the size and placement of any layer glyphs from the 'COLR' table (this causes issues computing damage rectangles or deciding when to draw a glyph when the sbix image falls outside the bounds or a 'COLR' layer glyph extends outside the bounds of the base glyph).

As a result of this behavior, it isn't currently possible to just leave the lower left of the bbox in the 'glyf' table at 0 (and in the planet font example use negative values of originOffsetY) to make things work correctly with both Edge and Safari, since this will cause drawing issues when using the font with CoreGraphics (DirectWrite/Edge shouldn't care what the bbox in the 'glyf' table is and should get the right bounds, but using just CoreGraphics it isn't possible to know the bounds of the drawing without ensuring that the bbox in the 'glyf' table covers the entire sbix image). Note that this would also just be a work-around for this particular font, if I wanted to also have a 'glyf' entry (for fallback, for example) then any non-0 lower left of the bbox would throw things off due to the differing origins.

The other result of this behavior is that using negative values for either of originOffsetX/Y with CoreGraphics means drawing outside of reported bounds, making it impossible to calculate re-draw correctly (knowing when a glyph should be drawn).

Now, this bounds issue may just be something which needs to be corrected in CTFontGetBoundingRectsForGlyphs, but it may explain the odd default of moving the sbix image with the 'glyf' bbox. However this came about it seems an unfortunate extra translation since it makes it a bit difficult to reason about where the image will actually be drawn, as well as needlessly bringing the 'glyf' table into this. On the other hand, it appears most sbix fonts are used by and created for this system, so other systems should probably match the basic behavior.

So after all of that, probably the easiest change overall in terms of specification would be:
* If there is a 'glyf' entry for the glyph, move the sbix-glyph-origin from the glyph-origin to the bottom left of the bbox
* positive originOffsetX shift the image right
* positive originOffsetY shift the image up

Anything else would probably require behavior changes in CoreText / CoreGraphics.

**Comment by drott** [comment]
@nedley @litherum - it'd be great if you could comment here and contribute your view of things. Thank you!

**Comment by apodtele** [comment]
In [FreeType](https://www.freetype.org/freetype2/docs/reference/site/ft2-base_interface.html#bitmap_left), the positive y-offset is up.

**Comment by bungeman** [comment]
FreeType does report the computed bitmap y-offset y-up as an API decision, but this is irrelevant here. If the earlier proposal is accepted, then the current behavior of FreeType is actually reporting the this value y-down for sbix, and will need to change. If simply making FreeType reverse the sign when adding this originOffsetY value caused all existing implementations place the image the same way I would have just opened an FreeType issue. However, this isn't enough, hence this request for clarification.

If you look at the planetsbix.ttf from the test.zip attached above and look into the sbix table at the originOffsetY values you will see that the values are positive. Opening this font in ftview will show that this positive value has pushed the images down from the baseline. Drawing with this font though CoreGraphics will show that it uses these positive values to push the image up from the bottom of the bbox of the entry in the 'glyf' table (Edge will use these positive values to push the image up from the baseline).

**Comment by bungeman** [comment]
To be more specific, the negative sign in FreeType at

http://git.savannah.gnu.org/cgit/freetype/freetype2.git/tree/src/sfnt/ttsbit.c?id=fbbcf50367403a6316a013b51690071198962920#n1584

seems to interpret originOffsetY as y-down.

**Comment by PeterCon** [comment]
I would assume CoreGraphics to be the reference implementation that others should conform to, unless Apple were to state that a bug was found showing their implementation to deviate from the intent, or showing that there's a gap in what their implementation anticipated.

After confirming what the expected implementation should be, the question for the spec is whether it is incomplete or unclear in communicating the intent.

**Comment by PeterCon** [comment]
There were clear errors in the descriptions for originOffsetX and, especially, for originOffsetY field. It may have been possible to infer what was intended, but not as clear as it should be. 

The intent has been confirmed with Apple, and the following is a proposed draft of corrected and clarified text for the next version. That should make clear the intent for the coordinate system.

><table>
<tr>
<td>int16</td>
<td>originOffsetX</td>
<td>The horizontal (x-axis) <del>offset from</del><ins>position of</ins> the left edge of the <ins>bitmap </ins>graphic <ins>in relation </ins>to the glyph’s origin. That is, the x-coordinate of the point on the baseline <del>at</del><ins>of</ins> the left edge of the <del>glyph</del><ins>graphic</ins>.</td>
</tr>
<tr>
<td>int16</td>
<td>originOffsetY</td>
<td>The vertical (y-axis) <del>offset from</del><ins>position of</ins> the bottom edge of the <ins>bitmap </ins>graphic <ins>in relation </ins>to the glyph’s origin. That is, the y-coordinate of the <del>point on the baseline at the left edge of the glyph</del><ins>bottom of the graphic</ins>.</td></table>

...

<ins>The originOffsetX and originOffsetY values gives the placement of the bitmap graphic in relation to the standard coordinate system of the glyph design space. For example, if originOffsetX equals 20, the left edge of the bitmap is place 20 units to the right of the origin; if originOffsetY equals -30, then the bottom edge of the graphic is 30 FUnits below the baseline.</ins>

**Comment by PeterCon** [comment]
>CoreGraphics appears to agree with DirectWrite in direction 

The draft revision should be consistent with that.

>but not with anyone else for origin (positive values push the bottom of the image up from the bottom of the cbox of the outline from the glyf table, or something like that).

I'll check with Apple on that, and leave this issue open until I get confirmation.

**Comment by PeterCon** [comment]
With clarification from Apple, updating the draft for the new paragraph after the table:

><ins>The originOffsetX and originOffsetY values give the placement of the bitmap graphic in relation to the standard coordinate system of the glyph design space. For example, if originOffsetX equals 20, the left edge of the bitmap is place 20 units to the right of the origin; if originOffsetY equals -30, then the bottom edge of the graphic is 30 FUnits below the baseline.</ins>
>
><ins>When placing the graphic within the line of text, the glyph design space origin is placed at the starting drawing position for this glyph. The lsb value for the current glyph ID from the &#39;hmtx&#39; table has no effect.</ins>

**Comment by PeterCon** [comment]
@bungeman : please check the proposed revisions and let me know if there are lingering ambiguities.

**Comment by behdad** [comment]
> ...in relation to the standard coordinate system of the glyph design space.

Suggest using "horizontal origin".

**Comment by PeterCon** [comment]
> > ...in relation to the standard coordinate system of the glyph design space.
> 
> Suggest using "horizontal origin".

Your suggestion isn't clear to me, particularly in relation to the portion of the draft you quoted. 

There's a particular reason for mentioning "the standard coordinate system of the glyph design space" since the report indicated confusion regarding how positive or negative X or Y values should be interpreted—i.e., in what directions do the coordinate scales for originOffsetX and originOffsetY go. I don't think that can be left out.

The second paragraph in the draft addition is intended to clarify placement of the "origin" that these fields are relative to. Two things mentioned in what was reported should be clear: (i) outline bounding box is not relevant, and (ii) lsb is not relevant. The two sentences in the draft should clarify each of those. 

Now "horizontal origin" could perhaps be used in the first sentence, though some might be left wondering why vertical position isn't clarified. In earlier drafts I discussed with Apple, I had tried mentioning the baseline or advance point (that term is used in Apple's spec", having in mind a _default_ glyph position before GPOS etc.; and also tried mentioning that positioning could be modified by GPOS. But it seemed best to me and Apple folk to leave out extra details and simply use the wording "the starting drawing position for the glyph".

**Comment by behdad** [comment]
Whatever works for you.

**Comment by bungeman** [comment]
Unfortunately this wording does not accurately describe how CoreText works. I just tried on macOS Big Sur 11.0 Beta 6 and the behavior has not changed, and at least this last line ("The lsb value ... has no effect") is not what happens with CoreText. CoreText currently takes the user provided draw position (where the glyph is to be nominally drawn), calculates the bounds of the glyph outline in the 'glyf' table (usually just a lower left and upper right point with no area, though it doesn't have to be) and uses the lower left of that as the 'sbix origin'. Then the originOffsetX/Y are applied to that 'sbix origin' to place the lower left of the sbix image.

The additional wrinkle here is that the 'glyph bounds' reported by CoreText are just the bounds of the 'glyf' entry and currently do not take the additional shift (or actual bounds of the image itself) into account. The only way to make things work out consistently with CoreText at the moment is to always leave originOffsetX/Y at 0 and translate the 'glyf' entry. (Also I just noticed that, at least with sbix fonts, if the hmtx entry for a glyph has an advance width of 0 the entire bounds seem to be forced to empty, which is probably just a bug that needs to be reported.)

I'm not sure what to take from the clarification from Apple. Perhaps they aren't aware of the current actual behavior (which has been the same for quite some time now)? The proposed wording does seem to reflect how DirectWrite seems to currently work, which isn't the same as CoreText. Note that Apple Color Emoji has, as far as I know, always used originOffsetX/Y of zero and the lower left of the 'glyf' entry at the origin. Since everything has been zero in that font it "works" pretty much however the data is interpreted.

**Comment by bungeman** [comment]
To demonstrate I went and manually created this test font [color-font.zip](https://github.com/MicrosoftDocs/typography-issues/files/5203823/color-font.zip) and some simple index.html files to look at it in a browser. This font (as opposed to the planet font in the test.zip previously provided) was made with CoreText as the target. This font has a wide space, and maps abcde and vwxyz to the same images, respectively. The abcde glyphs all have originOffsetX/Y set to zero and are translated by adjusting the 'glyf' entries. The vwxyz glyphs have all 'glyf' entries bounds set to the EM and then use originOffsetX/Y to translate the glyph image. 'a' and 'v' (the red) are both at the origin and have everything set to zero as reference. The others are placed at offsets so as to have their pointer lines going toward the 'a' or 'v'.

CoreText blindly drawing these without regard to the reported bounding boxes should (and does in Safari) draw as expected and both sets draw the same. The abcde will have proper bounds and generally work; however the vwxyz set will not. While initially the vwxyz set seems to draw correctly in Safari, there will be issues with redraw (scrolling, selecting, etc). Chromium on Mac will use CoreText but will not draw outside the bounds so abcde draw as expected but vwxyz will not (it will draw only the potion which Safari won't have issues re-drawing).

However, with the proposed wording (and currently on both FreeType and DirectWrite) the abcde portion would not take the 'glyf' entries into account at all and just dump all the glyphs on top of each other. This is what Chromium will end up doing on platforms without CoreText at the moment. Of course with the vwxyz set DirectWrite and FreeType will further diverge in the y direction (which was the original motivation for this issue).

**Comment by bungeman** [comment]
I suppose the real point of all of this explanation is that while it would be nice if things worked the way the proposed wording indicated that would be great; however if someone actually followed the proposed wording as a guideline the result would be the creation of fonts which are problematic on the system where they are most used. At the very least hit testing and redraw would end up being incorrect. Arguably that could just mean file bugs until the behavior matches the specification, but in this case it seems the specification is trying to document the implementation.

**Comment by bungeman** [comment]
I suppose I should have phrased that as "in this case it seems the specification is trying to document the implementation (but documenting the DirectWrite implementation and not the CoreText implementation)".

**Comment by PeterCon** [comment]
As I said earlier, I take CoreText to be the reference for this. My draft revisions were prepared without any input from DWrite folk.

**Comment by PeterCon** [comment]
Apple acknowledged there was more going on: a distinction between whether the 'glyf' table has an outline or not. Based on their further input, here's the revised draft:

><table>
<tr id="originOffsetX">
<td>int16</td>
<td>originOffsetX</td>
<td><del>The horizontal (x-axis) offset from the left edge of the graphic to the glyph’s origin. That is, the x-coordinate of the point on the baseline at the left edge of the glyph.</del><ins>The horizontal (x-axis) position of the left edge of the bitmap graphic in relation to the glyph design space origin.</ins></td>
</tr>
<tr id="originOffsetY">
<td>int16</td>
<td>originOffsetY</td>
<td><del>The vertical (y-axis) offset from the bottom edge of the graphic to the glyph’s origin. That is, the y-coordinate of the point on the baseline at the left edge of the glyph.</del><ins>The vertical (y-axis) position of the bottom edge of the bitmap graphic in relation to the glyph design space origin.</ins></td>
</tr>
</table>

<ins>The originOffsetX and originOffsetY values give the placement of the bitmap graphic in relation to the standard coordinate system of the glyph design space. For example, if originOffsetX equals 20, the left edge of the bitmap is place 20 units to the right of the origin; if originOffsetY equals -30, then the bottom edge of the graphic is 30 FUnits below the origin.</ins>

<ins>When placing the graphic within the line of text, the placement depends upon whether there are contours in the [&#39;glyf&#39;](glyf.md) table for the current glyph ID:</ins>

* <ins>If there is no glyph contour, the glyph design space origin for the graphic is placed at the starting drawing position for this glyph.</ins>

* <ins>If there is a glyph contour, the glyph design space origin for the graphic is placed at the lower left corner of the glyph bounding box (xMin, yMin).</ins>

<ins>In either case, the lsb value for the current glyph ID from the &#39;hmtx&#39; table has no effect.</ins>

**Comment by bungeman** [comment]
This mostly looks good, but I would leave off the last line "In either case, the lsb value for the current glyph ID from the 'hmtx' table has no effect." And maybe put "The lsb value for the current glyph ID from the 'hmtx' table has no effect." after the sentence starting "If there is no glyph contour...".

To test this I created an updated color font set 
[color-font.zip](https://github.com/MicrosoftDocs/typography-issues/files/5209365/color-font.zip) which in addition has a colorheads-lsb.ttf in which all of the entries for abcde in the 'glyf' table are adjusted for the left to be at 0 but the lsb left as it was (b, d, and e have non-zero lsb), allowing the xMin to differ from the lsb (so no setting bit 1 of the flags in the 'head' table). This works as one would expect with CoreText, it appears the 'glyf' outline is loaded normally so the xMin != lsb translates the outline by the difference, so all the glyphs are drawn just as they were in the normal colorheads.ttf where the xMin is always equal to the lsb. So the lsb value does apply in the case where there is a glyph contour, as one would expect.

I've also verified the 'no glyph contour' case. If the 'glyf' entries are completely empty (repeated 'loca' entry) CoreText seems to take that as a zero sized outline at the origin and doesn't apply the lsb to it (tested with colorheads-emptyglyf). It will draw it when requested, but the bounds will currently be reported as empty (though this is likely a bug). Note that 'bare sbix' doesn't seem to be supported by CoreText, the colorheads-noglyf.ttf is the same font but with the 'loca' and 'glyf' tables removed and CoreText appears to not load the font at all (unsure if this is by design or not).

**Comment by PeterCon** [comment]
>This mostly looks good...

Makes sense. Revised draft:

><table>
<tr id="originOffsetX">
<td>int16</td>
<td>originOffsetX</td>
<td><del>The horizontal (x-axis) offset from the left edge of the graphic to the glyph’s origin. That is, the x-coordinate of the point on the baseline at the left edge of the glyph.</del><ins>The horizontal (x-axis) position of the left edge of the bitmap graphic in relation to the glyph design space origin.</ins></td>
</tr>
<tr id="originOffsetY">
<td>int16</td>
<td>originOffsetY</td>
<td><del>The vertical (y-axis) offset from the bottom edge of the graphic to the glyph’s origin. That is, the y-coordinate of the point on the baseline at the left edge of the glyph.</del><ins>The vertical (y-axis) position of the bottom edge of the bitmap graphic in relation to the glyph design space origin.</ins></td>
</tr>
</table>

<ins>The originOffsetX and originOffsetY values give the placement of the bitmap graphic in relation to the standard coordinate system of the glyph design space. For example, if originOffsetX equals 20, the left edge of the bitmap is place 20 units to the right of the origin; if originOffsetY equals -30, then the bottom edge of the graphic is 30 FUnits below the origin.</ins>

<ins>When placing the graphic within the line of text, the placement depends upon whether there are contours in the [&#39;glyf&#39;](glyf.md) table for the current glyph ID:</ins>

* <ins>If there is no glyph contour, the glyph design space origin for the graphic is placed at the starting drawing position for this glyph. The lsb value for the current glyph ID from the &#39;hmtx&#39; table has no effect.</ins>

* <ins>If there is a glyph contour, the glyph design space origin for the graphic is placed at the lower left corner of the glyph bounding box (xMin, yMin).</ins>

**Comment by bungeman** [comment]
This seems to be consistent with the behavior I've seen. Looks good to me.
