### ISSUE TITLE
URLs to pages top-level pages please.

### ISSUE THREAD

**Issue by bobh0303** [MicrosoftDocs/typography-issues#193]
Within the Microsoft Typography site, there are currently 10 top-level headings. Of those top-level headings the following can be referenced directly by URLs:

- Microsoft Typography  (https://docs.microsoft.com/en-us/typography/)
- About Microsoft Typography (https://docs.microsoft.com/en-us/typography/about)
- Font vendors (https://docs.microsoft.com/en-us/typography/vendors/)
- OpenType font development (https://docs.microsoft.com/en-us/typography/develop/)
- OpenType specs (https://docs.microsoft.com/en-us/typography/opentype/spec/)
- Tools (https://docs.microsoft.com/en-us/typography/tools/)

However the following cannot be referenced by URL:

- Fonts and typefaces
- Script development specs
- ClearType
- Legacy font technologies

Can you make it so all of them can be referenced?
Thx

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d43be991-71e4-56f0-fec0-df35d187a0b8
* Version Independent ID: 3ba72d0d-49d0-b525-5a0d-fbe56aa9329c
* Content: [About Microsoft Typography - Typography](https://docs.microsoft.com/en-us/typography/about)
* Content Source: [typographydocs/about.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/about.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
Thank you. This is by design as we currently do not have a landing page for all the top-level headings.
