### ISSUE TITLE
About Yahei font license

### ISSUE THREAD

**Issue by easysoft** [MicrosoftDocs/typography-issues#194]
Hello, we're a software company and we use Yahei font as the first font for our B/S software through css code.
And we support manual and documents for our users on our website which contain screenshot of our software and of course with Yahei font in these screenshots.

So my question is these screenshots need to buy extra license? Thanks a lot.

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: ab667f80-7df3-bafa-0877-51e7af198d44
* Version Independent ID: cfd7b5d4-d79a-36d2-049e-a5d6fff1c270
* Content: [Fonts and supported products - Typography](https://docs.microsoft.com/zh-cn/typography/font-list/?FID=350#feedback)
* Content Source: [typographydocs/font-list/index.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/index.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
This [FAQ ](https://docs.microsoft.com/en-us/typography/fonts/font-faq)explains what a customer can do with the fonts supplied with Windows.

**Comment by easysoft** [comment]
Sorry I don't find the case about yahei font. Just a few days ago, a news abount Yahei font, you can find on the Internet https://baijiahao.baidu.com/s?id=1627321833237898525&wfr=spider&for=pc

Yahei font is owned by Founder company and Microsft just has the using right. So please check my question again because It may effect every software copamny in China most of them using Yahei as the default font in theire software and thus their documents will contains images on website with Yahei font on it.

Thanks a lot.
