### ISSUE TITLE
YaHei font broken link

### ISSUE THREAD

**Issue by ariszlo** [MicrosoftDocs/typography-issues#196]
Clicking Microsoft YaHei at https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list
opens the Microsoft Yi Baiti page instead of this:
https://docs.microsoft.com/en-us/typography/font-list/microsoft-yahei

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0610f6-7c7b-b771-e635-84663af729db
* Version Independent ID: 50a9b23c-733c-c934-95dc-0bbd5d502fea
* Content: [Font List Windows 10 - Typography](https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list#feedback)
* Content Source: [typographydocs/fonts/Windows_10_Font_List.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/fonts/Windows_10_Font_List.md)
* Product: **typography**
* GitHub Login: @nihar
* Microsoft Alias: **nihar**

**Comment by alibasi** [comment]
Thank you for reporting this. Fixed.=!
