### ISSUE TITLE
还我http://www.microsoft.com/typography/cleartype/tuner/Step1.aspx

### ISSUE THREAD

**Issue by ahdung** [MicrosoftDocs/typography-issues#197]
还我http://www.microsoft.com/typography/cleartype/tuner/Step1.aspx
还我http://www.microsoft.com/typography/cleartype/tuner/Step1.aspx
还我http://www.microsoft.com/typography/cleartype/tuner/Step1.aspx

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: bf2300b8-71e0-a6fe-b12f-f47b2b9564c1
* Version Independent ID: e771c103-3be0-7747-0084-be7bdef7bf63
* Content: [Microsoft ClearType - Typography](https://docs.microsoft.com/zh-cn/typography/cleartype/index)
* Content Source: [typographydocs/cleartype/index.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/cleartype/index.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
The ClearType tuner page was retired. This can be viewed on the [Wayback Machine](https://web.archive.org/web/20090212095944/http://www.microsoft.com/typography/cleartype/tuner/Step1.aspx), 

We expect everyone to use the ClearType Tuner built into Windows from now on.

**Comment by ahdung** [comment]
@alibasi It is a very useful online tool for XP users, I request you guys let it return back please, no reason for closing a beneficial and harmless thing, right?

**Comment by ahdung** [comment]
A useful thing, exists before, but not now, this is a disappointment. If you want people like "docs.microsoft.com" more than old documentation system, please don't do anything disappointing.
