### ISSUE TITLE
Segoe UI - website use

### ISSUE THREAD

**Issue by comede** [MicrosoftDocs/typography-issues#199]
Hi, 
I would like to embed the segoe ui as the webfont for a website but I can't find any font provider where I can purchase this font. On fonts.com there are only other segoe versions like segoe tv or segoe script (https://www.fonts.com/de/font/microsoft-corporation). 
I also couldn't find any more informations in the End User License Agreements. 
Is this font licence-free and if yes, where can I download it?

Thank you!

**Comment by PaulDempsey-ms** [comment]
See https://docs.microsoft.com/en-us/typography/fonts/font-faq. 
Consider the open-source Selawik font, which is not restricted the way Segoe UI is: https://github.com/Microsoft/fonts

**Comment by alib-ms** [comment]
Segoe UI can be acquired from our licensing partner Monotype. [License Microsoft fonts](https://www.fonts.com/content/microsoft-typography) for enterprises, web developers, for hardware & software redistribution or server installations.
