### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by omarquelal2018** [MicrosoftDocs/typography-issues#2]
gracias por todo

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 8b54ea3c-81d8-f3bb-75c7-51320c585b49
* Version Independent ID: 010f5039-716b-4c64-b41e-f3835b975404
* Content: [Fonts - Typography](https://docs.microsoft.com/es-es/typography/fonts/)
* Content Source: [typographydocs/fonts/index.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/fonts/index.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by PeterCon** [comment]
Thanks for the feedback.
