### ISSUE TITLE
GPOS Type 4 / 6: Explicitly specify whether baseAnchorOffset can be NULL

### ISSUE THREAD

**Issue by be5invis** [MicrosoftDocs/typography-issues#200]
Ref: https://github.com/googlei18n/ufo2ft/issues/259
From @anthrotype

&gt; The OpentType spec does not explicitly mention that MarkBasePos subtables (GPOS lookup type 4) or MarkMarkPos subtables (GPOS lookup type 6) can have NULL offsets to Anchor tables; only for MarkLigaPos (lookup type 5) it mentions this explicitly.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f748ff4-44a6-6395-e0ce-d249b8c9541b
* Version Independent ID: b80d0359-5657-632b-29e8-142c06902001
* Content: [GPOS — Glyph Positioning Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/gpos#feedback)
* Content Source: [typographydocs/opentype/spec/gpos.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gpos.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Added "offsets may be NULL" in BaseRecord.baseAnchorOffsets and Mark2Record.mark2AnchorOffsets, for next version.
