### ISSUE TITLE
[USE] New vowel constraint for Tamil

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#205]
_The Unicode Standard_ 12.0 includes [a new table 12-26](https://www.unicode.org/versions/Unicode12.0.0/ch12.pdf#G734091) with a vowel constraint for Tamil. Accordingly, the following should be added to the “Independent Vowel (IV) plus Dependent Vowel constraints (DV)” section:

```
  0B85 0BC2       ; # TAMIL LETTER A, TAMIL VOWEL SIGN UU
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 194a6d3c-4137-46e9-3a4b-44b990200986
* Version Independent ID: a0c8e788-5228-aa28-670e-3ba1ac3faecd
* Content: [Creating and supporting OpenType fonts for the Universal Shaping Engine - Typography](https://docs.microsoft.com/en-us/typography/script-development/use)
* Content Source: [typographydocs/script-development/use.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/use.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by behdad** [comment]
@dscorbett do we need a patch for this in HarfBuzz?

**Comment by dscorbett** [comment]
I was hoping to get it in the spec first, but yes.

**Comment by xadxura** [comment]
Fix pushed.
