### ISSUE TITLE
The link to purchase and download the fonts is broken (404)

### ISSUE THREAD

**Issue by Clonkex** [MicrosoftDocs/typography-issues#206]
That's all. I wanted to purchase Berlin Sans FB Demi Bold but the link to do so comes up with 404.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea00eecc-6816-77be-6d53-a910e47d279e
* Version Independent ID: df6b0b98-073d-84bc-0f94-8e579aa0ebbb
* Content: [Berlin Sans FB font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/berlin-sans-fb)
* Content Source: [typographydocs/font-list/berlin-sans-fb.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/berlin-sans-fb.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
Thank you for letting us know. We will update the link.

**Comment by httpmax** [comment]
Hi. I too want to buy it but the link remains broken. :(
