### ISSUE TITLE
Issue https://github.com/MicrosoftDocs/typography-issues/issues/183 is closed

### ISSUE THREAD

**Issue by PiotrGrochowski** [MicrosoftDocs/typography-issues#208]
Issue https://github.com/MicrosoftDocs/typography-issues/issues/183 was closed by a mistake, probably bot.

**Comment by PeterCon** [comment]
Issue #183 is feedback for Microsoft software products, not for the content in the Typography site. Please use feedback channels for the products in question, such as the Windows Feedback Hub.
