### ISSUE TITLE
All instances of 65536 should be 65535

### ISSUE THREAD

**Issue by kenlunde** [MicrosoftDocs/typography-issues#209]
All four instances of 65536 in the CFF2 table specification should be 65535.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f3f1db1-b1f0-587c-0dbe-9e090b32c5d9
* Version Independent ID: 49bd6461-28c0-a133-77b1-617b8f2f5dab
* Content: [CFF2 - Compact font format version 2 table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/cff2#feedback)
* Content Source: [typographydocs/opentype/spec/cff2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cff2.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by alibasi** [comment]
Thank you for reporting this issue. We will fix and update here when done.

**Comment by alibasi** [comment]
Fixed!
