### ISSUE TITLE
'DHV ' is deprecated

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#21]
Dhivehi has two language system tags: 'DHV ' and 'DIV '. This page only mentions 'DHV ', but that tag is deprecated. It should mention both or just 'DIV '.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f13af92a-15c2-6551-da19-56043b140718
* Version Independent ID: b36855f6-c15e-615b-6c9f-9ff53d370c7d
* Content: [Developing OpenType Fonts for Thaana Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/thaana)
* Content Source: [typographydocs/script-development/thaana.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/thaana.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by PeterCon** [comment]
Fixed
