### ISSUE TITLE
Images being used to display fonts in documentation.

### ISSUE THREAD

**Issue by shinsetsu** [MicrosoftDocs/typography-issues#210]
Just wondering if this has been noted, and it could probably be easily cleaned up all at once? Perhaps the image is being used to display the text moving forward? As a legacy type display thing? It is however blurry as can be. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 066e3064-216a-ec82-0a23-6bb572dc08db
* Version Independent ID: ab853639-424f-a547-6dc8-f21cb73204b9
* Content: [Gill Sans MT Condensed font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/gill-sans-mt-condensed#feedback)
* Content Source: [typographydocs/font-list/gill-sans-mt-condensed.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/gill-sans-mt-condensed.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by shinsetsu** [comment]
![gill-sans-mt-ext-condensed-bold](https://user-images.githubusercontent.com/6089887/56700059-e480a900-66bd-11e9-905b-a6fe7b34f1a5.png)

I like the idea of keeping it an image so it natural to its appearance. Allowing people to look back on it in 15 years if needed. But the images do need to be cleaned up.  

Perhaps something to dig into?

**Comment by alibasi** [comment]
Thank you for pointing this out we will investigate this on our end.
