### ISSUE TITLE
Missing word

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#212]
The sentence “All decomposition glyphs used for the Syriac Abbreviation Mark but must be defined as mark glyphs” seems to be missing something between “but” and “must”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d7ea0b7-0363-c4b7-a9d8-bab46dd6a80a
* Version Independent ID: f64aee9e-4d52-cb98-bb88-ee482ba09995
* Content: [Developing OpenType Fonts for Syriac Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/syriac)
* Content Source: [typographydocs/script-development/syriac.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/syriac.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
Thank you for reporting the issue. We are correcting the wording.
