### ISSUE TITLE
This font is also included with Office 2019 but it isn't listed here.

### ISSUE THREAD

**Issue by joaopaulo1511** [MicrosoftDocs/typography-issues#213]
This font is also included with Office 2019 but it isn't listed here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3107a831-b448-cf8f-2994-883465f6b398
* Version Independent ID: 3e962bfc-6bc4-6ca7-3879-7ded5b44c348
* Content: [Lucida Calligraphy font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/lucida-calligraphy#feedback)
* Content Source: [typographydocs/font-list/lucida-calligraphy.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/lucida-calligraphy.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
You are correct. We need to update the information area for many fonts.
