### ISSUE TITLE
minor typos

### ISSUE THREAD

**Issue by mekkablue** [MicrosoftDocs/typography-issues#215]
find and replace: varible
with: variable

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dac86fb-3792-6630-ade2-32bfc4bba93a
* Version Independent ID: 9de5c023-f363-3e42-43c9-eac7793c8eaa
* Content: [STAT — Style Attributes Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/stat)
* Content Source: [typographydocs/opentype/spec/stat.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/stat.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by alibasi** [comment]
Thank you for letting us know. I will this fixed shortly.
