### ISSUE TITLE
Incorrect description of U+00B7

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#217]
U+00B7 has the description “middle dot, kana conjoctive”. That last word is misspelled, and anyway the kana middle dot is not U+00B7 but U+30FB.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 94ac16f5-ac66-b0f2-401b-e58b2ed160dd
* Version Independent ID: 6d51161e-f3fd-6096-878f-192165e622ce
* Content: [WGL4 character set U+0020 to U+00BB - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/wgl4b)
* Content Source: [typographydocs/opentype/spec/wgl4b.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/wgl4b.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Changed for next version to "middle dot".
