### ISSUE TITLE
Duplicate fi and fl

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#218]
Two code points have the PostScript name “fi” and two have the name “fl”. The names of U+F001 and U+F002 should have asterisks after them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 68b43370-6edf-e42d-8714-c901fc23964c
* Version Independent ID: 991fd196-590d-85c4-82f2-eee61ce78cfc
* Content: [WGL4 character set U+017F to U+1EF3 - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/wgl4e)
* Content Source: [typographydocs/opentype/spec/wgl4e.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/wgl4e.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by emuller-amazon** [comment]
Since U+F001 and U+F002 are PUA code points, I suspect that they should be removed from the list altogether.

**Comment by dscorbett** [comment]
That would not be appropriate, as they are part of the WGL4 character set, unless you mean removing them from WGL4 itself.

**Comment by PeterCon** [comment]
Hmmm... Not sure why PUA code points are listed at all. The F0?? characters are duplicating the FB?? characters, so seem redundant and I'm not sure why they would have ever have been recommended. My inclination would be to remove F001 and F002 altogether.

**Comment by tiroj** [comment]
As I recall, the F001 and F002 mappings for fi and fl ligatures on Windows preceded Unicode encoding of the ligatures in the Alphabetic Presentation Forms block, so were recorded in WGL4 for backwards compatibility.

**Comment by PeterCon** [comment]
@tiroj Plausible... except that FB01, FB02 date to Unicode 1.1. But I suppose there might have been a short windows of Unicode 1.0 TT overlap.

In any case, is there really a need to keep these in WGL at this point?

**Comment by PeterCon** [comment]
Given the possibility that F001/F002 might have been used in old documents but these should not be used in newer documents, it's probably best to remove these entries but add a note mentioning earlier inclusion of F001/F002 for compat with old documents.

**Comment by tiroj** [comment]
I would purge the PUA codepoints.

**Comment by tiroj** [comment]
As a general point, WGL4 has been superseded by other base sets, both within Microsoft (e.g. the set Office now requests for fonts) and in the wider type industry. I would consider removing it from the OT spec appendices.

**Comment by PeterConstable** [comment]
Besides being superseded, I don't think a character repertoire like this really belongs in the OT spec at all. But I'd treat that as a separate issue to be discussed separately. 

Cf. #561

**Comment by behdad** [comment]
Agree to remove these from the spec. In 20 years I didn't need them. As long as they are available from Unicode or Adobe, that's enough for implementations / whoever needs to consult them.

**Comment by PeterCon** [comment]
Fixed for next version: removed entries for F001, F002 and added footnote explaining the legacy usage.
