### ISSUE TITLE
Euro page is out of date

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#219]
The euro is no longer a proposed currency. It is already in general use. Various code pages already include it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1c4cd112-6c63-bdb9-8cfa-d8697b659a68
* Version Independent ID: fb414ab2-d056-ef00-db33-a8e6c214d887
* Content: [The euro currency symbol - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/euro)
* Content Source: [typographydocs/opentype/spec/euro.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/euro.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
In proposed revisions for the next version, this page as well as the WGL4 pages are removed from the OT spec. They have been moved elsewhere on the MS site:

<https://docs.microsoft.com/en-us/typography/develop/wgl4>
