### ISSUE TITLE
Typo: "sso2"

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#22]
“sso2” should be “ss02”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3b75f69-8bb1-88e5-05b9-035c9f3ec528
* Version Independent ID: 9a9af849-512e-5dfd-b9a6-c05480f34f01
* Content: [Registered features, p-t - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/features_pt)
* Content Source: [typographydocs/opentype/spec/features_pt.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_pt.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Fixed for the next version. Thanks!
