### ISSUE TITLE
EBSC: Incorrect title

### ISSUE THREAD

**Issue by thetoastcaper** [MicrosoftDocs/typography-issues#226]
The page's HTML title is erroneously being shown as "EBLC - Embedded Bitmap Location Table"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6b8bf491-e146-c74e-4303-413e064ad34e
* Version Independent ID: e8e9a9e0-fb3d-fb71-e5c8-b0b8f84128f3
* Content: [EBLC - Embedded Bitmap Location Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/ebsc#feedback)
* Content Source: [typographydocs/opentype/spec/ebsc.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/ebsc.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Thanks for reporting. Fixed!
