### ISSUE TITLE
ind_reph2.gif

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#227]
ind_reph2.gif is an example of 'rphf' but it is in the 'rkrf' section. It is redundant with repf2.gif in the 'rphf' section, so one or the other should be deleted.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c1a0129-e23f-c785-89bc-25fb41b378c0
* Version Independent ID: b2a39f6a-94ed-b3ff-effb-17b2cc31b9e1
* Content: [Developing OpenType Fonts for Devanagari Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/devanagari)
* Content Source: [typographydocs/script-development/devanagari.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/devanagari.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
Thank you for reporting the issue. Fixed!
