### ISSUE TITLE
Poorly worded reference to 'jp78'

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#23]
The description of 'expt' mentions “the JIS78 Forms described above”. The JIS78 forms are described neither above nor below but on a different page, but the feature tags are listed alphabetically, so if they were on the same page, 'jp78' would be below. Better than this oblique reference would be a link to https://docs.microsoft.com/en-us/typography/opentype/spec/features_fj with the anchor text “'jp78'”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4da11419-0864-96ff-7f67-296680843fc1
* Version Independent ID: 1d46dac1-d559-ce3e-2f6f-f47cf8cd9e0f
* Content: [Registered features, a-e - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae)
* Content Source: [typographydocs/opentype/spec/features_ae.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_ae.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Fixed for the next version. Thanks!
