### ISSUE TITLE
[USE] Contradiction about valid bases for variation selectors

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#230]
The section “Cluster validation” says “When a VARIATION_SELECTOR occurs in any context other than immediately following one of the valid bases (IND, O, Rsv, WJ, B, GB, N, S), it forms an independent cluster.” However, the definitions of standard clusters and virama-terminated clusters include &lt; H B | SUB &gt; [VS], which means that a variation selector can also immediately follow a SUB without forming an independent cluster.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 194a6d3c-4137-46e9-3a4b-44b990200986
* Version Independent ID: a0c8e788-5228-aa28-670e-3ba1ac3faecd
* Content: [Creating and supporting OpenType fonts for the Universal Shaping Engine - Typography](https://docs.microsoft.com/en-us/typography/script-development/use)
* Content Source: [typographydocs/script-development/use.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/use.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by xadxura** [comment]
PR posted

**Comment by NorbertLindenberg** [comment]
What does “PR posted” mean?

**Comment by xadxura** [comment]
PR = Pull Request, i.e., for the update to the document.

**Comment by xadxura** [comment]
Change verified.
