### ISSUE TITLE
Unclear effect of ZWJ on clustering

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#232]
It is not clear what effect ZWJ has on cluster boundaries: does it glue two different clusters together, can it only appear in certain places like next to a virama, or is it ignored like CGJ?

The “Zero-width joiner (ZWJ)” section says:
>It continues a preceding cluster and joins it to a following character unless the following character is another ZWJ.

That implies that it glues any two characters (except another ZWJ) together into the same cluster. For example, if ⟨C H C⟩ is a cluster, and ⟨S SMAbv⟩ is a cluster, then ZWJ would join them together and ⟨C H C ZWJ S SMAbv⟩ would be a single cluster. This interpretation is supported by Andrew Glass in harfbuzz/harfbuzz#1013:
>```
>>What does "ZWNJ does not reset the cluster model." mean?
>
> We had feedback on the spec at one point on ZWJ. There was an expectation that ZWJ had the effect of gluing two clusters together. So this is intended to clarify that what follows a ZWJ/ZWNJ doesn’t initiate a new cluster. So that needs further clarification.
>```

I created a font to test this with the rule `sub u1BC02 uni200D u1BC02 by u1BC02_uni200D_u1BC02;` in 'ccmp'. Uniscribe did not apply the substitution, indicating that the sequence is not considered a single cluster, despite having a ZWJ in the middle. I conclude that ZWJ does _not_ have the effect of gluing two clusters together.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 194a6d3c-4137-46e9-3a4b-44b990200986
* Version Independent ID: a0c8e788-5228-aa28-670e-3ba1ac3faecd
* Content: [Creating and supporting OpenType fonts for the Universal Shaping Engine - Typography](https://docs.microsoft.com/en-us/typography/script-development/use)
* Content Source: [typographydocs/script-development/use.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/use.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by xadxura** [comment]
@dscorbett, In this case, the spec is correct, the implementation is lacking. So this is a product issue.

**Comment by xadxura** [comment]
Known issue: 13844238
