### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by akmacks** [MicrosoftDocs/typography-issues#233]
This article doesn't describe how to install a TrueType font. Could that please be included?

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb966bef-f887-40af-3602-46cdf4bf96ec
* Version Independent ID: 39c36be8-9aac-9f6b-04d3-53fbf5acd31f
* Content: [TrueType overview - Typography](https://docs.microsoft.com/en-au/typography/truetype/#feedback)
* Content Source: [typographydocs/truetype/index.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/truetype/index.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
Thank you for the feedback. We will investigate.
