### ISSUE TITLE
Incorrect external link on "Sandoll"

### ISSUE THREAD

**Issue by Lenny-Kim** [MicrosoftDocs/typography-issues#234]
Hi, this is a staff of Sandoll and we found out that external link of "Sandoll" above is incorrect. 
Clicking "Sandoll' will leads to some kind of spam site which definitely not is our link.

Please redirect "Sandoll" link to below address.

http://www.sandoll.co.kr/?lang=en_US

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 91d203fe-edb5-7fd0-88f1-40a688aee010
* Version Independent ID: 42388cb3-6080-2322-5f5f-5111f3b70ffb
* Content: [Registered typography vendors - Typography](https://docs.microsoft.com/en-us/typography/vendors/#feedback)
* Content Source: [typographydocs/vendors/index.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/vendors/index.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
Thank you. Please email us to make the changes so can confirm the request is from the owner of the ID

**Comment by Lenny-Kim** [comment]
Dear Mr./Ms. Ali

Thank you for your reply.

We are checking internally about our vendor ID and Password for Microsoft
Vendor system.

Is there any other way that we can request the correction?

Correct url for Sandoll is "http://www.sandoll.co.kr/?lang=en_US"

Best Regards
Lenny




2019년 5월 30일 (목) 오전 10:25, Basit Ali <notifications@github.com>님이 작성:

**Comment by v-nihar** [comment]
Hello,
To update your Vendor ID or any other part of your foundry email mstwsite@microsoft.com with the updated information. 
Source: https://docs.microsoft.com/typography/vendors/register

For verification purposes it is helpful to send this information from the email address registered to the vendor.
