### ISSUE TITLE
Wrong FLIPRGOFF[] description

### ISSUE THREAD

**Issue by lemzwerg** [MicrosoftDocs/typography-issues#235]
The description of `FLIPRGOFF[ ]` is the same as of `FLIPRGON[]`, which is wrong.  It should be the inverse.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb69554-e257-e483-2e26-7f04fdf44fd8
* Version Independent ID: d560a11c-2ac5-1abc-7165-453c3a9618c8
* Content: [The TrueType Instruction Set - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/tt_instructions)
* Content Source: [typographydocs/opentype/spec/tt_instructions.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/tt_instructions.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **v-nihar**

**Comment by alibasi** [comment]
Thank for reporting the issue. Fixed!
