### ISSUE TITLE
Wrong IUP[] description

### ISSUE THREAD

**Issue by lemzwerg** [MicrosoftDocs/typography-issues#236]
In the `Uses:` section `freedom_vector` and `projection_vector` is mentioned.  This is incorrect and should be removed.  It is not mentioned in Apple's TrueType specification of `IUP[]`, and Greg Hitchcock told me that it is also not part of the MS bytecode engine implementation (and FreeType has it neither).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb69554-e257-e483-2e26-7f04fdf44fd8
* Version Independent ID: d560a11c-2ac5-1abc-7165-453c3a9618c8
* Content: [The TrueType Instruction Set - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/tt_instructions)
* Content Source: [typographydocs/opentype/spec/tt_instructions.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/tt_instructions.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **v-nihar**

**Comment by alibasi** [comment]
Thank for reporting the issue. Fixed!
