### ISSUE TITLE
Alignment of loca offsets contradicted

### ISSUE THREAD

**Issue by wezm** [MicrosoftDocs/typography-issues#241]
The alignment of the offsets in the `loca` table/glyphs is unclear.

On the [loca table documentation](https://docs.microsoft.com/en-us/typography/opentype/spec/loca#long-version) at the bottom it states:

> Note that the local offsets should be 32-bit aligned. Offsets which are not 32-bit aligned may seriously degrade performance of some processors.

On the [Recommendations for OpenType Fonts](https://docs.microsoft.com/en-us/typography/opentype/spec/recom#loca-table) page it states:

> We recommend that local offsets should be 16-bit aligned, in both the short and long formats of this table.

On [Apple's loca documentation](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6loca.html) it says:

> The glyph data is always word aligned.

Elsewhere in the Apple docs they refer to long as 32-bits, so I'm assuming word here means 16-bits.

Given two resources say 16-bit I suspect that's what it should be on the first page linked above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 30bacf43-af31-8fc8-09cc-f243c0011506
* Version Independent ID: 8afa0adc-50b9-3571-bfe7-32d5efb893a5
* Content: [loca - Index-to-location - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/loca)
* Content Source: [typographydocs/opentype/spec/loca.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/loca.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by behdad** [comment]
All the requirements should be removed since 2019.

In reality, in the short format, you are forced to do 16-bit alignment because of how offsets are stored.  In the long format, use alignment 1.  We've been doing that in fonttools for years and never ever heard a complaint whatsoever.

**Comment by PeterCon** [comment]
@behdad What do you mean by "alignment 1"?

**Comment by PeterCon** [comment]
Friendly ping: @behdad What do you mean by "alignment 1"?

**Comment by behdad** [comment]
"alignment 1" means no alignment, ie. all are multiples of 1-byte.

**Comment by PeterConstable** [comment]
In TrueType 1.66, the loca spec said that offsets should be long aligned; there was no separate mention in the recommendations chapter.

By OT 1.2, the loca chapter continued to say "should be long-aligned", but the recommendations chapter was recommending word alignment.

**Comment by PeterCon** [comment]
Since the glyf data doesn't use any 32-bit types, there doesn't seem to be any real point of requiring 32-bit alignment. So will revise text in loca to align (ahem) with Apple's spec and recommendations.

**Comment by PeterCon** [comment]
Proposed change for next version:

>Note that the local offsets should be <del>32-bit</del><ins>word</ins> aligned.<del> Offsets which are not 32-bit aligned may seriously degrade performance of some processors.</del>
