### ISSUE TITLE
Add a clarifying note after the paragraph that follows Table 13 Range3 Record Format

### ISSUE THREAD

**Issue by kenlunde** [MicrosoftDocs/typography-issues#244]
Add the following clarifying note after the paragraph that follows [Table 13 Range3 Record Format](https://docs.microsoft.com/en-us/typography/opentype/spec/cff2#table-13-range3-record-format):

_Note:_ Since a sentinel GID is used to delimit the last range in the array, its value, encoded as a uint16, cannot exceed the value 65535. Therefore, the last GID encoded when using FDSelect Format 3 cannot exceed 65534.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f3f1db1-b1f0-587c-0dbe-9e090b32c5d9
* Version Independent ID: 49bd6461-28c0-a133-77b1-617b8f2f5dab
* Content: [CFF2 - Compact font format version 2 table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/cff2)
* Content Source: [typographydocs/opentype/spec/cff2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cff2.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterConstable** [comment]
Corresponds to the change to clause 5.4.3.10 in ISO/IEC 14496-22:2019 Amd 1.

**Comment by PeterCon** [comment]
Fixed for next version.
