### ISSUE TITLE
Missing script tag 'orya'

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#25]
This page mentions the old shaping engine but does not say that 'orya' is its script tag. The other Indic pages mention their old script tags in appendix A, alongside their new script tags.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 44ae8394-9429-2014-4f3f-04a2cff64444
* Version Independent ID: 236f022e-c0fe-740c-83b5-61817643f020
* Content: [Developing OpenType Fonts for Oriya Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/oriya)
* Content Source: [typographydocs/script-development/oriya.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/oriya.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment]
Closing.
The Indic shaping engine was revised before the Kalinga font was released and the tag is set for the sake of consistency.

**Comment by dscorbett** [comment]
I’m sorry, but that makes no sense. The other Indic font development pages list both the old and new script tags; for the sake of consistency, this page should too. Why does this page mention old shaping behavior at all, if you refuse to explain how it works?
