### ISSUE TITLE
In the side bar table of content, the PCLT table is listed as "pclt", lowercase instead of uppercase.

### ISSUE THREAD

**Issue by emuller-amazon** [MicrosoftDocs/typography-issues#251]
In the side bar table of content, the PCLT table is listed as "pclt", lowercase instead of uppercase.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1e2f091-5f77-212d-00e6-634a2e0bbc03
* Version Independent ID: 96873917-b737-0f8e-e7ee-97e2fba125e5
* Content: [PCLT - PCL 5 Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/pclt)
* Content Source: [typographydocs/opentype/spec/pclt.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/pclt.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Thanks for the feedback. Fixed.
