### ISSUE TITLE
[USE] U+002D is in two USE classes

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#252]
U+002D is explicitly listed as being in the USE class BASE_IND. Its Indic_Syllabic_Category is Consonant_Placeholder, which puts it in the USE class BASE_OTHER.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 194a6d3c-4137-46e9-3a4b-44b990200986
* Version Independent ID: a0c8e788-5228-aa28-670e-3ba1ac3faecd
* Content: [Creating and supporting OpenType fonts for the Universal Shaping Engine - Typography](https://docs.microsoft.com/en-us/typography/script-development/use)
* Content Source: [typographydocs/script-development/use.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/use.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by xadxura** [comment]
Thank you, @dscorbett! I'm removing explicit assignment of 2D to BASE_IND. It should go to BASE_OTHER.

**Comment by xadxura** [comment]
Document has been updated.
