### ISSUE TITLE
JROF case diagrams have parameters out of order

### ISSUE THREAD

**Issue by DSouzaM** [MicrosoftDocs/typography-issues#257]
In the diagrams showing the two possible cases for JROF, the offset is placed on top of the stack above the boolean condition. I think it should be the other way around (as is the case with the JROT diagrams).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb69554-e257-e483-2e26-7f04fdf44fd8
* Version Independent ID: d560a11c-2ac5-1abc-7165-453c3a9618c8
* Content: [The TrueType Instruction Set - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/tt_instructions#flow)
* Content Source: [typographydocs/opentype/spec/tt_instructions.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/tt_instructions.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **v-nihar**

**Comment by PeterCon** [comment]
An erratum for OT183 was published to call out the error. A fix has been made for the next version.
