### ISSUE TITLE
nice

### ISSUE THREAD

**Issue by bozeha** [MicrosoftDocs/typography-issues#258]
nice

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2442e3c5-90a6-65ea-d210-678943e0dfa9
* Version Independent ID: ed6eb987-6a33-ed05-b787-0d1b5e78c198
* Content: [FrankRuehl font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/frankruehl#feedback)
* Content Source: [typographydocs/font-list/frankruehl.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/frankruehl.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alib-ms** [comment]
Thank you!
