### ISSUE TITLE
Round To Half Grid description copy from Set Zone PointerS

### ISSUE THREAD

**Issue by xaml78** [MicrosoftDocs/typography-issues#259]
Round To Half Grid description contains text looks like copy from previous operation

"Pops a zone number from the stack and sets all of the zone pointers to point to the zone with that number. If n is 0, all three zone pointers will point to zone 0. If n is 1, all three zone pointers will point to zone 1. Any other value for n is an error."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb69554-e257-e483-2e26-7f04fdf44fd8
* Version Independent ID: d560a11c-2ac5-1abc-7165-453c3a9618c8
* Content: [The TrueType Instruction Set - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/tt_instructions#feedback)
* Content Source: [typographydocs/opentype/spec/tt_instructions.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/tt_instructions.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **v-nihar**

**Comment by PeterCon** [comment]
It appears that paragraph got inserted inadvertently when the content was ported from .docx to .md. This issue applies across all OT versions.

**Comment by PeterCon** [comment]
Fixed
