### ISSUE TITLE
Unclear order of 'vatu'

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#26]
The description of 'vatu' says “For Indic script implementations that use the Vattu Variants feature, the application is expected to process this feature and certain other features in an appropriate order to obtain the correct set of basic forms: nukt, akhn, rphf, rkrf, pref, blwf, half, pstf, cjct.” That list does not include 'vatu', so the appropriate order is unclear.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dd547c7a-0679-c1f5-9bd8-6e0249218aca
* Version Independent ID: 38e91354-2503-9b0c-c0da-a0cd808e1e35
* Content: [Registered features, u-z - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/features_uz)
* Content Source: [typographydocs/opentype/spec/features_uz.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_uz.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
It would stretch the scope of the feature tag registry entries to specify in any greater detail an appropriate algorithm for shaping Indic text. 

The wording is a bit odd, however, and will be revised in the next version.
