### ISSUE TITLE
Error in "The C expression that yields the glyph index"

### ISSUE THREAD

**Issue by fetisov** [MicrosoftDocs/typography-issues#260]
Should be startCode instead of startCount in C expression?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта docs.microsoft.com с вопросом на GitHub.*

* ID: 86923ff4-2b60-9144-e2b4-77cdb36fd698
* Version Independent ID: ea221e53-f51a-8233-3c0b-d416e5360623
* Content: [cmap - Character To Glyph Index Mapping Table - Typography](https://docs.microsoft.com/ru-ru/typography/opentype/spec/cmap#feedback)
* Content Source: [typographydocs/opentype/spec/cmap.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cmap.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by alib-ms** [comment]
Fixed!
