### ISSUE TITLE
[USE] Unclear how non-Brahmic scripts are handled

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#267]
The USE is obviously primarily designed to support Brahmic scripts (or Indic, as they're called here, even though many of them originated outside India).

However, the scripts registered for the USE also includes non-Brahmic scripts, such as Egyptian Hieroglyphs, N’Ko, and Tifinagh. The Unicode data assigns all characters of such scripts the default Indic syllabic category "Other" and the default Indic positional category "NA".

It's unclear how the USE deals with the characters of such scripts. Most USE character classes are defined based on the Indic syllabic category, and do not use the value "Other", while those that are defined otherwise use specific code points, the Unicode general categories Po, Zs, So, Sc, the script SCRIPT_COMMON, or include only unassigned and reserved code points. There doesn't seem to be any provision for non-Brahmic characters with Unicode general categories Lo, Lm, Mn, Nd, as occur in the three scripts named above.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 194a6d3c-4137-46e9-3a4b-44b990200986
* Version Independent ID: a0c8e788-5228-aa28-670e-3ba1ac3faecd
* Content: [Creating and supporting OpenType fonts for the Universal Shaping Engine - Typography](https://docs.microsoft.com/en-us/typography/script-development/use)
* Content Source: [typographydocs/script-development/use.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/use.md)
* Product: **typography**

**Comment by xadxura** [comment]
I've now made the USE ISC and IPC override files available so that the the missing values can be documented while they are not yet supported directly by Unicode properties:
https://github.com/microsoft/font-tools/tree/master/USE
Links to these source files have been added to the USE spec.

**Comment by NorbertLindenberg** [comment]
The override files mentioned above address some of the issue. However, they don’t seem to be complete – for example, I don’t see an override for 07CA NKO LETTER A, which has general category Lo. @xadxura, can you explain how the USE would recognize this character as starting a cluster?

**Comment by punchcutter** [comment]
Having N'Ko doesn't make any sense to me. I expect N'Ko to be run through the Arabic/Joining shaper as it is a RTL joining script. Not everything on the USE list is necessary. Wancho, for one, doesn't require USE at all.

**Comment by xadxura** [comment]
@punchcutter Microsoft passes joining scripts to USE if they are not supported by our Arabic engine. So N'ko is processed by USE. The intention behind this was to have one engine supporting all new scripts being added to Windows. This also puts control over which features are desired for shaping a particular script mostly in the hands of the font developer, which I think is a clear benefit at this point.
N'ko consonants need to be added as overrides. So I'll use this issue to track that.

**Comment by punchcutter** [comment]
Ok, harfbuzz is running N'ko (also Adlam and Hanifi Rohingya) through the Arabic joining shaper which is why it wasn't totally clear to me why this was needed. If Windows is running these through USE then harfbuzz might need some updates.

**Comment by behdad** [comment]
HarfBuzz does implement joining in the USE.  So it's a matter of rerouting N'ko et al and do the testing.

**Comment by NorbertLindenberg** [comment]
One thing to consider when moving scripts from the Arabic shaping engine to the USE is that the former applies three features that the latter doesn’t: _dlig_, _cswh_, and _mset_.

**Comment by xadxura** [comment]
USE assigns characters with Arabic Joining Type C, D, L, or R to BASE, allowing them to cluster with marks. These have not all been added to the override files, so I'm making an update to USE spec to call this out.

**Comment by xadxura** [comment]
Document has been updated.
