### ISSUE TITLE
[cmap] Which cmap subtables are still relevant today?

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#269]
This page documents a large number of cmap subtables that may have been relevant at some point in the past. It would be useful to also document which ones still matter today. As far as I know, the primary ones today are 3/1 (Windows / Unicode BMP) and 3/10 (Windows / Unicode full repertoire). Apple's CoreText system works fine with these two, so at least for rendering through Apple's platforms the Macintosh platform encodings are no longer needed.

Do any other platforms or applications still depend on other cmap subtables?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86923ff4-2b60-9144-e2b4-77cdb36fd698
* Version Independent ID: ea221e53-f51a-8233-3c0b-d416e5360623
* Content: [cmap - Character To Glyph Index Mapping Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap)
* Content Source: [typographydocs/opentype/spec/cmap.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cmap.md)
* Product: **typography**

**Comment by behdad** [comment]
Def only format 4, 10, 12, 13, 14 are relevant.  As to the plat/encoding, also, 3/1 and 3/10 are sufficient.  3/0 (symbol) is also used by hacky symbol fonts.

**Comment by Lorp** [comment]
First issue… I would recommend clarity on multiple cmap subtables. Intended behaviour for multiple cmap subtables with the same format/encodingid is not specified AFAICT. Is an implementation supposed to maintain a ordered list of Format IDs, from which it uses the first it finds? One reading of the spec is that the only subtable format that is usable alongside other subtables is Format 14. Yet Format 13 (many-to-one) has obvious use cases as a supplemental mapping. Implementors of font creation tools may be tempted to use format 4 for Unicode IDs < 65536 and format 12 for IDs >= 65536 in the same font, yet the sentence in the Format 12 spec "This is the standard character-to-glyph-index mapping table for the Windows platform for fonts supporting Unicode supplementary-plane characters" hints that a Format 4 subtable also in the font might be ignored.

Assuming subtables are intended to be unified, then handling of overlaps in coverage must be considered too. "Undefined behaviour" is more useful than leaving implementors to figure it out.

Second issue… The meaning of "symbol font" in the statement "When building a symbol font for Windows, the platform ID should be 3 and the encoding ID should be 0." is not clear. I assume it refers to the old 8-bit character set of MS Symbol, which I think used "Unicode IDs" 32-255 without any 16-bit interlopers. @behdad mentions "hacky symbol fonts" above.

Some attempt should be made in the ‘cmap’ spec to explain how to map arbitrary sets of graphics to Unicode. PUA is the obvious place for them, if there are no relevant Unicode points, yet builders of such fonts often want to add handy alphabetic keystrokes to their fonts too. Which is hackier, the old-style 3/0 symbol fonts or pointing A,B,C… at arbitrary glyphs using 3/1?

**Comment by PeterCon** [comment]
Apple's cmap spec currently has this:

>Many of the cmap formats are either obsolete or were designed to meet anticipated needs which never materialized. Modern font generation tools need not be able to write general-purpose cmaps in formats other than 4, 6, and 12. Formats 13 and 14 are both for specialized uses. Of the two, only support for format 14 is likely to be needed.

Curious as to whether format 6 is really still used.

**Comment by PeterCon** [comment]
Reportedly, format 6 is still often encountered in fonts embedded in PDF files.

**Comment by PeterCon** [comment]
#604 pertains to Mac platform (PID 1); see that issue for proposed changes in that regard.

Wrt formats, the following is a proposed addition in the Overview section, after other discussion of the various formats:

><ins>Of the seven available formats, not all are commonly used today. Formats 4 or 12 are appropriate for most new fonts, depending on the Unicode character repertoire supported. Format 14 is used in many applications for support of Unicode variation sequences. Application developers should anticipate that other formats may also be used in fonts.</ins>

**Comment by Lorp** [comment]
I would recommend a table of contents introducing the Formats.

**Comment by PeterCon** [comment]
I'm not sure I understand. The site generates navigation links already (on the right), so a TOC would be duplication.

**Comment by behdad** [comment]
> Of the seven available formats, not all are commonly used today. Formats 4 or 12 are appropriate for most new fonts, depending on the Unicode character repertoire supported. Format 14 is used in many applications for support of Unicode variation sequences. Application developers should anticipate that other formats may also be used in fonts.

I suggest you also call out Format 13, since it's a legit format and is not obsolete. Everything else I consider obsolete legacy.

**Comment by Lorp** [comment]
Thanks @PeterCon, I’d never noticed that before :-O

**Comment by PeterCon** [comment]
Format 13 has its advocates but also its detractors. Is there more than a few fonts in the world that use it?

Even so...

Revised draft per feedback:
><ins>Of the seven available formats, not all are commonly used today. Formats 4 or 12 are appropriate for most new fonts, depending on the Unicode character repertoire supported. Format 14 is used in many applications for support of Unicode variation sequences. Some platforms also make use for format 13 for a last-resort fallback font. Application developers should anticipate that other formats may also be used in fonts.</ins>

**Comment by behdad** [comment]
> Format 13 has its advocates but also its detractors.

It was added into OT in recent times. So unless we want to agree to deprecate it, I see it as an active format.

> Is there more than a few fonts in the world that use it?

No. But that's exactly what it was added for: catch-all fallback-fonts.

**Comment by NorbertLindenberg** [comment]
This is one issue that would really benefit from distinguishing font producers and font consumers, as in:

> Font producers should only produce subtables in the following platform/encoding/format combinations:
> 
> * If the font supports only characters in the Unicode Basic Multilingual Plane: platform 3, encoding 1, format 4.
> 
> * If the font supports characters in any supplementary plane: platform 3, encoding 10, format 12 or (for last-resort fonts) 13.
> 
> * If the font supports variation sequences (see chapter 23.4 of the Unicode Standard): platform 0, encoding 5, format 14, in addition to one of the other two subtables.
> 
> To support characters or symbols that are not encoded in the Unicode Standard, Private Use Area code points must be used.
> 
> Font consumers should also support other platform/encoding/format combinations that have been used in fonts in the past.
> 

There are several statements on the page that contradict these prescriptions and need to be deleted.

**Comment by behdad** [comment]
Agree with Norbert's assessment. I suggest using 0/3 instead of 3/1, and 0/6 instead of 3/10. Ie. use the Unicode platform, not Microsoft platform.

FWIW here's how HarfBuzz picks what subtables to use:
```
  const CmapSubtable *find_best_subtable (bool *symbol = nullptr) const
  {
    if (symbol) *symbol = false;

    const CmapSubtable *subtable;

    /* Symbol subtable.
     * Prefer symbol if available.
     * https://github.com/harfbuzz/harfbuzz/issues/1918 */
    if ((subtable = this->find_subtable (3, 0)))
    {
      if (symbol) *symbol = true;
      return subtable;
    }

    /* 32-bit subtables. */
    if ((subtable = this->find_subtable (3, 10))) return subtable;
    if ((subtable = this->find_subtable (0, 6))) return subtable;
    if ((subtable = this->find_subtable (0, 4))) return subtable;

    /* 16-bit subtables. */
    if ((subtable = this->find_subtable (3, 1))) return subtable;
    if ((subtable = this->find_subtable (0, 3))) return subtable;
    if ((subtable = this->find_subtable (0, 2))) return subtable;
    if ((subtable = this->find_subtable (0, 1))) return subtable;
    if ((subtable = this->find_subtable (0, 0))) return subtable;

    /* Meh. */
    return &Null (CmapSubtable);
  }
```

**Comment by PeterCon** [comment]
The change you're suggesting, effectively deprecating platform 3, is a major change that would need broad consensus. It should be a distinct issue from the one opened here, and is too big a change to put into a dot-dot version.

**Comment by NorbertLindenberg** [comment]
That still leaves my proposal on the table, and I think it would bring some much-needed clarity about current reality.

**Comment by PeterCon** [comment]
>That still leaves my proposal on the table, ...

See proposed changes I've shown for #599, which also includes changes for some other related issues. I think it does a good amount of what, but doesn't come up with a short set of bullet points. It's a goal I think all would say is good, but I don't think we can quite get there yet: I think we need multiple vendors to agree on one set of platform/encoding. Right now, Apple recommends platform 0, while MS recommends platform 3. My changes for #599 have tried to steer a somewhat neutral course.

**Comment by NorbertLindenberg** [comment]
Where does Apple recommend platform 0 by itself?

I see a recommendation in [their cmap description](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6cmap.html):

> Font should all have a Unicode cmap, either with a Unicode platformID or a Microsoft platformID and appropriate platformSpecificID.

Which would mean that platform 3 works for all.

**Comment by PeterCon** [comment]
Adding this in the 'cmap' section of the Recommendations chapter:

><ins>New fonts should use Unicode encoding: either a Unicode platform encoding (e.g., platform 0, encoding 4), or a Windows platform encoding (platform 3, encoding 1 or 10). The Unicode encodings for the Windows platform are also widely supported in other software platforms.</ins>

**Comment by behdad** [comment]
> Adding this in the 'cmap' section of the Recommendations chapter:
> 
> > New fonts should use Unicode encoding: either a Unicode platform encoding (e.g., platform 0, encoding 4), or a Windows platform Unicode encoding (platform 3, encoding 1 or 10). The Unicode encodings for the Windows platform are also widely supported in other software platforms.

Minor suggestion: for platform 0, recommend encoding 6.

**Comment by PeterCon** [comment]
Revised:

><ins>New fonts should use Unicode encoding: either a Unicode platform encoding (e.g., platform 0, encoding 4 or 6), or a Windows platform Unicode encoding (platform 3, encoding 1 or 10). The Unicode encodings for the Windows platform are also widely supported in other software platforms.</ins>

It's not clear that the spec could recommend one particular platform 0 encoding since, from what I've seen, the platforms that support platform 0 aren't aligned on which encodings are supported.

**Comment by NorbertLindenberg** [comment]
Before the spec can recommend any Unicode platform encoding at all, it needs to specify which “encoding” values exist and what they mean.

**Comment by behdad** [comment]
Those are listed in the name table spec and referred to from cmap. I find
it bizarre as well.

**Comment by PeterCon** [comment]
Are you suggesting that the same details should be listed in two places? Or that the details should only be in the cmap chapter?

**Comment by NorbertLindenberg** [comment]
I didn’t even notice the reference to the `name` table spec, because I was looking at the Windows platform section, which lists all the encodings, and then the Unicode platform section, which doesn’t.

Now looking at the `name` table documentation, I see that most of the Unicode platform section is actually about `cmap`. This is truly bizarre.

So yes, copy the content of that section into the `cmap` page, with edits:
* Reduce the first paragraph after the table to “Encoding IDs 0, 1 and 2 are deprecated.”
* Reduce the second paragraph to “Only the 'cmap' subtable formats listed in the table above may be used for the corresponding encoding ID.”
* Delete the third and fourth paragraph.

There’s of course more to do to disentangle the two table specifications. I’ll write a separate bug for that.

**Comment by NorbertLindenberg** [comment]
I’m also wondering: Is there any situation where a Unicode platform cmap works better than a Windows platform cmap? Or is support for Unicode platform cmap tables just a matter of platform neutrality? And conversely: Are you sure that Unicode platform cmap tables are equally well supported as Windows platform cmap tables in all OpenType implementations?

**Comment by behdad** [comment]
> I’m also wondering: Is there any situation where a Unicode platform cmap works better than a Windows platform cmap?

As long as they are picked up by the implementation, there's no difference whatsoever.

> Or is support for Unicode platform cmap tables just a matter of platform neutrality?

It seems like both are equally supported by the major implementations. So, no real difference there.

> And conversely: Are you sure that Unicode platform cmap tables are equally well supported as Windows platform cmap tables in all OpenType implementations?

Definitely can't talk to "all". But all major are.

**Comment by NorbertLindenberg** [comment]
> It's not clear that the spec could recommend one particular platform 0 encoding since, from what I've seen, the platforms that support platform 0 aren't aligned on which encodings are supported.

Peter, can you elaborate on the misalignments you’ve seen?

**Comment by PeterCon** [comment]
>Peter, can you elaborate on the misalignments you’ve seen?

Based on info about Harfbuzz provided 3 days ago (above), and the list of supported platforms in [Apple's doc'n](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6cmap.html).

**Comment by behdad** [comment]
> Are you suggesting that the same details should be listed in two places? Or that the details should only be in the cmap chapter?

Like Norbert said, the section on Unicode encoding in name table talks about cmap subtable formats... I do believe cmap is a better place if we don't want to duplicate. But I also don't see any problem with duplication if can't be moved to a third page.

I see Norbert opened https://github.com/MicrosoftDocs/typography-issues/issues/615

One thing I just note here: when we removed all non-Unicode encoding supports from Fontconfig, had to add back support for English MacRoman in the `name` table strings, because (at least some versions of) AppleColorEmoji used MacRoman English name. Which makes sense for ASCII strings given that MacRoman is a single-byte encoding and all Unicode encodings available are 2byte or more. So that's the only non-Unicode encoding, and only in the `name` table, that I think we should endorse still supporting.

I also want to document another anomaly in the `name` table. We've seen, and I think is the `name`-table recommendation as well, that in symbol fonts, that is, those with 3/0 `cmap`, the English name strings *also* use 3/0 instead of 3/1. That's bizarre but definitely something in the wild that might have even been endorsed by the spec.

**Comment by behdad** [comment]
> Based on info about Harfbuzz provided 3 days ago (above), and the list of supported platforms in [Apple's doc'n](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6cmap.html).

See discussion from https://github.com/MicrosoftDocs/typography-issues/issues/599#issuecomment-690675822 and on.

**Comment by NorbertLindenberg** [comment]
> I also want to document another anomaly in the `name` table. We've seen, and I think is the `name`-table recommendation as well, that in symbol fonts, that is, those with 3/0 `cmap`, the English name strings _also_ use 3/0 instead of 3/1. That's bizarre but definitely something in the wild that might have even been endorsed by the spec.

Can you open a separate bug against the name table specification for that?

**Comment by NorbertLindenberg** [comment]
Updated proposal for addressing this issue:

* Add the following text after the Overview section of the cmap table specification:

> **Requirements**
>
> New fonts must only contain subtables in the following platform/encoding/format combinations:
> 
> * If the font supports only characters in the Unicode Basic Multilingual Plane: Either platform 3, encoding 1, or platform 0, encoding 3; using format 4.
> 
> * If the font supports characters in any Unicode supplementary plane: Either platform 3, encoding 10, or platform 0, encoding 4; using format 12.
>
>* If the font is designed as a font of last resort: Platform 0, encoding 6, format 13 instead of any of the subtables listed above.
> 
>* If the font supports Unicode variation sequences: platform 0, encoding 5, format 14 in addition to one of the subtables listed above.
> 
> To support characters or symbols that are not encoded in the Unicode Standard, Private Use Area code points must be used.
>
> Applications must support the platform/encoding/format combinations mentioned above, and may support additional ones as needed to handle older fonts.

* Delete the following text sections from the cmap table specification:

> Unicode Variation Sequences supported by the font should be specified in the 'cmap' table using a format 14 subtable. A format 14 subtable must only be used under platform ID 0 and encoding ID 5.

> When building a font that will be used on the Macintosh, the platform ID should be 1 and the encoding ID should be 0.

> When building a Unicode font for Windows, the platform ID should be 3 and the encoding ID should be 1. When building a symbol font for Windows, the platform ID should be 3 and the encoding ID should be 0.
Microsoft strongly recommends using Unicode 'cmap' subtables for all fonts. However, other non-Unicode encodings are also used in existing fonts with the Windows platform.

> When building a symbol font for Windows, the platform ID should be 3 and the encoding ID should be 0.
>
> Fonts that support Unicode BMP characters (U+0000 to U+FFFF) on the Windows platform must have a format 4 'cmap' subtable for platform ID 3, platform-specific encoding 1.
>
> Fonts that support Unicode supplementary-plane characters (U+10000 to U+10FFFF) on the Windows platform must have a format 12 subtable for platform ID 3, encoding ID 10. To ensure backward compatibility with older software and devices, a format 4 subtable for platform ID 3, encoding ID 1 is also required. The characters supported in the format 4 subtable must be a subset of the characters in the format 12 subtable and should include all of the Unicode BMP characters supported by the font.

* Replace for format 4:
    > This is the standard character-to-glyph-index mapping table for the Windows platform for fonts that support Unicode BMP characters. See Windows platform (platform ID = 3) above for additional details regarding subtable formats for Unicode encoding on the Windows platform.

    with:

    > This is the standard character-to-glyph-index subtable format for fonts that support only Unicode Basic Multilingual Plane characters (U+0000 to U+FFFF).

* Replace for format 12:
    > This is the standard character-to-glyph-index mapping table for the Windows platform for fonts supporting Unicode supplementary-plane characters (U+10000 to U+10FFFF). See Windows platform (platform ID = 3) above for additional details regarding subtable formats for Unicode encoding on the Windows platform.

    with:

    > This is the standard character-to-glyph-index subtable format for fonts supporting any Unicode supplementary plane characters (U+10000 to U+10FFFF).

* Delete the recommendations for the cmap table from the Recommendations page.

**Comment by PeterCon** [comment]
Some of what you propose is new requirements, in particular:

>Applications must support the platform/encoding/format combinations mentioned above,

I'm not comfortable putting that into a dot-dot release or adding it without knowing there is very broad consensus. Having a recommendation, however, would be fine IMO.

**Comment by PeterCon** [comment]
I'm OK with some of the other suggestions that don't add any new constraints on implementations, and will work on that.

**Comment by NorbertLindenberg** [comment]
I noticed your comment in #599 that Windows doesn’t support format 13; so we probably need an exception for that. Do you see anything else that you think might not be universally supported at this point?

**Comment by PeterCon** [comment]
A survey of CoreText and Harfbuzz is hardly the same as universally supported. If fonts ship with only 0/4 or 0/6 cmaps, how can we possible know how many libraries or apps they might not work in? How many printer drivers they won't work in? Whether they work in TT rasterizers but not in CFF rasterizers? There are just way too many unknowns. "Must" is saying that all of those things that have worked for years are not conformant. (Yes, we could say "conforming to version N", but that is not going to help many people in the real world.) "Should" would be fine; but I think "must" is too strong.

**Comment by PeterCon** [comment]
Some of the changes you propose were already in my current draft. At any rate, here's the revised draft for format 4 and format 12 sections:

**format 4:**
><del>This is the standard character-to-glyph-index mapping table for the Windows platform for fonts that support Unicode BMP characters. See [Windows platform (platform ID = 3)][3] above for additional details regarding subtable formats for Unicode encoding on the Windows platform.</del><ins>This is the standard character-to-glyph-index mapping subtable for fonts that support only Unicode Basic Multilingual Plane characters (U+0000 to U+FFFF).</ins>
>
>> <ins>*Note:* To support Unicode supplementary-plane characters, format 12 should be used.</ins>

**format 12:**
>This is the standard character-to-glyph-index mapping <del>table</del><ins>subtable</ins> for <del>the Windows platform for </del>fonts supporting Unicode <ins>character repertoires that include </ins>supplementary-plane characters (U+10000 to U+10FFFF). <del>See [Windows platform (platform ID = 3)][3] above for additional details regarding subtable formats for Unicode encoding on the Windows platform.</del>
>
><ins>Fonts that include a format 12 subtable can also include a format 4 subtable for compatibility with older applications. This is not required, however. See the [Recommendations](recom.md#cmap-table) chapter for additional information.</ins>

**Comment by PeterCon** [comment]
Here's the current draft for the 'cmap' section in the Recommendations chapter:

>## &#39;cmap&#39; Table
>
><del>### Windows &#39;cmap&#39; Table</del>
>
><del>When building a font for Windows, a &#39;cmap&#39; subtable for platform ID 3 should be included. When building a Unicode font, encoding ID 1 should be used for this subtable. (This subtable must use format 4.) When building a symbol font for Windows, encoding ID 0 should be used for this subtable.</del>
>
><del>When building a font to support Unicode supplementary characters (U+10000 to U+10FFFF)), include a &#39;cmap&#39; subtable for platform ID 3, encoding ID 10. (This subtable must use format 12.) To provide compatibility with older software, a subtable for platform 3, encoding ID 1 should also be included. Depending on application support and the content of text being displayed, either the 3/1/4 or 3/10/12 subtable may be used. Therefore, glyph mappings for characters in the range U+0000 to U+FFFF must be **identical** between the 3/1/4 and 3/10/12 subtables. Also note that the characters mapped in the 3/10/12 subtable must be a superset of the characters mapped in the 3/1/4 subtable.</del>
>
><del>Remember that encoding records must be stored in sorted order by platform ID, then by encoding ID.</del>
>
><del>### Macintosh &#39;cmap&#39; Table</del>
>
><del>When building a font containing Roman characters that will be used on the Macintosh, an additional subtable is required, specifying platform ID of 1 and encoding ID of 0 (this subtable may use &#39;cmap&#39; formats 0, 2, 4, or 6).</del>
>
><del>In order for the Macintosh &#39;cmap&#39; table to be useful, the glyphs required for the Macintosh must have glyph indices less than 256 (since the &#39;cmap&#39; subtable format 0 uses uint8 indices and therefore cannot index any glyph above 255).</del>
>
><del>The Apple &#39;cmap&#39; subtable should be constructed according to Apple guidelines.</del>
>
><ins>New fonts should use Unicode encoding:</ins>
>
>* <ins>If the font supports only characters in the Unicode Basic Multilingual Plane (U+0000 to U+FFFF): either platform 3, encoding 1; or platform 0, encoding 3. With either encoding, use a format 4 subtable.</ins>
>
>* <ins>If the font supports any characters in a Unicode supplementary plane (U+10000 to U+10FFFF): either platform 3, encoding 10; or platform 0, encoding 4. With either encoding, use a format 12 subtable.</ins>
>
>* <ins>If the font supports Unicode variation sequences: platform 0, encoding 5, with a format 14 subtable. This is in addition to a format 4 or format 12 subtable with encodings as listed above.</ins>
>
>* <ins>If the font is designed as a font of last resort, using single glyphs for entire Unicode character ranges: platform 0, encoding 6, with a format 13 subtable. A last-resort font should not use any other encodings or subtable formats.</ins>
>
><ins>When creating a font to support Unicode supplementary-plane characters, a format 4 subtable can be included, as well as a format 12 subtable, to provide compatibility with older applications might not support a format 12 subtable. This is not required, however. If both are included, either subtable may be used in different contexts, and so the glyph mappings for characters in the range U+0000 to U+FFFF should be identical. The format 12 table should include all BMP and supplementary-plane characters supported by the font. For each subtable, use the encodings indicated above.</ins>

**Comment by NorbertLindenberg** [comment]
We know that the text we’re working on will be presented to ISO for inclusion into an ISO standard. The purpose of a standard is interoperability. The cmap table is essential to OpenType; a font is unusable if font and rendering system don’t agree on it. If we offer both font developers and implementers a range of options, but don’t require anything to be supported, we have failed to provide interoperability. Yes, that standard has failed to do so for at least 13 years, but that doesn’t seem like a good justification for failing again.

That’s why I think there has to be a statement that starts with “Applications must support the platform/encoding/format combinations...” followed by something that is sufficient for general-purpose full-Unicode fonts. I’m OK if last-resort fonts are not covered.

**Comment by PeterCon** [comment]
I completely agree that interoperability should be the aim. But if our aim is really to provide guidance that is most likely to produce interoperability with the widest range of fonts and the widest range of platforms, libraries and applications, then I think the best way to do that would be to say:

* BMP-only fonts: use 3/1/4
* BMP/SMP fonts: use 3/10/12

Considering that 3/1/4 has been in use for 30 years and 3/10/12 for almost 20 years, there's extremely high likelihood that those are close to universally supported.

But saying that apps must support 0/3 or 0/4 is only likely to mean a lot of software or devices can't claim conformance. I don't think it particularly helps drive interoperability.

**Comment by NorbertLindenberg** [comment]
> Here's the current draft for the 'cmap' section in the Recommendations chapter:

Why should this remain hidden away in the Recommendations chapter, and not be directly in the cmap table specification?

**Comment by NorbertLindenberg** [comment]
> to provide compatibility with older applications might not support a format 12 subtable.

In Apple’s documentation I found this recommendation linked to Windows XP, which Microsoft formally abandoned six years ago. Is there any “application” that’s still relevant and requires this workaround?

**Comment by NorbertLindenberg** [comment]
> * BMP-only fonts: use 3/1/4
> * BMP/SMP fonts: use 3/10/12

That would take us back to something close to my earlier proposal. What do you think is the situation for 0/5/14?

**Comment by PeterCon** [comment]
> Why should this remain hidden away in the Recommendations chapter, and not be directly in the cmap table specification?

This amount of detail strikes me more like implementation guidance than format specification. If there were short requirement statements, those clearly would belong in the cmap chapter.

**Comment by PeterCon** [comment]
> > to provide compatibility with older applications might not support a format 12 subtable.
> 
> In Apple’s documentation I found this recommendation linked to Windows XP, which Microsoft formally abandoned six years ago. Is there any “application” that’s still relevant and requires this workaround?

I'm not personally strongly attached to this. However, (i) I don't think that guidance ("if you do this, make sure that...") does any harm to have. And (ii) XP still shows up >0 in usage stats, and who knows how many XP devices in Asia aren't getting reported. Given the app back compat situation for some platforms, it may be a valid concern. I don't think it should be removed without input from platforms that might have that back compat concern, particularly in this case MS.

**Comment by PeterCon** [comment]
> > * BMP-only fonts: use 3/1/4
> > * BMP/SMP fonts: use 3/10/12
> 
> That would take us back to something close to my earlier proposal. What do you think is the situation for 0/5/14?

I was only commenting on those two in contrast to 0/3/4 and 0/4/12. Of course, 0/5/14 is essential for variation sequences, and 0/6/13 for last-resort fonts.

The fastest route to convergence would be to require 3/1/4, 3/10/12 and to deprecate 0/3/4, 0/4/12. But any such deprecation would be out of scope for OT 184 and should be done with broad consensus.

**Comment by NorbertLindenberg** [comment]
> This amount of detail strikes me more like implementation guidance than format specification. If there were short requirement statements, those clearly would belong in the cmap chapter.

The current cmap specification runs to 21 pages when printed in Safari. I’d think adding half a page that informs readers which of those 21 pages are relevant today and which ones aren’t is a good investment.

Also, I don’t know how many people have read the OpenType spec cover to cover. I haven’t. The spec needs to be organized so that readers looking for specific information can easily find it. cmap table information belongs into the cmap table specification page.

**Comment by NorbertLindenberg** [comment]
> I'm not personally strongly attached to this. However, (i) I don't think that guidance ("if you do this, make sure that...") does any harm to have. And (ii) XP still shows up >0 in usage stats, and who knows how many XP devices in Asia aren't getting reported. Given the app back compat situation for some platforms, it may be a valid concern. I don't think it should be removed without input from platforms that might have that back compat concern, particularly in this case MS.

Information about old implementations can be useful if it clearly identifies them. If the note starts with “For compatibility with Windows XP”, then readers can at that point consider to what extent Windows XP still matters to their business, and proceed based on that.

Without that identification, I think the note is harmful: It forces people to research what those “old applications” are, or add a subtable to fonts that will be useless in almost all cases, or (for tools developers) add an option that forces their customers to make that decision.

**Comment by NorbertLindenberg** [comment]
Take 3 on the requirements:

> **Requirements**
>
> New fonts must contain subtables in the following platform/encoding/format combinations:
> 
> * If the font supports only characters in the Unicode Basic Multilingual Plane: Platform 3, encoding 1, format 4.
> 
> * If the font supports characters in any Unicode supplementary plane: Platform 3, encoding 10, format 12.
>
>* If the font is designed as a font of last resort: Platform 0, encoding 6, format 13 instead of any of the subtables listed above.
> 
>* If the font supports Unicode variation sequences: platform 0, encoding 5, format 14 in addition to one of the subtables listed above.
> 
> To support characters or symbols that are not encoded in the Unicode Standard, Private Use Area code points must be used.
>
> Applications must support the following platform/encoding/format combinations:
>
> * Platform 3, encoding 1, format 4.
> * Platform 3, encoding 10, format 12.
> * Platform 0, encoding 5, format 14.
>
> Applications should also support the following platform/encoding/format combinations:
> * Platform 0, encoding 3, format 4.
> * Platform 0, encoding 4, format 12.
> * Platform 0, encoding 6, format 13.
>
> Applications may support additional platform/encoding/format combinations as needed to handle older fonts.

This is designed to guarantee interoperability for most fonts (not for last-resort fonts) while minimizing the number of applications that would be declared out of compliance.

**Comment by PeterCon** [comment]
>The current cmap specification runs to 21 pages when printed in Safari. I’d think adding half a page that informs readers which of those 21 pages are relevant today and which ones aren’t is a good investment.

That's taken care of by text added in the overview section:

><ins>Of the seven available formats, not all are commonly used today. Formats 4 or 12 are appropriate for most new fonts, depending on the Unicode character repertoire supported. Format 14 is used in many applications for support of Unicode variation sequences. Some platforms also make use for format 13 for a last-resort fallback font. Other subtable formats are not recommended for use in new fonts. Application developers, however, should anticipate that any of the formats may be used in fonts.</ins>

>Information about old implementations can be useful if it clearly identifies them. If the note starts with “For compatibility with Windows XP”...

I only mentioned XP in the discussion because you had mentioned it. There's really no way of knowing what applications have the limitation in question, though it's reasonable to believe there are some such applications in use.

> It forces people to research what those “old applications” are...

With a font format that has maintained forward compatibility for 30 years of software, I'm not sure how that can be avoided for this or several other app-compat caveats.

Several hours have already gone into this chapter. If more work is to be done on it in the near term, I think #615 would have greater benefit. In the meantime, there are yet other issues that need to be considered that would have as much or greater impact, and so I won't prioritize more time on this until after other work is done, unless there's something egregiously wrong in the current draft.
