### ISSUE TITLE
[USE] Maximum cluster length

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#272]
The section "Cluster validation" says: "The maximum cluster length is 31 glyphs. After this limit is reached, a cluster break is forced and a new cluster is started."

What happens if during cluster validation a cluster has 31 or fewer glyphs, but application of GSUB features later expands the cluster to over 31 glyphs?
 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 194a6d3c-4137-46e9-3a4b-44b990200986
* Version Independent ID: a0c8e788-5228-aa28-670e-3ba1ac3faecd
* Content: [Creating and supporting OpenType fonts for the Universal Shaping Engine - Typography](https://docs.microsoft.com/en-us/typography/script-development/use)
* Content Source: [typographydocs/script-development/use.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/use.md)
* Product: **typography**

**Comment by behdad** [comment]
I suggest spec just say at least 31 should be supported.  Leaving the rest implementation-defined.

**Comment by xadxura** [comment]
Correcting. Thank you @behdad and @NorbertLindenberg.

**Comment by xadxura** [comment]
Document has been updated.
