### ISSUE TITLE
Need language tags for Batak

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#274]
For a complete font for Batak, it would be useful to be able to identify all the Batak languages. Only two are currently registered: Batak Simalungun BTS and Batak Toba BBC. The following should be added:
* Batak languages – BTK
* Batak Karo – BTX
* Batak Dairi (Pakpak) – BTD
* Batak Mandailing – BTM

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662c6f54-f90c-52ed-dca2-0f0a0a49fee5
* Version Independent ID: 6aa33924-d45e-60c3-a9fd-e317ff662993
* Content: [Language system tags - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags)
* Content Source: [typographydocs/opentype/spec/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/languagetags.md)
* Product: **typography**

**Comment by dscorbett** [comment]
Is 'BTK ' needed? When would it behave differently from 'dflt'?

These are not the only Batak languages with ISO 639 codes. How did you choose this selection?

**Comment by NorbertLindenberg** [comment]
I don’t have an example at hand where `BTK ` would lead to behavior that differs from `dflt`, but shaping engines generally make language tags for the default languages available: ARA for Arabic, BRM for Burmese, THA for Thai...

The languages listed in this request are those documented in the [Proposal for encoding the Batak script in the UCS](http://www.unicode.org/L2/L2008/08011r-n3320r-batak.pdf). Sorry if I overlooked others. The real solution would be one for issue #275, but that seems a long way off.

**Comment by lianghai** [comment]
The `dflt` language tag is meant to be a cross-language (i.e., language-agnostic) default state instead of a default language (i.e., the most active/influential/big/dominant language). Associating a script tag with a “default” language is inappropriate. Does `latn dflt` suggest English or Spanish or French or German?

**Comment by PeterCon** [comment]
Cf. #275

**Comment by PeterCon** [comment]
>The real solution would be one for issue #275, but that seems a long way off.
Hopefully not a long way off ('cause these things are tedious).

**Comment by PeterCon** [comment]
Changed for next version: added &#39;AKB &#39;, &#39;BTD &#39;, &#39;BTK &#39;, &#39;BTM &#39;, &#39;BTX &#39;, &#39;BTZ &#39;

><table>
<tr>
<td><ins>Batak Angkola</ins></td>
<td><ins>&#39;AKB &#39;</ins></td>
<td><ins>akb</ins></td>
</tr>
<tr>
<td>Batak Toba</td>
<td>&#39;BBC &#39;</td>
<td>bbc</td>
</tr>
<tr>
<td><ins>Batak Dairi (Pakpak)</ins></td>
<td><ins>&#39;BTD &#39;</ins></td>
<td><ins>btd</ins></td>
</tr>
<tr>
<td><ins>Batak languages</ins></td>
<td><ins>&#39;BTK &#39;</ins></td>
<td><ins>akb, bbc, btd, btk, btm, bts, btx, btz</ins></td>
</tr>

<tr>
<td><ins>Batak Mandailing</ins></td>
<td><ins>&#39;BTM &#39;</ins></td>
<td><ins>btm</ins></td>
</tr>
<tr>
<td>Batak Simalungun</td>
<td>&#39;BTS &#39;</td>
<td>bts</td>
</tr>
<tr>
<td><ins>Batak Karo</ins></td>
<td><ins>&#39;BTX &#39;</ins></td>
<td><ins>btx</ins></td>
</tr>
<tr>
<td><ins>Batak Alas-Kluet</ins></td>
<td><ins>&#39;BTZ &#39;</ins></td>
<td><ins>btz</ins></td>
</tr>
</table>
