### ISSUE TITLE
Wrong new script tag 'guj2'

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#28]
Appendix A says that the new script tag is 'guj2'. It is 'gjr2'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b1eeb67-8285-00a8-d921-59076d4a001a
* Version Independent ID: c88c880c-96c3-0c66-8200-5c57fb0836f3
* Content: [Developing OpenType Fonts for Gujarati Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/gujarati)
* Content Source: [typographydocs/script-development/gujarati.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/gujarati.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment]
Closing As Fixed.
