### ISSUE TITLE
[USE] Inserted dotted circle should be treated as base of new cluster

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#289]
The section “Defective clusters” of the USE documentation says:

`When a cluster starts with any character that has UGC=Mc or UGC=Mn, USE inserts a dotted circle glyph (U+25CC) to indicate a broken cluster. Defective clusters do not form extended clusters themselves. A sequence of marks without a valid base forms separate clusters for each mark. Note that an explicit character U+25CC is a valid generic base (GB, BASE_OTHER) and so can form extended clusters.`

Similarly, the section “Handling invalid combining marks” says:

`Combining marks and signs that do not occur in conjunction with a valid base are considered invalid. USE treats an invalid mark as a separate cluster and displays the stand-alone mark positioned on a dotted circle (U+25CC). If multiple marks are required to position on a dotted circle, the dotted circle can be explicitly inserted into the text stream followed by any marks in accordance with the standard clustering rules.`

Essentially, when the USE finds that it needs to insert a dotted circle, it also terminates the new cluster right after the mark that required the insertion.

This is quite unfortunate from a user point of view. There are many situations where the user has written a valid multi-character cluster with a dotted circle as a base, and the dotted circle then gets separated from the rest of the cluster as a side effect of script segmentation (see OpenType/opentype-layout#13) or font fallbacks. It may well happen right here for ◌꧀ꦏ or for ◌ꦺꦴ. In this situation the shaping engine should not compound the issue by inserting yet more dotted circles or by separating a virama from the consonant with which it should combine to create a conjunct form.

My proposal: When the USE finds that it needs to insert a dotted circle, it treats this inserted dotted circle as the base of a new cluster, and proceeds as if the dotted circle had been in the input character sequence.

It appears that HarfBuzz already works this way, while CoreText and DirectWrite/Uniscribe would have to be updated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 194a6d3c-4137-46e9-3a4b-44b990200986
* Version Independent ID: a0c8e788-5228-aa28-670e-3ba1ac3faecd
* Content: [Creating and supporting OpenType fonts for the Universal Shaping Engine - Typography](https://docs.microsoft.com/en-us/typography/script-development/use)
* Content Source: [typographydocs/script-development/use.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/use.md)
* Product: **typography**

**Comment by NorbertLindenberg** [comment]
Correct rendering of the Javanese clusters  ◌꧀ꦏ and ◌ꦺꦴ in the comment above:
<img width="107" alt="Screen Shot 2019-08-23 at 14 52 46" src="https://user-images.githubusercontent.com/216206/63625993-468ee380-c5b6-11e9-8c92-8b1e41de5bd3.png">

Actual rendering in different browsers:

Safari:
<img width="95" alt="Screen Shot 2019-08-23 at 14 56 42" src="https://user-images.githubusercontent.com/216206/63625998-48f13d80-c5b6-11e9-85ad-0fbf7eaea930.png">

Firefox:
<img width="106" alt="firefox" src="https://user-images.githubusercontent.com/216206/63626069-8229ad80-c5b6-11e9-81fe-52a3eb3fbc48.png">

Chrome:
<img width="100" alt="chrome" src="https://user-images.githubusercontent.com/216206/63626110-a6858a00-c5b6-11e9-9871-90fa592b6439.png">

Edge:
<img width="124" alt="edge" src="https://user-images.githubusercontent.com/216206/63626254-290e4980-c5b7-11e9-930e-6a221a1775f1.png">

**Comment by xadxura** [comment]
Since the cluster is defective, the aesthetics of the broken cluster are of lesser significance. Having extra dotted circles simply flags the issue for greater attention. I don't think this is a critical issue to drive consistency on.
USE does allow 25CC to act as a based when inserted explicitly by the user. The recent updated to override the ISC for 25CC to cosonant, will allow it to appear in subjoined forms also.
