### ISSUE TITLE
GETVARIATION error in description

### ISSUE THREAD

**Issue by Gr3gH** [MicrosoftDocs/typography-issues#292]
The text for **GETVARIATION[]** indicates that the normalized coordinates are 2.14 fixed-point numbers that are _padded with zeros in the upper 16 bits_ (in order to work on a 32-bit stack). This is incorrect as the 2.14 number is sign-extended into 32-bits. Here is the recommend change:
OLD
(Values are 2.14 fixed-point numbers padded with zeroes in the upper 16 bits.)
NEW
(Values are 2.14 fixed-point numbers, sign-extended in the upper 16 bits).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb69554-e257-e483-2e26-7f04fdf44fd8
* Version Independent ID: d560a11c-2ac5-1abc-7165-453c3a9618c8
* Content: [The TrueType Instruction Set - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/tt_instructions#misc)
* Content Source: [typographydocs/opentype/spec/tt_instructions.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/tt_instructions.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **v-nihar**

**Comment by ValZapod** [comment]
https://docs.microsoft.com/en-us/typography/opentype/spec/errata fixed close it

**Comment by PeterCon** [comment]
Already fixed as OT1.8.3 erratum
