### ISSUE TITLE
Bahnschrift Variable licence

### ISSUE THREAD

**Issue by robinmetral** [MicrosoftDocs/typography-issues#295]
Hi,

I've read in several places that the new Bahnschrift Variable is OFL. Can you confirm this? Can I use it in a web project?

Also, where can I find the otf filed for Bahnschrift as a non-Windows user?

Thank you :slightly_smiling_face: 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b0aa22d-ec65-a36b-3a23-ca87e18ada28
* Version Independent ID: 05d3eb61-7b3c-24f6-dc0e-cb9d02e1c3a0
* Content: [Bahnschrift font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/bahnschrift)
* Content Source: [typographydocs/font-list/bahnschrift.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/bahnschrift.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **v-nihar**

**Comment by alib-ms** [comment]
Please review the [Font redistribution FAQ for Windows ](https://docs.microsoft.com/en-us/typography/fonts/font-faq).

**Comment by robinmetral** [comment]
Reply for others seeing this in the future: it's not OFL, and no you can't use it on the web.

**Comment by kumpelloOne** [comment]
Can i buy somewhere license for this font for commercial use?

**Comment by zivi78** [comment]
for the app AnyFont on the iPad i need a ttf.-File wich contains only one Font of Font Family Bahnschrift. All ttf. i found there are 14 fonts in it.

Where can i get ttf's with only 1 font e.g. Bahnschrift Light
