### ISSUE TITLE
Figure images are missing.

### ISSUE THREAD

**Issue by LiLejia** [MicrosoftDocs/typography-issues#297]
Showing code instead of image itself.
![diagram](images/propnums.gif)  
![diagram](images/tabnums.gif)  
![diagram](images/ranging.gif)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00037af8-d570-2b6d-e467-9b13dde79795
* Version Independent ID: 6eb9f94f-ed70-f850-c33d-3ceec15495ac
* Content: [Character design standards - Figures for Latin 1 - Typography](https://docs.microsoft.com/en-us/typography/develop/character-design-standards/figures#feedback)
* Content Source: [typographydocs/develop/character-design-standards/figures.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/develop/character-design-standards/figures.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alib-ms** [comment]
Thank you for letting us know. Fixed!
