### ISSUE TITLE
7 lost italic style.

### ISSUE THREAD

**Issue by LiLejia** [MicrosoftDocs/typography-issues#298]
This is the value of uppercase flat heights such as the top of the _1_, _4_, _5_, and _7 _in most typefaces with proportional and lining numerals.

should be 

This is the value of uppercase flat heights such as the top of the _1_, _4_, _5_, and _7_ in most typefaces with proportional and lining numerals.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 00037af8-d570-2b6d-e467-9b13dde79795
* Version Independent ID: 6eb9f94f-ed70-f850-c33d-3ceec15495ac
* Content: [Character design standards - Figures for Latin 1 - Typography](https://docs.microsoft.com/en-us/typography/develop/character-design-standards/figures#feedback)
* Content Source: [typographydocs/develop/character-design-standards/figures.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/develop/character-design-standards/figures.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alib-ms** [comment]
Thank you for letting us know. Fixed!
