### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Sifyrena** [MicrosoftDocs/typography-issues#299]
Search for “isn?t” and you’ll see it

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 396d524a-d8fc-79ed-b4ee-ac8a132ff5dd
* Version Independent ID: 7d465b6b-d588-dc6c-b4ac-0a64b5db55cc
* Content: [Cambria font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/cambria#feedback)
* Content Source: [typographydocs/font-list/cambria.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/cambria.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment]
Issue has been corrected. Closing
