### ISSUE TITLE
Wrong language system tag 'MLM '

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#30]
Appendix A lists 'MLM ' as the language system tag for Malayalam, but that is not a registered tag. Malayalam has two tags: 'MAL ' and 'MLR '.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b4d0aca4-2f6f-2174-f0cf-5612a12d4454
* Version Independent ID: 9847e477-302e-5de8-366c-284fff86bc83
* Content: [Developing OpenType Fonts for Malayalam Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/malayalam)
* Content Source: [typographydocs/script-development/malayalam.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/malayalam.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by PeterCon** [comment]
Fixed
