### ISSUE TITLE
Potential error in क्त (kta) glyph?

### ISSUE THREAD

**Issue by ckrf** [MicrosoftDocs/typography-issues#300]
I believe this conjunct consonant is normally written an irregular form: https://commons.wikimedia.org/wiki/File:Deva-kta.png.

I'm only just learning Hindi so I'm probably mistaken.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c629c9b-d28b-aa25-5344-376a3dd28b2e
* Version Independent ID: 991734e0-5210-6a12-f671-1c0b07d11e58
* Content: [Mangal font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/mangal#feedback)
* Content Source: [typographydocs/font-list/mangal.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/mangal.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alib-ms** [comment]
Thank you for the feedback. I have updated the sample image.
