### ISSUE TITLE
[USE] Incomplete name of U+AA35 in a comment

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#301]
In the “Overrides to Indic_Positional_Category” section, U+AA35 has the name CHAM CONSONANT SIGN. In fact, its name is CHAM CONSONANT SIGN LA.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 194a6d3c-4137-46e9-3a4b-44b990200986
* Version Independent ID: a0c8e788-5228-aa28-670e-3ba1ac3faecd
* Content: [Creating and supporting OpenType fonts for the Universal Shaping Engine - Typography](https://docs.microsoft.com/en-gb/typography/script-development/use)
* Content Source: [typographydocs/script-development/use.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/use.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by xadxura** [comment]
Push fix.
