### ISSUE TITLE
“Foreground color” in OpenType+SVG fonts

### ISSUE THREAD

**Issue by twardoch** [MicrosoftDocs/typography-issues#305]
The [SVG](https://docs.microsoft.com/en-us/typography/opentype/spec/svg) table spec says

> Previous versions of this specification allowed use of context-fill and other context-* property values, which are defined in the draft SVG 2 specification. Use of these properties is deprecated: conforming implementations may support these properties, but support is not required or recommended, and use of these properties in fonts is strongly discouraged.

The [CPAL](https://docs.microsoft.com/en-us/typography/opentype/spec/cpal) table spec says:

>Foreground color and foreground color opacity are expressed by the context-fill and context-fill-opacity attributes in the SVG glyph descriptions.

1. How to reconcile these two statements? 
2. What’s the “right” way to specify the “foreground color” in OpenType+SVG fonts?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7982ac71-0e79-40ed-11ce-1a42674ad14f
* Version Independent ID: b3d4ac02-0d14-a9fd-b76e-9883796a0309
* Content: [svg - Scalable vector graphics table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/svg)
* Content Source: [typographydocs/opentype/spec/svg.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/svg.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by twardoch** [comment]
Sorry, re-read SVG, it says

> Implementations must also support the “currentColor” keyword. The initial value must be set by the text-layout engine or application environment. This can be set in whatever way is considered most appropriate for the application. In general, it is recommended that this be set to the text foreground color applied to a given run of text.

So it's more clear how to do it in SVG. It's just the wording in CPAL spec that needs to replace context-fill with currentColor.

A.

**Comment by PeterConstable** [comment]
Amendment 1 to ISO/IEC 14492-22:2019 has made an appropriate correction:

>In the last section entitled “SVG and CPAL”, replace the text of the second paragraph with the following:
>
>Foreground color is expressed by the “currentColor” keyword in the SVG glyph descriptions.

**Comment by PeterCon** [comment]
Fixed for next version, as in OFF Amd 1.
