### ISSUE TITLE
Replace mention of context-fill > currentColor for SVG glyphs

### ISSUE THREAD

**Issue by twardoch** [MicrosoftDocs/typography-issues#306]
The [CPAL](https://docs.microsoft.com/en-us/typography/opentype/spec/cpal) table spec says:

> Foreground color and foreground color opacity are expressed by the context-fill and context-fill-opacity attributes in the SVG glyph descriptions.

However, in OT 1.8.3, the [SVG](https://docs.microsoft.com/en-us/typography/opentype/spec/svg) table spec was amended and it now says:

> Implementations must also support the “currentColor” keyword. The initial value must be set by the text-layout engine or application environment. This can be set in whatever way is considered most appropriate for the application. In general, it is recommended that this be set to the text foreground color applied to a given run of text.

> Previous versions of this specification allowed use of context-fill and other context-* property values, which are defined in the draft SVG 2 specification. Use of these properties is deprecated: conforming implementations may support these properties, but support is not required or recommended, and use of these properties in fonts is strongly discouraged.

So, the CPAL sentence should be amended to something alone the lines of:

> Foreground color is expressed by the currentColor keyword in the SVG glyph descriptions. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 649f6376-f113-0a6f-d633-37ed967d8c29
* Version Independent ID: 043109db-6c34-6c15-b4fb-6280b5131fcc
* Content: [CPAL - Color Palette Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/cpal)
* Content Source: [typographydocs/opentype/spec/cpal.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cpal.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Fixed for next version. Cf. #305
