### ISSUE TITLE
Erroneous “=""”

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#307]
The automated conversion from HTML to Markdown has resulted in a few erroneous instances of “=""”. Specifically, “< h="" |="" dv="">” should be “< H | DV >” (twice) and “< x="" |="" y="">” should be “< x | y >”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b600ff4-6e07-bce1-ac22-14bbecfa9ea4
* Version Independent ID: f9de5cd2-043e-5e2b-33d7-7c27b10f2928
* Content: [Creating and Supporting OpenType Fonts for Sinhala Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/sinhala)
* Content Source: [typographydocs/script-development/sinhala.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/sinhala.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alib-ms** [comment]
Thank you for reporting this.
