### ISSUE TITLE
SideBearings of empty glyphs

### ISSUE THREAD

**Issue by schriftgestalt** [MicrosoftDocs/typography-issues#308]
What values for SideBearings should be used for empty glyphs (like `space`)?
It seems to be `zero`?
And how to calculate the `minLeftSideBearing` in hhea table. Are those zero values taken into account (makeOTF seems to ignore them).

And the same issue is with the vertical tables (vmtx and vhea).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b569bf16-eea2-0953-3345-024bbd9bd8d4
* Version Independent ID: 5e1b6957-a7c9-fef1-5928-dca56d848565
* Content: [hmtx - Horizontal metrix table specification - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/hmtx#feedback)
* Content Source: [typographydocs/opentype/spec/hmtx.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/hmtx.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by alib-ms** [comment]
Hi, Here is the response from the engineering team. "Because empty glyphs don’t have glyph data, and solely rely on the hmtx (or proxies) for their spacing we are not able to define a right sidebearing (RSB) value. (Because there is no bounding box available). If you can’t have a RSB value, I don’t think an LSB value makes sense. Therefore, I’d recommend that the LSB value be zero—as we find with most fonts. 

As far as minLeftSideBearing is concerned—I’m not confident about who actually uses that value and why. I’d argue that both minLeftSideBearing and minRightSideBearing values of zero are useless unless the whole font has zero respective side bearings. "

**Comment by schriftgestalt** [comment]
The issue is not solved. The documentation needs to clarify this. 

So I should ignore the sideBearing values for emtpy glyphs?

And there is a similar issue in the vmtx table. makeOTF uses the ascender value for the TSB for empty glyphs. I would expect zero.

**Comment by PeterCon** [comment]
Clarify sidebearings for glyphs without outline data.

**Comment by PeterCon** [comment]
Proposed changes for next version:

**'hmtx'**
Add at the end of the chapter:

><ins>If a glyph has no contours, xMax/xMin are not defined. The left side bearing indicated in the &#39;hmtx&#39; table for such glyphs should be zero.</ins>

**'hhea'**

><table>
<tr id="minLeftSideBearing">
<td>FWORD</td>
<td>minLeftSideBearing</td>
<td>Minimum left sidebearing value in &#39;hmtx&#39; table<ins> for glyphs with contours (empty glyphs should be ignored)</ins>.</td>
</tr>
<tr id="minRightSideBearing">
<td>FWORD</td>
<td>minRightSideBearing</td>
<td>Minimum right sidebearing value; calculated as <del>Min(aw - lsb - (xMax - xMin))</del><ins>min(aw - (lsb + xMax - xMin)) for glyphs with contours (empty glyphs should be ignored)</ins>.</td>
</table>

**Comment by behdad** [comment]
This also is relevant to x/y min/max bounding box data in the head table. Ie, empty glyphs should be ignored while computing those as well.

**Comment by PeterCon** [comment]
Adding changes in 'head':

><table>
<tr><td>int16</td><td>xMin</td><td>For all glyph bounding boxes. <ins>(Glyphs without contours are ignored.)</ins></td></tr>  
<tr><td>int16</td><td>yMin</td><td>For all glyph bounding boxes. <ins>(Glyphs without contours are ignored.)</ins> </td></tr> 
<tr><td>int16</td><td>xMax</td><td>For all glyph bounding boxes. <ins>(Glyphs without contours are ignored.)</ins> </td></tr> 
<tr><td>int16</td><td>yMax</td><td>For all glyph bounding boxes. <ins>(Glyphs without contours are ignored.)</ins></td></tr>
</table>
