### ISSUE TITLE
Optical size recommended implementation is ambiguous

### ISSUE THREAD

**Issue by robmck-ms** [MicrosoftDocs/typography-issues#310]
We intended the opsz value to be the document text size in points. Focusing on the document keeps layout consistent within a document, regardless of on-screen rendering, which helps for zooming and accesssibility scenarios (mentioned here: https://github.com/w3c/csswg-drafts/issues/807), and keeps layouts consistent between screen and print.

Unfortunately, the spec's recommended implementation lack any of this detail.

Related: https://github.com/w3c/csswg-drafts/issues/4430

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3061e37e-08cf-d8be-345c-7f762521b910
* Version Independent ID: 9314da1d-dd1c-5730-ca08-a5b30ad7213f
* Content: [Registered design-variation axis tag 'opsz' - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_opsz#feedback)
* Content Source: [typographydocs/opentype/spec/dvaraxistag_opsz.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/dvaraxistag_opsz.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Proposed revisions for the next version, based on a draft by John Hudson and comments from David Berlow and Vlad Levantovsky:

>*Scale interpretation:* Values can be interpreted as text size, in <del>points.</del><ins>typographic points, as defined in the OpenType specification: a physical unit equal to 1/72 of a standard physical inch.</ins>
>
>*Recommended or required “Regular” value:* A value in the range <del>9 to 13</del><ins>10 to 16</ins> is recommended<ins> for typical text settings</ins>.
>
>*Suggested programmatic interactions:* Applications may choose to select an optical-size variant automatically based on the <ins> displayed</ins>text size.
>
>## Additional information
>
>The Optical size axis can be used as a variation axis within a variable font. It can also be used within a [STAT](stat.md) table in non-variable fonts within a family that has optical-size variants to provide a complete characterization of a font in relation to its family within the STAT table. In the STAT table of a non-variable font, a format 2 axis value table is recommended to characterize the range of text sizes for which the optical-size variant is intended.
>
><ins>Typical font implementation of optical size design variants involves adapting glyph proportions, stem weights, and details to be appropriate to specific sizes of displayed text. These adaptations may be both functional and aesthetic, ensuring legibility at smaller sizes and refinement of fine details and overall width at larger sizes. The nature of the adaptations may depend on aspects of the individual typeface design, the characters or scripts involved, targeted devices on which the font may be displayed, and known or intended distance from which text will be viewed.</ins>
>
><ins>Type designers may develop size-specific design variations based on print or screen rendering, typically evaluating the design of these variations at a reading distance of 14 to 16 inches. This can be used as a basis for determining appropriate optical size variants for different distances. For example, if the design of a given optical size variant is appropriate for 12 point text viewed from a reading distance of 15 inches, it should also be appropriate for 24 point text viewed from a reading distance of 30 inches.</ins>
>
>The scale for the Optical size axis is text size in points. For these purposes, the text size is as determined by the document or application for its intended use; the actual physical size on a display may be different due to <del>document or application zoom settings</del><ins>platform or application scaling methods</ins> or intended viewing distance.
>
><ins>The target of size-specific design is optical; i.e., tailored to what the reader is seeing. For this reason, Optical size axis variant selection should be determined, so far as possible, by as much information as available regarding displayed size of text *as seen by the reader*. Factors to be taken into account should include the scaling of type on specific platforms and the translation of document and platform units to 1/72 of a physical inch, as well as typical reading distances for applications and devices. This may mean that a nominally specified text size in a document could result in a different Optical size axis variant selection on different platforms and devices, determined by the actual size of text seen by the reader.</ins>
>
> > <ins>*Note:* User-perceived size is very dependent on viewing distance, not only physical size on the display. For example, when viewing text on a large-screen TV, the physical size on the display will be many times larger than the size perceived by the user. In this case, selecting an Optical size variant based only on the physical size on the display would likely result in reduced legibility for the user.</ins>
>
><ins>When translating between document units and the point (1/72 inch) scale for this axis, care should be taken not to assume equivalences between units that may apply on some platforms but not others.</ins>
>
>In applications that automatically select an Optical size variant, this should normally be done based on the text size with a default or “100%” zoom level, not on a combination of text size and zoom level. <ins>Types of zoom that do not trigger re-layout of text should not change Optical size variant selection, while content enlarging or diminishing operations that change re-layout of text should make a new Optical size variant selection based on the new displayed sized.</ins>
>
><ins>If the size of displayed text is smaller or greater than the minimum and maximum extent of the axis range, Optical size axis variant selection should be clamped to the appropriate minimum or maximum axis value, not reset to the default instance.</ins>
>
><ins>It is recommended that software provide means to override automatic Optical size variant selection, as may be appropriate for particular platforms, intended use, known viewing distance, or accessibility.</ins>

**Comment by schriftgestalt** [comment]
Is it possible to use SI units as much as possible (e.g. for the reading distances).

**Comment by PeterConstable** [comment]
Revised this sentence:

>Type designers may develop size-specific design variations based on print or screen rendering, typically evaluating the design of these variations at a reading distance of 14 to 16 inches, or 35 to 40 cm.

**Comment by davelab6** [comment]
SI means size independent?

**Comment by schriftgestalt** [comment]
No: https://en.wikipedia.org/wiki/International_System_of_Units

**Comment by vlevantovsky** [comment]
In general, I very much like the proposed updated description, I think it is necessary and appropriate to emphasize the fact that it's the text optical size _as seen by the reader_ that should drive the selection of variation axis value, _not_ the nominally declared point size alone.

One minor comment - in the fifth paragraph of the "Additional information" section, the sentence

> Factors to be taken into account should include the scaling of type on specific platforms and the translation of document and platform units to 1/72 of a physical inch, as well as typical reading distances for applications and devices.

should be extended to mention display resolution as one of the factors, e.g. [with emphasis added only to highlight the proposed change]:

Factors to be taken into account should include the scaling of type on specific platforms and the translation of document and platform units to 1/72 of a physical inch, as well as _display resolution and_ typical reading distances for applications and devices.

**Comment by tiroj** [comment]
Vlad, can you explain in more detail how you see display resolution being relevant here? I am concerned to avoid overlap of optical size design and instance selection with what has traditionally been the domain of hinting, and which could conceivably by the domain of an axis specifically addressing device resolution.

**Comment by PeterConstable** [comment]
I don't like "display resolution" since that term is ambiguous: pixel dimensions, or pixel density. The term gets used in Windows, but in contexts in which it means pixel dimensions. 

It's not clear to me how pixel dimensions would be relevant for selecting optical size variants.

**Comment by vlevantovsky** [comment]
The second paragraph of the updated description says:

> Typical font implementation of optical size design variants involves adapting glyph proportions, stem weights, and details to be appropriate to specific sizes of displayed text. These adaptations may be both functional and aesthetic, ensuring legibility at smaller sizes and refinement of fine details and overall width at larger sizes.

Let's consider two possible scenarios: a reader viewing text at the normal viewing distance (14-16 inches) on a standard laptop screen (1366 x 768 pixels) vs. viewing same text at the same reading distance on iPad with 2388 x 1668 pixels. The level of contrast, the amount of aesthetic details, and legibility in general that can be rendered at the same size on these two different screens would vary significantly. Hence, my suggestion to include display resolution as one of the factors was simply based on the fact that optical styling / optical size selection may be different based on screen resolution alone, even if nothing else changes. And yes, I am  speaking about pixel density here, so if using display resolution as a term is ambiguous, we can say pixel density, or screen resolution defined by pixels per inch, etc.

**Comment by tiroj** [comment]
> The level of contrast, the amount of aesthetic details, and legibility in general that can be rendered at the same size on these two different screens would vary significantly.

Yes, but that is orthogonal to optical size design, which is resolution independent. I really don't want to overload opsz with things that can and, I think, should be handled via other mechanisms. Apart from the traditional hinting mechanisms, we also have concepts like grade, or resolution-specific axes that would work indepedently of and interact with opsz. If I design a 6pt optical size design, I do so either in a way that is independent of rendering—i.e. presuming a high resolution—, or I am targeting a specific rendering at the font level, or I am anticipating tailoring that design to specific rendering, e.g. with hinting.

**Comment by vlevantovsky** [comment]
Like I said, that was a minor comment. ;-)
