### ISSUE TITLE
Code Sample confuses axisDefault and axisDefaultValue

### ISSUE THREAD

**Issue by mekkablue** [MicrosoftDocs/typography-issues#313]
The code samples on how to normalize the axis value into -1…0…+1 uses two variable names for hte same thing: `axisDefault` and `axisDefaultValue`, but should only use one of them.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06ab9f03-9923-3400-5ae2-b650dcf7fb83
* Version Independent ID: 8b1c2a74-1f8e-cfc3-6472-36727c362e71
* Content: [avar — Axis variations table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/avar#feedback)
* Content Source: [typographydocs/opentype/spec/avar.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/avar.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Fixed for next version: two instances of "axisDefaultValue" have been changed to "axisDefault".
