### ISSUE TITLE
No way to download the font?

### ISSUE THREAD

**Issue by David263** [MicrosoftDocs/typography-issues#314]
Segoe UI is the system font for Windows 10, but my system seems to lack the Regular Segoe UI font and page https://docs.microsoft.com/en-us/typography/font-list/segoe-ui seems not to allow it to be downloaded.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3c2a6fb-3005-b23b-bc83-f8046b852851
* Version Independent ID: f5d0fbf0-990b-7b3d-0c4a-bd4b51c8532e
* Content: [Segoe UI font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/segoe-ui#feedback)
* Content Source: [typographydocs/font-list/segoe-ui.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/segoe-ui.md)
* Product: **typography**
* GitHub Login: @nihar
* Microsoft Alias: **mihar**

**Comment by alib-ms** [comment]
Hi David, 

Thank you for contacting us. I am sorry to hear that you are having problem with Regular weight of Segoe UI missing from your computer. 

Please contact https://support.microsoft.com/. They should be able to further assist you with your issue of missing font.

**Comment by David263** [comment]
I am not going to struggle with Microsoft support. I'll look elsewhere. Segoe UI fonts keep disappearing due to a bug in Winaero Tweaker. Microsoft should provide easy download links for Windows components that must be replaced! If you are worried about copyrights, just use your own feature that checks to see if a Windows installation is authentic.
