### ISSUE TITLE
[USE] Out of date

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#315]
The overrides and cluster patterns are out of date with [the latest override files](https://github.com/microsoft/font-tools/tree/d6514ee7f25cf04cd0ce6427dc9626cab191db1e/USE). When can we expect a spec update?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 194a6d3c-4137-46e9-3a4b-44b990200986
* Version Independent ID: a0c8e788-5228-aa28-670e-3ba1ac3faecd
* Content: [Creating and supporting OpenType fonts for the Universal Shaping Engine - Typography](https://docs.microsoft.com/en-us/typography/script-development/use)
* Content Source: [typographydocs/script-development/use.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/use.md)
* Product: **typography**
* GitHub Login: @Anglass
* Microsoft Alias: **anglass**

**Comment by xadxura** [comment]
Pushed updates for data files and overrides quoted in spec. Cluster updates for Egyptian will be done separaretly.
