### ISSUE TITLE
Tiny grammar fix

### ISSUE THREAD

**Issue by alfiedotwtf** [MicrosoftDocs/typography-issues#316]
- different glyphs representing the same text string The backing string of Unicode characters is not changed, only the visual representation.
+ different glyphs representing the same text string (the backing string of Unicode characters is not changed, only the visual representation).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c7943de-3f8a-35bb-4161-fe81702e3092
* Version Independent ID: 11014449-3ad3-4c87-a71a-c0a0d1e0df63
* Content: [OpenType glyph processing - Typography](https://docs.microsoft.com/en-us/typography/opentype/processing-part1#feedback)
* Content Source: [typographydocs/opentype/processing-part1.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/processing-part1.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alib-ms** [comment]
Thank you for the feedback. Fixed.
