### ISSUE TITLE
typo: EBLC points to "EDBT" rather than "EBDT"

### ISSUE THREAD

**Issue by Pomax** [MicrosoftDocs/typography-issues#319]
https://docs.microsoft.com/en-us/typography/opentype/spec/EBLC#indexsubtables starts with "The EBLC provides embedded bitmap locators. It is used together with the EDBT table", which should be "The EBLC provides embedded bitmap locators. It is used together with the EBDT table"

**Comment by alib-ms** [comment]
Thank you for the feedback. Fixed.
