### ISSUE TITLE
Poorly formatted description of 'stch'

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#32]
The “Stretching Glyph Decomposition” section is misformatted: it says “* Reordering” and “* Positioning” instead of rendering those as their own list items.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4d7ea0b7-0363-c4b7-a9d8-bab46dd6a80a
* Version Independent ID: f64aee9e-4d52-cb98-bb88-ee482ba09995
* Content: [Developing OpenType Fonts for Syriac Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/syriac)
* Content Source: [typographydocs/script-development/syriac.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/syriac.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment]
Closing As Fixed

**Comment by alibasi** [comment]
Thank you for fixing and closing all the bugs.

Ali
