### ISSUE TITLE
typo: CBLC BitmapSize Table "numberofIndexSubTables" should use a capital O

### ISSUE THREAD

**Issue by Pomax** [MicrosoftDocs/typography-issues#323]
https://docs.microsoft.com/en-us/typography/opentype/spec/cblc currently lists the BitmapSize Table "numberOfIndexSubTables" as "numberofIndexSubTables" with a lowecase "O"

**Comment by PeterCon** [comment]
@Pomax Thanks for reporting. In the future, it will help if you file issues using the feedback button at the bottom of the page. That will add metadata in the issue that helps us find and track it. This would have been relevant for the OpenType 1.8.4 revision but was overlooked for this reason. Thanks.

**Comment by Pomax** [comment]
In the future, two years ago, eversincewhen I've already been using the feedback form. As you probably know given that several issues I've reported since were taken on board already =)

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
