### ISSUE TITLE
Very interesting 

### ISSUE THREAD

**Issue by tyeth** [MicrosoftDocs/typography-issues#328]
Thank you

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0ee809a-5ab1-b7de-1321-c91eb9fb0efa
* Version Independent ID: 6cd983a2-c989-d007-9e25-182d7f4a8dd0
* Content: [The science of word recognition - Typography](https://docs.microsoft.com/en-us/typography/develop/word-recognition)
* Content Source: [typographydocs/develop/word-recognition.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/develop/word-recognition.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alib-ms** [comment]
Thanks.
