### ISSUE TITLE
Typos on GSUB page

### ISSUE THREAD

**Issue by sergeresko** [MicrosoftDocs/typography-issues#330]
Please make these contextual substitutions :-)
- “see Figure **3g**” → “see Figure **7**”
- “This currently used” → “This **is** currently used”
- “offsets to **a** three tables” → “offsets to three tables”
- “substitute **a** swash glyphs” → “substitute swash glyphs”
- “from 0 to **ChainSubClassSetCnt** - 1” → “from 0 to **chainSubClassSetCount** - 1”
- “an array of substitute **glyphs** indices” → “an array of substitute **glyph** indices”
- “has a format identifier of **1**” → “has a format identifier of **2**”
- “Example 10: ReverseChainSingleSubstFormat1 Subtable **and SubstLookupRecord**” → “Example 10: ReverseChainSingleSubstFormat1 Subtable”
- “**for glyph sequences to glyph with the correct** form” → “**to substitute glyphs with a** form”
- “This **allow** the glyph” → “This **allows** the glyph”

There’s a tautology in the sentence “Input sequence match begins at *i* where the input sequence match begins.”

The subtable in example 9 has a gap: the last byte of substLookupRecords array is at offset 0x0013 from the beginning of SwashSubtable, but AscenderDescenderCoverage that follows it begins at offset 0x0030 (not 0x0014). If it’s intentional, consider adding a brief note to explain this. (I suppose the reason is that there’s another subtable at 0x0014...0x002F sharing the same coverages.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34e7df21-eb35-19ab-3573-e075872e5d3b
* Version Independent ID: 4656a3f9-95ea-15cc-25ed-6eccf7adf370
* Content: [GSUB — Glyph Substitution Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/gsub#feedback)
* Content Source: [typographydocs/opentype/spec/gsub.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gsub.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by alib-ms** [comment]
Thank you for the feedback, fixed some grammatical related issues.

**Comment by PeterCon** [comment]
Some typos were fixed already in version 1.8.3. Other issues have been fixed for the next version.

In example 9, coverage offsets will be changed to 0014, 0030, 0052.

For type 6 format 1, wording is changed as follows:

>To clarify the ordering of glyph arrays for input, backtrack and lookahead sequences, the following illustration is provided. <del>Input sequence match begins at *i* where the input sequence match begins</del><ins>Suppose within a logically-ordered glyph sequence the input sequence match beings at index *i*.</ins>. The backtrack sequence is ordered beginning at *i* - 1 and increases in offset value as one moves away from *i*. The lookahead sequence begins after the input sequence and increases in logical order.

Also, the table that follows is revised for clarity. (Having a glyph "i" and index "i" was confusing, as well as not having the row with the "i" index labeled.)

><table>
<tbody>

<tr>
<td>Logical order:</td>
<td>a </td>
<td>b </td>
<td>c </td>
<td>d </td>
<td>m</td>
<td>n</td>
<td>w</td>
<td>x</td>
<td>y</td>
<td>z</td>
</tr>

<tr>
<td>Sequence index:</td>
<td> </td>
<td> </td>
<td>…</td>
<td><i>i</i> - 1</td>
<td><i>i</i></td>
<td><i>i</i> + 1</td>
<td><i>i</i> + 2</td>
<td>…</td>
<td> </td>
<td> </td>
</tr>

<tr>
<td>Input sequence index:</td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td>0 </td>
<td>1 </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
</tr>

<tr>
<td>Backtrack sequence index:</td>
<td>3 </td>
<td>2 </td>
<td>1 </td>
<td>0 </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
</tr>

<tr>
<td>Lookahead sequence index:</td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td> </td>
<td>0 </td>
<td>1 </td>
<td>2 </td>
<td>3 </td>
</tr>

</tbody>
</table>
