### ISSUE TITLE
Is Arial contained in a default windows 10 installation ?

### ISSUE THREAD

**Issue by andreas-eternach** [MicrosoftDocs/typography-issues#331]
Hi,

on this page it is written that Arial ISincluded in in Windows 10 (https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list).

accoring to page https://docs.microsoft.com/en-us/typography/font-list/arial IS NOT included in Windows 10.

Which information is correct?

BR, Andreas

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0610f6-7c7b-b771-e635-84663af729db
* Version Independent ID: 50a9b23c-733c-c934-95dc-0bbd5d502fea
* Content: [Font List Windows 10 - Typography](https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list#feedback)
* Content Source: [typographydocs/fonts/Windows_10_Font_List.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/fonts/Windows_10_Font_List.md)
* Product: **typography**
* GitHub Login: @nihar
* Microsoft Alias: **nihar**

**Comment by alib-ms** [comment]
Thank you for the feedback. 

Information here https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list is correct. Arial is included with Windows 10. 

Many of the font informational pages have not been updated for a very long time. I will have the Arial page updated soon.
