### ISSUE TITLE
Typo: “wiht”

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#335]
“wiht” should be “with”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ea55ee-53f0-15da-1819-6dbbd9ae0e51
* Version Independent ID: 5746bf07-2094-52b3-3285-dadc590006c7
* Content: [OpenType Font Variations overview - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otvaroverview)
* Content Source: [typographydocs/opentype/spec/otvaroverview.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otvaroverview.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by alib-ms** [comment]
Thank you for the feedback, fixed!
