### ISSUE TITLE
Currency Text Type

### ISSUE THREAD

**Issue by osaroadade** [MicrosoftDocs/typography-issues#337]
I would really love to see currency text type for the Bookman Old Style as well as some other font weights.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c4b3a772-b1f4-f767-a22c-e96c3d039078
* Version Independent ID: 0a09c8c4-95c7-4051-a33f-767f615e233a
* Content: [Bookman Old Style font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/bookman-old-style#feedback)
* Content Source: [typographydocs/font-list/bookman-old-style.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/bookman-old-style.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alib-ms** [comment]
Thank you for the feedback, we will look into this.
