### ISSUE TITLE
[vhea] Contradictory information on vertTypoDescender

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#339]
The statements about vertTypoDescender in the vhea table description partially contradict each other.

① Description of vertTypoDescender, second sentence: “is the distance in FUnits from the ideographic em-box center baseline for the vertical axis to the left edge of the ideographic em-box”. In math, distances are always positive, but in OpenType they can be negative, so this could mean that a left edge that’s to the left of the ideographic em-box center baseline for the vertical axis gets a negative value. It’s not really clear though.

② Description of vertTypoDescender, second sentence: “it is usually set to (head.unitsPerEm)/2”. This expression always produces a positive value.

③ Description of vertTypoDescender, third sentence: “a font with an em of 1000 fUnits will set this field to -500.” That’s a negative value – clearly in contradiction to ②.

④ Vertical Header Table Example, vertTypoDescender line: Value “-1024”, comment “Minus half the em-square height.” Both the value and the comment are in contradiction to ②.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 312f3284-9ca3-b310-e0e7-d2912d674f88
* Version Independent ID: 81687336-c575-3041-f241-b7ff15b49965
* Content: [vhea — Vertical header table specification - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/vhea)
* Content Source: [typographydocs/opentype/spec/vhea.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/vhea.md)
* Product: **typography**

**Comment by PeterCon** [comment]
Good catch. See discussion in #3: it appears the change made in OT1.8.3 for that issue was incomplete: the example value `500` was corrected to `-500`, but the computation that gave rise to it, `(head.unitsPerEm)/2` was not corrected but should have been.

**Comment by PeterCon** [comment]
Changed for next version:

><table>
<tr><td>int16</td><td>vertTypoDescender</td><td>The vertical typographic descender for this font. It is the distance in FUnits from the ideographic em-box center baseline for the vertical axis to the left edge of the ideographic em-box.<br><br>It is usually set to <del>(head.unitsPerEm)/2</del><ins>-(head.unitsPerEm/2)</ins>. For example, a font with an em of 1000 <del>fUnits</del><ins>FUnits</ins> will set this field to -500.</td></tr>
</table>
