### ISSUE TITLE
[vhea] Dependency on ideographic em-box center baseline

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#340]
The descriptions of vertTypoAscender and vertTypoDescender both depend on “the ideographic em-box center baseline for the vertical axis”. This is problematic for several reasons:

– Vertical text occurs not only in ideographic scripts; some non-ideographic scripts such as Mongolian are normally rendered vertically, and others such as Latin can be rendered vertically if required by the usage context. An ideographic em-box center baseline may not make sense for these scripts.

– The description of how to determine the [ideographic em-box center baseline](https://docs.microsoft.com/en-us/typography/opentype/spec/baselinetags#ideoembox) states that the ideographic em-box cannot be determined in some cases if the font is not a CJK font. In this situation, the meaning of vertTypoAscender and vertTypoDescender is undefined.

– The description of how to determine the [ideographic em-box center baseline](https://docs.microsoft.com/en-us/typography/opentype/spec/baselinetags#ideoembox) assumes that “ideo” and “idtp” baselines are defined for the font, but in reality the [BASE table](https://docs.microsoft.com/en-us/typography/opentype/spec/base) defines them on a per-script basis. It’s undefined how “ideo” and “idtp” baselines for the entire font would be derived, especially in cases where these baselines aren’t defined for all scripts and orientations, or if the values for them differ between scripts.

To be useful, vertTypoAscender and vertTypoDescender should not rely on script-specific properties.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 312f3284-9ca3-b310-e0e7-d2912d674f88
* Version Independent ID: 81687336-c575-3041-f241-b7ff15b49965
* Content: [vhea — Vertical header table specification - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/vhea)
* Content Source: [typographydocs/opentype/spec/vhea.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/vhea.md)
* Product: **typography**

**Comment by khaledhosny** [comment]
> Vertical text occurs not only in ideographic scripts; some non-ideographic scripts such as Mongolian are normally rendered vertically,

Mongolian OpenType fonts are designed to be laid horizontally from left to right then rotated, so they wouldn’t use vhea table.

**Comment by NorbertLindenberg** [comment]
Is that documented anywhere?

**Comment by khaledhosny** [comment]
I don’t know, but I thought it is a common knowledge. It is how existing Mongolian fonts are designed and how vertical Mongolian is handled in the applications that support it (the ones I’ve seen at least).

**Comment by punchcutter** [comment]
This isn’t entirely true. If the font has vmtx/vhea tables then certain characters will be substituted with alternate forms depending on the layout engine. Not all characters will be rotated.

**Comment by kojiishi** [comment]
> Is that documented anywhere?

Please see [UAX50](http://unicode.org/reports/tr50/).

But aside Mongolian, it is true that non-CJK fonts may need vertical metrics; e.g.,
```
vertical-upright {
  font-family: Arial;
  writing-mode: vertical-lr;
  text-orientation: upright;
}
```

**Comment by PeterCon** [comment]
Cf. #3 , #339

**Comment by PeterCon** [comment]
>Mongolian OpenType fonts are designed to be laid horizontally from left to right then rotated, so they wouldn’t use vhea table.
>Is that documented anywhere?
>I don’t know, but I thought it is a common knowledge.

I wouldn't have assumed it's common knowledge. I think this is the first I've heard that suggestion, though I might not have considered the scenario before.

**Comment by PeterCon** [comment]
This issue is really old, dating right back to the creation of vhea version 1.1 in OT 1.3 (2001).

**Comment by PeterCon** [comment]
>I wouldn't have assumed it's common knowledge...

Drilling in, it would make sense that, if vertTypoAscender is described in terms either of an ideographic em-box (as in OT) or a "vertical center baseline" (as in Apple's spec) that it should only apply to scripts for which that would be appropriate. (Perhaps might include e.g., Ogham, not just ideographic scripts.)

Potentially the definition could be revised to allow for usage with non-ideographic or center-baseline scripts when in vertical layout. But that should probably only be considered in the context of broader discussion of specifications for vertical layout. And as the 'vhea' table was defined by Apple, their input should certainly be considered.

But such non-CJK considerations aside, there is a fundamental issue being called out, which is that in the title of this issue:

>The description of how to determine the ideographic em-box center baseline assumes that “ideo” and “idtp” baselines are defined for the font, but in reality the BASE table defines them on a per-script basis. It’s undefined how “ideo” and “idtp” baselines for the entire font would be derived, especially in cases where these baselines aren’t defined for all scripts and orientations, or if the values for them differ between scripts.

As it stands, the current description of the vertTypo* values has significant holes:
- undefined if there is no BASE table, or if the [description of ideographic em-box](https://docs.microsoft.com/en-us/typography/opentype/spec/baselinetags#ideographic-em-box) can't be resolved
- undefined for an scripts other than "CJK" scripts even if vhea would be appropriate, such as other Asian ideographic scripts (e.g, Tangut)

The only easy remedies for this issue (short of longer, more general work on vertical layout) that come to mind would be:

1) Stipulate that the 'vhea' table is only to be used with "CJK" fonts (in which case ideographic em box is defined regardless of BASE tags) — but that seems overly constraining
2) Stipulate that the 'vhea' table is only to be used with ideographic scripts commonly written in vertical layout, along with modification of the description of ideographic em box to be broader than CJK
3) Change the description of the vertTypo* values to "vertical center baseline", as in Apple's spec.

(Or other ideas?)

Option 3 basically amounts to dropping reference to "ideographic em box" in the description of the vertTypo* fields. A link to discussion of ideographic em box in the Baseline Tags chapter could still be kept. So, this would be the smallest change.

At some point, it would be good to make the text less constrained to CJK and, so, accommodate other scripts like Tangut for which it should also be applicable. But maybe that can wait for more work (hopefully not distant future) to be done on vertical layout issues.

Does option 3 sound reasonable for now?

**Comment by PeterCon** [comment]
Proposed changes for next version:

Chapter intro:
>The vertical header table (tag name: &#39;vhea&#39;) contains information needed for vertical <del>fonts</del><ins>layout of ideographic scripts</ins>. <del>The glyphs of vertical fonts</del><ins>In vertical layout, ideographic scripts</ins> are written either top to bottom or bottom to top. This table contains information that is general to the font as a whole. Information that pertains to specific glyphs is given in the [vertical metrics table](vmtx.md) (tag name: &#39;vmtx&#39;) described separately. The formats of these tables are similar to those for horizontal metrics (&#39;hhea&#39; and &#39;hmtx&#39;)

Field descriptions:
><table>
<tr><td>int16</td><td>vertTypoAscender</td><td>The vertical typographic ascender for this font. It is the distance in FUnits from the <del>ideographic em-box</del><ins>vertical</ins> center baseline <del>for the vertical axis </del>to the right edge of the <del>ideographic em-box</del><ins>design space for ideographic glyphs (or “ideographic em box”)</ins>.<br><br>It is usually set to (head.unitsPerEm)/2. For example, a font with an em of 1000 <del>fUnits</del><ins>FUnits</ins> will set this field to 500. See the Baseline tags section of the OpenType Layout Tag Registry for a description of the ideographic em-box.</td></tr>
<tr><td>int16</td><td>vertTypoDescender</td><td>The vertical typographic descender for this font. It is the distance in FUnits from the <del>ideographic em-box</del><ins>vertical</ins> center baseline <del>for the vertical axis </del>to the left edge of the <del>ideographic em-box</del><ins>design space for ideographic glyphs</ins>.<br><br>It is usually set to <del>(head.unitsPerEm)/2</del><ins>-(head.unitsPerEm/2)</ins>. For example, a font with an em of 1000 <del>fUnits</del><ins>FUnits</ins> will set this field to -500.</td></tr>
</table>

**Comment by NorbertLindenberg** [comment]
Is vhea not used with Hangul?

**Comment by PeterCon** [comment]
Yes, of course.

**Comment by NorbertLindenberg** [comment]
Then the term “ideographic script” is inappropriate.

**Comment by PeterCon** [comment]
> Then the term “ideographic script” is inappropriate.

What, then, would you propose instead?

**Comment by PeterCon** [comment]
Revised draft per feedback:

Chapter intro:
>The vertical header table (tag name: &#39;vhea&#39;) contains information needed for vertical <del>fonts</del><ins>layout of Chinese, Japanese, Korean (CJK) and other ideographic scripts</ins>. <del>The glyphs of vertical fonts</del><ins>In vertical layout, these scripts</ins> are written either top to bottom or bottom to top. This table contains information that is general to the font as a whole. Information that pertains to specific glyphs is given in the [vertical metrics table](vmtx.md) (tag name: &#39;vmtx&#39;) described separately. The formats of these tables are similar to those for horizontal metrics (&#39;hhea&#39; and &#39;hmtx&#39;).

Field descriptions:
><table>
<tr><td>int16</td><td>vertTypoAscender</td><td>The vertical typographic ascender for this font. It is the distance in FUnits from the <del>ideographic em-box</del><ins>vertical</ins> center baseline <del>for the vertical axis </del>to the right edge of the <del>ideographic em-box</del><ins>design space for CJK / ideographic glyphs (or “ideographic em box”)</ins>.<br><br>It is usually set to (head.unitsPerEm)/2. For example, a font with an em of 1000 <del>fUnits</del><ins>FUnits</ins> will set this field to 500. See the Baseline tags section of the OpenType Layout Tag Registry for a description of the ideographic em-box.</td></tr>
<tr><td>int16</td><td>vertTypoDescender</td><td>The vertical typographic descender for this font. It is the distance in FUnits from the <del>ideographic em-box</del><ins>vertical</ins> center baseline <del>for the vertical axis </del>to the left edge of the <del>ideographic em-box</del><ins>design space for CJK / ideographic glyphs</ins>.<br><br>It is usually set to <del>(head.unitsPerEm)/2</del><ins>-(head.unitsPerEm/2)</ins>. For example, a font with an em of 1000 <del>fUnits</del><ins>FUnits</ins> will set this field to -500.</td></tr>
</table>

**Comment by NorbertLindenberg** [comment]
List the actual scripts for which vhea is intended.

**Comment by PeterCon** [comment]
A complete listing would need on-going maintenance. I've used "CJK and other ideographic scripts" as a compromise.

**Comment by behdad** [comment]
> I wouldn't have assumed it's common knowledge. I think this is the first I've heard that suggestion, though I might not have considered the scenario before.

It is common knowledge among those who have had to deal with vertical Mongolian.

**Comment by PeterCon** [comment]
One can be generally familiar with how Mongolian is displayed without having had to consider whether the vhea table is relevant or not.
