### ISSUE TITLE
The "Purchase & Download Microsoft fonts" link is broken

### ISSUE THREAD

**Issue by rmedaer** [MicrosoftDocs/typography-issues#341]
In _Licensing info_ section,  the _Purchase & Download Microsoft fonts_ link is broken.
Indeed https://www.fonts.com/font/ascender/arial-unicode returns a `404`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e542900f-429c-499a-be33-06ed008076fc
* Version Independent ID: b7e1af17-8a49-ab34-9dc4-686adc66a357
* Content: [Arial Unicode MS font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/arial-unicode-ms)
* Content Source: [typographydocs/font-list/arial-unicode-ms.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/arial-unicode-ms.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alib-ms** [comment]
Hi, Thank you letting us know, and I am sorry the "Purchase & Download Microsoft fonts" link is broken. I will get this fixed, meanwhile, please go to https://www.fonts.com/content/microsoft-typography/ to purchase Microsoft fonts.
