### ISSUE TITLE
Font list in CSV format?

### ISSUE THREAD

**Issue by caraitto** [MicrosoftDocs/typography-issues#342]
Thanks for providing these font lists!

I'd be nice if these font lists could be downloaded in a machine-readable form, like CSV.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0610f6-7c7b-b771-e635-84663af729db
* Version Independent ID: 50a9b23c-733c-c934-95dc-0bbd5d502fea
* Content: [Font List Windows 10 - Typography](https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list#feedback)
* Content Source: [typographydocs/fonts/Windows_10_Font_List.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/fonts/Windows_10_Font_List.md)
* Product: **typography**
* GitHub Login: @nihar
* Microsoft Alias: **nihar**

**Comment by alib-ms** [comment]
Thank you for the feedback. I will look into this in the future updates.
