### ISSUE TITLE
Alignment typo

### ISSUE THREAD

**Issue by ckitagawa-work** [MicrosoftDocs/typography-issues#345]
&gt; "The EBLC table specification requires 16-bit alignment for all subtables."

I believe this should be 32-bit not 16-bit as by default all formats are 16-bit aligned...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76746ffb-7c69-8d2f-935d-84f15e69116a
* Version Independent ID: 42535fd9-5463-8f94-042c-47307a5d28c8
* Content: [EBLC - Embedded Bitmap Location Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/eblc#feedback)
* Content Source: [typographydocs/opentype/spec/eblc.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/eblc.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Thanks. You're correct: this is a typo that was introduced in version 1.8.1.

**Comment by alib-ms** [comment]
Thank you for the feedback. This is fixed.
