### ISSUE TITLE
ff

### ISSUE THREAD

**Issue by akira159** [MicrosoftDocs/typography-issues#348]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 98c6db8c-d347-baa2-ca72-68f05976e119
* Version Independent ID: f64621c7-8259-8529-4416-e8fa24528433
* Content: [Comic Sans MS font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/comic-sans-ms#feedback)
* Content Source: [typographydocs/font-list/comic-sans-ms.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/comic-sans-ms.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alib-ms** [comment]
Sorry we did not see any information in the feedback.
