### ISSUE TITLE
[Javanese Text] Irrelevant code page and sample text

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#349]
The description of the Javanese Text font has two pieces of information that are irrelevant for this font and should be replaced by relevant information:

– The “Code pages” entry lists “1252 Latin 1”. The main purpose of this font is to render Javanese text, which cannot be represented in this code page. Instead, text needs to be encoded in a Unicode encoding, using the Javanese Unicode block U+A980 – U+A9DF.

– The “Style & Weight Examples” section uses the text “The Five Boxing Wizards Jump Quickly!”. Again, the main purpose of this font is to represent Javanese text, so there should be a Javanese text sample instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75a7b3f2-0df0-cf58-61ad-1fd6e9da91f5
* Version Independent ID: 31a0e1ce-4261-1635-01ff-d77960236ef6
* Content: [Javanese Text - Typography](https://docs.microsoft.com/en-us/typography/font-list/javanese)
* Content Source: [typographydocs/font-list/javanese.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/javanese.md)
* Product: **typography**

**Comment by alib-ms** [comment]
Thank you for the feedback. I have updated the image to show the Javanese characters. You are right that the Code Page information is not relevent to the Javanese Text typeface. This information is present for consistency sake as it is part of the template we use for publishing information related to fonts that ships with Microsoft products.
