### ISSUE TITLE
\tunga font support for windows 10

### ISSUE THREAD

**Issue by naveento** [MicrosoftDocs/typography-issues#350]
Please provide tunga font support for windows 10 as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c695d5cf-8f39-35cb-3752-e3f9c56c760b
* Version Independent ID: 67d5518d-a4d0-be84-d7f4-b1effc2fd526
* Content: [Tunga font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/tunga#feedback)
* Content Source: [typographydocs/font-list/tunga.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/tunga.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alib-ms** [comment]
Thank you for contacting us. For Windows 10 Tunga designed for Kannada language support was moved to feature-on-demand packages, which get installed automatically based on language settings, or can be added manually by users. If you want all fonts installed that were part of the Windows 7 image, easiest way (this doesn’t add keyboards or proofing tools) is to navigate to Font Settings on Windows 10 and click “Download fonts for all languages”. This installs all the optional fonts simultaneously.
