### ISSUE TITLE
Fields of BigGlyphMetrics and SmallGlyphMetrics lack a description

### ISSUE THREAD

**Issue by wezm** [MicrosoftDocs/typography-issues#352]
It wasn't immediately clear to me what the units of the fields in these structures were (pixels or font units) as they lack a description. 

This applies to the following pages

* [EBLC](https://docs.microsoft.com/en-us/typography/opentype/spec/eblc#bitmapFlags)
* [EBDT](https://docs.microsoft.com/en-us/typography/opentype/spec/ebdt)
* [CBDT](https://docs.microsoft.com/en-us/typography/opentype/spec/cbdt)

I note that [Apple's `bdat` documentation](https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6bdat.html), which some of the OpenType documentation seems to be derived from does contain a description of each of the fields.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0365b54a-dcf0-ee85-aae7-4e2a2288793f
* Version Independent ID: dc587a8a-3ab6-5d0c-6743-c0a46992d391
* Content: [EBDT - Embedded Bitmap Data Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/ebdt)
* Content Source: [typographydocs/opentype/spec/ebdt.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/ebdt.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Fixed for the next version.
