### ISSUE TITLE
Show font changes for different Windows 10 build versions

### ISSUE THREAD

**Issue by caraitto** [MicrosoftDocs/typography-issues#355]
Windows 10 has had several feature updates since it's initial launch. Have any fonts changed in those feature updates? It would be good to have information about such changes, if they occurred (or a note that the installed fonts haven't changed yet).

I tried to find such information by clicking on the "contributors" circular badges next to the "14 minutes to read" (to view the page markdown history on Github), but the link was broken. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0610f6-7c7b-b771-e635-84663af729db
* Version Independent ID: 50a9b23c-733c-c934-95dc-0bbd5d502fea
* Content: [Font List Windows 10 - Typography](https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list#feedback)
* Content Source: [typographydocs/fonts/Windows_10_Font_List.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/fonts/Windows_10_Font_List.md)
* Product: **typography**
* GitHub Login: @nihar
* Microsoft Alias: **nihar**

**Comment by alib-ms** [comment]
Hi

Thank you for the feedback. We will look into adding information related to new fonts added to various Windows 10 feature updates. 

> I tried to find such information by clicking on the "contributors" circular badges next to the "14 minutes to read" (to view the page markdown history on Github), but the link was broken.

The link is not broken. You are not able to see version history of the page due to permissions.
