### ISSUE TITLE
Calibri Rendering of the joined up P پ in Persian

### ISSUE THREAD

**Issue by HB1591** [MicrosoftDocs/typography-issues#356]
Calibri font renders the پ  (P) when joining it with ی (E) n Persian in correctly. Only two of its 3 dots are displayed unless the line spacing is increased dramatically otherwise the third dot disappears.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c7cadc-6eb0-3a3a-b325-de0aa45e4852
* Version Independent ID: 65e39cbd-0456-87d9-2446-d46dd39dce71
* Content: [Calibri font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/calibri#feedback)
* Content Source: [typographydocs/font-list/calibri.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/calibri.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alib-ms** [comment]
Thank you for the feedback. I typed P-Y in a Word document with default settings and the dots display fine. I changed the line spacing to 1.05, where some clipping occurs, and changed to 1.0 where the third dot is clipped completely. We had to work with the limited metrics of the Latin when we designed the Arabic and this is one of the limitations. This is by design.

**Comment by HB1591** [comment]
This is REALLY a POOR answer. Arabic does not have the letter P. But language aside, the persian language users may as well stop using this font because it has a BASIC DESIGN FLAW. Fix it! And please give the user more time before closing tickets. Ridiculous.

**Comment by HB1591** [comment]
I have been a supporter of Microsoft and Windows as a standard not using imported fonts to avoid the problem of having to embed fonts or requiring the user to import fonts. The same problem does not occur with Arial or Times New Roman (or even the new Dubai font which given its name may not even accommodate Persian but it does beautifully). I would have liked to use the new Calbri for Persian but the above excludes it now. Why can the joined up پ be stretched in those fonts and not in Calibri. It is a problem specific to Calibri design it seems so it can be corrected.
Also in future please give more time before closing a ticket.
