### ISSUE TITLE
Incomplete example for 'ssty'

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#357]
The example for 'ssty' is truncated. It also begins with the word “Depending”, which serves no purpose in that sentence.

> Depending In <var>a</var><sup><var>b</var><sup><var>c</var></sup></sup> formula letter b will be substituted with script level 1 variant and letter c

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3b75f69-8bb1-88e5-05b9-035c9f3ec528
* Version Independent ID: 9a9af849-512e-5dfd-b9a6-c05480f34f01
* Content: [Registered features, p-t - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/features_pt)
* Content Source: [typographydocs/opentype/spec/features_pt.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_pt.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Partial fix was made in OT183, but not mentioned in the errata. Added that, then cleaned up the changes in features_pt for the next version.
