### ISSUE TITLE
Advice from Unicode about meteg and hataf vowels

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#36]
Beyond what is written in appendix C, Unicode gives further advice for combinations of meteg and hataf vowels (https://www.unicode.org/versions/Unicode11.0.0/ch09.pdf#page=7). It would be helpful to copy that advice here, or link to it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f254cf36-ec09-f8a5-ce2a-02f435b4f43e
* Version Independent ID: c48c2f0f-48e6-e1ee-9bd4-4627b87ac621
* Content: [| Microsoft Docs](https://docs.microsoft.com/en-us/typography/script-development/hebrew)
* Content Source: [typographydocs/script-development/hebrew.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/hebrew.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
Added the link to Unicode.
