### ISSUE TITLE
USE script tags missing from script tag registry

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#363]
The following script tags are defined in the Universal Shaping Engine documentation, but are missing from the Script Tags registry:

Elymaic / elym
Nandinagari / nand
Nyiakeng Puachue Hmong / hmnp
Wancho / wcho

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49c1efc4-e864-0727-9663-7cec0ec4d9f1
* Version Independent ID: 36ec4396-b9cb-cba9-1582-d8400296d249
* Content: [Script tags - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/scripttags)
* Content Source: [typographydocs/opentype/spec/scripttags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/scripttags.md)
* Product: **typography**

**Comment by PeterCon** [comment]
Cf. #410

**Comment by PeterCon** [comment]
Need to add scripts from Unicode 12 and Unicode 13: 

* Chorasmian: 'chrs'
* Dives Akuru: 'diak'
* Elymaic: 'elym'
* Nyiakeng Puachue Hmong: 'hmnp'
* Khitan small script: 'kits'
* Nandinagari: 'nand'
* Wancho: 'wcho'
* Yezidi: 'yezi'

**Comment by PeterCon** [comment]
Fixed for the next version.
