### ISSUE TITLE
Great font and nice page, but how do I download it????

### ISSUE THREAD

**Issue by johnerbes** [MicrosoftDocs/typography-issues#375]
How do I download this font?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6183f33-6bd9-d594-abb1-55d7a7e7a429
* Version Independent ID: 58b29f6a-b523-b47a-611d-1b9f936bbc22
* Content: [Arial Rounded MT font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/arial-rounded-mt#feedback)
* Content Source: [typographydocs/font-list/arial-rounded-mt.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/arial-rounded-mt.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by RossKor** [comment]
I found it for download by searching for the file name "arlrdbd.ttf" in this case.
