### ISSUE TITLE
Thanks for taking the time...

### ISSUE THREAD

**Issue by Hyakamooks** [MicrosoftDocs/typography-issues#376]
...to make this humorous.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6eb90a9a-7d51-e91b-93a1-51c089d94d0a
* Version Independent ID: 40f302ed-fd04-71e6-0f13-d7622d4f7d12
* Content: [Old English Text MT font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/old-english-text-mt#feedback)
* Content Source: [typographydocs/font-list/old-english-text-mt.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/old-english-text-mt.md)
* Product: **typography**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alib-ms** [comment]
Thank you for the feedback!
