### ISSUE TITLE
vert table vs. vert feature

### ISSUE THREAD

**Issue by mekkablue** [MicrosoftDocs/typography-issues#378]
I assume the reference to a ‘vert _table’_ in the description of the vert _feature_ is a typo. I believe there never was a vert _table._

HTH, Rainer

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fbeb5c1d-50da-292e-f57c-3ab31fec293d
* Version Independent ID: 04608cee-166f-715a-10fc-9f62139b99e2
* Content: [Registered features, u-z - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec150/features_uz)
* Content Source: [typographydocs/opentype/otspec150/features_uz.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec150/features_uz.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by alib-ms** [comment]
Thank you for letting us know. I have fixed the typo.
