### ISSUE TITLE
Inappropriate example for language system

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#379]
The page “OpenType Layout common table formats” uses an image (figure 2b) with sentences in English, French, and German to illustrate the differences between language systems, and explains in the text that “the eszet ligature is used in the German language system, but not in French or English”.

However, the differences that matter in the context of OpenType layout are those that result in identical character sequences being rendered with different glyph sequences, or differently positioned glyphs. That’s not the case here. The “eszet ligature” is encoded in Unicode as a separate character U+00DF, more recently complemented by an uppercase forms U+1E9E. The difference between “ss” and “ß” may be semantically significant; for example, “Masse” and “Maße” are two different words in German. A font should therefore never attempt to form an “eszet ligature” through OpenType shaping.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb42967-20ca-9270-4572-65315127fcc5
* Version Independent ID: 1fa413f1-71cf-ac2a-0999-70dd5d8ac4cd
* Content: [OpenType layout common table formats - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/chapter2#slTbl_sRec)
* Content Source: [typographydocs/opentype/spec/chapter2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/chapter2.md)
* Product: **typography**

**Comment by PeterCon** [comment]
Valid issue, but old, doesn't mislead on what language systems _do_, and will require crafting a new figure.

**Comment by PeterCon** [comment]
The same example was being used in [ttochap1](https://docs.microsoft.com/en-us/typography/opentype/spec/ttochap1), and a separate issue (#501 ) was opened for that. Changes for both are made for the next version using smcp for "i" in English vs. Turkish as the example.
![otlch2_fig2b](https://user-images.githubusercontent.com/12788502/91893717-6507d000-ec49-11ea-839f-31fcba265b21.png)
