### ISSUE TITLE
Bahnschrift Family in seperated TTF-Files

### ISSUE THREAD

**Issue by zivi78** [MicrosoftDocs/typography-issues#384]
for the app AnyFont on the iPad i need a ttf.-File wich contains only one Font of Font Family Bahnschrift. All ttf. i found there are 14 fonts in it.

Where can i get ttf's with only 1 font e.g. Bahnschrift Light

_Originally posted by @zivi78 in https://github.com/MicrosoftDocs/typography-issues/issues/295#issuecomment-600243058_

**Comment by alib-ms** [comment]
Hi,

Bahnschrift is designed in a variable font format with built in name instances in a single .ttf file. When this font is installed, you will see all the built-in name instances in the font menu. You might want to look for alternate versions of DIN (Bahnschrift is Microsoft version of DIN) that are in regular formats (not the “Variable Font” format) for use on iOS.
