### ISSUE TITLE
Bahnschrift font commercial usage

### ISSUE THREAD

**Issue by respecter44** [MicrosoftDocs/typography-issues#386]
Hi,

we are a small design studio is Hungary, and we made beer label for a client with use of Bahnschrift font. 
I red the licence but for me that isn't clear that we have permission to use it on a label.

Thanks for your reply.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ea5ad39-ec78-af12-1479-e3def2c62723
* Version Independent ID: 4c9dbe2a-0d30-42fe-34be-38053fcf5c4e
* Content: [Font redistribution FAQ - Typography](https://docs.microsoft.com/en-us/typography/fonts/font-faq#feedback)
* Content Source: [typographydocs/fonts/font-faq.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/fonts/font-faq.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Hi, 

The FAQ seems to be very clear on this subject. In particular… 
“Can I sell things I print from Windows, say a book, report, t-shirts or crafts that use fonts that come with Windows?” 
Do you not feel a label falls into this category?
