### ISSUE TITLE
OCR-A font usage for advertisement/ package

### ISSUE THREAD

**Issue by imjudy** [MicrosoftDocs/typography-issues#387]
Hello, I'd like to verify the usage permission for the OCR-A font.
We're considering to use it in print ads. 

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 1ea5ad39-ec78-af12-1479-e3def2c62723
* Version Independent ID: 4c9dbe2a-0d30-42fe-34be-38053fcf5c4e
* Content: [Font redistribution FAQ - Typography](https://docs.microsoft.com/ko-kr/typography/fonts/font-faq#feedback)
* Content Source: [typographydocs/fonts/font-faq.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/fonts/font-faq.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Hi, , We currently don't ship OCR-A with Windows or Office.
