### ISSUE TITLE
So where is it?

### ISSUE THREAD

**Issue by SplatManDK** [MicrosoftDocs/typography-issues#388]
How do I download or purchase this font? It is not in Office or Windows, and I can't find any information on where to get it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f1360cc-06aa-3a93-dae0-69bbae45cac3
* Version Independent ID: 41421a84-cd8c-6536-9e5f-c964eddd3a9d
* Content: [LCD font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/lcd#feedback)
* Content Source: [typographydocs/font-list/lcd.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/lcd.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
LCD font is no longer shipped with Office. If you wish to you can license/purchase this font from https://www.fonts.com/font/itc/lcd
