### ISSUE TITLE
Windows Server 2012 R2: Only Bahnschrift Regular gets installed

### ISSUE THREAD

**Issue by CBDFactum-com** [MicrosoftDocs/typography-issues#389]
On Windows Server 2012 R2 only Bahnschrift Regular gets installed, while on Windows 10 all available font styles get installed from the same font package.

How can be this fixed so all styles become available?

Windows 10:
![image](https://user-images.githubusercontent.com/9625486/77781411-d10c5980-7055-11ea-8dd2-1bdcbc734b3f.png)

Windows Server 2012 R2:
![image](https://user-images.githubusercontent.com/9625486/77781450-e1243900-7055-11ea-8a18-f48651ecd660.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b0aa22d-ec65-a36b-3a23-ca87e18ada28
* Version Independent ID: 05d3eb61-7b3c-24f6-dc0e-cb9d02e1c3a0
* Content: [Bahnschrift font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/bahnschrift)
* Content Source: [typographydocs/font-list/bahnschrift.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/bahnschrift.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **v-nihar**

**Comment by alib-ms** [comment]
Hi 

Thank you for the feedback. Bahnschrift is a variable font. It was introduced as a new addition to the Windows font family (Windows 10 version 1709 release on October 17, 2017). Prior version of Windows do not support variable fonts.  This is why you are seeing only regular weight available on Windows Server 2012 R2. This font should not be available on Windows Server 2012 R2. Can you please share how did you discover this font on Windows Server 2012 R2? 

Thanks,
Ali

**Comment by CBDFactum-com** [comment]
Hi Ali,

as I wrote, I installed the font file on Windows 10 & Windows Server 2012 R2 and discovered the differences.

I understand your explanation. So, to make a long story short: Windows Server 2012 R2 will never support “Variable fonts”?

Thank you for your support, Peter

**Comment by alib-ms** [comment]
Hi Peter, 
Windows Server 2012 R2 is long past getting feature updates, so it will never support variable fonts.
