### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by shandysulen** [MicrosoftDocs/typography-issues#390]
There should be a space in History of TrueTypedocument

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bb966bef-f887-40af-3602-46cdf4bf96ec
* Version Independent ID: 39c36be8-9aac-9f6b-04d3-53fbf5acd31f
* Content: [TrueType overview - Typography](https://docs.microsoft.com/en-us/typography/truetype/#feedback)
* Content Source: [typographydocs/truetype/index.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/truetype/index.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Thank you for the feedback. Fixed!
