### ISSUE TITLE
typo / off by one in the os/2 table section.

### ISSUE THREAD

**Issue by HinTak** [MicrosoftDocs/typography-issues#392]
Further up, in the description about the individual bits, it says bit 92 was added in Version 3. So the paragraph below should read "84 to 92" and "93 to 122". 

```
Version 3: Version 3 was defined in OpenType 1.4 with assignments for bits 84 to 91 corresponding to additional ranges in Unicode 3.2. In addition, some already-assigned bits were extended to cover additional Unicode ranges for related characters; see details in the table above. 

Version 4: Version 4 was defined in OpenType 1.5 with assignments for bit 58 and bits 92 to 122 corresponding to additional ranges in Unicode 5.1. Also, bits 8, 12, 14, 27 and 53 were re-assigned (see version 1 for previous assignments). In addition, some already-assigned bits were extended to cover additional Unicode ranges for related characters; see details in the table above.
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ae9457c-0d3d-c137-588b-81d54a086f07
* Version Independent ID: 658c6d22-b9d1-1007-9cdb-6898911c9c75
* Content: [OS/2 - OS/2 and Windows metrics table specification - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#feedback)
* Content Source: [typographydocs/opentype/spec/os2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/os2.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterConstable** [comment]
I agree. This is informative info that should get corrected in the next version of the spec, as follows:

**Version 3:** Version 3 was defined in OpenType 1.4 with assignments for bits 84 to 92 corresponding to additional ranges in Unicode 3.2. In addition, some already-assigned bits were extended to cover additional Unicode ranges for related characters; see details in the table above.

**Version 4:** Version 4 was defined in OpenType 1.5 with assignments for bit 58 and bits 93 to 122 corresponding to additional ranges in Unicode 5.1. Also, bits 8, 12, 14, 27 and 53 were re-assigned (see version 1 for previous assignments). In addition, some already-assigned bits were extended to cover additional Unicode ranges for related characters; see details in the table above.

**Comment by alib-ms** [comment]
Thank you we will get this fixed in the next version of the spec.
