### ISSUE TITLE
Errors in this list

### ISSUE THREAD

**Issue by DLasher106** [MicrosoftDocs/typography-issues#393]
I have Win 10 1909 installed. I do not have the following fonts that are listed on this page:
Arial Black Italic
Wingdings 2
Wingdings 3
Is the above list in error (caused by wrongly including all the fonts in the Arial Black and Wingdings families)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0610f6-7c7b-b771-e635-84663af729db
* Version Independent ID: 50a9b23c-733c-c934-95dc-0bbd5d502fea
* Content: [Font List Windows 10 - Typography](https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list#feedback)
* Content Source: [typographydocs/fonts/Windows_10_Font_List.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/fonts/Windows_10_Font_List.md)
* Product: **typography**
* GitHub Login: @nihar
* Microsoft Alias: **nihar**

**Comment by alib-ms** [comment]
Thank you for letting us know. I have fixed it. These fonts Arial Black Italic, Wingdings 2, and Wingdings 3 are installed with Office. 

Ali
