### ISSUE TITLE
GPOS Type 7, format 2: "PosClassRuleSet" would be better name  

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#394]
In the spec for type 7, format 2, there's a table structure currently named "PosClassSet". This contains an array of offsets to "PosClassRule" tables. This is parallel in structure to type 7, format 1, in which the "PosRuleSet" table contains an array of offsets to "PosRule" tables. So, to be consistent in naming and to reflect what the table contains, "PosClassSet" would be better named as "PosClassRuleSet". 

If changed as proposed, then the fields "posClassSetCount" and "posClassSetOffsets" in the ContextPosFormat2 table should also be renamed "posClassRuleSetCount" and "posClassRuleSetOffsets".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f748ff4-44a6-6395-e0ce-d249b8c9541b
* Version Independent ID: b80d0359-5657-632b-29e8-142c06902001
* Content: [GPOS — Glyph Positioning Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/gpos#feedback)
* Content Source: [typographydocs/opentype/spec/gpos.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gpos.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Need to take #519 into consideration as well.

**Comment by PeterCon** [comment]
Superseded by changes for #519. (Would need to revisit if those changes were not kept.)
