### ISSUE TITLE
GPOS type 8, format 2: "ChainPosClassRuleSet" would be better name

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#395]
As per the feedback in issue #394, regarding type 7, format 2, the following name changes would provide better consistency:

ChainContextPosFormat2 members:
- chainPosClassSetCount -&gt; chainPosClassRuleSetCount
- chainPosClassSetOffsets -&gt; chainPosClassRuleSetOffsets

ChainPosClassSet table -&gt; ChainPosClassRuleSet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f748ff4-44a6-6395-e0ce-d249b8c9541b
* Version Independent ID: b80d0359-5657-632b-29e8-142c06902001
* Content: [GPOS — Glyph Positioning Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/gpos#feedback)
* Content Source: [typographydocs/opentype/spec/gpos.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gpos.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Superseded by changes for #519. (Would need to revisit if those changes were not kept.)
