### ISSUE TITLE
GPOS type 7, format 2: "inputSequence" would be better name

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#397]
GPOS type 7, format 2 is analogous and similar in structure to GSUB type 5, format 2. Because of the similarities, it is helpful to use similar naming conventions. There is also similarity with GPOS type 7, format 1 (glyph IDs vs. glyph classes) and so it is helpful to have similar naming conventions with that.

In the PosClassRule table, the third field is currently named "classes". This differs from GPOS type 7, format 1 and from GSUB type 5, format 2, both of which use "inputSequence" for the corresponding field. That would be a better name for the third field in the PosClassRule table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f748ff4-44a6-6395-e0ce-d249b8c9541b
* Version Independent ID: b80d0359-5657-632b-29e8-142c06902001
* Content: [GPOS — Glyph Positioning Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/gpos#lookup-type-7-contextual-positioning-subtables)
* Content Source: [typographydocs/opentype/spec/gpos.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gpos.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Superseded by changes for #519. (Would need to revisit if those changes were not kept.)
