### ISSUE TITLE
logical OR: Wrong description

### ISSUE THREAD

**Issue by jenskutilek** [MicrosoftDocs/typography-issues#399]
https://docs.microsoft.com/de-de/typography/opentype/spec/tt_instructions#logical-or

The description states that the instruction pushes "(e1 and e2): logical and of e1 and e2 (uint32)", but it should read "(e1 or e2): logical or of e1 and e2 (uint32)".

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 9eb69554-e257-e483-2e26-7f04fdf44fd8
* Version Independent ID: d560a11c-2ac5-1abc-7165-453c3a9618c8
* Content: [The TrueType Instruction Set - Typography](https://docs.microsoft.com/de-de/typography/opentype/spec/tt_instructions)
* Content Source: [typographydocs/opentype/spec/tt_instructions.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/tt_instructions.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **v-nihar**

**Comment by alib-ms** [comment]
Thank you for the feedback. Fixed!

**Comment by alib-ms** [comment]
Thank you for the feedback. This issue has been corrected.

**Comment by PeterCon** [comment]
This should have been called out as an erratum for OT 1.8.3.

Also, this error was introduced when this content was ported from .docx files to .md. It is repeated across all OT versions, which should also be fixed since all versions were regressed during the port.

**Comment by PeterCon** [comment]
Fixed in all versions.
