### ISSUE TITLE
Typo: "boundries"

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#4]
In “All tables must begin on four-byte boundries, and any remaining space between tables is padded with zeros” the word “boundries” should be “boundaries”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a1bda96-a268-b684-6cea-9b0c7be6f24e
* Version Independent ID: 36485fec-f05d-3984-6da8-ff2dd2799041
* Content: [OpenType font file - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otff)
* Content Source: [typographydocs/opentype/spec/otff.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otff.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Thanks. This will be fixed in OpenType 1.8.3.
