### ISSUE TITLE
Confusion about the order of 'frac', 'numr', and 'dnom'

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#40]
The description of 'frac' mentions “the numr feature (see below)” and “the dnom feature (see below)”. They are on different pages, not above or below; if they were all on the same page, 'dnom' would be above 'frac'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb16259e-1f7c-4e96-02b8-f692eb3e77e7
* Version Independent ID: eab1b2c5-0209-ccdf-b898-bbc5b5dbbe0f
* Content: [Registered features, f-j - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/features_fj)
* Content Source: [typographydocs/opentype/spec/features_fj.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_fj.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Fixed for the next version. (Also looked for other "see above" / "see below" issues in the feature tag registry.) Thanks!
