### ISSUE TITLE
'post' table section could be updated to reflect the current Adobe Glyph List Specification

### ISSUE THREAD

**Issue by eliheuer** [MicrosoftDocs/typography-issues#400]
Looking at the [Adobe Glyph List Specification](https://github.com/adobe-type-tools/agl-specification), It appears the note in the ['post' section](https://docs.microsoft.com/en-us/typography/opentype/spec/recom#post-table) about the 31 character limit is out of date.

In the change-log for the Adobe spec, Ken Lunde wrote:

>Version 2.8 (August 9, 2018) The length-limit of glyph names was adjusted from 31 to 63 characters to reflect current practices and implementations, along with a note that some older implementations may impose a 31-character limit.

The Adobe spec now says:

>...in practice, particularly in modern environments, glyph names can be as long as 63 characters...

>All glyph names are subject to a length-limit of 63 characters, and require that they be entirely composed of characters from the following set: A–Z, a–z, 0–9, ‘.’ (period; U+002E FULL STOP), and ‘_’ (underscore; U+005F LOW LINE). Some older implementations may impose a length-limit of 31 characters.

Please update the note in the ['post' section](https://docs.microsoft.com/en-us/typography/opentype/spec/recom#post-table) to mention the new 63 character limit. I have found that for most fonts that include the Arabic script, the 31 character limit is too short. 

I had an issue recently with a QA check in the Google Fonts tool FontBakery that was related to this information being out of date: https://github.com/googlefonts/fontbakery/issues/2832 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95e88b53-d670-0240-422c-72748258ab2a
* Version Independent ID: b5fff1ee-cf03-e424-a2dc-aee58e0429e4
* Content: [Recommendations for OpenType Fonts - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/recom#feedback)
* Content Source: [typographydocs/opentype/spec/recom.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/recom.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by alib-ms** [comment]
Thank you for the feedback. I spoke to one of the engineers regarding this proposed change. Looks like this change needs to be further investigated due to its implications on existing applications.  Therefore pushing this issue to next version of the spec.

**Comment by PeterCon** [comment]
Change made for next version: Moved requirements out of the Recommendations chapter into the 'post' chapter, incorporating the proposed change.

'post':
><ins>Name strings are encoded in ASCII. Valid characters are limited to A–Z, a–z, 0–9, “.” (FULL STOP), and “_” (LOW LINE). Names must be no longer than 63 characters; some older implementations may assume a length limit of 31 characters.</ins>

Recommendations:
><del>All information required, although the VM Usage fields may be set to zero. </del>OpenType fonts containing CFF outlines use only format 3.0 of the &#39;post&#39; table. Glyph names <del>must be assigned as described</del><ins>should follow conventions provided</ins> in the [Adobe Glyph List Specification](https://github.com/adobe-type-tools/agl-specification), which specifies glyph naming conventions for all Unicode characters as well as those that don’t have standard Unicode values such as <del>certain </del>ligatures or glyphic variants.
...
><del>NOTE: The PostScript glyph name must be no longer than 31 characters, include only uppercase or lowercase English letters, European digits, the period or the underscore, i.e. from the set [A-Za-z0-9_.] and should start with a letter, except the special glyph name “.notdef” which starts with a period.</del>

**Comment by tiroj** [comment]
I'm not entirely happy with this recommendation even as a _should_, although that is certainly better than _must_. Glyph names _may_ map, using Adobe’s conventions, to Unicode characters, and should if one wants fonts to work with Acrobat text reconstruction from glyph strings, but they may also use other conventions, not map to Unicode characters, or be entirely absent.

**Comment by PeterCon** [comment]
Thanks, John. Based on that feedback, I've revised to the following:

><del>All information required, although the VM Usage fields may be set to zero. </del>OpenType fonts containing CFF outlines use only format 3.0 of the &#39;post&#39; table. <del>Glyph names must be assigned as described</del><ins>When devising glyph names, font developers may wish to consider conventions provided</ins> in the [Adobe Glyph List Specification](https://github.com/adobe-type-tools/agl-specification), which specifies glyph naming conventions for all Unicode characters as well as <del>those that don’t have standard Unicode values</del><ins>for glyphs not directly encoded as Unicode characters,</ins> such as <del>certain </del>ligatures or glyphic variants.

**Comment by NorbertLindenberg** [comment]
What other conventions are there for glyph names in the `post` table?

**Comment by tiroj** [comment]
Our convention of totally not bothering to follow Adobe's convention for complex script fonts because the Acrobat text reconstruction doesn't work anyway. :)

**Comment by sairuspatel** [comment]
Re. the length limits part of the proposal ("Names must be no longer than 63 characters; some older implementations may assume a length limit of 31 characters") – sounds good to me.

**Comment by behdad** [comment]
> Name strings are encoded in ASCII. Valid characters are limited to A–Z, a–z, 0–9, “.” (FULL STOP), and “_” (LOW LINE).

Any reason for this? I suggest adding plus/minus as well. In general, why is this limitation still there at all?

**Comment by PeterCon** [comment]
In this draft, I've maintained limitations that were already stated in the spec. I'd have no problem loosening the restriction if there's general consensus to do so.

**Comment by khaledhosny** [comment]
I think the assumption is that the glyph names have to be valid for using in CFF/PostScript/PDF whatever, but this ship has long sailed and fonts on the wild don’t respect this restriction (same for name ID 6) and software that needs this (e.g. for embedding fonts in PDF) have to work around such fonts.

**Comment by sairuspatel** [comment]
Those limitations on valid characters in glyph names are from the Adobe Glyph List Specification. A lot of careful research went into coming up with that set in the AGL Spec. Extending it to allow for  to allow for hyphen for example may be problematic in feature file syntax (e.g. denoting ranges can be done today by "[A-F]") and yes are almost certainly problematic in the specs Khaled mentioned (I haven't checked recently).

Glyph names are interesting in that they are a somewhat legacy concept in OT, but are still definitely useful as human-readable names when producing a font or peeking into a font.

> this ship has long sailed and fonts on the wild don’t respect this restriction (same for name ID 6) and software that needs this (e.g. for embedding fonts in PDF) have to work around such fonts.

If I had more of a sense of what kind of fonts are doing this, and how many there are, and why they're doing it, I could get a better feel for whether such names should be allowed for in the post table spec (even if they don't follow the AGL Spec's character limitations).

**Comment by PeterCon** [comment]
If there's a broad consensus, I could see this being relaxed to allow for other characters (but what set?), or to relax the requirement to a recommendation. But if relaxed, it seems like some caveats would need to be called out in terms of expectations of different tools. I don't think the spec should get bogged down in details regarding different tools; so a general and conservative comment would be best—e.g., "Some tools or applications require the set of characters to be limited to those permitted by AGL."

**Comment by behdad** [comment]
> A lot of careful research went into coming up with that set in the AGL Spec.

lol

> Extending it to allow for to allow for hyphen for example may be problematic in feature file syntax (e.g. denoting ranges can be done today by "[A-F]") and yes are almost certainly problematic in the specs Khaled mentioned (I haven't checked recently).

Any format should allow for specifying full ASCII graphic range, possibly by allowing use of quotation marks. A literal quotation mark in the name can be escaped using a backslash character. A literal backslash can be escaped using another backslash. "A lot of careful research went into" how to specify strings in textual formats...

**Comment by khaledhosny** [comment]
> Extending it to allow for to allow for hyphen for example may be problematic in feature file syntax

Feature file syntax already supports hyphen in glyph names for a while now already.

> If I had more of a sense of what kind of fonts are doing this, and how many there are, and why they're doing it, I could get a better feel for whether such names should be allowed for in the post table spec (even if they don't follow the AGL Spec's character limitations).

I did not do a survey of existing fonts, but PDF producers, for example, have to take care of creating valid PDF files even of PostScript name or glyph names are not valid for PDF, so fonts already get away with this. Since fonts can be created with no glyph names at all, “bad” glyph names can’t be any worse.

**Comment by sairuspatel** [comment]
I wasn’t sure, but I do see the syntax has been extended to handle that for “development glyph names” (as opposed to final production glyph names). Thanks, Khaled.

**Comment by NorbertLindenberg** [comment]
The purpose of specifications is to enable interoperability, in this case between various pieces of software producing or consuming fonts. For the `post` table, one known group of consumers are PDF producers, and the AGL is a spec that connects fonts and PDF.

It seems to me that if we want to extend the set of characters allowed in `post` tables, then this needs to be coordinated with the AGL. It’s not enough to rely on undocumented workarounds that some consumers may have implemented.

**Comment by sairuspatel** [comment]
I propose we defer resolution of extending characters allowed in 'post' glyph names to OT 1.9. It will require more investigation.

**Comment by PeterCon** [comment]
Clarifying: here is the current draft revisions that I have:

**post:**
(new paragraph added--the length limit was previously stated as a req't, but in the Recommendations)

><ins>Name strings are encoded in ASCII. Valid characters are limited to A–Z, a–z, 0–9, “.” (FULL STOP), and “_” (LOW LINE). Names must be no longer than 63 characters; some older implementations may assume a length limit of 31 characters.</ins>

**Recommendations:**

><del>All information required, although the VM Usage fields may be set to zero. </del>OpenType fonts containing CFF outlines use only format 3.0 of the &#39;post&#39; table. <del>Glyph names must be assigned as described</del><ins>When devising glyph names, font developers may wish to consider conventions provided</ins> in the [Adobe Glyph List Specification](https://github.com/adobe-type-tools/agl-specification), which specifies glyph naming conventions for all Unicode characters as well as <del>those that don’t have standard Unicode values</del><ins>for glyphs not directly encoded as Unicode characters,</ins> such as <del>certain </del>ligatures or glyphic variants.
>
><del>Note that names for all glyphs must be supplied as it cannot be assumed that all Microsoft platforms will support the default names supplied on the Macintosh.</del><ins>Some applications might not implicitly support standard Macintosh glyph names. Any glyph names should be provided explicitly in the font.</ins>
>
><del>NOTE: The PostScript glyph name must be no longer than 31 characters, include only uppercase or lowercase English letters, European digits, the period or the underscore, i.e. from the set [A-Za-z0-9_.] and should start with a letter, except the special glyph name “.notdef” which starts with a period.</del>

@sairuspatel Please clarify: you're suggesting to postpone any question of extending the set of valid characters, or postpone extending the length limit from 31 to 63?

(Btw, I would not have changed the set of valid characters based on this issue: if desired, it should be opened as a new issue.)

**Comment by sairuspatel** [comment]
@PeterCon to clarify: Adobe is good with going ahead with extending the glyph name length limit ("Names must be no longer than 63 characters; some older implementations may assume a length limit of 31 characters") for OT 1.8.4.
