### ISSUE TITLE
Missing a new line between "Segoe UI Light" and "Segoe UI Light Italic"

### ISSUE THREAD

**Issue by abu-co** [MicrosoftDocs/typography-issues#402]
It is displaying as "Segoe UI LightSegoe UI Light Italic".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3c2a6fb-3005-b23b-bc83-f8046b852851
* Version Independent ID: f5d0fbf0-990b-7b3d-0c4a-bd4b51c8532e
* Content: [Segoe UI font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/segoe-ui#feedback)
* Content Source: [typographydocs/font-list/segoe-ui.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/segoe-ui.md)
* Product: **typography**
* GitHub Login: @nihar
* Microsoft Alias: **nihar**

**Comment by alib-ms** [comment]
Thank you for the feedback. This issue has been corrected.
