### ISSUE TITLE
Need a ruling on the ambiguity of a format 4 record conflicting with other records

### ISSUE THREAD

**Issue by robmck-ms** [MicrosoftDocs/typography-issues#403]
E.g. If you have a format 2 record that specifies a range, and a format 4 record that includes a point in that range as part of it's coordinates, or if you have a format 1 that defines a value (e.g. Semibold), and a format 4 that includes that value as part of it's coordinates. 

Which takes precedence? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dac86fb-3792-6630-ade2-32bfc4bba93a
* Version Independent ID: 9de5c023-f363-3e42-43c9-eac7793c8eaa
* Content: [STAT — Style Attributes Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/stat#feedback)
* Content Source: [typographydocs/opentype/spec/stat.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/stat.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by robmck-ms** [comment]
Also need to add a ruling on how to compose names with a Format 4. 

Normally, as described in the spec, the axisOrdering property determines the order in which strings are concatenated. But, Format 4 includes multiple axes, so it's not clear where the string for Format 4 should go. 

Example: 

STAT table:
  format 1, “ital”=0, “Regular”
  format 1, “ital”=0.5, “Semitalic”
  **format 1, “ital”=1, “Italic”**
  format 4, “wdth”=50 “wght”=700, “Nold” // Narrow + Bold (silly nonsense name)
  **format 4, “wdth”=200 “wght”=300, “Wight” // Wide + Light**

Requested instance: {“wdth”=200, “wght”=300, “ital”=1}

Assuming the records marked in Bold above are selected, then should the name be "Wight Italic" or "Italic Wight"? The axisOrdering field helps somewhat, e.g. in the case above, if wdth and wght had axisOrdering of 0, 1 respectively, and ital of 2, then the obvious answer would be "Wight Italic". But, if the wdth, wght, ital ordering was 0, 2, 1, then the Format 4 record would have both a higher and lower ranking than the Italic Format 1.

**Comment by Lorp** [comment]
Thanks for adding this, Rob.

I encountered the issue when implementing STAT Format 4 in the [Samsa VF inspector tool](https://lorp.github.io/samsa/src/samsa-gui.html). The heuristic I used was that any format 4 match, being more specific, has a higher precedence in name composition than other matches, and is therefore always _prepended_ to the name string being composed.

Note that there may be _multiple_ format 4 matches, in which case the format 4 strings should all come at the start of the name, in the same order they are indexed in the list of axisValueTables.

Possibly any single-axis matches, i.e. not format 4, should be used only if they are not already matched by a Format 4 match. So, in Rob’s example above, if there was another axisValueTable:

format 1, “wght”=300, “Light”

Then, at the same requested instance {“wdth”=200, “wght”=300, “ital”=1}, we would again obtain the name “Wight Italic”. The string “Light” would be elided because its value of 300 was already matched in the matching Format 4 entry. (This not implemented.)

This still leaves a more general problem of a Format 4 match on _n_ axes, and other Format 4 matches on _m_ axes (where _m_<_n_). So the above heuristic could be generalized to include strings based on matching each axis only once, starting with the axisValueTable covering the most axes.

**Comment by PeterCon** [comment]
There seem to be two distinct issues:
- Precedence: format 4, vs format 2 range, vs format 1

Name ordering involving format 4 and other AVTs.

**Comment by PeterCon** [comment]
Wrt precedence, I think the general rule should be most specific takes precedence. So, given

>Requested instance: {“wdth”=200, “wght”=300, “ital”=1}

and 
>format 1, “wght”=300, “Light”
>format 4, “wdth”=200 “wght”=300, “Wight” // Wide + Light

the format4 AVT takes precedence over the format1 AVT, and the latter is not used. Same would be true if the format1 were replaced with a format2 having a range that includes wght=300.

Similarly, given
>format 1, “wght”=300, “Light”
>format 2, "wght", nominal = 250, range [100, 350], "Lightish"
>requested instance: {wdth=300}
I think the format1 table should take precedence.

Apart from pathalogic cases involving two format4 tables with overlapping but distinct specs, is there any case that this principle wouldn't cover?

**Comment by PeterCon** [comment]
Wrt ordering and format4:

>The heuristic I used was that any format 4 match, being more specific, has a higher precedence in name composition than other matches, and is therefore always prepended to the name string being composed.

Interesting. Suppose 
>format1 wdth=200, "Wide"
> format4 wght=300 ital=1, "Lightalic"
>axis ordering: wdth < wght < ital
It sounds from what you said that you would make the composed string "Lightalic Wide". Given the values and ordering, I would have thought it should be "Wide Lightalic".

**Comment by Lorp** [comment]
Hmm, yes, I can’t see now why composition ordering should be anything other than the order of the axisValueTables.

**Comment by PeterCon** [comment]
In my current draft, I've added text in the section on AVT format 4 as a partial fix for this issue:

><ins>When searching for an axis value table to match a particular combination of values, if two format 4 tables are found to be a partial match for that combination of values, the table that matches a greater number of values (the most specific match) should be used. If two matching tables are equally specific—the same number of values for for a different set of axes—then the first matching table should be used.</ins>

**Comment by PeterCon** [comment]
Added to the previous revision:

><ins>Similarly, if a format 1, format 2 or format 3 table has a (nominal) value used in a format 4 table that also has values for other axes, the format 4 table, being the more specific match, is used.</ins>

**Comment by PeterCon** [comment]
Reconsidering the case of format 1 with value strictly within the range of a format 2 table (not at the min/max), I'm inclined to think the example I gave doesn't make sense—e.g., having a "Lightish" range from [100, 350], but then at one point, 300, using "Light". That seems like it would be confusing. 

In working out revisions for issues #466 and #576, the revisions now include that a format 1 value should not be within the range of a format 2 unless it is the same as the range min or max.

So, altogether, between the revisions mentioned above and other changes pertaining to ranges, I think the precedence issue is covered.

**Comment by PeterCon** [comment]
Wrt ordering for format 4 in name composition, what about saying that the precedence given to the label should be that of the lowest axis referenced in the format 4 table?

**Comment by PeterCon** [comment]
Assuming that works, I propose this addition:

><ins>Because a format 4 table combines values on multiple axes, there may be ambiguity about axis ordering. This may arise when dynamically composing names using the labels provided by axis value tables, or in other situations in which the axisOrdering values of axis records are used. For a format 4 table, the axisOrdering value assumed should be the lowest axisOrdering value for the axes referenced by the format 4 table.</ins>

**Comment by PeterCon** [comment]
With the above revisions, I think this issue has been more or less addressed, so closing.
