### ISSUE TITLE
[GSUB] Interpretation of lookup flags of nested lookups unclear

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#407]
The interpretation of the lookup flags of the nested lookups within contextual, chaining contextual, and reverse chaining contextual substitutions is unclear.

From the specification it would appear that the lookup flags would be respected, which could lead to a different set of glyphs being ignored than in the containing lookup.

However, at the time I ran into a [bug in makeotf](https://github.com/adobe-type-tools/afdko/issues/196) that resulted in this situation, it turned out that the more current versions of the shapers I tested with (HarfBuzz, CoreText, DirectWrite) behaved as if the lookup flag were either 0 or equal to the one of the containing lookup, even when that was not the case. An older version of HarfBuzz on the other hand respected the lookup flag of the nested lookup.

It needs to be clarified in the specification whether the lookup flag of a nested lookup should be applied as is, replaced by 0, or replaced by the the lookup flag of the containing lookup, or if there are any variations on these schemes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34e7df21-eb35-19ab-3573-e075872e5d3b
* Version Independent ID: 4656a3f9-95ea-15cc-25ed-6eccf7adf370
* Content: [GSUB — Glyph Substitution Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/gsub)
* Content Source: [typographydocs/opentype/spec/gsub.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gsub.md)
* Product: **typography**

**Comment by PeterCon** [comment]
Cf. #184

**Comment by PeterCon** [comment]
This issue is relevant for GSUB lookup types 5, 6 or 8, and also to GPOS lookup types 7 or 8.

Reportedly, the intent in the original design and reflected in Microsoft's implementation is that filtering lookup flags in the containing lookup have effect when matching sequences for those lookup subtables; then, after a subtable and sequence have been matched and a nested lookup is referenced, the filtering flags in the nested have effect while processing the nested lookup.

I haven't done any experimentation with font data to confirm this behaviour in MS's or other implementations.

**Comment by PeterCon** [comment]
Addendum to last comment: that makes sense for most of the flags, which have filtering effects. But it still leaves ambiguity regarding the RIGHT_TO_LEFT flag that affects GPOS type 3 (which could be nested in a GPOS type 7 or 8 lookup).

**Comment by dscorbett** [comment]
A quirk in HarfBuzz that I’ve been relying on is that the nested lookups’ flags are respected, except that the first glyph in a nested lookup’s input is never ignored. That makes it easy to substitute a mark, ignoring other marks in its context. For example:
```fea
lookup nested {
    lookupflag IgnoreMarks;
    sub @base1 mark1' by mark2;
} nested;

lookup outer {
    sub mark1' lookup nested @base2;
} outer;
```
That replaces `mark1` with `mark2` when it is between `@base1` and `@base2`, where `mark1` is the last mark in a sequence of marks.

I don’t know whether this behavior is intentional or what other shaping engines do.

**Comment by PeterCon** [comment]
That seems like a separate detail that might need clarification.

**Comment by PeterCon** [comment]
In relation to this issue (the main one, not the separate issue mentioned by dscorbett), here is proposed text to be added at the end of the description of lookup flags in chapter2.htm:

><ins>Certain lookup types support a nested organization of lookup data. In this structure, a lookup subtable specifies a pattern for glyph sequences that can be modified, and then references one or more “nested” lookup tables in the LookupList that describe the actions to be applied to individual glyphs within a matching sequence. (GPOS lookup type 7 and type 8 have this nature, as well as GSUB lookup type 5, type 6, and type 8.) In these cases, there is a lookupFlag field in the main lookup table, and separate lookupFlag fields in the nested lookups. For these lookup types, the effect of the main lookup is to filter glyph sequences to which they apply, but not directly to modify glyphs in a matched sequence. The lookup flags in the main lookup table will affect this initial matching process. For example, the IGNORE_MARKS flag will cause mark glyphs to be ignored when evaluating if a glyph sequence matches the pattern specified by the lookup. Once a sequence is matched against the pattern in the main lookup, the nested lookups are then processed on glyphs in the sequence. Lookup flags in the main lookup table are not considered while the nested lookups are being processed. Instead, lookup flags in the nested lookups are considered. Note that the flags in the nested lookup can result in a secondary level of filtering over sequences initially matched by the main lookup table.</ins>

As the spec had not made such details clear up to now, it's possible that different implementations have had different interpretations of the spec (though it seems likely that implementations could be architected in a way in which the behaviour described follows at lowest cost). So, this may require discussion among different implementers on how to converge on any differences.

**Comment by NorbertLindenberg** [comment]
From what I saw back in 2017, prescribing that nested lookups respect their lookup flags does not reflect what implementations did at the time and runs the risk of breaking fonts that were generated with makeotf while it had the bug mentioned in the initial comment.

This should not go into the specification until we have comprehensive information about what the major implementations actually do.

**Comment by behdad** [comment]
> A quirk in HarfBuzz that I’ve been relying on is that the nested lookups’ flags are respected, except that the first glyph in a nested lookup’s input is never ignored.

This matches my understanding of what HarfBuzz does indeed.

**Comment by PeterCon** [comment]
@behdad : Apart from special consideration of the first mark in an input sequence, please let me know if the proposed new text in my comment above from 3 days ago is consistent with HarfBuzz.

**Comment by NorbertLindenberg** [comment]
You can’t just ignore that special consideration of the first glyph.

**Comment by PeterCon** [comment]
>You can’t just ignore that special consideration of the first glyph.

I didn't say it was my intent to do so. I want to unearth what are all the commonalities or differences between Microsoft's OTLS code (the lower-level layer that processes OTL tables) and corresponding parts of HarfBuzz and CoreText. (And I wish MS would may OTLS open source to make it a whole lot easier to unearth the details.)

**Comment by behdad** [comment]
> @behdad : Apart from possible special consideration of the first mark in an input sequence, please let me know if the proposed new text in my comment above from 3 days ago is consistent with HarfBuzz.

Looks good to me.

> still leaves ambiguity regarding the RIGHT_TO_LEFT flag that affects GPOS type 3 (which could be nested in a GPOS type 7 or 8 lookup).

To me the right thing to do is clear: the nested lookup's flag decides which glyph is attached to which. Ie. this flag is not special and is treated like the other flags in that the nested lookup's flags win.

**Comment by behdad** [comment]
> You can’t just ignore that special consideration of the first glyph.

To me there's no special consideration: lookup flags control the *search* for _next_/_previous_ glyph to process when a search happens. When a lookup is invoked from a (Chain)Context lookup, it is invoked at a certain position. Since there is no search, lookup flags are not consulted. If the recursed-to lookup has to find a glyph (eg. is a Ligature, PairPos, Cursive, or (Chain)Context) itself, then the lookup flags are consulted as usual. So I don't see any problem here.

**Comment by NorbertLindenberg** [comment]
Can we keep this bug open while actual behavior is still being investigated?

**Comment by PeterCon** [comment]
>lookup flags control the search for next/previous glyph to process when a search happens.

Indeed, though I didn't notice this stated explicitly. So, I've drafted a new paragraph to state that, directly after the table of flags. Hopefully this addresses the concern raised by David and Norbert.

I've also made revised the draft text quoted earlier, adding mention of the RTL flag. Here's the updated draft:

><ins>As noted above, lookups are processed for each glyph in the glyph sequence for a string. Each lookup type specifies a glyph pattern to be matched: single glyphs, or sequences of glyphs, depending upon the lookup type. The current glyph in the lookup processing loop is always matched against the first glyph in a lookup’s glyph sequence pattern. Lookup flags affect pattern matching for other glyphs in the sequence but not the current glyph.</ins>
>
>...
>
><ins>Certain lookup types support a nested organization of lookup data. In this structure, a lookup subtable specifies a pattern for glyph sequences that can be modified, and then references one or more “nested” lookup tables in the LookupList that describe the actions to be applied to individual glyphs within a matching sequence. In these cases, there is a lookupFlag field in the main lookup table, and separate lookupFlag fields in the nested lookups.</ins>
>
><ins>GPOS lookup type 7 and type 8 have this nature, as well as GSUB lookup type 5, type 6, and type 8. For these lookup types, the effect of the main lookup is to filter glyph sequences to which they apply, but not directly to modify glyphs in a matched sequence. The lookup flags in the main lookup table will affect this initial matching process. For example, the IGNORE_MARKS flag will cause mark glyphs to be ignored when evaluating if a glyph sequence matches the pattern specified by the lookup. Note that the RIGHT_TO_LEFT flag is not used in the main lookup.</ins>
>
><ins>Once a sequence is matched against the pattern in the main lookup, the nested lookups are then processed on glyphs in the sequence. Lookup flags in the main lookup table are not considered while the nested lookups are being processed. Instead, lookup flags in the nested lookups are considered. Note that the flags in the nested lookup can result in a secondary level of filtering over sequences initially matched by the main lookup table.</ins>

**Comment by PeterCon** [comment]
Minor edit in previous comment: `a lookup's glyph sequence pattern` to `a lookup's input glyph sequence pattern`.
