### ISSUE TITLE
[GPOS] Contextual Positioning Subtables “the most powerful”?

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#408]
The introduction for Lookup Type 7: Contextual Positioning Subtables claims that this subtable “defines the most powerful type of glyph positioning lookup”. Is that really true? Can it do anything that a chaining contextual positioning subtable can’t do? Are such marketing terms needed at all in an engineering document?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f748ff4-44a6-6395-e0ce-d249b8c9541b
* Version Independent ID: b80d0359-5657-632b-29e8-142c06902001
* Content: [GPOS — Glyph Positioning Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/gpos)
* Content Source: [typographydocs/opentype/spec/gpos.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gpos.md)
* Product: **typography**

**Comment by PeterCon** [comment]
See similar issue for GSUB in #60

**Comment by PeterCon** [comment]
For the next version, removed the "powerful" characterization in GPOS and also GSUB.
