### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by koavf** [MicrosoftDocs/typography-issues#409]
“Find the SemiBold is too light? _Making_ it a little darker.” should read “Find the SemiBold is too light? _Make_ it a little darker.”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b0aa22d-ec65-a36b-3a23-ca87e18ada28
* Version Independent ID: 05d3eb61-7b3c-24f6-dc0e-cb9d02e1c3a0
* Content: [Bahnschrift font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/bahnschrift#feedback)
* Content Source: [typographydocs/font-list/bahnschrift.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/bahnschrift.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **v-nihar**

**Comment by PeterCon** [comment]
Issue has been fixed.
