### ISSUE TITLE
Unregistered language system tags in the Tibetan script

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#41]
The language system tags 'TSJ ', 'XKF ', and 'KJZ ' for Tshangla, Khengkha, and Bumthangkha are not registered at https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afaf5060-fd0d-2b4c-7555-e3d81ccafe24
* Version Independent ID: 06c7f355-4cd9-4d0c-188b-4d65d4a5b406
* Content: [Creating and Supporting OpenType Fonts for Tibetan Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/tibetan)
* Content Source: [typographydocs/script-development/tibetan.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/tibetan.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by PeterCon** [comment]
If they're not registered, what's the basis for calling these "language system tags"?

**Comment by dscorbett** [comment]
Was that a question for me? I called them that because they’re in the “Language system tag” column.

**Comment by PeterCon** [comment]
Sorry, I missed that you were commenting on the script-development page for Tibetan script. Makes sense now. Thanks. I'll add those to the language system tag registry.

**Comment by PeterCon** [comment]
Mixup on Balti: the tag 'BLT ' was registered for that a looong time ago -- 2002 or earlier. So, the Tibetan script page has a bug.

**Comment by PeterCon** [comment]
Added KJZ ', 'TSJ ', 'XKF to the lang sys tag registry, to be published with OT 1.8.3.
