### ISSUE TITLE
Update to reflect recent additions in ISO 15924

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#410]
Various IDs have been added to ISO 15924 since 2018 that are not reflected here.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49c1efc4-e864-0727-9663-7cec0ec4d9f1
* Version Independent ID: 36ec4396-b9cb-cba9-1582-d8400296d249
* Content: [Script tags - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/scripttags)
* Content Source: [typographydocs/opentype/spec/scripttags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/scripttags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Fixed for the next version
