### ISSUE TITLE
Consider more guidance wrt ascender/descender and line metrics

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#412]
For developers of new layout apps, it may be unclear which metric values to use. The note above mentions that hhea values are Apple specific and points to the OS/2 table, but not to specific discussion in the OS/2 table. (There is clearer discussion in the sTypo* and usWin* fields in that page, but they may go unnoticed.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dcd0423a-ccb2-5540-7597-8f1afc794287
* Version Independent ID: 4e00e04a-62a6-f943-a5b4-e5305c06e78c
* Content: [hhea - Horizontal header table specification - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/hhea)
* Content Source: [typographydocs/opentype/spec/hhea.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/hhea.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Proposed change for next version:

> > <ins>*Note:* The ascender, descender and linegap values in this table are Apple specific; see [Apple's specification](http://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6hhea.html) for details regarding Apple platforms. The [sTypoAscender](os2.md#stypoascender), [sTypoDescender](os2.md#stypodescender) and [sTypoLineGap](os2.md#stypolinegap) fields in the OS/2 table are used on the Windows platform, and are recommended for new text-layout implementations. Font developers should evaluate behavior in target applications that may use fields in this table or in the OS/2 table to ensure consistent layout. See the descriptions of the OS/2 fields for additional details.</ins>
