### ISSUE TITLE
Unclear requirements for dist feature

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#415]
Various parts of the OpenType documentation as well as implementor’s documentation contradict each other with regards to the applicability of the dist feature.

The “UI suggestion” in the feature tag registry says “This feature could be made active or inactive by default, at the user’s preference.” It’s unclear what “by default” here means, as a default generally requires a specific setting, not an “or” combination of opposite settings, and a way to override, which here is ... what?

The “Script/language sensitivity” right below says “Required in Indic scripts.” It’s not clear who is required to do what – are fonts required to have lookups for this feature, are rendering systems / applications required to apply them, are UIs required to show them as active, or something else? It also doesn’t define “Indic scripts” – some people consider all scripts derived from Brahmi as “Indic”, others only those native to India, and the Microsoft “script development specs” only a small subset of nine of those native to India.

The documentation of the shaping engines for simple (“standard”) scripts, for complex scripts, for Bengali, Devanagari, Gujarati, Gurmukhi, Kannada, Malayalam, Oriya, Tamil, Telugu, Khmer, Myanmar, say that the dist feature should be applied, while those for Arabic, Hangul, Hebrew, Lao, Syriac, Thaana, Thai don’t mention it. Note that Lao and Thai are sometimes considered “Indic” scripts, while many of those supported by the Universal Shaping Engine are clearly not.

The [OpenType features](https://harfbuzz.github.io/shaping-opentype-features.html) documentation page for HarfBuzz lists dist as one of the features that are applied by default for horizontal text. This makes application independent of the script, but brings up writing direction as a condition that none of the other bits of documentation mention.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4da11419-0864-96ff-7f67-296680843fc1
* Version Independent ID: 1d46dac1-d559-ce3e-2f6f-f47cf8cd9e0f
* Content: [Registered features, a-e - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae)
* Content Source: [typographydocs/opentype/spec/features_ae.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_ae.md)
* Product: **typography**

**Comment by PeterCon** [comment]
Some of the info needed for implementations should really be informed by complete specs on shaping. So, might not be able to resolve completely in next OT spec update, but will consider what's feasible.

**Comment by khaledhosny** [comment]
HarfBuzz treats `dist` similar to `kern`, which should explain the point about horizontal direction. The documentation was inconsistent and incomplete as mentioned here, so we went for the simplest solution and enabled it everywhere `kern` was enabled (previously it was enabled for a select set of scripts based on older versions of the documentation). So far, it is not clear to me what is the difference, if any, between `dist` and `kern`, probably something like `rlig` and `liga`?

**Comment by tiroj** [comment]
My understanding of dist is that it is the _required_ variant of kern (in the same way as rlig is the required variant of liga and rclt is the required variant of calt). Indeed, when I asked Paul Nelson why there was a separate dist feature for Indic scripts, instead of just using kern, that is how the difference was explained to me: the dist feature should be active by default and it should not be possible for the user to turn it off or to modify the output of the feature in the same way that kern can be turned off or kern adjustments overridden. I think the dist feature description should be reworded to reflect this.

**Comment by tiroj** [comment]
PS. The use case Paul described to me was using dist to adjust spacing vowel signs relative to bases, i.e. cluster-internal kerning that should remain static even when tracking is applied to a string, in other words, _really really required._

**Comment by khaledhosny** [comment]
That was our educated guess as well, but AFAIK this is not spelled out anywhere. The case that lead us to enable `dist` for all scripts, was [Segoe UI Emoji](https://github.com/harfbuzz/harfbuzz/issues/1907) using `dist` to adjust the side bearings of some emoji combinations.

**Comment by PeterConstable** [comment]
I basically always understood dist to be a required variant of kern, but lost track over the past 10+ years if there had been any change in actual use.

**Comment by punchcutter** [comment]
Over the past couple years dist has become more "required" for dealing with all the scripts in Unicode we'd never really dealt with until Noto and USE came around. At that time I requested that we turn it on by default in harfbuzz.

**Comment by PeterCon** [comment]
Proposed changes for next version:

>*Friendly name:* Distances
>
>*Registered by:* Microsoft
>
>*Function:* Provides a means to control distance between glyphs. <ins>Note: this feature should only be used for required positioning adjustments, not as an alternate kerning feature.</ins>
>
>*Example:* In the Devanagari (Indic) script, the distance between the vowel sign U and a consonant can be adjusted using this.
>
>*Recommended implementation:* The &#39;dist&#39; table provides distances by which a glyph needs to move towards or away from another glyph (GPOS lookup type 2).
>
>*Application interface:* For GIDs found in the &#39;dist&#39; coverage table, the application passes their GID to the table and gets back the distance that needs to be maintained between them.
>
>*UI suggestion:* <del>This feature could be made active or inactive by default, at the user’s preference.</del><ins>This feature should be on by default.</ins>
>
>*Script/language sensitivity:* Required in Indic scripts.
>
>*Feature interaction:* None.

(A UI suggestion of "on by default" and "required" for X script is sub-optimal for indicating "mandatory", but that's a separate issue spanning many feature descriptions.)

**Comment by tiroj** [comment]
This feature description is still problematic (mind you, many of them are).

It would be good for both this and the kern feature description to note that single and adjustment positioning (unlike attachment positioning) is additive, and hence the content of the dist and kern features should be exclusive unless the intent is for one to affect the output of the other.

I suggest noting here that this feature is for required positioning adjustments, and that user-adjustable spacing should use the kern feature, and vice versa.

The example provided is just plain wrong: in Devanagari, the vowel sign U is a below-base combining mark. I recall Paul Nelson suggesting a use of dist with the pre-base vowel sign I, but this is not done and would mess up the rhythm of stems. A better example would be something like adjusting the distance between base and post-base forms in Kannada or Telugu.

**Comment by NorbertLindenberg** [comment]
A good example for `dist` that’s far removed from traditional kerning would be its use to move entire clusters apart to prevent collisions between their above-base or below-base marks in scripts such as Myanmar and Khmer (and likely some Indic ones).

**Comment by PeterCon** [comment]
I seem to recall using 'dist' in the Kalinga font for adjusting placement of subjoined consonant forms: for UI text (Vista), we didn't want to stack two levels deep and so positioned additional subjoined forms to the right of the preceding one.

**Comment by NorbertLindenberg** [comment]
The proposed spec text does not address the issue of writing direction. Does any implementation enable `dist` for vertical text?

**Comment by NorbertLindenberg** [comment]
“ Recommended implementation” talks about a 'dist' table. There is no such thing; it’s a feature.

**Comment by NorbertLindenberg** [comment]
“Recommended implementation” refers to GPOS lookup type 2. Is that commonly used in `dist` features? In my use of it, it’s always been contextual lookups.

**Comment by PeterCon** [comment]
>*Feature interaction:* <del>None.</del><ins>This and other certain other features, such as [&#39;kern&#39;](features_ko.md#kern), are typically implemented using single or pair adjustment positioning lookups. Note that, if multiple lookups are applied to a glyph, the positioning adjustments will be additive. The glyphs affected by the &#39;dist&#39; and &#39;kern&#39; features should be distinct unless it is intended that their effects can be combined.</ins>

(That might be the first case I can think of in which the *Feature interaction* details are actually useful!)

**Comment by PeterCon** [comment]
> In my use of it, it’s always been contextual lookups.

But presumably the nested lookup is type 1 or 2?

I would expect any of 1, 2 or a contextual lookup that references a type 1 or 2 lookup.

**Comment by NorbertLindenberg** [comment]
> A UI suggestion of "on by default" and "required" for X script is sub-optimal for indicating "mandatory"

The issue isn’t really “required” or “mandatory” – it’s that the spec doesn’t say which of the many interested parties in OpenType it’s required of. In this context, fonts and shaping engines are the primary candidates.

**Comment by NorbertLindenberg** [comment]
> But presumably the nested lookup is type 1 or 2?
> 
> I would expect any of 1, 2 or a contextual lookup that references a type 1 or 2 lookup.

I mean the lookups that are directly referenced in the lookup list of the `dist` feature. Yes, contextual lookups would use type 1 or 2 as nested lookups.

**Comment by PeterCon** [comment]
The *Application interface* info (`gets back the distance that needs to be maintained between them`) was also wrong.

Here's a revised draft based on review feedback:

>*Friendly name:* Distances
>
>*Registered by:* Microsoft
>
>*Function:* Provides a means to control distance between glyphs. 
>
>><ins>Note: this feature should only be used for required positioning adjustments, not as an alternate kerning feature. For spacing adjustments that can be controlled by the user, the [&#39;kern&#39;](features_ko.md#kern) feature should be used.</ins>
>
>*Example:* <del>In the Devanagari (Indic) script, the distance between the vowel sign U and a consonant can be adjusted using this.</del><ins>In Telugu script, adjust the placement of subjoined consonant forms to avoid collision with other glyphs.</ins>
>
>*Recommended implementation:* The &#39;dist&#39; table provides distances by which a glyph needs to move towards or away from another glyph (GPOS lookup <del>type 2</del><ins>type 1, type 2, or contextual lookups that reference type 1 or type 2 lookups</ins>).
>
>*Application interface:* For GIDs found in the &#39;dist&#39; coverage table, the application <del>passes their GID to the table and gets back the distance that needs to be maintained between them</del><ins>finds a lookup subtable for a matching sequence and retrieves position adjustment values, in design units</ins>.
>
>*UI suggestion:* <del>This feature could be made active or inactive by default, at the user’s preference.</del><ins>This feature should be on by default.</ins>
>
>*Script/language sensitivity:* Required in Indic scripts.
>
>*Feature interaction:* <del>None.</del><ins>This and other certain other features, such as [&#39;kern&#39;](features_ko.md#kern), are typically implemented using single or pair adjustment positioning lookups. Note that, if multiple lookups are applied to a glyph, the positioning adjustments will be additive. The glyphs affected by the &#39;dist&#39; and &#39;kern&#39; features should be distinct unless it is intended that their effects can be combined.</ins>

**Comment by PeterCon** [comment]
Added this to the 'kern' description:

>> <ins>*Note:* This feature should only be used for optional spacing adjustments that can be controlled by the user. For required spacing adjustments not under user control, as may be needed for certain scripts, the [&#39;dist&#39;](features_ae.md#dist) feature should be used.</ins>

**Comment by tiroj** [comment]
I wouldn't refer to kern adjustments as ‘optional’—that will encourage the kind of developers who turned them off by default in MS Word. Maybe e.g.

_Note:_ This feature should only be used for intended spacing adjustments that may be overridden by the user. For required spacing adjustments not under user control, as may be needed for certain scripts, the 'dist' feature should be used.

**Comment by PeterCon** [comment]
>“ Recommended implementation” talks about a 'dist' table. There is no such thing; it’s a feature.

Missed that.

>*Recommended implementation:* <del>The &#39;dist&#39; table</del><ins>The font</ins> provides distances by which a glyph needs to move towards or away from another glyph (GPOS lookup <del>type 2</del><ins>type 1, type 2, or contextual lookups that reference type 1 or type 2 lookups</ins>).

Also rev'd the note for 'kern' per John's suggestion.

**Comment by rahulgajjar** [comment]
Hi, I work on font production. The inconsistent implementation of the 'dist' feature is causing bugs for some scripts and some software. As per my understanding, if the 'dist' feature exists in the font, it should be enabled by default. Classifying it per language basis is causing a problem, it was mainly created for Indic scripts, so if it somehow exists in the font, it is essential and thus it should be enabled.

Difference between 'dist' and 'kern':
Apart from the obvious difference described in the above posts, I observed that you can not define spacing for single glyphs using kern feature. I am working on 'Takri' script and I use 'dist' feature for defining the glyph width for post base marks (Like half form of 'Ha') To make sure that marks are placed on base glyph and not on the half form of 'Ha' The glyph is defined as mark glyph using GDEF table. By doing this the default spacing of the glyph is ignored and to reintroduce the spacing 'dist' feature is used. 

example: 
`pos signha-takr <0 0 235 0>;`

I observed that Microsoft Word (for Mac) enables the 'dist' feature by default for the 'Kannada' script but not for 'Takri'. I see no reason why the 'dist' feature should not be enabled by default. The spacing changes made using the 'dist' feature should be essential and part of the design. User or software does not need to give an option to enable or disable them.

Fonts compiled using 'fontmake' consider these scripts as Indic scripts and generate the necessary 'dist' feature block

`DIST_ENABLED_SCRIPTS = {
    # Indic shaper's scripts
    # Unicode-1.1 additions
    "Beng",  # Bengali
    "Deva",  # Devanagari
    "Gujr",  # Gujarati
    "Guru",  # Gurmukhi
    "Knda",  # Kannada
    "Mlym",  # Malayalam
    "Orya",  # Oriya
    "Taml",  # Tamil
    "Telu",  # Telugu
    # Unicode-3.0 additions
    "Sinh",  # Sinhala
    # Khmer shaper
    "Khmr",  # Khmer
    # Myanmar shaper
    "Mymr",  # Myanmar
    # USE shaper's scripts
    # Unicode-3.2 additions
    "Buhd",  # Buhid
    "Hano",  # Hanunoo
    "Tglg",  # Tagalog
    "Tagb",  # Tagbanwa
    # Unicode-4.0 additions
    "Limb",  # Limbu
    "Tale",  # Tai Le
    # Unicode-4.1 additions
    "Bugi",  # Buginese
    "Khar",  # Kharoshthi
    "Sylo",  # Syloti Nagri
    "Tfng",  # Tifinagh
    # Unicode-5.0 additions
    "Bali",  # Balinese
    # Unicode-5.1 additions
    "Cham",  # Cham
    "Kali",  # Kayah Li
    "Lepc",  # Lepcha
    "Rjng",  # Rejang
    "Saur",  # Saurashtra
    "Sund",  # Sundanese
    # Unicode-5.2 additions
    "Egyp",  # Egyptian Hieroglyphs
    "Java",  # Javanese
    "Kthi",  # Kaithi
    "Mtei",  # Meetei Mayek
    "Lana",  # Tai Tham
    "Tavt",  # Tai Viet
    # Unicode-6.0 additions
    "Batk",  # Batak
    "Brah",  # Brahmi
    # Unicode-6.1 additions
    "Cakm",  # Chakma
    "Shrd",  # Sharada
    "Takr",  # Takri
    # Unicode-7.0 additions
    "Dupl",  # Duployan
    "Gran",  # Grantha
    "Khoj",  # Khojki
    "Sind",  # Khudawadi
    "Mahj",  # Mahajani
    "Modi",  # Modi
    "Hmng",  # Pahawh Hmong
    "Sidd",  # Siddham
    "Tirh",  # Tirhuta
    # Unicode-8.0 additions
    "Ahom",  # Ahom
    "Mult",  # Multani
    # Unicode-9.0 additions
    "Bhks",  # Bhaiksuki
    "Marc",  # Marchen
    "Newa",  # Newa
    # Unicode-10.0 additions
    "Gonm",  # Masaram Gondi
    "Soyo",  # Soyombo
    "Zanb",  # Zanabazar Square
    # Unicode-11.0 additions
    "Dogr",  # Dogra
    "Gong",  # Gunjala Gondi
    "Maka",  # Makasar
    # Unicode-12.0 additions
    "Nand",  # Nandinagari
}`

**Comment by tiroj** [comment]
> Apart from the obvious difference described in the above posts, I observed that you can not define spacing for single glyphs using kern feature.

Technically, any OTL feature can include any lookup type, so there is no limitation preventing use of single adjustment GPOS in the kern feature. There may be limitations in some tools or in some layout implementations, but these are bugs.

> I observed that Microsoft Word (for Mac) enables the 'dist' feature by default for the 'Kannada' script but not for 'Takri'.

I think Takri script is processed by the Universal Shaping Engine, which definitely includes dist feature support. I think this is probably a Mac Word issue. Are you able to also test in the Windows version?

**Comment by rahulgajjar** [comment]
Hi Tiroj,

> I think Takri script is processed by the Universal Shaping Engine, which definitely includes dist feature support. I think this is probably a Mac Word issue. Are you able to also test in the Windows version?


I am having the same issue with the windows version of microsoft word.
