### ISSUE TITLE
Incorrectly placed diacritical characters in Calibri

### ISSUE THREAD

**Issue by xbotuk** [MicrosoftDocs/typography-issues#418]
For the following text, the two diacritical characters in appearing incorrectly for Calibri font compared to any other font like Arial.

بِّ

**Comment by alib-ms** [comment]
Thank you for contacting us. The position of the two diacritical characters on the letter ‘Beh’ in your example is acceptable in both styles. 
When the marks are combined, bot marks are placed on top of the base character as shown in Calibri. 
When the marks are not combined, the ‘Kasra’ mark is placed below the base character as observed in Arial. 

It’s a design choice. To my understanding, in modern style Arabic writing Calibri style is preferred. However, in traditional writing the Arial style is more common.
