### ISSUE TITLE
Inconsistent link anchors 

### ISSUE THREAD

**Issue by schriftgestalt** [MicrosoftDocs/typography-issues#421]
The link-anchors to the features are not consistent. Some are `#tag-kern` and others just `#ljmo`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a9106c-ca98-1891-2c00-ace78615994f
* Version Independent ID: 0feefbc8-23a7-5bc8-76dc-0a336a1c7968
* Content: [Registered features, k-o - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ko#tag-liga)
* Content Source: [typographydocs/opentype/spec/features_ko.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_ko.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by alib-ms** [comment]
Thank you for the feedback. I've gone through and updated the links with the same format using #tag-. Please let us know if you find a link that I might have missed.

**Comment by schriftgestalt** [comment]
the anchors on that page: `https://docs.microsoft.com/en-us/typography/opentype/spec/featurelist` don’t use the "tag": `https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae#afrc`

**Comment by PeterCon** [comment]
@schriftgestalt You haven't replied to my last comment: both format of anchor links, e.g. `#kern` and `#tag-kern`, should work for all features. So, it's not clear to me that there is any issue to fix unless you see only one format working in some situations.

Without further clarification, there's nothing to act on, so I'll close this. But feel free to re-open if you have additional clarification.

**Comment by schriftgestalt** [comment]
I was confused why the seemingly same link uses a different anchor.  
The "featurelist" has the anchors without the tag. On the "Registered features", in the right sidebar (In this article) it uses the tag. The issue is with the inconsistency.

**Comment by PeterCon** [comment]
Ah, I see where you see the different tags appearing.

I can explain why this is happening: the links without "tag-" were created when the spec was being maintained on the old Typography site as HTML files. When the content got migrated to the new site using Markdown sources, I made sure the old anchors were retained so any existing links to those locations wouldn't break. Hence the anchors you see in the "featurelist" page. But then the new CMS automatically generates anchors from the Markdown headings and also automatically generates the TOC links, which is what you see in the right sidebar in the features_?? pages.

I could get rid of the duplication and use only anchors of the form "tag-*". But that would require many other changes to fix broken links within the Typography site, and there could be broken links elsewhere that couldn't be fixed. So, unless this is creating a problem other than "why one kind of anchor here but another there?", then I'm inclined not to take any further action.

**Comment by schriftgestalt** [comment]
I’m OK with this. It would be nice if the most obvious links use the same format (but keep both anchors to not break stuff).

**Comment by PeterCon** [comment]
OK. As the "tag-*" anchors and links using them are automatically generated, they can't be eliminated. The other form of anchors could be kept but links within the OT spec changed to use the "tag-*" form. But apparently that was tried before and resulted in some warnings, e.g., `Cannot find bookmark '#tag-palt' in 'opentype/spec/features_pt.md', did you mean '#-tag-palt'?` That seems unexpected, and I haven't gotten any explanation from the relevant people at MS as to why. I'll continue to ask, and if I think it will be feasible to resolve this then I'll attempt to do that.

**Comment by PeterCon** [comment]
This is old; both links work and there's no significant problem to be solved. Closing.
