### ISSUE TITLE
Unclear language system tag: 'ZHP '

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#424]
What does 'ZHP ' (Chinese Phonetic) refer to? Bopomofo? Pinyin? Romanizations of Chinese in general? Chinese phonetic systems of any script in general?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662c6f54-f90c-52ed-dca2-0f0a0a49fee5
* Version Independent ID: 6aa33924-d45e-60c3-a9fd-e317ff662993
* Content: [Language system tags - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags)
* Content Source: [typographydocs/opentype/spec/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by xadxura** [comment]
I don't have definitive information. Bopomofo or romanizations in general are good suggestions.
