### ISSUE TITLE
Where's the download link ?

### ISSUE THREAD

**Issue by revoker** [MicrosoftDocs/typography-issues#429]
Where is the download link ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c7cadc-6eb0-3a3a-b325-de0aa45e4852
* Version Independent ID: 65e39cbd-0456-87d9-2446-d46dd39dce71
* Content: [Calibri font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/calibri)
* Content Source: [typographydocs/font-list/calibri.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/calibri.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Calibri font family is available with Windows and Office.

**Comment by avkvirtru** [comment]
If we're designing for Office apps like an Outlook Add-in, our design tools (e.g. Sketch, Figma) also need copies of fonts like Calibri. Any help?

**Comment by alib-ms** [comment]
Hi, As Calibri and Cambria are bundled with Office and Windows. In Figma you should be able to access these as part of the local fonts.

**Comment by avkvirtru** [comment]
I'm primarily in Sketch on Mac. Calibri appears in all Office apps but no design tools and not Font Book.app.

**Comment by alib-ms** [comment]
Microsoft uses Segoe UI for Windows and Office UI. You can download a copy of the fonts from the design [toolkits](https://docs.microsoft.com/en-us/windows/apps/design/downloads/#fonts)

**Comment by alib-ms** [comment]
I hope that the [FAQ ](https://learn.microsoft.com/en-us/typography/fonts/font-faq) will be helpful in addressing your question. It contains useful information about fonts and their usage.
As your original post was made some time ago, I am going to close this matter for now. However, please don't hesitate to reach out and reopen this issue if you have any further questions or concerns.
Thank you for your feedback and patience.
