### ISSUE TITLE
One question about "Name Records"

### ISSUE THREAD

**Issue by U-F-O** [MicrosoftDocs/typography-issues#441]
Question:

I've seen there's one item named languageID in the Name Records.  I want to know how many languages and what languages this font supports. Can I use the languageID to achieve that goal? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc5a9d9-70e1-97b3-6926-c176e1a2401d
* Version Independent ID: 1afb0f5b-d1a7-7d69-d175-a5c9382b74be
* Content: [name - Naming table specification - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/name)
* Content Source: [typographydocs/opentype/spec/name.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/name.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterConstable** [comment]
The languageIDs indicate the language of strings in the name table. Suppose the font is "Arial Bold" and the nameID is 2, subfamily name: the languageID is used to differentiate between the English string "Bold", the French string "Gras", etc. So looking at the languageIDs will tell you for how many languages that string can appear in a user interface. 

But if the question is "For how many languages can Arial be used to format text?" then that's a very different matter. That's not what the languageIDs were intended for. The only information they provide for that question is that, presumably, the font supports _at least_ those languages.

**Comment by U-F-O** [comment]
Thank you so much. It helps a lot.
