### ISSUE TITLE
MarkGlyphSets table naming is inconsistent

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#442]
The mark glyph sets definition table is described in the header as `MarkGlyphSetsDef` table. In the section headed "Mark Glyph Sets Table", it is referred to as `a MarkGlyphSets table`, and in
the overview, it is defined as a `MarkGlyphSetsTable`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8d3d5b8-059a-613d-8666-80438ebd7aa7
* Version Independent ID: 6a0f2873-97c3-833c-45e4-340ea96667a0
* Content: [GDEF — Glyph Definition Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/gdef)
* Content Source: [typographydocs/opentype/spec/gdef.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gdef.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by alib-ms** [comment]
Thank you for the feedback.. This will be fixed in the version of the OpenType space. Change should be made in the Overview section at the top, it should say MarkGlyphSetsDef.

**Comment by PeterCon** [comment]
Compare with naming for other tables that "define" sets, classes, etc.

**Comment by PeterCon** [comment]
The convention that's been used (for the most part) across the spec is that the structure name for a *foo* table is  "Foo", not "FooTable". Scanning across the entire spec for other instances, one other occurrence of this class of issue is "ConditionTableFormat1" in chapter2. There are also some cases of this issue reflected in field names; e.g., "markGlyphSetsTableFormat".

Changed for next version:

chapter2: 
* "ConditionTableFormat1" to "ConditionFormat1"

features_pt:
* reference to "FeatureTable" to "Feature table"

GDEF:
* "MarkGlyphSetsTable" to "MarkGlyphSets"
* "markGlyphSetsTableFormat" to "format"

GPOS:
* reference to "xDeviceTableOffset" to "xDeviceOffset"
* reference to "yDeviceTableOffset" to "yDeviceOffset"

MATH:
* "deviceTableOffset" to "deviceOffset"
