### ISSUE TITLE
`name` table recommendations to include mac platform

### ISSUE THREAD

**Issue by bobh0303** [MicrosoftDocs/typography-issues#443]
For the `name` table, the Recommendations page says:

> When building a font containing Roman characters that will be used on the Macintosh, an additional name record is required, specifying platform ID of 1 and encoding ID of 0.

but according to [this 2018 post from Sascha Brawer](https://github.com/fonttools/fonttools/issues/1170#issuecomment-368492829) and by evidence of many fonts that work on Apple platforms without Platform ID 1 strings, such is no longer required.

Bob

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95e88b53-d670-0240-422c-72748258ab2a
* Version Independent ID: b5fff1ee-cf03-e424-a2dc-aee58e0429e4
* Content: [Recommendations for OpenType Fonts - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/recom#name)
* Content Source: [typographydocs/opentype/spec/recom.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/recom.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Proposed change for next version:

><del>When building a font containing Roman characters that will be used on the Macintosh, an additional name record is required, specifying platform ID of 1 and encoding ID of 0.</del><ins>Names for the Macintosh platform (platform ID 1) were required on Apple platforms, but are no longer required on modern platforms. Some legacy font installers, however, may require names platform ID 1, encoding ID 0.</ins>

**Comment by PeterCon** [comment]
Per review feedback on mpeg-otspec list, revising to "Some legacy software..."
