### ISSUE TITLE
I've found some issues in Shan Text. How can I request to fix them? Thanks.

### ISSUE THREAD

**Issue by saimawnkham** [MicrosoftDocs/typography-issues#447]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56b8cbdd-0a23-9f66-6f22-90317472e990
* Version Independent ID: c4dc5b5d-f391-fe19-d9d3-aeae9c9f5e7a
* Content: [Myanmar Text font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/myanmar-text)
* Content Source: [typographydocs/font-list/myanmar-text.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/myanmar-text.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by xadxura** [comment]
@saimawnkham please provide more information.
