### ISSUE TITLE
Misleading description of DeltaSet record

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#449]
The DeltaSet record is defined as follows:

Type|Name|Description
-|-|-
int16, int8|DeltaData[shortDeltaCount + regionIndexCount]|Variation delta values.

This indicates that there are `shortDeltaCount + regionIndexCount` elements in the array. But right after, the text says

>Logically, each DeltaSet record has regionIndexCount number of elements... The length of the data for each row is shortDeltaCount + regionIndexCount.

The table is misleading: it is showing the length of data in bytes, but the type is shown as either bytes or shorts. It would be clearer to state the number of elements, `DeltaData[regionIndexCount]`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc38f55-a142-6d66-fc68-1bb6e6e9ed56
* Version Independent ID: 0665d6f2-4150-1977-4fd6-91c50c226ed9
* Content: [OpenType Font Variations Common Table Formats - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otvarcommonformats)
* Content Source: [typographydocs/opentype/spec/otvarcommonformats.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otvarcommonformats.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Changed for next version:

><table>
<tbody>

<tr>
<th>Type</th>
<th>Name</th>
<th>Description</th>
</tr>

<tr>
<td>int16, int8</td>
<td><del>DeltaData</del><ins>deltaData</ins>&#x200B;[<del>shortDeltaCount + </del>regionIndexCount]</td>
<td>Variation delta values.</td>
</tr>

</tbody>
</table>

Logically, each DeltaSet record has regionIndexCount number of elements. The first shortDeltaCount elements are represented as signed 16-bit values (int16), and the remaining regionIndexCount - shortDeltaCount elements are represented as signed 8-bit values (int8). The length of the data for each row is shortDeltaCount + regionIndexCount.

**Comment by behdad** [comment]
Alternatively we can say:
```
int16 shortDeltas[shortDeltaCount];
int8 byteDeltas[regionIndexCount - shortDeltaCount];
```

**Comment by PeterCon** [comment]
There aren't many parts of the format in which a structure field allows for more than one type in an array. (glyf, gvar are two other cases.) But wherever that occurs, the description given indicates the number of array elements, not the byte length of the array. So, `regionIndexCount` would be appropriate in this case.

But are you suggesting instead to document this as two separate arrays, one after the other?

On the one hand, that might make clearer how those arrays are organized as word/byte sequences. But on the other hand, it makes _less_ clear that this data is meant to be treated *logically* like a single array in relation to the deltaSet indices. It feels like it would be harder to explain that than it is to explain how the logical array is organized in terms of word/byte sequences.

**Comment by behdad** [comment]
Whichever. Doesn't matter. Was just sharing alternatives.
