### ISSUE TITLE
Incomplete Khmer diacritic table

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#45]
>Class | Description | Code points
>-- | -- | --
>XXXX | NEED CLASS INFO HERE | and unicode points
This table is incomplete.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aad9cb38-9a74-d136-23f6-0fdc5dca33c8
* Version Independent ID: ef6b84e4-d3a7-8c34-78ac-1b5788765fb8
* Content: [Developing OpenType Fonts for Khmer Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/khmer)
* Content Source: [typographydocs/script-development/khmer.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/khmer.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment]
Closing as Fixed.
