### ISSUE TITLE
BitmapSize should be characterized as a record, not a table

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#450]
The conventions in the OT spec regarding tables are:
- tables are referenced by offset
- if tables contain offsets to sub-structs, the offsets are from the start of that table

The conventions for records are:
- records occur sequentially within some sequence of table fields or within an array sequence
- if records contain offsets, the offsets are from the start of the parent table

BitmapSize satisfies the latter, not the former.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 76746ffb-7c69-8d2f-935d-84f15e69116a
* Version Independent ID: 42535fd9-5463-8f94-042c-47307a5d28c8
* Content: [EBLC - Embedded Bitmap Location Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/eblc)
* Content Source: [typographydocs/opentype/spec/eblc.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/eblc.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Changes made for next version. Also touched ebdt, ebsc, cbdt, cblc for references to "BitmapSize table". 

Related, also added wording to otff describing the distinction between records and tables, as mentioned above.
