### ISSUE TITLE
Gabriola licensing unavailable 

### ISSUE THREAD

**Issue by SimonVanacco** [MicrosoftDocs/typography-issues#452]
The licensing link links to fonts.com website, however Gabriola is not available on fonts.com (confirmed by the website support). 
Either the link has to be deleted because Gabriola is not disponible for licensing (i found no info on this font), or updated with the correct website to buy a license. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1265e0b5-5b81-c5e5-7d24-fc9d79aecbe4
* Version Independent ID: 98675a4c-4f0f-cd2f-be9e-297aecd1d15b
* Content: [Gabriola font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/gabriola)
* Content Source: [typographydocs/font-list/gabriola.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/gabriola.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Thank you for the feedback. I will follow up with team to have the addressed.

**Comment by alib-ms** [comment]
Fixed. Link removed.
