### ISSUE TITLE
[USE] Cluster overrides out of date, again

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#453]
With the removal of the override for Javanese Layar from [IndicSyllabicCategory-Additional.txt](https://github.com/microsoft/font-tools/blob/master/USE/IndicSyllabicCategory-Additional.txt), the overrides listed in the USE documentation are out of date again.

How about simply removing the inline override tables, which are incomplete anyway, and simply referring to the [override files](https://github.com/microsoft/font-tools/tree/master/USE) as the real source?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 194a6d3c-4137-46e9-3a4b-44b990200986
* Version Independent ID: a0c8e788-5228-aa28-670e-3ba1ac3faecd
* Content: [Creating and supporting OpenType fonts for the Universal Shaping Engine - Typography](https://docs.microsoft.com/en-us/typography/script-development/use)
* Content Source: [typographydocs/script-development/use.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/use.md)
* Product: **typography**

**Comment by xadxura** [comment]
Fix in progress

**Comment by xadxura** [comment]
Fixed
