### ISSUE TITLE
[USE] List of invalid character sequences is incomplete

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#454]
The list of invalid character sequences, which the USE documentation describes as “a complete listing of prohibited sequences documented in TUS version 12.1”, is not in fact complete. For Devanagari, it includes the sequences labeled “Do Not Use” of table 12.1, but lacks the sequences labeled in the same way in tables 12.2 and 12.3.

It can be argued that these tables don’t need to be explicitly handled in the USE because their invalid character sequences would already be detected as invalid by not matching any of the regular expressions for well-formed clusters. Stating this in the documentation would be better than claiming “a complete listing”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 194a6d3c-4137-46e9-3a4b-44b990200986
* Version Independent ID: a0c8e788-5228-aa28-670e-3ba1ac3faecd
* Content: [Creating and supporting OpenType fonts for the Universal Shaping Engine - Typography](https://docs.microsoft.com/en-us/typography/script-development/use)
* Content Source: [typographydocs/script-development/use.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/use.md)
* Product: **typography**

**Comment by xadxura** [comment]
Fix in progress.

**Comment by xadxura** [comment]
Fixed
