### ISSUE TITLE
consider using FWord / UFWord as types in MATH table

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#456]
Most instances of `uint16` are counts or glyphIDs, but some (7 of 20) are distances in design units. Consider changing these from uint16 to UFWord.

Similarly, int16 is used in MathValueRecord, which is used many times in this table; and the int16 is always a design-grid X or Y coordinate value. Consider changing this to FWord.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0076fd2-52b0-2989-3142-fd9e456b9514
* Version Independent ID: 4aef8fa3-2ad3-7933-5a77-0a7473e66112
* Content: [MATH - The mathematical typesetting table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/math)
* Content Source: [typographydocs/opentype/spec/math.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/math.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Changed types of 8 struct members for next version.
