### ISSUE TITLE
[USE] Wrong or questionable siglum for some vowel subclasses

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#458]
The USE documentation lists the vowel subclasses VOWEL_PRE_ABOVE, VOWEL_PRE_ABOVE_POST, VOWEL_PRE_POST under the siglum VPst. For VOWEL_PRE_ABOVE that’s clearly wrong because it has no post-base component; for the other two it seems questionable, because usually the first component in the order pre, above, below, post determines the siglum.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 194a6d3c-4137-46e9-3a4b-44b990200986
* Version Independent ID: a0c8e788-5228-aa28-670e-3ba1ac3faecd
* Content: [Creating and supporting OpenType fonts for the Universal Shaping Engine - Typography](https://docs.microsoft.com/en-us/typography/script-development/use)
* Content Source: [typographydocs/script-development/use.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/use.md)
* Product: **typography**

**Comment by xadxura** [comment]
Fix in progress.

**Comment by xadxura** [comment]
Fixed
