### ISSUE TITLE
Incorrect tag name: psts instead of ssty

### ISSUE THREAD

**Issue by floorish** [MicrosoftDocs/typography-issues#459]
The OpenType documentation page for features p-t contains the 'psts' tag twice. Once for the correct 'psts' tag and once incorrectly instead of the 'ssty' tag.

Observed:
```
Tag: 'psts'
Friendly name: Math script style alternates
```

Expected:
```
Tag: 'ssty'
Friendly name: Math script style alternates
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c3b75f69-8bb1-88e5-05b9-035c9f3ec528
* Version Independent ID: 9a9af849-512e-5dfd-b9a6-c05480f34f01
* Content: [Registered features, p-t - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/features_pt#-tag-psts)
* Content Source: [typographydocs/opentype/spec/features_pt.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_pt.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by alib-ms** [comment]
Thank for letting us know. This is a typo and should be fixed. I will follow up with team to get this fixed.

**Comment by alib-ms** [comment]
Thank you for the feedback. This has been fixed.

**Comment by PeterCon** [comment]
Typo was introduced on May 18 in a change to fix some anchor tags; it was not present when first published.
