### ISSUE TITLE
Swapped monetary and math pages

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#46]
Clicking “Monetary” in the sidebar brings up the page about math symbols, and vice versa.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8b81bf0-ec85-e0ce-d13f-49b4752b1afd
* Version Independent ID: ee7ea40e-3894-762d-1d2c-bfa74099aebc
* Content: [Character design standards - Math symbols for Latin 1 - Typography](https://docs.microsoft.com/en-us/typography/develop/character-design-standards/monetary)
* Content Source: [typographydocs/develop/character-design-standards/monetary.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/develop/character-design-standards/monetary.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment]
Closing As Fixed
