### ISSUE TITLE
Bahnschrift lacks tabular figures

### ISSUE THREAD

**Issue by buttercookie42** [MicrosoftDocs/typography-issues#461]
The Bahnschrift documentation mentions that "The weight axis of Bahnschrift is fully duplexed—that is to say, the width of each letter is exactly the same whether in Light, Bold, or any weight in-between! This is pretty unusual in the world of fonts and makes Bahnschrift particularly useful for tabular data where everything needs to align, or in applications where line lengths are locked.", but at the same time Bahnschrift only seems to include proportional figures, which somewhat defeats that advantage again.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b0aa22d-ec65-a36b-3a23-ca87e18ada28
* Version Independent ID: 05d3eb61-7b3c-24f6-dc0e-cb9d02e1c3a0
* Content: [Bahnschrift font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/bahnschrift)
* Content Source: [typographydocs/font-list/bahnschrift.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/bahnschrift.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **v-nihar**

**Comment by alib-ms** [comment]
Hi, 

Thank you for the feedback. The 2.06 version of Bahnschrift adds support for Vietnamese language along with tabular figures.  These figures can be accessed through the OpenType features.

**Comment by buttercookie42** [comment]
Great to know, thank you. I assume that that version of Bahnschrift is shipped with Windows 2004?

**Comment by alib-ms** [comment]
Yes, Windows 10, version 2004 includes Bahnschrift version 2.06.

**Comment by alib-ms** [comment]
Regular figures
<img width="417" alt="regular_fig" src="https://user-images.githubusercontent.com/36778811/88842164-e58f6880-d193-11ea-9be7-99999936340d.png">
Tabular figures
<img width="431" alt="tabu_fig" src="https://user-images.githubusercontent.com/36778811/88842250-08218180-d194-11ea-93cb-8ac05748a92c.png">
