### ISSUE TITLE
Correction of section name.

### ISSUE THREAD

**Issue by ln-north** [MicrosoftDocs/typography-issues#462]
> The OpenType Layout tables are described in more detail in the “Font File tables” section of the OpenType specification.

“Font File tables” section is incorrect.

> The OpenType Layout tables are described in more detail in the “Font Tables” section of the OpenType specification.

"Font Tables" section is correct .

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b15ab9e-86c5-f6e0-0145-f9de77c60141
* Version Independent ID: 0ebe3dec-cc24-b6a4-01b8-73bfdb79a71a
* Content: [Advanced typographic tables - OpenType Layout - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/ttochap1)
* Content Source: [typographydocs/opentype/spec/ttochap1.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/ttochap1.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by alib-ms** [comment]
Hi, Thank you for letting us know. I will have this corrected. 

Ali

**Comment by ln-north** [comment]
Thanks!
