### ISSUE TITLE
Link to "VOLT community Web site" no longer works

### ISSUE THREAD

**Issue by bjh21** [MicrosoftDocs/typography-issues#463]
On https://docs.microsoft.com/en-gb/typography/script-development/arabic there's a link with the text "VOLT community Web site" which is meant to be where one can download the _Arabic Typesetting_ font.  However that link, to 
http://communities.msn.com/MicrosoftVOLTuserscommunity, now just gives an error message saying

>Invalid URL
>The requested URL "[no URL]", is invalid.
>
>Reference #9.4e86768.1594677744.bb3208f 

I think that either the link should work or it should be removed, maybe replaced with a note indicating that _Arabic Typesetting_ is no longer distributed.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2296e659-a278-4505-3dbe-54e2f8e51a54
* Version Independent ID: 5af9216e-b435-4a4c-3c5a-94756409f8f5
* Content: [Developing OpenType Fonts for Arabic Script - Typography](https://docs.microsoft.com/en-gb/typography/script-development/arabic)
* Content Source: [typographydocs/script-development/arabic.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/arabic.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Thank you for the feedback. Agree this needs to be updated as the Arabic Typesetting is included with VOLT supplemental files package.

**Comment by alib-ms** [comment]
Fixed.
