### ISSUE TITLE
Revise constraint on Axis Value Tables to allow for format 4

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#473]
In the section on Axis Value Tables, just before the section for format 1, a constraint is stated:

"No two tables should provide information for the same axis value."

This predates the addition of format 4 axis value tables, and format 4 seems to contravene this. Certainly the data in example 6 is inconsistent with it. But the intent was that no two AVTs should provide the same _set_ of axis values. 

Consider revising to:

“No two tables should provide information for the same axis value or (in the case of format 4) combination of axis values. A format 4 table may specify an axis value that is also specified in another table, but only if there is some other difference in the axis values specified by those tables.”

Or:

"For formats 1, 2 and 3, no two tables should provide information for the same axis value. For format 4, no two tables should provide information for the same combination of axis values."

Or, simply,

"No two tables should provide information for the same combination of axis values."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dac86fb-3792-6630-ade2-32bfc4bba93a
* Version Independent ID: 9de5c023-f363-3e42-43c9-eac7793c8eaa
* Content: [STAT — Style Attributes Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/stat#axis-value-tables)
* Content Source: [typographydocs/opentype/spec/stat.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/stat.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by sairuspatel** [comment]
Also consider inserting "of the same format" into Peter's proposed wording; this solves the problem described in the current  OTFonVar thread "STAT Axis Value tables: allowing for both ranges & style linking". Thus:

In the STAT spec, replace “No two tables should provide information for the same axis value” with:
 
“No two tables of the same format should provide information for the same axis value or (in the case of format 4) combination of axis values. A format 4 table may specify an axis value that is also specified in another table, but only if there is some other difference in the axis values specified by those tables.”

Also note ambiguities in what fields "axis value" refers to in the above stricture. I believe the intention is that it applies only to the value (fmt 1&3), nominalValue (fmt 2), and axisValues (fmt 4) fields, which are regarded as the "keys" to those tables in a key-value system. It does not apply to the linkedValue or ranges, which are the "values" of those tables. We should consider clarifying this while we're revising this stricture.

**Comment by PeterCon** [comment]
>Also consider inserting "of the same format"...

I think that suggestion is really addressing a separate issue which is filed as #576 . The core problem cited in this issue is that format 4 is in conflict with the intent of the current wording.

**Comment by PeterCon** [comment]
Proposed change for the next version in relation just to this issue:

>No two tables should provide information for the same <del>axis value.</del><ins>combination of axis values. A format 4 table may specify an axis value that is also specified in another table, but only if there is some other difference in the combination of axis values specified by those two tables.</ins>

This text will be revisited in relation to #576.
