### ISSUE TITLE
Can an offset in itemVariationDataOffsets be NULL?

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#481]
The spec for IVS doesn't indicate whether an element of the itemVariationDataOffsets[] array can be NULL (0), to mean there are no deltas for that IVS outer index. Up to now, there has never been any need, so a reasonable expectation is that there are no NULL offsets (or, a NULL offset is treated as just that: the subtable starts at offset 0). But in the future, it might be a useful way to indicate that all deltas for an item are 0s.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc38f55-a142-6d66-fc68-1bb6e6e9ed56
* Version Independent ID: 0665d6f2-4150-1977-4fd6-91c50c226ed9
* Content: [OpenType Font Variations Common Table Formats - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otvarcommonformats)
* Content Source: [typographydocs/opentype/spec/otvarcommonformats.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otvarcommonformats.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
There isn't any obvious alternate semantic for NULL offsets that some implementation might have found useful. So if we add an explicit statement of semantic intent for NULL offsets, then it wouldn't be breaking some previously-assumed interoperable behaviour. (They might have assumed the parent table was invalid; we'd make that a false assumption, but wouldn't break a feature.)

So, it seems safe to add this. And there are reasons to expect it will be useful in the future. In particular, this will be useful for a proposed future enhancement to COLR—see <https://github.com/googlefonts/colr-gradients-spec/issues/31>.

**Comment by PeterCon** [comment]
Change made for next version:

><ins>The item variation store includes an array of offsets to item variation data subtables. A NULL offset indicates that there is no item variation data subtable for that index into the array.</ins>
>
> ><ins>*Note:* Indices into the itemVariationDataOffsets array are stored in parent tables as delta-set “outer” indices with each such index having a corresponding “inner” index. If the outer index points to a NULL offset, then any inner index will be invalid. The itemVariationDataOffsets array should not include any NULL offsets.</ins>
>
><del>The item variation store includes an array of offsets to item variation data subtables. </del>Each item variation data subtable includes deltas for some number of items, and some subset of regions. The regions are indicated by an array of indices into the variation region list.

**Comment by behdad** [comment]
> If the outer index points to a NULL offset, then any inner index will be invalid. The itemVariationDataOffsets array should not include any NULL offsets.

Vast majority of the OT spec doesn't specify how NULL offsets should be dealt with.

In this case, it's easy to imagine a simple / fast font subsetter resulting in NULL offsets, if they were allowed in the spec, when all minor values for a major are unused in the subset...

Anyway. My point is: how to deal with NULL offsets is a spec-wide issue and you seem determined to address it in this case. Feel free to do whatever you want, but this is just one instance of a bigger issue.

**Comment by PeterCon** [comment]
That's valid feedback, and you're right: it would be better to address once (in otff.htm), unless there really is some exceptional behaviour that needs to be called out in some location. For some time, the spec has had "may be NULL" in many places, so it will take a bit of work to review across the spec how best to consolidate that.
