### ISSUE TITLE
Remove historical information

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#485]
This introduction:

> The OpenType font format is an extension of the TrueType font format, adding support for PostScript font data. The OpenType font format was developed jointly by Microsoft and Adobe.

made sense when everyone knew about TrueType and nothing about OpenType. It's now somewhat irrelevant. It's also incomplete, as OpenType does an awful lot more than PostScript data. Rewrite or remove.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5d56f7d-d695-789b-aabf-380f8b2029b2
* Version Independent ID: 0283c098-6f8a-e30c-78a5-e27b9b3c05a0
* Content: [OpenType overview - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/overview)
* Content Source: [typographydocs/opentype/spec/overview.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/overview.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Probably the whole page should be re-written.

**Comment by simoncozens** [comment]
Lets face it, the whole *spec* needs a rewrite. And because the editing process is closed, proprietary and opaque, it wasn’t exactly clear whether you’d prefer to see issues on a per-item, per-section or per-chapter basis.

Open the thing up, and I’ll happily send chapter-level PRs with a nice commit granularity, and you can cherry-pick which ones you think are appropriate.

**Comment by PeterCon** [comment]
Attached is a proposed rewrite of this chapter for the next version.

[overview_draft_201004_delta-from-183.pdf](https://github.com/MicrosoftDocs/typography-issues/files/5323468/overview_draft_201004_delta-from-183.pdf)
