### ISSUE TITLE
Clarify fonts / font files, system services, and outlines

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#486]
> OpenType fonts and the operating system services which support OpenType fonts provide users with a simple way to install and use fonts, whether the fonts contain TrueType outlines or CFF (PostScript) outlines.

This sentence says that OpenType fonts make it easy to use fonts, which makes no sense. This is a result of the fact that although supposed to be a specification there is no definition of terms. Consider adding one. What we are talking about here is font files - font files are the on-disk binary representation of the font, which is what the spec actually deals with. Consider differentiating between "fonts" and "font files" throughout the spec.

Also remove the last clause about outlines, as although historically the main difference was bringing together TrueType and PostScript outlines, OT has since grown many different outline formats and so TTF and CFF cross-compatibility is no longer the main distinguishing factor of OT.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5d56f7d-d695-789b-aabf-380f8b2029b2
* Version Independent ID: 0283c098-6f8a-e30c-78a5-e27b9b3c05a0
* Content: [OpenType overview - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/overview)
* Content Source: [typographydocs/opentype/spec/overview.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/overview.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
A proposed rewrite of this chapter has been attached in a comment to #485.
