### ISSUE TITLE
Remove historical comparisons

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#487]
> The OpenType font format addresses the following goals:
> * broader multi-platform support
> * better support for international character sets
> * better protection for font data
> * smaller file sizes to make font distribution more efficient
> * broader support for advanced typographic control

These initial design goals are expressed as comparatives - better than... what? We know historically the answer is "better than TrueType", but this is no longer relevant. Either rewrite as present-oriented goals removing the comparatives, or remove altogether.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5d56f7d-d695-789b-aabf-380f8b2029b2
* Version Independent ID: 0283c098-6f8a-e30c-78a5-e27b9b3c05a0
* Content: [OpenType overview - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/overview)
* Content Source: [typographydocs/opentype/spec/overview.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/overview.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
A proposed rewrite of this chapter has been attached in a comment to #485.
