### ISSUE TITLE
Wrong link target for em footnote

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#49]
In “1/5 the em”, “em” links to https://www.microsoft.com/#em_footnote.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49d63447-f3fe-ec7e-d41a-9042ee0f4be4
* Version Independent ID: e991c452-6645-de6f-93fd-f307dc8c4172
* Content: [Character design standards - Space characters for Latin 1 - Typography](https://docs.microsoft.com/en-us/typography/develop/character-design-standards/whitespace)
* Content Source: [typographydocs/develop/character-design-standards/whitespace.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/develop/character-design-standards/whitespace.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment]
Closing As Fixed
