### ISSUE TITLE
Dangling comparative

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#490]
> OpenType fonts can include the OpenType Layout tables, which allow font creators to design better international and high-end typographic fonts

Better than what? Also "*the* OpenType Layout tables" here is strange. Remove "the".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5d56f7d-d695-789b-aabf-380f8b2029b2
* Version Independent ID: 0283c098-6f8a-e30c-78a5-e27b9b3c05a0
* Content: [OpenType overview - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/overview)
* Content Source: [typographydocs/opentype/spec/overview.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/overview.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
A proposed rewrite of this chapter has been attached in a comment to #485.
