### ISSUE TITLE
Text-processing applications

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#491]
> The OpenType Layout tables contain information on glyph substitution, glyph positioning, justification, and baseline positioning, enabling text-processing applications to improve text layout.

The term "text-processing applications" is not defined. As we know, most OTL processing is done through a shaping engine, and not the responsibility of the layout engine or user application. The spec should capture this model and its distinctions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5d56f7d-d695-789b-aabf-380f8b2029b2
* Version Independent ID: 0283c098-6f8a-e30c-78a5-e27b9b3c05a0
* Content: [OpenType overview - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/overview)
* Content Source: [typographydocs/opentype/spec/overview.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/overview.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by NorbertLindenberg** [comment]
See also bug #290.

**Comment by PeterCon** [comment]
A proposed rewrite of this chapter has been attached in a comment to #485.
