### ISSUE TITLE
Remove and reword related documentation

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#492]
> TrueType 1.0 Font Files, Technical Specification. Microsoft.

No longer available or relevant.

> OpenType Layout Font Specification. Microsoft.

No longer available.

> Technical Note #5015: “The Type 1 Font Format Supplement.”

*Adobe* Technical Note. Also provide link.

> This document contains all updates to the Type 1 format.

Wording of "this document" here is awkward. "This document" (the one currently being read) is the OpenType Spec!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5d56f7d-d695-789b-aabf-380f8b2029b2
* Version Independent ID: 0283c098-6f8a-e30c-78a5-e27b9b3c05a0
* Content: [OpenType overview - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/overview)
* Content Source: [typographydocs/opentype/spec/overview.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/overview.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterConstable** [comment]
Cf. links in <https://docs.microsoft.com/en-us/typography/opentype/spec/cff>

**Comment by PeterCon** [comment]
A proposed rewrite of this chapter has been attached in a comment to #485.
