### ISSUE TITLE
Choose a name and stick to it

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#493]
> The Advanced typographic tables (OpenType Layout tables) 

Everywhere else referred to as "OpenType Layout tables". If you want to say that they enable advanced typography, say that in a description or definition.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b15ab9e-86c5-f6e0-0145-f9de77c60141
* Version Independent ID: 0ebe3dec-cc24-b6a4-01b8-73bfdb79a71a
* Content: [Advanced typographic tables - OpenType Layout - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/ttochap1)
* Content Source: [typographydocs/opentype/spec/ttochap1.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/ttochap1.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Changed for next version:

><del>The Advanced typographic tables (OpenType Layout tables) extend the functionality of fonts with either TrueType or CFF outlines. OpenType Layout fonts contain additional information that extends the capabilities of the fonts to support</del><ins>OpenType Layout tables provide advanced typographic capabilities for</ins> high-quality international typography:
