### ISSUE TITLE
OTL "helps" the text-processing application

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#496]
> OpenType Layout helps a text-processing application determine which variant to substitute when composing text.

"helps" is a strange word to use here. Better to spell out the responsibilities of the shaper and the capabilities of the font file, and explain what actually happens: OpenType Layout tables inform the shaping engine which glyph variant should be substituted in each situation.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b15ab9e-86c5-f6e0-0145-f9de77c60141
* Version Independent ID: 0ebe3dec-cc24-b6a4-01b8-73bfdb79a71a
* Content: [Advanced typographic tables - OpenType Layout - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/ttochap1)
* Content Source: [typographydocs/opentype/spec/ttochap1.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/ttochap1.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Changed for next version in the cited sentence and also in the following paragraph.
