### ISSUE TITLE
"TrueType versus OpenType Layout"

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#498]
This section is muddled and should probably be removed. The first paragraph compares TT and OT, which is no longer relevant. The second paragraph repeats previous material. The third paragraph tries to distinguish the responsibilities of the layout engine, shaping engine and font file, but does so in a way that is unclear and at any rate has nothing to do with TrueType versus OpenType.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b15ab9e-86c5-f6e0-0145-f9de77c60141
* Version Independent ID: 0ebe3dec-cc24-b6a4-01b8-73bfdb79a71a
* Content: [Advanced typographic tables - OpenType Layout - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/ttochap1)
* Content Source: [typographydocs/opentype/spec/ttochap1.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/ttochap1.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Changed for the next version: removed the heading and the first two paragraphs. The third paragraph has some relevant info and is kept with some revisions:

>As much as possible, <del>the tables of </del>OpenType Layout <ins>tables </ins>define only the information that is specific to <del>the</del><ins>a particular </ins>font<del> layout</del>. The tables do not try to encode information that remains constant within the conventions of a particular language or the typography of a particular script. Such information that would be replicated across all fonts in a given language belongs in <del>the</del><ins>a</ins> text-processing application for that language, not in the fonts.

The placement of this paragraph at the end of (now) the "OpenType Layout at a glance" section seems reasonable.
