### ISSUE TITLE
Font versus font file

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#499]
This is a clear example of why we need to be more precise about terminology:

>  A font is a collection of glyphs. To retrieve glyphs, the client uses information in the 'cmap' table of the font, ...

If a font is "a collection of glyphs", how does it have a cmap table?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b15ab9e-86c5-f6e0-0145-f9de77c60141
* Version Independent ID: 0ebe3dec-cc24-b6a4-01b8-73bfdb79a71a
* Content: [Advanced typographic tables - OpenType Layout - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/ttochap1)
* Content Source: [typographydocs/opentype/spec/ttochap1.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/ttochap1.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Changed for next version:

>A font <del>is</del><ins>contains</ins> a collection of glyphs.
