### ISSUE TITLE
Dead link to the font properties editor

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#5]
The “Font properties editor” link is dead. It should point to https://docs.microsoft.com/en-us/typography/tools/font-properties-editor.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a1c6588-f887-46ea-8f19-aed067e6c0d5
* Version Independent ID: 76804d51-3c1a-761f-48ea-b6e176aaf286
* Content: [Register as a typography vendor - Typography](https://docs.microsoft.com/en-us/typography/vendors/register)
* Content Source: [typographydocs/vendors/register.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/vendors/register.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alibasi** [comment]
Done!
