### ISSUE TITLE
Typo: "Standard Morrocan Tamazigh"

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#50]
“Standard Morrocan Tamazigh” should be “Standard Moroccan Tamazight”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662c6f54-f90c-52ed-dca2-0f0a0a49fee5
* Version Independent ID: 6aa33924-d45e-60c3-a9fd-e317ff662993
* Content: [Language system tags - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags)
* Content Source: [typographydocs/opentype/spec/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/languagetags.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Fixed for the next version. Thanks!

**Comment by dscorbett** [comment]
“Tamazigh” was fixed, but “Morrocan” still needs to be changed to “Moroccan”.

**Comment by PeterCon** [comment]
Fixed.
