### ISSUE TITLE
Figure 1h does not really show anything

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#501]
This figure claims to show "Differences in the English, French, and German language system". In reality it shows different characters normally associated with those languages; you could correctly display those examples in a font file with no language-specific information at all.

A better example would explain processing differences specific to the language system; for example, applying the small-caps feature to text with language set to English and to Turkish.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b15ab9e-86c5-f6e0-0145-f9de77c60141
* Version Independent ID: 0ebe3dec-cc24-b6a4-01b8-73bfdb79a71a
* Content: [Advanced typographic tables - OpenType Layout - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/ttochap1)
* Content Source: [typographydocs/opentype/spec/ttochap1.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/ttochap1.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Changed for the next version with a figure based on the suggestion of small caps for English versus Turkish.
![otlch1_fig1h](https://user-images.githubusercontent.com/12788502/91645086-09de9f00-e9f7-11ea-9c98-b2d18f9959a1.png)
