### ISSUE TITLE
"Features" section

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#502]
> Features define the basic functionality of the font.

This is a strange way to introduce the topic. What do you mean by "basic functionality" here? Better to describe what a feature is: a collection of lookups which specify information to the shaper about what substitutions and positioning adjustments need to be applied in particular circumstances.

> The OpenType Layout feature model provides great flexibility to font developers because features do not have to be predefined by Microsoft Corporation. Instead, font developers can work with application developers to determine useful features for fonts, add such features to OpenType Layout fonts, and enable client applications to support such features.

This paragraph is somewhat misleading; was it written before the explosion of features in the features registry? While it is technically true that font developers could create arbitrary features outside the spec and then somehow convince layout engines to turn on processing for them, it's hardly common or best practice.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b15ab9e-86c5-f6e0-0145-f9de77c60141
* Version Independent ID: 0ebe3dec-cc24-b6a4-01b8-73bfdb79a71a
* Content: [Advanced typographic tables - OpenType Layout - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/ttochap1)
* Content Source: [typographydocs/opentype/spec/ttochap1.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/ttochap1.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Two separate issues here: (i) describing "features" in general, and (ii) the registry part.

**Comment by PeterCon** [comment]
The first issue, describing features, has been address in the changes made for #506.

Wrt the second issue, the quoted paragraph is a bit misleading, but not entirely so: even after the initial explosion of features in the late 1990s, there have been new features defined over time since then, driven by font vendors, layout format specs (e.g., CSS WG) or app vendors.

Changes for next version:
>The OpenType Layout feature model provides <del>great flexibility to font developers because features do not have to be predefined by Microsoft Corporation. Instead, font developers can work with application developers to determine useful features for fonts, add such features to OpenType Layout fonts, and enable client applications to support such features.</del><ins>flexibility for font developers, allowing them to choose capabilities to support in a font as appropriate for a given design or the requirements of their customers. The model also provides extensibility for future enhancements: on-going innovation can lead to features for new capabilities being defined over time.</ins>
