### ISSUE TITLE
OpenType Layout and Font Variations

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#504]
> many design variations along one or more axes of design variation.

Reword to avoid repetition.

> Mechanisms used to support Font Variations are integrated into the tables used for OpenType Layout.

Just a slight quibble: *mechanisms* are ways of doing things. Font files have no mechanisms, only information.

> Enhancements to OpenType Layout formats

These aren't enhancements any more; they're a full part of the same spec, not an enhancement of it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b15ab9e-86c5-f6e0-0145-f9de77c60141
* Version Independent ID: 0ebe3dec-cc24-b6a4-01b8-73bfdb79a71a
* Content: [Advanced typographic tables - OpenType Layout - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/ttochap1)
* Content Source: [typographydocs/opentype/spec/ttochap1.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/ttochap1.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Wrt "mechanisms": the enhancements in OT 1.8 included data _and_ algorithms for processing that data. Is it not reasonable to consider the combination of data and algorithms a "mechanism" for providing functionality?

**Comment by PeterCon** [comment]
Changed for next version:

>OpenType Font Variations allow a single font to support many design variations along one or more axes<del> of design variation</del>. For example, a font with weight and width variations might support weights from thin to black, and widths from ultra-condensed to ultra-expanded. For general information on OpenType Font Variations, see the chapter [OpenType Font Variations overview](otvaroverview.md).
>
><del>Mechanisms</del><ins>Data</ins> used to support Font Variations are integrated into the tables used for OpenType Layout. Variation of glyph outlines and metrics across a font’s variation space can impact the design-grid distances that get used in OpenType Layout tables, such as anchor positions used in a GPOS attachment lookup. <del>Enhancements to</del><ins>Data elements in</ins> OpenType Layout formats <del>allow the default values found in existing formats to</del><ins>can</ins> be associated with variation data that describes how the <del>given</del><ins>default</ins> value is adjusted for different variation instances.
