### ISSUE TITLE
"Lookup" is never defined

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#506]
The first use of the word "lookup" in this chapter is in a figure; the second is in the section on OpenType variations(!). It's worth explaining what a lookup is.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b15ab9e-86c5-f6e0-0145-f9de77c60141
* Version Independent ID: 0ebe3dec-cc24-b6a4-01b8-73bfdb79a71a
* Content: [Advanced typographic tables - OpenType Layout - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/ttochap1)
* Content Source: [typographydocs/opentype/spec/ttochap1.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/ttochap1.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Fixing for the next version:

>### Features<ins> and lookups</ins>
>
> Features define <del>the basic functionality</del><ins>advanced typographic capabilities</ins> of the font<ins>, and are the means that applications use to invoke those capabilities</ins>. A font that <del>contains tables to handle</del><ins>supports positioning of</ins> diacritical marks will <del>have</del><ins>implement</ins> a &#39;mark&#39; feature. A font that supports substitution of vertical glyphs will <del>have</del><ins>implement</ins> a &#39;vert&#39; feature.
>
> <ins>Lookups are data used to implement the capabilities invoked by features. Lookup tables describe glyph substitution or glyph positioning actions that an application should apply to achieve the desired typographic effect. A feature can be used to refer to a typographic capability in a font-independent way, but lookups provide the font-specific implementation for that capability.</ins>

**Comment by NorbertLindenberg** [comment]
Features define both basic functionality (for complex scripts) and advanced typographic capabilities (for all scripts).

**Comment by PeterCon** [comment]
The pre-edit sentence said "basic functionality of the font". I'd think of basic font functionality as char-glyph mapping, glyph outlines and glyph metrics. I was trying to fix that. But I'll revise in the spirit of your comment:

>Features define typographic capabilities of the font, and are the means that applications use to invoke those capabilities. These can include essential capabilities required for display of some scripts, as well as other capabilities for fine typography.

**Comment by PeterCon** [comment]
Tweak:
>...lookups provide the font-specific data used to implement that capability.
