### ISSUE TITLE
Outline formats

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#507]
> An OpenType font file contains data, in table format, that comprises either a TrueType or a Compact Font Format (CFF) outline font. Rasterizers use combinations of data from the tables contained in the font to render the TrueType or PostScript glyph outlines.

This was true before the introduction of SVG and bitmap formats. Consider using the term "glyph representation format", and spelling out here which formats are supported.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a1bda96-a268-b684-6cea-9b0c7be6f24e
* Version Independent ID: 36485fec-f05d-3984-6da8-ff2dd2799041
* Content: [OpenType font file - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otff)
* Content Source: [typographydocs/opentype/spec/otff.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otff.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
The SVG table requires that every glyph have TrueType, CFF or CFF2 outlines. 

Apple's TT spec allows for bitmap-only fonts, but from what I can tell, OT has never allowed for that. (Whether by design or by oversight, I don't know.)

But this paragraph is a bit simplistic.

**Comment by PeterCon** [comment]
Change for next version—I propose replacing that paragraph with the following:

>An OpenType font file contains data, in table format, used for rendering of text. Portions of the data are used by applications to calculate the layout of text using the font; that is, the selection of glyphs and their placement within a line. Other data provide descriptions of glyphs as TrueType or Compact Font Format (CFF) outlines. Still other data can provide monochromatic or color bitmaps or SVG documents as alternate glyph descriptions. The font data also includes meta-information, such as name strings that can used to present the font as an available choice in a font-picker user interface. Each of these types of data is stored in one or more tables each designed for a particular purpose.
