### ISSUE TITLE
May, must, should, etc.

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#508]
> OpenType fonts may have the extension .OTF, .TTF, .OTC or .TTC.

Possibly you mean "OpenType font files *must*..."

More generally there is a [de facto standard](https://tools.ietf.org/html/rfc2119) for the use of words like "may/must/should/etc." in technical specifications, to which this specification *should* adhere.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a1bda96-a268-b684-6cea-9b0c7be6f24e
* Version Independent ID: 36485fec-f05d-3984-6da8-ff2dd2799041
* Content: [OpenType font file - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otff)
* Content Source: [typographydocs/opentype/spec/otff.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otff.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
In this case, "should" may be appropriate, but I could go with "must" if there's community consensus around that.

**Comment by NorbertLindenberg** [comment]
I’d think an OpenType font packaged as .woff or .woff2 is still an OpenType font. Also, almost all OpenType font files on my Mac have the extension in lower-case. The statement about filenames must allow for these, and can't be more than "should".

**Comment by PeterCon** [comment]
Changed for next version:

>OpenType <del>fonts may have</del><ins>font files should use</ins> the extension .OTF, .TTF, .OTC or .TTC.<ins> (The extension may be upper or lower case.)</ins>

**Comment by behdad** [comment]
+1 to using MAY, SHOULD, MUST according to IETF definitions (and uppercasing).

Re file extension, to me, a MAY as best. Use of extensions had become irrelevant in the past two decades and we should reflect that. Any extensions should be only a suggestion.

I also suggest we only encouraging one ("otf") and discontinue the distinction between glyf-flavored and CFF-flavored fonts.

And +1 to making sure the wording is consistent with allowing other transportation formats like WOFF and WOFF2.

**Comment by behdad** [comment]
Also something that we pick one SFNT signature tag and recommend it for all fonts moving forward. Suggesting 'OTTO'.

And OTF/OTC for font/collection.

**Comment by simoncozens** [comment]
> I also suggest we only encouraging one ("otf") and discontinue the distinction between glyf-flavored and CFF-flavored fonts.

Agree with this. Literally the whole point of OT is that you can have different outlines within the font and the end user doesn't have to care. People still talk about "OTFs" versus "TTFs" as if they're separate things, when they're really just talking about implementation details within OpenType, and it's not helpful.

**Comment by PeterCon** [comment]
Different topic. Please open a separate issue.

**Comment by tiroj** [comment]
Created new issue:
https://github.com/MicrosoftDocs/typography-issues/issues/583
