### ISSUE TITLE
Fixed version numbers deserve their own type

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#509]
> The representation of a non-zero minor version, however, is not consistent with the normal treatment of Fixed values, in which the lower 16 bits represent a fractional value, N * 2 ^ -16.

In which case this *isn't* a Fixed value, so it's better to stop pretending that it is. Just define it as a Version or something.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a1bda96-a268-b684-6cea-9b0c7be6f24e
* Version Independent ID: 36485fec-f05d-3984-6da8-ff2dd2799041
* Content: [OpenType font file - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otff)
* Content Source: [typographydocs/opentype/spec/otff.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otff.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
I concur. (Why didn't we do this a few years ago when we discussed how rationalize better the table version mess?)

**Comment by PeterCon** [comment]
Added a new type, Version16Dot16, and revised the Table Version Numbers section:

>## Table Version Numbers
>
>Most tables have version numbers, and the version number for the entire font is contained in the [Table Directory](#tabledirectory). Note that there are five different version number types, each with its own numbering scheme.
>
>* A single uint16 field. This is used in a number of tables, usually with versions starting at zero (0).
>* Separate, uint16 major and minor version fields. This is used in a number of tables, usually with versions starting at 1.0.
>* <del>A Fixed field for major/minor version numbers. This is used in the [&#39;maxp&#39;](maxp.md), [&#39;post&#39;](post.md) and [&#39;vhea&#39;](vhea.md) tables.</del>
>* A uint32 field with enumerated values.
>* A uint32 field with a numeric value. This is used only in the [DSIG](dsig.md) and [&#39;meta&#39;](meta.md) tables.
>* <ins>A Version16Dot16 field for major/minor version numbers. This is used only in the [&#39;maxp&#39;](maxp.md), [&#39;post&#39;](post.md) and [&#39;vhea&#39;](vhea.md) tables.</ins>
>
><del>Only certain tables use a Fixed value for version</del><ins>The Version16Dot16 type is used for the version field of certain tables</ins>, and only for reasons of backward compatibility. <ins>(In earlier versions, these fields were documented as using a Fixed value, but had minor version numbers that did not follow the definition of the Fixed type.) </ins><del>When a Fixed number is used as a version,</del><ins>Version16Dot16 is a packed value:</ins> the upper 16 bits comprise a major version number, and the lower 16 bits, a minor version. <del>The representation of a non-zero minor version, however, is not consistent with the normal treatment of Fixed values, in which the lower 16 bits represent a fractional value, *N &ast; 2 ^ -16*. Rather, tables with non-zero minor version numbers always specify the literal value of the version number.</del><ins>Non-zero minor version numbers are represented digits 0 to 9 in the highest-order nibbles of the lower 16 bits.</ins> For example, the version <del>number</del><ins>field</ins> of &#39;maxp&#39; table version 0.5 is 0x00005000, and that of &#39;vhea&#39; table version 1.1 is 0x00011000. <del>When Fixed is indicated as the type for a version field, the possible values should be treated as an enumeration of specific values, rather than as a numeric value capable of representing many potential major and minor versions.</del><ins>This type is used only in the &#39;maxp&#39;, &#39;post&#39; and &#39;vhea&#39; tables, and will not be used for any other tables in the future.</ins>

The 'maxp', 'post' and 'vhea' tables were also updated to use the new type for their version fields.
