### ISSUE TITLE
Table Record versus Table Record Entries

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#510]
> The Offset Table is followed immediately by the Table Record entries. Entries in the Table Record must be sorted in ascending order by tag. Offset values in the Table Record are measured from the start of the font file.

The Offset Table is followed immediately by the Table Record, which is a collection of Table Record Entries. Entries in the Table Record must be sorted in ascending order by tag. Offset values in Table Record Entries are measured from the start of the font file.

(The table following this paragraph describes a Table Record Entry, not a Table Record.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a1bda96-a268-b684-6cea-9b0c7be6f24e
* Version Independent ID: 36485fec-f05d-3984-6da8-ff2dd2799041
* Content: [OpenType font file - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otff)
* Content Source: [typographydocs/opentype/spec/otff.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otff.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by simoncozens** [comment]
Note also that the `Font Collection File Structure` section refers to this as the Table Directory.

**Comment by PeterCon** [comment]
Would be good to clean up wording here. But I doubt this is hindering any implementations, so doesn't need to be high priority.

**Comment by PeterCon** [comment]
>followed immediately by the Table Record, which is a collection of Table Record Entries

A record is not an array. 

I think a better way to fix this is to have Offset Table include a `tableRecords[]` member. That's how tables that have a sequence of simple-type members followed by an array of records are usually documented. (E.g., avar, cmap, gasp, etc.; and many subtable formats, e.g., SinglePosFormat2, etc.)

**Comment by PeterCon** [comment]
>Note also that the Font Collection File Structure section refers to this as the Table Directory.

Ah! Thanks for calling this out.

**Comment by PeterCon** [comment]
Ugh! The "Table Directory" terminology is not used consistently.

Apple uses "font directory" to mean a two-part item comprised of "offset table" followed by the "table directory" (the array of table records).

Currently, the OT spec doesn't use "font directory", and uses "table directory" to mean
* the table records array (same usage as Apple)
* the Offset Table, or else the combined Offset Table + table records array (which Apple would call "font directory")
* (in an instance of poor wording) a particular record (for head) in the table records array

**Comment by PeterCon** [comment]
Tentatively have made changes adding `tableRecords[]` to Offset Table, but usage of "table directory" really should be cleaned up. Need to solicit input on how different implementers have understood the terminology / struct names and suggestions for how to clean it up.

**Comment by PeterCon** [comment]
Change completed for next version.
