### ISSUE TITLE
Table padding

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#511]
> This function implies that the length of a table must be a multiple of four bytes. In fact, a font is not considered structurally well-formed without the correct padding. All tables must begin on four-byte boundaries, and any remaining space between tables is padded with zeros.

This is important structural information and should not be buried in a side-note in a section on how to calculate checksums.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a1bda96-a268-b684-6cea-9b0c7be6f24e
* Version Independent ID: 36485fec-f05d-3984-6da8-ff2dd2799041
* Content: [OpenType font file - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otff)
* Content Source: [typographydocs/opentype/spec/otff.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otff.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by simoncozens** [comment]
Here is a better way to write it:

> The `head` table is a special case, as it  contains a `checkSumAdjustment` field which is calculated and written *after* the table's checksum is calculated, necessarily invalidating that checksum.  A *font consumer* attempting to verify that the `head` table has not changed should calculate the checkSum for that table by assuming that the `checkSumAdjustment` value is zero before comparing the result with the entry in the *Table Directory*.

**Comment by PeterCon** [comment]
If revising, note discussion of alignment in recom.htm (which adds to current ambiguity)

**Comment by PeterCon** [comment]
See related mentions in otff.htm at the start of the "Font Tables" section, and in the Recommendations chapter.

**Comment by PeterCon** [comment]
Draft revisions for the next version:

**The OpenType Font File:**
Inserted a paragraph after the description of TableRecord:

><ins>All tables must begin on four-byte boundaries, and any remaining space between tables must be padded with zeros. The length of each table should be recorded in the table record with the actual length of data, not the padded length.</ins>
>
>Some tables have an internal structure with subtables located at specified offsets...

Revised the note that follows the algorithm for calculating a checksum:
>> *Note:* This function <del>implies</del><ins>assumes</ins> that the length of <del>a table must be</del><ins>any table is</ins> a multiple of four bytes<del>. In fact, a font is not considered structurally well-formed without the correct padding. All tables must begin on four-byte boundaries, and any remaining space between tables is padded with zeros. The length of all tables should be recorded in the table record with their actual length (not their padded length).</del><ins>, or that tables are padded with zero to four-byte aligned offsets. Actual table lengths recorded in the TableDirectory should not include padding, however. To accommodate data with a length that is not a multiple of four, the above algorithm must be modified to treat the data as though it contains zero padding to a length that is a multiple of four.</ins>

Deleted the first paragraph in the Font Tables section:

>## Font Tables
>
><del>The TrueType rasterizer has a much easier time traversing tables if they are padded so that each table begins on a 4-byte boundary. Also, the algorithm for calculating table checksums assumes that tables are 32-bit aligned. For this reason, all tables must be 32-bit aligned and padded with zeroes.</del>

**Recommendations:**
Revised the content in the Table Alignment and Length section:

><del>All tables should be aligned to begin at offsets which are multiples of four bytes. While this is not required by the TrueType rasterizer, it does prevent ambiguous checksum calculations and greatly speeds table access on some processors.</del>
>
><del>All tables should be recorded in the [table directory](otff.md#tabledirectory) with their actual length. To ensure that checksums are calculated correctly, it is suggested that tables begin on 32-bit boundaries. Any extra space after a table (and before the next 32-bit boundary) should be padded with zeros.</del>
>
><ins>Some implementations do not assume that tables have four-byte aligned offsets, and some do not validate table checksums. However, there are also implementations that do validate table checksums and that calculate checksums assuming that tables have four-byte aligned offsets with padded zeros. Also, having tables begin at four-byte aligned offsets provides performance benefit when accessing tables, and minimizes potential for erroneous checksum calculation. New fonts are required to align table offsets to multiples of four bytes. However, new software implementations should allow for table lengths that are not a multiple of four when calculating checksums, if checksums are validated.</ins>

**Comment by behdad** [comment]
> All tables must begin on four-byte boundaries

This sounds like a strict requirement you just slipped in without broad consensus. I object to this.

**Comment by PeterCon** [comment]
No, read the opening comment and the current text: It's a currently-stated requirement; I've just moved it to a more appropriate location in the spec.

**Comment by behdad** [comment]
> No, read the opening comment

I don't consider that comment in the checksum part of the spec as authoritative and implying that 4byte-padding was always a requirement.

Anyway. Doesn't matter because the spec has no enforcement.

**Comment by PeterCon** [comment]
Add'l info: Several engineers have confirmed to me that unaligned access remains slower even on modern hardware. Also, on Intel Itanium (produced until last year), it would result in hardware interrupts.

**Comment by mikeday** [comment]
I think it makes sense for tables to be aligned on four byte boundaries but it's worth pointing out that not all fields in OpenType are aligned at present, for example the ScriptRecord.scriptTag and LangSysRecord.langSysTag fields are 32-bit but only have 16-bit alignment, so applications must be prepared to make unaligned reads for these fields.

**Comment by PeterCon** [comment]
I'll add a note in that regard after the mention of four-byte table alignment:

><ins>All tables must begin on four-byte boundaries, and any remaining space between tables must be padded with zeros. The length of each table should be recorded in the table record with the actual length of data, not the padded length.</ins>
>
>> <ins>*Note:* The requirement for four-byte alignment applies to top-level tables only and does not extend to sub-table offsets, records, or fields within tables or records. Some 32-bit fields (int32, uint32 or Offset32 types) might not be four-byte aligned within the file.</ins>

Does that work?

**Comment by mikeday** [comment]
"fields within tables or records" sure, but are there no alignment constraints at all on subtables and other linked records within a table?

**Comment by PeterCon** [comment]
Well, all subtables are accessed via offsets from the start of their parent table, with either 16-bit or 32-bit offsets. (Unless I'm forgetting some really quirky exception --- maybe need to dbl check what apple did in the meta table.) So, I guess that all subtables would have to be at least two-byte aligned within the file.

**Comment by PeterCon** [comment]
(There was a quirk in Apple's initial doc'n of meta, but didn't affect subtable word alignment.)

**Comment by mikeday** [comment]
"would have to be at least two-byte aligned" because the spec requires it? Is there anything in the spec saying that an Offset16 cannot be an odd number?

**Comment by mikeday** [comment]
Another way of enforcing a minimal alignment constraint would be if no empty space or padding is allowed _within_ a table, then if all the subtable sizes are multiples of two (which appears to be the case for GSUB, GPOS, and cmap) then all of them will be 16-bit aligned.

**Comment by PeterCon** [comment]
>"would have to be at least two-byte aligned" because the spec requires it? Is there anything in the spec saying that an Offset16 cannot be an odd number?

Doh! You're right. So there's no direct or indirect constraint on subtable alignments.

>Another way of enforcing a minimal alignment constraint would be if no empty space or padding is allowed within a table...

It's waaayyy too late to add that as a requirement: any number of fonts from the past 30 years might not conform.

So, I think the note I suggested above is a clean as is feasible at this point.

**Comment by mikeday** [comment]
Sounds reasonable to me, although it would be nice to at least _recommend_ font creators to align their subtables and/or refrain from adding unnecessary padding inside tables.

Thank you for putting in the effort to polish up the spec for 1.8.4, it's much appreciated!

**Comment by PeterCon** [comment]
>Thank you for putting in the effort...

YW. Appreciate you mentioning it.

>it would be nice to at least recommend font creators to align their subtables and/or refrain from adding unnecessary padding inside tables.

If subtable (d)word alignment is desirable, wouldn't that mean _adding_ padding within tables? 

Something could be added in [recommendations](https://docs.microsoft.com/en-us/typography/opentype/spec/recom#table-alignment-and-length), though I'd like to hear owners of runtime implementations indicating it would be desirable.

**Comment by mikeday** [comment]
> If subtable (d)word alignment is desirable, wouldn't that mean adding padding within tables?

Good point, if a `cmap` subtable format 0 was followed by a `cmap` subtable format 8 the `length` field would not be 32-bit aligned unless two bytes of padding was inserted between the subtables. It seems unreasonable to demand this, and it's unlikely that implementations are inserting an _odd_ number of padding bytes, so it is probably best to remain silent on the matter. :laughing:

**Comment by behdad** [comment]
I'm aware of faster aligned access in modern hardware. And that's why I believe in fonttools and HarfBuzz we pad tables to four bytes. That's worth a note in the specification. But implementations are going to accept unaligned tables anyway. So I don't see why it's a good reason to disallow them in the specification.

**Comment by PeterCon** [comment]
> So I don't see why it's a good reason to disallow them in the specification.

You've given a valid reason to consider changing to a recommendation. On the other hand, I've been told there are CFF rasterizers that will reject fonts if tables aren't four-byte aligned. (That could explain why this wasn't a requirement in TT or TTO specs but was added in OT.)

At any rate, I'd consider changing to a recommendation, but given the potential impact I think it shouldn't be in a dot-dot release, and that should only be done on the basis of a broad consensus, not as a unilateral decision.

**Comment by behdad** [comment]
> On the other hand, I've been told there are CFF rasterizers that will reject fonts if tables aren't four-byte aligned.

We should not be driving the file format with handwavy implementations that do not matter in any significant way.

**Comment by behdad** [comment]
Specially when we are talking about future fo things, not the past.
