### ISSUE TITLE
head entry checksum

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#512]
> The checkSum for the 'head' table which includes the checkSumAdjustment entry for the entire font is now incorrect. That is not a problem. Do not change it.

Leaving aside the fact that "This is not a problem. Do not change it" reads more like a implementation note than a file format specification, if the value being written is the value that is intended, then it's not "incorrect".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a1bda96-a268-b684-6cea-9b0c7be6f24e
* Version Independent ID: 36485fec-f05d-3984-6da8-ff2dd2799041
* Content: [OpenType font file - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otff)
* Content Source: [typographydocs/opentype/spec/otff.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otff.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by simoncozens** [comment]
Here is a better way to write it:

> The `head` table is a special case, as it contains a `checkSumAdjustment field` which is calculated and written after the table's checksum is calculated, necessarily invalidating that checksum. A *font consumer* attempting to verify that the `head` table has not changed should calculate the `checkSum` for that table by assuming that the `checkSumAdjustment` value is zero before comparing the result with the entry in the *Table Directory*.

**Comment by PeterCon** [comment]
Cf. #417

**Comment by PeterCon** [comment]
Changed for the next version:

><del>To calculate the checkSum for the &#39;head&#39; table which itself includes the checkSumAdjustment entry for the entire font, do the following:</del><ins>The &#39;head&#39; table is a special case in checksum calculations, as it includes a checkSumAdjustment field that is calculated and written after the table’s checksum is calculated and written into the table directory entry, necessarily invalidating that checksum value.</ins>
>
><ins>When generating font data, to calculate and write the &#39;head&#39; table checksum and checksumAdjustment field, do the following:</ins>
>
> 1. Set the checkSumAdjustment <ins>field </ins>to 0.
> 2. Calculate the checksum for all <del>the </del>tables including the &#39;head&#39; table and enter <del>that</del><ins>the</ins> value <ins>for each table </ins>into the <ins>corresponding record in the </ins>table directory.
> 3. Calculate the checksum for the entire font.
> 4. Subtract that value from 0xB1B0AFBA.
> 5. Store the result in <ins>the &#39;head&#39; table </ins>checkSumAdjustment<ins> field</ins>.
>
><del>The checkSum for the &#39;head&#39; table which includes the checkSumAdjustment entry for the entire font is now incorrect. That is not a problem. Do not change it. </del>An application attempting to verify that the &#39;head&#39; table has not changed should calculate the checkSum for that table <del>by not including</del><ins>assuming</ins> the checkSumAdjustment value<del>, and compare</del><ins> is zero, rather than the actual value in the font, before comparing</ins> the result with the <del>entry</del><ins>&#39;head&#39; table record</ins> in the table directory.
