### ISSUE TITLE
"A tool is available from Microsoft to help build .TTC files."

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#513]
This probably refers to `makettc`. It is no longer available from Microsoft.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a1bda96-a268-b684-6cea-9b0c7be6f24e
* Version Independent ID: 36485fec-f05d-3984-6da8-ff2dd2799041
* Content: [OpenType font file - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otff)
* Content Source: [typographydocs/opentype/spec/otff.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otff.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
References to tools (from MS or anyone) don't belong in the OT spec.

**Comment by PeterCon** [comment]
Fixed for next version:

><del>A tool is available from Microsoft to help build .TTC files. The process involves paying</del><ins>When building a collection file from separate font files,</ins> close attention <ins>must be paid to </ins>the issue of glyph renumbering in a font and the side effects that can result, in the &#39;cmap&#39; table and elsewhere.
