### ISSUE TITLE
Remove long explanation of fvar

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#516]
> The 'fvar' table defines a range of design variations supported by a font — the font’s variation space. It specifies certain axes of variation that are used, and a range of supported values for each axis using scales appropriate to the nature of each axis. When processing a font’s variation data to derive glyph outlines or other values for a particular variation instance, the coordinates selected by the user must be mapped from the scales that are used to define the axes in the 'fvar' table to a normalized scale that is the same for every axis.
> A default normalization mapping is defined that maps the minimum, default and maximum values specified for each axis in the 'fvar' table to -1, 0, and 1, respectively, and that maps other values in between by linear interpolation between those values. The default mapping can be represented by the following pseudo-code.

A long explanation of how the fvar table works belongs in the fvar table chapter, but probably not in the avar table chapter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06ab9f03-9923-3400-5ae2-b650dcf7fb83
* Version Independent ID: 8b1c2a74-1f8e-cfc3-6472-36727c362e71
* Content: [avar — Axis variations table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/avar)
* Content Source: [typographydocs/opentype/spec/avar.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/avar.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Revised for the next version.

Some reference to fvar and axis scales/ranged defined there must be kept since avar must be explained in terms of how it fits into the normalization process of mapping "user" coordinates as described in fvar into normalized coordinates as used in the variation data.
