### ISSUE TITLE
Move "Processing" section

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#517]
In general, there is a problem throughout the spec of interleaving *file format specification* and *implementation directions*. These two things should be separated, as having them interleaved results in implementation notes being scattered over multiple chapters, instead of being readily accessible in one place and describing a joined-up process that implementors need to follow.

The details of how to normalize axes using the avar table should be moved into a chapter which describes the whole process of transforming points for variable fonts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 06ab9f03-9923-3400-5ae2-b650dcf7fb83
* Version Independent ID: 8b1c2a74-1f8e-cfc3-6472-36727c362e71
* Content: [avar — Axis variations table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/avar)
* Content Source: [typographydocs/opentype/spec/avar.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/avar.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
@simoncozens I have a draft of this change. It's too big to reflect here, but have generated PDFs from the markdown. Please take a look; within otvaroverview.pdf, the relevant changes are on pages 12 to 14 of the PDF. 

[otvaroverview.pdf](https://github.com/MicrosoftDocs/typography-issues/files/5139696/otvaroverview.pdf)
[avar.pdf](https://github.com/MicrosoftDocs/typography-issues/files/5139661/avar.pdf)

A problem created by moving the details out of the Processing section of the avar chapter is that there are no longer those details to refer to when considering the example in the following section. The example could get moved into the otvaroverview chapter, but normally examples are kept near the data structures they exemplify—though I guess the example is of the data and the processing.

Anyway, comments on this draft are invited.

**Comment by PeterCon** [comment]
Change for next version: moved description of normalization process and following example into the normalization section in otvaroverview.
