### ISSUE TITLE
Ambiguous language system tag: 'CPP '

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#52]
'CPP ' is named “Creoles” and corresponds to the ISO 639 code cpp, which is specifically for “Portuguese-based creoles and pidgins”. If 'CPP ' is intended to map only to cpp, the name “Creoles” is too broad; otherwise, there are many other ISO 639 codes it should map to too.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662c6f54-f90c-52ed-dca2-0f0a0a49fee5
* Version Independent ID: 6aa33924-d45e-60c3-a9fd-e317ff662993
* Content: [Language system tags - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags)
* Content Source: [typographydocs/opentype/spec/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/languagetags.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
It's impossible to know what was intended when this tag was registered, other than multiple creole languages. Mappings will be added for crp, cpe and cpf.
