### ISSUE TITLE
Incorrect ISO 639 mappings for 'FNE ' and 'TNE '

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#53]
'FNE ' and 'TNE ' (Forest Nenets and Tundra Nenets) are mapped to the ISO 639 codes enf and enh (Forest Enets and Tundra Enets). Confusingly, Nenets and Enets are different languages, each with a forest and a tundra variety. Nenets’s varieties don’t have distinct ISO 639 codes, so 'FNE ' and 'TNE ' should both be mapped to yrk (Nenets).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662c6f54-f90c-52ed-dca2-0f0a0a49fee5
* Version Independent ID: 6aa33924-d45e-60c3-a9fd-e317ff662993
* Content: [Language system tags - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags)
* Content Source: [typographydocs/opentype/spec/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/languagetags.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
It's impossible to know for certain what these language system tags were originally registered for. It seems unlikely that there's an actual need to make typographic distinctions between any of these, so getting these "right" doesn't seem like a high priority. A mapping to "yrk" will be added for each.
