### ISSUE TITLE
add entries for 'chws', 'vchw'

### ISSUE THREAD

**Issue by PeterCon** [MicrosoftDocs/typography-issues#535]
Amendment 1 of ISO/IEC 14496-22:2019 adds entries for two new feature tags:

'chws' Contextual Half-width Spacing
'vchw' Vertical Contextual Half-width Spacing

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b624d059-5498-9f87-7be3-8ab01aaf3b89
* Version Independent ID: cc92acc8-d227-09e4-a1eb-140d185308e5
* Content: [Registered features - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/featurelist)
* Content Source: [typographydocs/opentype/spec/featurelist.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/featurelist.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Issue in OFF wording:
>When using the [GPOS] type 2 lookup on a run of glyphs, it’s critical to remember to not consume the last glyph, but to keep it available as the first glyph in a subsequent run (this is a departure from normal lookup behavior).

This seems to contradict the spec for how lookup processing is done, which doesn't allow for any feature-specific processing differences.

It turns out this wording was copied from 'kern' and 'vkrn' feature descriptions. Looking into history, the wording wasn't in the TTO feature registry, but was added some time before OT 1.4.

I got feedback leading me to conclude that what was intended was actually not something for application / layout engine implementers to do as currently suggested by the text in question being in the “Application interface” portion of the feature descriptions. Rather, it appears what was likely intended was guidance to font implementations: when crafting type 2 lookups for ‘kern’/’vkrn’/’chws’/’vchw’, make sure to have the valueFormat2 field set to 0 so that the second glyph is not “consumed” as the lookup is processed over the glyph sequence but becomes the “next” glyph (first glyph for the next pair in the sequence. Otherwise, only every other pair of glyphs can be kerned.

**Comment by PeterCon** [comment]
Using revised wording for *Recommended implementation* and *Application interface* sections of 'kern' etc. feature descriptions:

> *Recommended implementation:* The font stores a set of adjustments for pairs of glyphs (GPOS lookup type 2 or 8). These may be stored as one or more tables matching left and right classes, &/or as individual pairs. Additional adjustments may be provided for larger sets of glyphs (e.g. triplets, quadruplets, etc.) to overwrite the results of pair kerns in particular combinations.
>
> <ins>When using a GPOS type 2 lookup, it is recommended that no positioning adjustment be applied to the second glyph in a pair. (That is, that valueFormat2 be set to 0.) As a result, the next glyph pair to be processed after the lookup has been applied to this pair will start at the second glyph. In this way, every glyph in a sequence can undergo positioning adjustment as the first glyph in a pair. Otherwise, if positioning of the second glyph is adjusted, then the next glyph pair to be processed will begin with the glyph following the second glyph. That will result in kerning adjustment happening only for every *other* pair of glyphs.</ins>
>
> *Application interface:* The application passes a sequence of GIDs to the &#39;kern&#39; table, and gets back adjusted positions (XPlacement, XAdvance, YPlacement and YAdvance) for those GIDs.<del> When using the type 2 lookup on a run of glyphs, it’s critical to remember to not consume the last glyph, but to keep it available as the first glyph in a subsequent run (this is a departure from normal lookup behavior).</del>

**Comment by NorbertLindenberg** [comment]
It seems that the new paragraph doesn't belong to the feature descriptions, but to the GPOS lookup type 2 description (as a note). That description states that “if valueFormat2 is set to 0, then the second glyph of the pair is the “next” glyph for which a lookup should be performed” or similar, but it’s easy to miss the significance of that.

**Comment by PeterCon** [comment]
The spec for GPOS lookup type 2 already states this.  

This is correcting the misleading description for these features suggesting that a client needs to use special-case lookup processing when processing these particular features, which definitely is wrong. The change could have been reduced to only deleting the second sentence in the *Application interface* section. But the feature descriptions that had been submitted were intending to provide guidance on how to implement so that each glyph pair could get kerned rather than only every other glyph pair. There's no reason to remove that guidance; it's just moved into the appropriate section, *Recommended implementation* and worded is a way that avoids jargon like "consuming" glyphs.

**Comment by PeterCon** [comment]
Fixed for next version.

**Comment by PeterCon** [comment]
See #536 for latest draft for 'chws. See #538 for latest draft for 'vchw'.

Review feedback applicable to both can be provided here.
