### ISSUE TITLE
Add entry for 'chws'

### ISSUE THREAD

**Issue by PeterCon** [MicrosoftDocs/typography-issues#536]
Amendment 1 of ISO/IEC 14496-22:2019 adds the 'chws' feature:

**Friendly name:** Contextual Half-width Spacing
**Registered by:** Adobe/W3C
﻿
**Function:** Contextually respaces glyphs designed to be set on full-em widths, fitting them onto individual
half-width horizontal widths, to approximate more sophisticated text layout, such as what is described
in Requirements for Japanese Text Layout (JLREQ [21]) or similar CJK text-layout specifications that
expect half-width forms of characters whose default glyphs are full-width. This differs from 'halt' in
that the respacing is contextual. This feature may be invoked to get better fit for punctuation or symbol
glyphs without disrupting the monospaced alignment, such as for UIs or terminal apps.

**Example:** When FULLWIDTH RIGHT PARENTHESIS (U+FF09; ")") is followed by IDEOGRAPHIC COMMA
(U+3001; "、"), the latter is respaced to remove half-em of width between them.

**Recommended implementation:** The font stores a set of adjustments for pairs of glyphs (GPOS lookup type
2 or 8). These may be stored as one or more tables matching left and right classes, &/or as individual
pairs. Additional adjustments may be provided for larger sets of glyphs (e.g. triplets, quadruplets, etc.)
to overwrite the results of pair kerns in particular combinations.

**Application interface:** The application passes a sequence of GIDs to the 'chws' table, and gets back
adjusted positions (XPlacement, XAdvance, YPlacement, and YAdvance) for those GIDs. When using the
type 2 lookup on a run of glyphs, it’s critical to remember to not consume the last glyph, but to keep it
available as the first glyph in a subsequent run (this is a departure from normal lookup behaviour).

**UI suggestion:** This feature would be off by default.

**Script/language sensitivity:** Used mostly in CJKV fonts.

**Feature interaction:** This feature is mutually exclusive with all other glyph-width features (e.g., 'fwid',
'halt', 'hwid', 'palt', 'pwid', 'qwid', 'twid'), which should be turned off when this feature is applied. It
deactivates the 'kern' feature. See also 'vchw'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4da11419-0864-96ff-7f67-296680843fc1
* Version Independent ID: 1d46dac1-d559-ce3e-2f6f-f47cf8cd9e0f
* Content: [Registered features, a-e - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae)
* Content Source: [typographydocs/opentype/spec/features_ae.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_ae.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
See also #535

**Comment by PeterCon** [comment]
In this entry, use "re-space" instead of "respace".

**Comment by PeterCon** [comment]
Investigate this part further:

"it’s critical to remember to not consume the last glyph, but to keep it
available as the first glyph in a subsequent run (this is a departure from normal lookup behaviour)."

**Comment by PeterCon** [comment]
Changed for next version.

**Comment by PeterCon** [comment]
Here's the current draft (not yet updated wrt #601):

>## <a name="chws" id="chws"></a><ins>Tag: &#39;chws&#39;</ins>
>
><ins>*Friendly name:* Contextual Half-width Spacing</ins>
>
><ins>*Registered by:* Adobe/W3C</ins>
>
><ins>*Function:* Contextually re-spaces glyphs designed to be set on full-em widths, fitting them onto individual half-width horizontal widths, to approximate more sophisticated text layout, such as what is described in [Requirements for Japanese Text Layout (JLREQ)][1] or similar CJK text-layout specifications that expect half-width forms of characters whose default glyphs are full-width. This differs from [&#39;halt&#39;](features_fj.md#halt) in that the re-spacing is contextual. This feature may be invoked to get better fit for punctuation or symbol glyphs without disrupting the monospaced alignment, such as for UIs or terminal apps.</ins>
>
><ins>*Example:* When FULLWIDTH RIGHT PARENTHESIS (U+FF09; “)”) is followed by IDEOGRAPHIC COMMA (U+3001; “、”), the latter is re-spaced to remove half-em of width between them.</ins>
>
><ins>*Recommended implementation:* The font stores a set of adjustments for pairs of glyphs (GPOS lookup type 2 or 8). These may be stored as one or more tables matching left and right classes, and/or as individual pairs. Additional adjustments may be provided for larger sets of glyphs (e.g. triplets, quadruplets, etc.) to overwrite the results of pair kerns in particular combinations.</ins>
>
><ins>When using a GPOS type 2 lookup for this feature, it is recommended that no positioning adjustment be applied to the second glyph in a pair. (That is, that valueFormat2 be set to 0.) As a result, the next glyph pair to be processed after the lookup has been applied to this pair will start at the second glyph. In this way, every glyph in a sequence can undergo positioning adjustment as the first glyph in a pair. Otherwise, if positioning of the second glyph is adjusted, then the next glyph pair to be processed will begin with the glyph following the second glyph. That will result in spacing adjustment happening only for every *other* pair of glyphs.</ins>
>
><ins>*Application interface:* The application passes a sequence of GIDs to the &#39;chws&#39; table, and gets back adjusted positions (XPlacement, XAdvance, YPlacement, and YAdvance) for those GIDs.</ins>
>
><ins>*UI suggestion:* This feature should be off by default.</ins>
>
><ins>*Script/language sensitivity:* Used mostly in CJKV fonts.</ins>
>
><ins>*Feature interaction:* This feature is mutually exclusive with all other glyph-width features (e.g., [&#39;fwid&#39;](features_fj.md#fwid), [&#39;halt&#39;](features_fj.md#halt), [&#39;hwid&#39;](features_fj.md#hwid), [&#39;palt&#39;](features_pt.md#palt), [&#39;pwid&#39;](features_pt.md#pwid), [&#39;qwid&#39;](features_pt.md#qwid), [&#39;twid&#39;](features_uz.md#twid)), which should be turned off when this feature is applied. It deactivates the [&#39;kern&#39;](features_ko.md#kern) feature. See also [&#39;vchw&#39;](features_uz.md#wchw).</ins>

**Comment by sairuspatel** [comment]
Shouldn't "latter" be "former" in your current draft, @PeterCon, in order to allow for the recommendation that no pos adjustment bet applied to the second glyph in a pair? I'm also checking with Ken Lunde.

**Comment by PeterCon** [comment]
What you say seems to make sense. I didn't review the example but just took that part of the text directly from what is in OFF, which I assume would be what Ken had provided.

**Comment by PeterCon** [comment]
Based on feedback and additional information provided by Koji Ishi, I've revised the draft as follows:

><ins>*Friendly name:* Contextual Half-width Spacing</ins>
>
><ins>*Registered by:* Adobe/W3C</ins>
>
><ins>*Function:* Contextually re-spaces glyphs designed to be set on full-em widths, fitting them onto individual half-width horizontal widths, to approximate more sophisticated text layout, such as what is described in [Requirements for Japanese Text Layout (JLREQ)][1] or similar CJK text-layout specifications that expect half-width forms of characters whose default glyphs are full-width.\* This differs from [&#39;halt&#39;](features_fj.md#halt) in that the re-spacing is contextual. This feature may be invoked to get better fit for punctuation or symbol glyphs without disrupting the monospaced alignment, such as for UIs or terminal apps.</ins>
>
><ins>\* In JLREQ, see, in particular, [3.1.4 Positioning of Consecutive Opening Brackets, Closing Brackets, Commas, Full Stops and Middle Dots][2] and [B. Spacing between Characters][3]. See also [Requirements for Chinese Text Layout (CLREQ)][4], [Requirements for Hangul Text Layout (KLREQ)][5].</ins>
>
><ins>*Example:* When FULLWIDTH RIGHT PARENTHESIS (U+FF09; “)”) is followed by IDEOGRAPHIC COMMA (U+3001; “、”), the former is re-spaced to remove half-em of width between them.</ins>
>
><ins>*Recommended implementation:* The font stores a set of adjustments for pairs of glyphs (GPOS lookup type 2 or 8, , XPlacement, XAdvance, YPlacement, and YAdvance). These may be stored as one or more tables matching left and right classes, and/or as individual pairs. Additional adjustments may be provided for larger sets of glyphs (e.g. triplets, quadruplets, etc.) to overwrite the results of pair kerns in particular combinations.</ins>
>
>> <ins>*Note:* When using a GPOS type 2 lookup for this feature, it is recommended that no positioning adjustment be applied to the second glyph in a pair. (That is, that valueFormat2 be set to 0.) As a result, the next glyph pair to be processed after the lookup has been applied to this pair will start at the second glyph. In this way, every glyph in a sequence can undergo positioning adjustment as the first glyph in a pair. Otherwise, if positioning of the second glyph is adjusted, then the next glyph pair to be processed will begin with the glyph following the second glyph. That will result in spacing adjustment happening only for every *other* pair of glyphs.</ins>
>
><ins>*Application interface:* If a layout engine supports advanced layout for CJK text as described in [CLREQ][4], [JLREQ][1] or [KLREQ][5], this feature should not be used. Otherwise, this feature should always be applied in horizontal layout of CJK text.</ins>
>
><ins>*UI suggestion:* This feature should not be used in combination with a layout engine that independently provides advanced layout as described in [CLREQ][4], [JLREQ][1] or [KLREQ][5]. For applications that provide such advanced layout, it may appropriate not to expose control of this feature to users. In applications that do not support such advanced layout, this feature should be enabled by default for horizontal layout of CJK text.</ins>
>
><ins>*Script/language sensitivity:* Used mostly in CJKV fonts.</ins>
>
><ins>*Feature interaction:* This feature is mutually exclusive with all other glyph-width features (e.g., [&#39;fwid&#39;](features_fj.md#fwid), [&#39;halt&#39;](features_fj.md#halt), [&#39;hwid&#39;](features_fj.md#hwid), [&#39;palt&#39;](features_pt.md#palt), [&#39;pwid&#39;](features_pt.md#pwid), [&#39;qwid&#39;](features_pt.md#qwid), [&#39;twid&#39;](features_uz.md#twid)), which should be turned off when this feature is applied. It deactivates the [&#39;kern&#39;](features_ko.md#kern) feature. See also [&#39;vchw&#39;](features_uz.md#wchw).</ins>
