### ISSUE TITLE
Unclear distinction between 'HYE ' and 'HYE0'

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#55]
'HYE ' (Armenian) and 'HYE0' (Armenian East) are both mapped to the ISO 639 code hye. What is the difference? My guess is that 'HYE ' is for Armenian in general, either eastern or western. In that case, 'HYE ' should be mapped to hye and hyw.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662c6f54-f90c-52ed-dca2-0f0a0a49fee5
* Version Independent ID: 6aa33924-d45e-60c3-a9fd-e317ff662993
* Content: [Language system tags - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags)
* Content Source: [typographydocs/opentype/spec/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/languagetags.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
A mapping to hyw will be added to 'HYE '.
