### ISSUE TITLE
Deprecated ISO 639 codes

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#56]
Some of these ISO 639 codes have been deprecated and split into more specific codes. The new codes should be added, keeping the deprecated codes as was done for 'ARK '.

* [bhk → fbl, lbl, rbl, ubl](https://iso639-3.sil.org/request/2009-078)
* [btb → beb, bum, bxp, eto, ewo, mct](https://iso639-3.sil.org/request/2009-032)
* [duj → dwu, dwy](https://iso639-3.sil.org/request/2015-053)
* [flm → cfm, rnl](https://iso639-3.sil.org/request/2006-023)
* [dap → njz, tgj](https://iso639-3.sil.org/request/2011-132)
* [xst → stv, wle](https://iso639-3.sil.org/request/2007-114)

One of btb’s replacements, fan, is already associated with a language system tag: 'FAN0'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662c6f54-f90c-52ed-dca2-0f0a0a49fee5
* Version Independent ID: 6aa33924-d45e-60c3-a9fd-e317ff662993
* Content: [Language system tags - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags)
* Content Source: [typographydocs/opentype/spec/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/languagetags.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Maintaining at this level of detail isn't a high priority, but thanks for providing the details. Adding in the next version.
