### ISSUE TITLE
Limit VariationRegionList.regionCount to < 32K

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#560]
To allow for future anticipated enhancements to support variation of Fixed or other 32-bit values, VariationRegionList.regionCount should be constrained to < 32K.

Background: for COLRv1, it is proposed that Fixed values can be variable. But Fixed is a 32-bit type. Currently, ItemVariationStore supports only 16-bit deltas. The proposed enhancement is that the high-order bit of ItemVariationData.shortDeltaCount be treated like a flag: if set, then the deltaSet[] array is comprised of 32-bit and 16-bit elements rather than 16-bit and 8-bit. See <https://github.com/googlefonts/colr-gradients-spec/issues/29> for more info.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc38f55-a142-6d66-fc68-1bb6e6e9ed56
* Version Independent ID: 0665d6f2-4150-1977-4fd6-91c50c226ed9
* Content: [OpenType Font Variations Common Table Formats - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otvarcommonformats#item-variation-store)
* Content Source: [typographydocs/opentype/spec/otvarcommonformats.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otvarcommonformats.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by behdad** [comment]
Sounds good. Make the `VariationRegionList.regionCount >= 32k` be Reserved, so we can use that bit in the future as well.

**Comment by PeterCon** [comment]
Make regionList >= 32K reserved? Or permanently constrain regionList to < 32K? I think we want the latter, no?

**Comment by behdad** [comment]
> Make regionList >= 32K reserved? Or permanently constrain regionList to < 32K? I think we want the latter, no?

By making regionList >= 32k reserved, instead of wasting a bit, we allow ourselves to use it in the future for other extensions.

**Comment by behdad** [comment]
> By making regionList >= 32k reserved, instead of wasting a bit, we allow ourselves to use it in the future for other extensions.

Same way that nameIDs are limited to 32k.

**Comment by PeterCon** [comment]
But if in the future we allow regionCount >= 32K, then wouldn't that will conflict with your proposal for using the high-order bit of shortDeltaCount to indicate 32-bit deltas?

IOW, aren't we in effect using the high-order bit in regionCount _now_?

**Comment by behdad** [comment]
> But if in the future we allow regionCount >= 32K...

That's not what I said. I want to have the option to use the highest-bit of regionCount being equal 1 for a future feature...

> IOW, aren't we in effect using the high-order bit in regionCount _now_?

No. We just are using high-bit of numShorts. That forces a limit on regionCount to be < 32K, which means the high bit of regionCount is unused and always 0.

In reality doesn't matter what you are proposing and what I am. Both say the high big of regionCount must be 0 according to current standard. A future version can always assign different semantic to high-bit==1.

Just do as you had planned. Thanks.

**Comment by PeterCon** [comment]
OK, now I understand the point you were making now. Thanks. I can say "reserved" for regionCount >= 32K.

**Comment by PeterCon** [comment]
Changed for next version.

In table describing VariationRegionList:
> <table><tr><td>uint16</td><td>regionCount</td><td>The number of variation region tables in the variation region list.<ins> Must be less than 32,768.</ins></td></tr></table>

Following the table:
> <ins>The high-order bit of the regionCount field is reserved for future use, and must be cleared. Applications may ignore the high-order bit if set.</ins>

**Comment by behdad** [comment]
> The high-order bit of the regionCount field is reserved for future use, and must be cleared. Applications may ignore the high-order bit if set.

The "ignore" part is problematic. Just saying `regionCount >= 32k` is reserved is enough.

**Comment by PeterCon** [comment]
Yeah, understand the concern. But what would the compat story be?

Suppose in OT v.next a semantic is defined for the high bit, and so fonts appear that have regionCount >= 32K. What should an app that supports only v.last do? Ignore the entire ItemVariationStore?

**Comment by PeterCon** [comment]
Revised change per feedback. Here's the current draft:

>*VariationRegionList:*
>
><table>
<tbody>

<tr>
<th>Type</th>
<th>Name</th>
<th>Description</th>
</tr>

<tr>
<td>uint16</td>
<td>axisCount</td>
<td>The number of variation axes for this font. This must be the same number as axisCount in the &#39;fvar&#39; table.</td>
</tr>

<tr>
<td>uint16</td>
<td>regionCount</td>
<td>The number of variation region tables in the variation region list.<ins> Must be less than 32,768.</ins></td>
</tr>

<tr>
<td>VariationRegion</td>
<td>variationRegions[regionCount]</td>
<td>Array of variation regions.</td>
</tr>

</tbody>
</table>

<ins>The high-order bit of the regionCount field is reserved for future use, and must be cleared.</ins>
