### ISSUE TITLE
Does WGL4 really belong in the OT spec?

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#561]
It doesn't seem appropriate to me that the OT spec would include data about some named character repertoires. That might have bearing for some vendor's font design requirements, or for support of particular scripts or languages. But it really has no bearing on specifying the font format.

Can WGL4 be removed from the spec? Does it need to be retained somewhere else instead (and, if so, where)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: aa41c886-9600-e8e8-22f9-df3c082d20ff
* Version Independent ID: 1688414c-bda3-07e5-001f-d68a5550baeb
* Content: [WGL4.0 Character Set - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/wgl4)
* Content Source: [typographydocs/opentype/spec/wgl4.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/wgl4.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
The MS-specific WGL4 content is now available elsewhere on the Microsoft Typgraphy site: <https://docs.microsoft.com/en-us/typography/develop/wgl4>. Hence, proposed draft for the next version will remove these pages from the OT spec.
