### ISSUE TITLE
Should lookup flags use CAP_SNAKE_CASE for consistency with other parts of the spec?

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#562]
Should lookup flags use CAP_SNAKE_CASE for consistency with other parts of the spec?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb42967-20ca-9270-4572-65315127fcc5
* Version Independent ID: 1fa413f1-71cf-ac2a-0999-70dd5d8ac4cd
* Content: [OpenType layout common table formats - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/chapter2)
* Content Source: [typographydocs/opentype/spec/chapter2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/chapter2.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Scanned across OT spec for other instances. Most chapters use CAP_SNAKE_CASE or (e.g., 'head') just describe a bit without giving a name. Only other instances:

* MATH: "fExtender"

**Comment by PeterCon** [comment]
Proposed changes for next version:

chapter2:

* Changed LookupFlag names:
  * “rightToLeft” to “RIGHT_TO_LEFT”
  * “ignoreBaseGlyphs” to “IGNORE_BASE_GLYPHS”
  * “ignoreLigatures” to “IGNORE_LIGATURES”
  * “ignoreMarks” to “IGNORE_MARKS”
  * “useMarkFilteringSet” to “USE_MARK_FILTERING_SET”
  * “markAttachmentType” to “MARK_ATTACHMENT_TYPE_MASK”

math:
* Changed flag name “fExtender” to “EXTENDER_FLAG”.

Mentions in other chapters changed accordingly.
