### ISSUE TITLE
image order issue

### ISSUE THREAD

**Issue by amlogu** [MicrosoftDocs/typography-issues#563]
In image 1-8 of the page has a image order [changed...](url)

![image](https://user-images.githubusercontent.com/18044413/91569880-8aec5680-e963-11ea-9476-fcd07c72c626.png)
----------------------------
First img should come, second;
Second img should come, first;
----------------------------

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c1e0369-7235-11e6-d1ef-f0a57fca7588
* Version Independent ID: 78d6c664-b275-f986-5374-c3d01ef3ccb2
* Content: [TrueType fundamentals - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/ttch01)
* Content Source: [typographydocs/opentype/spec/ttch01.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/ttch01.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
It appears this was changed for some reason at some point between TrueType 1.66 and OpenType 1.4.

**Comment by PeterCon** [comment]
Fixed for next version.
