### ISSUE TITLE
MARTEN

### ISSUE THREAD

**Issue by kme2300** [MicrosoftDocs/typography-issues#564]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1b85c199-c5b8-50cc-1733-60f4cc7fce43
* Version Independent ID: f29de214-2597-5e3a-c2ec-8c55f509c558
* Content: [Andy font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/andy)
* Content Source: [typographydocs/font-list/andy.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/andy.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
This no feedback just the title says “MARTEN” I am not sure what this means.

**Comment by PeterCon** [comment]
No actionable feedback, so closing.
