### ISSUE TITLE
OT variations: need an explicit way to indicate that an item has no variation

### ISSUE THREAD

**Issue by PeterCon** [MicrosoftDocs/typography-issues#569]
See discussion at <https://github.com/googlefonts/colr-gradients-spec/issues/31>. 

Make an index pair ffff/ffff the means to indicate no variation.

**Comment by PeterCon** [comment]
Cf #560

**Comment by PeterCon** [comment]
Proposed change in otvarcommonformats:

><ins>A complete delta-set index involves an outer-level index into the ItemVariationData subtable array, plus an inner-level index to a delta-set row within that subtable. A special meaning is assigned to a delta-set index 0xFFFF/0xFFFF (that is, outer-level and inner-level portions are both 0xFFFF): this is used to indicate that there is no variation data for a given item. Functionally, this would be equivalent to referencing delta-set data consisting of only deltas of 0 for all regions.</ins>
>
><del>A complete delta-set index involves an outer-level index into the itemVariationData subtable array, plus an inner-level index to a delta-set row within that subtable. </del>As noted above, delta-set indices are stored outside the variation store. Different parent tables that use an item variation store will store indices in different ways, and may utilize different schemes for how to represent the indices in an efficient manner. For example, the HVAR and VVAR tables allow the outer and inner indices to be combined into one-byte, two-byte, three-byte or four-byte representations depending on the indexing requirements of the variation store. For larger sets of variation data, such as may be needed for HVAR or VVAR tables, optimization of the indices data as well as the delta data may have a significant impact on overall size. Optimizing compilers may need to consider the impact on representation of indices in tandem as it optimizes the item variation store to achieve the best overall results.

**Comment by PeterCon** [comment]
Proposed change in mvar:

>><ins>Note: deltaSetOuterIndex = 0xFFFF and deltaSetInnerIndex = 0xFFFF can be used to indicate an item has no variation. However, this means should not be used to indicate that an item does not vary. Rather, a ValueRecord for that item should be omitted.</ins>

**Comment by PeterCon** [comment]
Proposed change in hvar (at the end of the Table Formats section):

><ins>Note that outerIndex = 0xFFFF and innerIndex = 0xFFFF can be used to indicate that a value does not vary. Functionally, this is equivalent to referencing delta-set data consisting of only deltas of 0 for all regions. Optimizing compilers may choose either means to achieve the best results.</ins>

**Comment by PeterCon** [comment]
The VVAR chapter has info specific to VVAR but otherwise refers to the HVAR chapter for details that are common to both. The note mentioned above proposed for addition to the HVAR chapter could also be added to the VVAR chapter, but that seems unnecessary given that common info is covered in the HVAR chapter.

**Comment by PeterCon** [comment]
Proposed change in the BASE chapter—additional note added after the exiting notes in the section for BaseCoord Format 3:

>><ins>*Note:* A VariationIndex table with deltaSetOuterIndex = 0xFFFF and deltaSetInnerIndex = 0xFFFF can be used to indicate that a value has no variation. However, this means should not be used to indicate that an item does not vary. Instead, a font should not include a VariationIndex table for the given value.</ins>

**Comment by PeterCon** [comment]
Proposed change in chapter2 (OTL common formats): at the end of the Device and VariationIndex Tables section, add the same note as added in the BASE chapter.

**Comment by PeterCon** [comment]
Proposed change in the GDEF chapter: add the same note added in the BASE chapter after the existing notes in the section for CaretValue Format 3.

**Comment by PeterCon** [comment]
Changes made for next version; see seven preceding comments.

**Comment by behdad** [comment]
No to all those proposed notes in BASE / OTL.

**Comment by PeterCon** [comment]
Depending on the parent table context, there will be two or three ways to achieve the same result. You're suggesting that the spec doesn't need to say anything about the alternatives and just leave it to tool developers to figure out which is most efficient?

**Comment by behdad** [comment]
> Depending on the parent table context, there will be two or three ways to achieve the same result. You're suggesting that the spec doesn't need to say anything about the alternatives and just leave it to tool developers to figure out which is most efficient?

Exactly.

You don't find the PNG spec or Brotli spec or any other spec trying to tell an optimizing compiler what to do...

**Comment by behdad** [comment]
Let alone that in OTL tabless, also in BASE I think, the most efficient way does not encode a variation-index at all. That's why initially I just opposed adding comments to those tables.

**Comment by PeterCon** [comment]
>the most efficient way does not encode a variation-index at all.

That's what the comments added in the other tables were pointing out: don't do that!

**Comment by PeterCon** [comment]
Based on review feedback, removed notes added to base, chapter2, gdef, hvar, mvar.
