### ISSUE TITLE
Dead links to briem.ismennt.is

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#57]
The links to http://briem.ismennt.is/ are dead. This is also the case on the page about uppercase letters.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13ec3a41-7b20-98ea-109d-ff22ddc6b126
* Version Independent ID: 8471196e-2ba6-627f-4c50-e026474b7a7b
* Content: [Character design standards - Lowercase for Latin 1 - Typography](https://docs.microsoft.com/en-us/typography/develop/character-design-standards/lowercase)
* Content Source: [typographydocs/develop/character-design-standards/lowercase.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/develop/character-design-standards/lowercase.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment]
Closing As Fixed
