### ISSUE TITLE
In TTC header, consider renaming "offsetTable" to "offsetTableOffsets"

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#570]
"offsetTable[]" in TTC header should be "offsetTableOffsets[]" to be consistent with spec naming conventions

If the offset table were renamed / more consistently referred to as "TableDirectory" (as suggested in other discussions), then this should be renamed to "tableDirectoryOffsets".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a1bda96-a268-b684-6cea-9b0c7be6f24e
* Version Independent ID: 36485fec-f05d-3984-6da8-ff2dd2799041
* Content: [OpenType font file - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otff)
* Content Source: [typographydocs/opentype/spec/otff.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otff.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Cf. #572

**Comment by PeterCon** [comment]
Changed for next version.
