### ISSUE TITLE
Missing ISO 639 code: den (Slavey)

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#579]
The ISO 639 codes associated with 'SLA ' (Slavey) are scs and xsl (North Slavey and South Slavey). It should also be associated with den, the code for the Slavey macrolanguage. den should also be associated with 'ATH ' (Athapaskan) which already lists scs and xsl.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662c6f54-f90c-52ed-dca2-0f0a0a49fee5
* Version Independent ID: 6aa33924-d45e-60c3-a9fd-e317ff662993
* Content: [Language system tags - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags)
* Content Source: [typographydocs/opentype/spec/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Can you please clarify the changes you think should be made: for which OT lang sys tags should what 639 associations be added/removed?

**Comment by dscorbett** [comment]
For 'SLA ', add den. For 'ATH ', add den.

**Comment by PeterCon** [comment]
Thanks.

**Comment by PeterCon** [comment]
Changed for next version.
