### ISSUE TITLE
Incorrect definition of 'med2'

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#58]
The description of 'med2' does not match its description in [the Syriac script development page](https://docs.microsoft.com/en-us/typography/script-development/syriac#medial-form-2) or its implementation in Uniscribe. It currently says:

> _Function:_ Replaces Alaph glyphs in the middle of Syriac words when the preceding base character cannot be joined to.
>
> _Example:_ When an Alaph is preceded by a Waw, the Alaph would be replaced by an appropriate form.

It should say:

> _Function:_ Replaces Alaph glyphs in the middle of Syriac words when the preceding base character can be joined to.
>
> _Example:_ When an Alaph is preceded by a Heth, the Alaph would be replaced by an appropriate form.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a9106c-ca98-1891-2c00-ace78615994f
* Version Independent ID: 0feefbc8-23a7-5bc8-76dc-0a336a1c7968
* Content: [Registered features, k-o - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ko)
* Content Source: [typographydocs/opentype/spec/features_ko.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_ko.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Contradictory statements, so clearly a problem. I suspect you are correct, but this can't be deduced simply by looking at how text displays with a certain font since it's not clear what lookups within the font actually led to that display.

**Comment by PeterCon** [comment]
Fixed for the next version.
