### ISSUE TITLE
explanation of alpha is missing

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#581]
The SVG table spec clarifies how the alpha member of CPAL color record is to be interpreted:

"CPAL alpha values are in the range 0 to 255, where 0 is fully transparent and 255 is fully opaque."

This isn't stated in the CPAL chapter. It should be.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 649f6376-f113-0a6f-d633-37ed967d8c29
* Version Independent ID: 043109db-6c34-6c15-b4fb-6280b5131fcc
* Content: [CPAL - Color Palette Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/cpal)
* Content Source: [typographydocs/opentype/spec/cpal.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cpal.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Changed for next version:

>The colors in the Color Record should not be pre-multiplied, and the alpha value should be explicitly set for each palette entry.
>
><ins>An alpha value of zero means no opacity (fully transparent); 255 means opaque (no transparency). Note that the alpha value in the color record can be combined with and does not supersede alpha or opacity attributes set in higher-level contexts.</ins>
