### ISSUE TITLE
Recommendations for 'ljmo', 'vjmo', and 'tjmo' contradict the Hangul script development spec

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#585]
'ljmo' is documented thus:

> _Recommended implementation:_ The 'ljmo' table maps the sequence required to convert a series of jamos into its leading jamo form (GSUB lookup type 4).

'vjmo' and 'tjmo' are documented similarly. This contradicts [the Hangul script development spec](https://docs.microsoft.com/en-us/typography/script-development/hangul), where 'ccmp' is responsible for converting a sequence of simple jamo into a single complex jamo (e.g. <pieup, sios, thieuth> into pieup_sios_thieuth), and 'ljmo', 'vjmo', and 'tjmo' are recommended for contextually replacing single jamo glyphs. I suggest:

> _Recommended implementation:_ The 'ljmo' table maps a jamo into its leading jamo form (GSUB lookup type 5).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a9106c-ca98-1891-2c00-ace78615994f
* Version Independent ID: 0feefbc8-23a7-5bc8-76dc-0a336a1c7968
* Content: [Registered features, k-o - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ko)
* Content Source: [typographydocs/opentype/spec/features_ko.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_ko.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Similar issues for 'vjmo' and 'tjmo'.

**Comment by PeterCon** [comment]
I don't think type 5 should be mentioned: an implementation might do contextual analysis in a shaping engine vs. doing contextual analysis in lookups. The general philosophy in the original OT design was don't repeat in fonts logic that would be common across fonts. Either way, that should be sorted out in a shaping spec.

**Comment by PeterCon** [comment]
Actually, type 5 (or perhaps 6) is really going to be needed (if nothing else, forms for LV vs. LVT syllables need to be distinguished). But I don't think it needs to be prescribed here.

**Comment by PeterCon** [comment]
Changed for next version:

'ljmo':
>*Recommended implementation:* The &#39;ljmo&#39; table maps <del>the sequence required to convert a series of jamos into its leading jamo form (GSUB lookup type 4)</del><ins>a default glyph for a leading jamo into into the form required for conjoining in a syllable</ins>.

'tjmo':
>*Recommended implementation:* The &#39;tjmo&#39; table maps <del>the sequence required to convert a series of jamos into its trailing jamo form (GSUB lookup type 4)</del><ins>a default glyph for a trailing jamo into into the form required for conjoining in a syllable</ins>.

'vjmo':
>*Recommended implementation:* The &#39;vjmo&#39; table maps <del>the sequence required to convert a series of jamos into its vowel jamo form (GSUB lookup type 4)</del><ins>a default glyph for a vowel jamo into the form required for conjoining in a syllable</ins>.
