### ISSUE TITLE
'KOH ' should be mapped to both Middle and Modern Korean

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#588]
'KOH ' (Korean Old Hangul) is associated with the ISO 639 code okm (Middle Korean). It should additionally be associated with the ISO 639 code kor (Korean).

In [the Hangul script development spec](https://docs.microsoft.com/en-us/typography/script-development/hangul), “Old Hangul” refers to any use of Hangul that cannot be represented using precomposed syllable blocks. This includes Korean as it was written up to the twentieth century, well after the end of Middle Korean. I find it more plausible that 'KOH ' was originally intended as a (completely unnecessary) OTLS-aware version of 'KOR ' than that Microsoft thought that a font might need to distinguish Middle Korean from Modern Korean.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662c6f54-f90c-52ed-dca2-0f0a0a49fee5
* Version Independent ID: 6aa33924-d45e-60c3-a9fd-e317ff662993
* Content: [Language system tags - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags)
* Content Source: [typographydocs/opentype/spec/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Sounds very plausible and likely. 

Would it help anything to make that change, though?

**Comment by dscorbett** [comment]
It would help fonts that use the tag 'KOH ' but not 'KOR ', where all the font’s lookups needed for Korean are associated only with 'KOH ' and not the default language system.

**Comment by PeterCon** [comment]
I'll buy that. Changing for the next version.
