### ISSUE TITLE
ISO 639 "cnr" should be mapped to 'SRB '

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#590]
Montenegrin (ISO 639 code "cnr") is a variety of Serbian. Since it doesn’t have its own language system tag, "cnr" should be mapped to 'SRB ' (Serbian).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662c6f54-f90c-52ed-dca2-0f0a0a49fee5
* Version Independent ID: 6aa33924-d45e-60c3-a9fd-e317ff662993
* Content: [Language system tags - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags)
* Content Source: [typographydocs/opentype/spec/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Hmmm... People that insisted that ISO 639 needed to code "Montenegrin" as distinct from "Serbian" might disagree. Should 'SRB ' be mapped to cnr, or should a separate language system tag be created?

**Comment by dscorbett** [comment]
I don’t think it’s necessary, unless there is some evidence that the two varieties have different glyph preferences, though it wouldn’t be wrong to create a new tag. A benefit of mapping it to 'SRB ' is that it is easier to update shaping engines to map "cnr" to 'SRB ' than it is to update all fonts that use 'SRB ' to also use 'CNR '. I leave it to you; my main concern is that it be mapped to something, because otherwise text tagged as Montenegrin will end up using the default (probably Russian) glyphs.

**Comment by PeterCon** [comment]
I don't have any strong opinion on this issue beyond that reasonable/relevant alternatives have been considered. Your rationale makes sense to me.

Changing for next version.
