### ISSUE TITLE
DSIG checksum in TTCHeader??

### ISSUE THREAD

**Issue by PeterCon** [MicrosoftDocs/typography-issues#593]
The DSIG chapter states:

>The DSIG table for a TrueType Collection (TTC) must be the last table in the TTC file. The offset and checksum to the table is put in the TTCHeader (version 2).

The DSIG offset is in the TTC header, but there is no field for the DSIG checksum in the current spec.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acf0601c-2dd5-c94c-8860-07e9def0c20c
* Version Independent ID: c69a8340-3140-31cf-d27b-c0e2b235ccc6
* Content: [DSIG — Digital signature table specification - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/dsig)
* Content Source: [typographydocs/opentype/spec/dsig.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/dsig.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by HinTak** [comment]
Argh, yes. That appears to be an oversight: for non-collections, there is a checksum in the head table, just like any other opentype table. That's not in practice a problem, as (except for an empty skeleton dsig) the content of dsig itself is cryptographically made so it is almost self-checksum'ing in the sense that any kind of change invalidates the signature, so a checksum is not needed.

Btw, I mentioned a few times that the microsoft signing tool does not check the ttc header being v2 before signing. (there are/were Microsoft signed and shipped fonts on windows which has a v1 header with dsig).

**Comment by PeterCon** [comment]
That paragraph was added in OT 1.4, for some reason mentioning a DSIG checksum. MS confirmed it's a spurious reference.

Changing for next version:
>The DSIG table for <del>a TrueType</del><ins>an OpenType</ins> Collection (TTC) must be the last table in the TTC file. The offset <del>and checksum </del>to the table is put in the TTCHeader (version 2). Signatures of TTC files are expected to be Format 1 signatures.
