### ISSUE TITLE
Typo: "Quenchua"

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#6]
In the “Macintosh language IDs” section, “Quenchua” should be “Quechua”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc5a9d9-70e1-97b3-6926-c176e1a2401d
* Version Independent ID: 1afb0f5b-d1a7-7d69-d175-a5c9382b74be
* Content: [name - Naming table specification - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/name)
* Content Source: [typographydocs/opentype/spec/name.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/name.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Thanks. This will be corrected in the next version (ETA is next week).
