### ISSUE TITLE
Which LookupType is the most powerful?

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#60]
These descriptions are contradictory:

> * _Contextual substitution,_ the most powerful type [...] A Contextual Substitution (ContextSubst) subtable defines the most powerful type of glyph substitution lookup
> * _Chaining contextual substitution,_ extends the capabilities of contextual substitution

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34e7df21-eb35-19ab-3573-e075872e5d3b
* Version Independent ID: 4656a3f9-95ea-15cc-25ed-6eccf7adf370
* Content: [GSUB — Glyph Substitution Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/gsub)
* Content Source: [typographydocs/opentype/spec/gsub.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gsub.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Fixed for the next version.

**Comment by dscorbett** [comment]
The section “LookupType 5: Contextual Substitution Subtable” still says “A Contextual Substitution (ContextSubst) subtable defines the most powerful type of glyph substitution lookup”.

**Comment by PeterCon** [comment]
Hmmm... I didn't catch that there were two different occurrences.
