### ISSUE TITLE
[cmap] What is the meaning of "symbol font"?

### ISSUE THREAD

**Issue by Lorp** [MicrosoftDocs/typography-issues#600]
The meaning of "symbol font" is not clear in the statement "When building a symbol font for Windows, the platform ID should be 3 and the encoding ID should be 0."

I assume it refers to the old 8-bit character set of MS Symbol, which (I think) used character IDs 32-255 without any 16-bit interlopers. In issue #269 (July 2019) about cmap subtable relevance, @behdad mentions ["hacky symbol fonts"](https://github.com/MicrosoftDocs/typography-issues/issues/269#issuecomment-512329328), presumably referring to the same thing. In any case, some attempt should be made in the ‘cmap’ spec to explain how to map arbitrary sets of graphics to Unicode codepoints, and to move away from the simplistic phrase "symbol font" since a valid font may have any number of symbols and any number of alphabetic characters.

PUA is the obvious place for arbitrary symbols of course, if there’s no relevant Unicode. Nevertheless builders of such fonts often want to add handy alphabetic keystrokes to their fonts. Which is hackier, the old-style 3/0 symbol fonts (which mapped A,B,C… to arbitrary glyphs) or pointing A,B,C… at arbitrary glyphs using 3/1?

It’s worth noting that there are popular counterexamples where "handy A,B,C mapping" is not used. For example, [FontAwesome](https://fontawesome.com/icons?d=gallery) publishes fonts that use PUA exclusively and offers mechanisms outside of the font (CSS classes) for handy usage.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86923ff4-2b60-9144-e2b4-77cdb36fd698
* Version Independent ID: ea221e53-f51a-8233-3c0b-d416e5360623
* Content: [cmap - Character To Glyph Index Mapping Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap)
* Content Source: [typographydocs/opentype/spec/cmap.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cmap.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
The Symbol encoding is... interesting. It was defined for TrueType outline fonts, not earlier bitmap fonts (though maybe some earlier fonts got ported to TT symbol-encoded fonts). I can't find any evidence that "symbol" fonts ever used anything but a format 4 cmap, even in the Windows 3.1x timeframe.

MS Office treats these in a very special way, which may well date to Word for DOS. Try this (it works in desktop Word on Windows, not sure about Mac):
1. enter into a new doc "F0A7" (without quotation marks), then press Alt+X (to convert to Unicode character U+F0A7).
2. format that text with the "Symbol" font
3. Result: you should see a club (playing card) symbol
4. On a new line, set the font to Calibri, enter "A7" (without quotation marks), then press Alt-X (to convert to Unicode character U+00A7).
5. Format that text with the Symbol font
6. Result: the club symbol
7. Check that you can select either of the characters entered above, press Alt-X, and that you'll get back the string "F0A7" (formatted with Symbol)
7. Using Words Insert > Symbol dialog, change the font to Symbol, locate and enter the club sign
8. Select that symbol and press Alt-X
9. Result: nothing: it won't give the underlying encoding of a _symbol_ entered from the Insert > Symbol dialog.

Now, in the font, the symbols are encoded using a format 4 cmap subtable, with 224 symbols starting at 0xF020. (It's not a Unicode encoding, so it's not U+F020.)

So, notice that you can use U+F0A7 to access the symbol encoded as 0xF0A7. But you could also use U+00A7 to access the same symbol. IOW, U+0020 .. U+00FF gets mapped into the font's 0xF020 .. 0xF0FF.

I haven't confirmed with any Word engineer, but I surmise it's treating characters entered with the selected font being a symbol-encoded font using a single-byte encoding. This stuff worked in Word before Word starting using Unicode in Word 97. And IIRC you can save to RTF and unpack what is effectively single-byte encoding.

But wait, there's more! 

Back around 1997, Bob Hallissy and I did an experiment with symbol encoding in which we created a font with 3/0/4 cmap, but with 224 characters encoded at a different starting code position—I forget what, but something like 0xE000. And we changed the OS/2.usFirstCharIndex value to match that. Result: it worked in Word and other Win9x (non-unicode) apps just like any other symbol-encoded font.

**Comment by PeterCon** [comment]
Here's a proposed draft change for the next version, in the "Windows platform (platform ID = 3)" section:

><del>When building a symbol font for Windows, the platform ID should be 3 and the encoding ID should be 0.</del><ins>The symbol encoding was created to support fonts with arbitrary ornaments or symbols not supported in Unicode or other standard encodings. A format 4 subtable would be used, typically with up to 224 graphic characters assigned at code positions beginning with 0xF020. This corresponds to a sub-range within the Unicode Private-Use Area (PUA), though this is not a Unicode encoding. In legacy usage, some applications would represent the symbol characters in text using a single-byte encoding, and then map 0x20 to the OS/2.usFirstCharIndex value in the font. In new fonts, symbols or characters not in Unicode should be encoded using PUA code points in a Unicode &#39;cmap&#39; subtable.</ins>
