### ISSUE TITLE
Soften Mac cmap requirements

### ISSUE THREAD

**Issue by sairuspatel** [MicrosoftDocs/typography-issues#604]
The "Macintosh 'cmap' Table" section on this Recommendations page says:

"When building a font containing Roman characters that will be used on the Macintosh, an additional subtable is required, specifying platform ID of 1 and encoding ID of 0 (this subtable may use 'cmap' formats 0, 2, 4, or 6)."

Since we are revisiting the platform ID 1 'name' requirements (https://github.com/MicrosoftDocs/typography-issues/issues/443), it would be a good time to revise the above platform ID 1 'cmap' requirement as well.

I see several system fonts on my Mac (macOS 10.15.6) which support Latin but don’t have a platform ID 1 cmap subtable, which suggests that such a subtable isn’t always needed for such fonts on modern macOS versions.

The rest of that section is quaint and outdated as well:

"In order for the Macintosh 'cmap' table to be useful, the glyphs required for the Macintosh must have glyph indices less than 256 (since the 'cmap' subtable format 0 uses uint8 indices and therefore cannot index any glyph above 255).
The Apple 'cmap' subtable should be constructed according to Apple guidelines."

and I'd recommend it simply be removed (the first sentence assumes only format 0 is needed, possibly dating from TT's early days; the second sentence seems unnecessary: all the info to construct platform ID 1 cmap subtables should already be in the OT 'cmap' spec).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95e88b53-d670-0240-422c-72748258ab2a
* Version Independent ID: b5fff1ee-cf03-e424-a2dc-aee58e0429e4
* Content: [Recommendations for OpenType Fonts - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/recom)
* Content Source: [typographydocs/opentype/spec/recom.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/recom.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Proposed changes for next version:

'cmap':
>### Macintosh platform (platform ID = 1)
>
><del>When building a font that will be used on the Macintosh, the platform ID should be 1 and the encoding ID should be 0.</del><ins>Older Macintosh versions required fonts to have a &#39;cmap&#39; subtable for platform ID 1. For current Apple platforms, use of platform ID 1 is discouraged.</ins>


Recommendations:
><del>### Macintosh &#39;cmap&#39; Table</del>
>
><del>When building a font containing Roman characters that will be used on the Macintosh, an additional subtable is required, specifying platform ID of 1 and encoding ID of 0 (this subtable may use &#39;cmap&#39; formats 0, 2, 4, or 6).</del>
>
><del>In order for the Macintosh &#39;cmap&#39; table to be useful, the glyphs required for the Macintosh must have glyph indices less than 256 (since the &#39;cmap&#39; subtable format 0 uses uint8 indices and therefore cannot index any glyph above 255).</del>
>
><del>The Apple &#39;cmap&#39; subtable should be constructed according to Apple guidelines.</del>
