### ISSUE TITLE
Typography 

### ISSUE THREAD

**Issue by B-starboy** [MicrosoftDocs/typography-issues#606]
I had no idea that a company with 900 mil. customers only has five people installing and implementing typography ...WOW !!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d43be991-71e4-56f0-fec0-df35d187a0b8
* Version Independent ID: 3ba72d0d-49d0-b525-5a0d-fbe56aa9329c
* Content: [About Microsoft Typography - Typography](https://docs.microsoft.com/en-us/typography/about)
* Content Source: [typographydocs/about.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/about.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by behdad** [comment]
> five

That's *very* optimistic of you...
