### ISSUE TITLE
Number of coordinates

### ISSUE THREAD

**Issue by schriftgestalt** [MicrosoftDocs/typography-issues#607]
from the description of `xCoordinates[variable]`

> See below for details regarding the number of coordinate array elements.

I can't find that description. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2a9a6a1-a9b9-0864-8982-322da821389e
* Version Independent ID: a42612e3-dc1d-f980-fe4a-4880d1fd0086
* Content: [glyf - Glyf data table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/glyf)
* Content Source: [typographydocs/opentype/spec/glyf.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/glyf.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Proposed change for next version:

>In logical terms, there is one flag byte element, one x-coordinate, and one y-coordinate for each point. <ins> The number of points is determined by the last entry in the endPtsOfContours array. </ins>Note, however, that the flag byte elements and the coordinate arrays use packed representations...
