### ISSUE TITLE
Typo in the cmap subtable 4 example

### ISSUE THREAD

**Issue by Pomax** [MicrosoftDocs/typography-issues#612]
The CMAP subtable format 4 example, in https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#format-4-segment-mapping-to-delta-values, shows a list of `idDelta` values `-9 -18 -27 1`, which should be `-9 -18 -80 1`:

    [10-20] with delta -9 is [1-11]
    [30-90] with delta -18 is [12-72]

The next block should start at mapped glyph id 73, but instead we see:

    [153-480] with delta -27 is [126-453]

which would be non-contiguous. This should be -80 to ensure the next glyphid is 73.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86923ff4-2b60-9144-e2b4-77cdb36fd698
* Version Independent ID: ea221e53-f51a-8233-3c0b-d416e5360623
* Content: [cmap - Character To Glyph Index Mapping Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#format-4-segment-mapping-to-delta-values's)
* Content Source: [typographydocs/opentype/spec/cmap.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cmap.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Current text was present in TrueType 1.66.

**Comment by Pomax** [comment]
wow, then it's probably well overdue an update =D

**Comment by PeterCon** [comment]
Fixed for next version.

**Comment by PeterCon** [comment]
Proposed revisions:

| | | | | | | |
| :----- | :----- | - | - | - | - | - |
| segCountX2: | 8 | | | | | |
| searchRange: | 8 | | | | | |
| entrySelector: | 4 | | | | | |
| rangeShift: | 0 | | | | | |
| endCode: | 20  90  480  0xffff | | | | | |
| reservedPad: | 0 | | | | | |
| startCode: | 10  30  153  0xffff | | | | | |
| idDelta: | -9  -18  <del>-27</del><ins>-80</ins>  1 | | | | | |
| idRangeOffset: | 0  0  0  0 | | | | | |



This table performs the following mappings:

>10 ⇒ 10 - 9 = 1  
20 ⇒ 20 - 9 = 11  
30 ⇒ 30 - 18 = 12  
90 ⇒ 90 - 18 = 72  
<ins>153 ⇒ 153 - 80 = 73  
480 ⇒ 480 - 80 = 400  
0xffff ⇒ 0</ins>
