### ISSUE TITLE
[Recommendations] Remove recommendations for `cmap` table

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#614]
Please remove the recommendations for the `cmap` table from the Recommendations page. Platforms have converged enough that requirements for new fonts can be clearly specified in the specification for the `cmap` table, as discussed in #269. The web and most font vendors depend on fonts to work across platforms.

There’s probably a lot more that should be removed from this Recommendations page and replaced with actual specification, but let’s start with this one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95e88b53-d670-0240-422c-72748258ab2a
* Version Independent ID: b5fff1ee-cf03-e424-a2dc-aee58e0429e4
* Content: [Recommendations for OpenType Fonts - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/recom)
* Content Source: [typographydocs/opentype/spec/recom.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/recom.md)
* Product: **typography**

**Comment by PeterCon** [comment]
As I mentioned in #269, you should review the combined changes that I showed in the discussion for #599. If you think more can be changed, I'll re-open.
