### ISSUE TITLE
Remove examples from smcp feature application interface section

### ISSUE THREAD

**Issue by tiroj** [MicrosoftDocs/typography-issues#616]
Current [smcp](https://docs.microsoft.com/en-us/typography/opentype/spec/features_pt#-tag-smcp) feature description reads

> _Application interface:_ For GIDs found in the 'smcp' coverage table, the application passes GIDs to the 'smcp' table, and gets back new GIDs. Note that applications should treat ß (U+00DF) as a pair of s characters, and that the Turkish dotless i maps to the normal small cap I.

I suggest removing the second sentence, regarding the German ß and the Turkish dotless i, because it incorrectly suggests that these are specific and limited language shaping behaviours associated with the smallcap feature, and also that the application is responsible for both, whereas handling of TRK langsys behaviour is the responsibility of the font lookups.

I think we can generalise the suggestion regarding ß like this:

> _Application interface:_ For GIDs found in the 'smcp' coverage table, the application passes GIDs to the 'smcp' table, and gets back new GIDs. For lowercase characters with corresponding uppercase, applications may opt to perform buffered case conversion and apply the c2sc feature first and then the smcp feature to pick up any smallcap substitutions not covered in c2sc; this approach enables application of Unicode [SpecialCasing.txt](https://unicode.org/Public/UNIDATA/SpecialCasing.txt) as part of the smallcap substitution process.

**Comment by PeterCon** [comment]
IMO the application interface field should only mention things that it's expected that the application will handle outside of lookup processing; and should not mention anything that is expected to be handled within the font lookups.

I think what you've proposed for the AI field is consistent with that.

Should the Recommended implementation field provide more info, mentioning language-specific behaviours? Or perhaps the example?

**Comment by tiroj** [comment]
Whenever an example is given in the feature descriptions, it should be preceded by a generalisation, so it is clear that the example is an example _of_ a general principle or something that font makers should consider. So, e.g.

_Recommended implementation:_ The 'smcp' table maps lowercase glyphs to the corresponding small-cap forms (GSUB lookup type 1). This may involve language-specific exceptions—for example the handling of Turkish (TRK) dotted and undotted i—that may be implemented in the 'smcp' feature directly or in concert with the 'locl' feature.

**Comment by PeterCon** [comment]
Also, I'm not sure about the guidance you propose involving c2sc: yes, uppercase mapping followed by c2sc could achieve the desired result. But how many fonts actually implement c2sc? (Far fewer, I'd guess, than smcp.) And it's asking apps to add special case processing for a feature that may not be be well-supported in fonts.

**Comment by PeterCon** [comment]
>On the other hand, a font could implement smcp for glyphs of particular characters like ß with a type 2 substitution.

I was pondering whether there's a problem with ambiguity as to what a font might do and what an app might do in a case like ß: it's not a problem if both the app and the font try to handle it since the paths would be mutually exclusive. (If the app does it, the font lookup won't be applying.) 

However, if both add developers and font developers are assuming the other will handle it, then the right thing won't happen.

**Comment by PeterCon** [comment]
Preliminary draft: this doesn't include anything related to ß, but does incorporate an unrelated change for #601.

>*Recommended implementation:* <del>The &#39;smcp&#39; table maps lowercase glyphs to the corresponding small-cap forms (GSUB lookup type 1).</del><ins>Glyphs for lowercase characters are mapped to the corresponding small-cap forms (GSUB lookup type 1). This may involve exceptions handled using separate language systems; for example, correct handling of Turkish dotted and undotted i could be implemented using a &#39;TRK &#39; language system, with appropriate mappings directly in a lookup for the 'smcp' feature or in concert with the 'locl' feature.</ins>
>
>*Application interface:* <del>For GIDs found in the &#39;smcp&#39; coverage table, the application passes GIDs to the &#39;smcp&#39; table, and gets back new GIDs. Note that applications should treat ß (U+00DF) as a pair of s characters, and that the Turkish dotless i maps to the normal small cap I.</del><ins>Discretionary feature: can be applied to glyph runs based on document markup, user control or other application criteria.</ins>

**Comment by khaledhosny** [comment]
> Also, I'm not sure about the guidance you propose involving c2sc: yes, uppercase mapping followed by c2sc could achieve the desired result. But how many fonts actually implement c2sc? (Far fewer, I'd guess, than smcp.) And it's asking apps to add special case processing for a feature that may not be be well-supported in fonts.

I think `smcp` feature was a mistake, as it asks font developers to implment complex, locale-specific case mapping in each font while it is already specified by Unicode. Fonts often do it wrong.

I think the spec (either in its current state on in a future iteration) should discourage `smcp` and `pcap` and instead encourage fonts and applications to use `c2sc` and `c2pc` instead.

**Comment by mikeday** [comment]
That's a good idea, is anything likely to break if applications do their own case conversion for fonts that have `c2sc` available and leave it up to the font if they only have `smcp`? If that's a safe approach then it sounds like it would be a smooth transition to make.

**Comment by PeterCon** [comment]
>is anything likely to break if applications do their own case conversion for fonts that have c2sc available

The app would (best case) have to do the following:
1. do an uppercase mapping into a temporary buffer
2. test the coverage of the c2sc feature to see which characters' default glyphs are or are not supported
3. use c2sc for those characters whose glyphs are found in the c2sc coverage *and that were not uppercase in the original string*
4. if the glyph for a character is not supported, and the lowercase of that character is in the original string (i.e., it was not a special-case case mapping), it can fallback to smcp for the lowercase character
4. if the glyph for the uppercase character is not in the c2sc coverage and the lowercase of that character was not in the original string (i.e., it was a special-case case mapping), then map the uppercase characters back to lowercase using standard casing; then apply smcp
6. hope for the best

Now, there still needs to be a contract with the font regarding c2sc. For example, consider Turkish dotted/dotless I. 

* Suppose the string contains lowercase dotless i, and the app uppercases that to capital dotless i then applies c2sc. And suppose the font has a variant c2sc feature table under the TRK language system, and the lookup for that maps capital dotless i to small cap dotless i. All good.

* But suppose instead the font didn't have a TRK language system. Its c2sc lookup will likely map capital dotless i to small cap dotted i. **Not good!** 

In the latter case, it would have been better for the app not to uppercase the dotless i but to apply smcp directly.

This need of a contract isn't just for this alternate small-cap implementation design. The c2sc/c2pc features were not registered only for use in this way. So, presumably there are cases in which content authors (for whatever reason) apply c2sc to uppercase characters in a string. The Turkish dotted/dotless i issue still arises. (Unless we propose that apps implement c2sc by lowercasing the string in a language-aware way then use smcp...)

>I think the spec ... should discourage smcp and pcap 
Well, it would be one thing to recommend fonts implement c2sc/c2pc instead. But that would require a broad range of apps to implement special casing as being discussed here. Note that today many content authors would be familiar with selecting entire strings and applying `small caps` formatting knowing that any uppercase letters will remain unaffected. There's no way for an author to achieve small caps except by a `small caps` formatting option.

And as mentioned above, c2sc/c2pc don't escape these special casing conundrums. (Granted, the ß problem doesn't exist for these features.)

**Comment by PeterCon** [comment]
Btw, the c2sc/c2pc descriptions don't mention anything wrt language-specific casing.

**Comment by tiroj** [comment]
> Also, I'm not sure about the guidance you propose involving c2sc: yes, uppercase mapping followed by c2sc could achieve the desired result. But how many fonts actually implement c2sc? (Far fewer, I'd guess, than smcp.)

Almost all Latin fonts support both c2sc and smcp: that's been standard practice for font makers since the late 90s, and that gets carried across to Cyrillic and Greek too.

> And it's asking apps to add special case processing for a feature that may not be be well-supported in fonts.

It's not asking them to, it is telling them that they can. And I suggested mentioning it because this is how Adobe's shapers have worked for a long time (thanks to Eric Mueller, as I recall): text is case converted and then c2sc is applied.

**Comment by PeterCon** [comment]
If it's been common practice, that gives me a lot more confidence.

**Comment by tiroj** [comment]
> I think the spec (either in its current state on in a future iteration) should discourage smcp and pcap and instead encourage fonts and applications to use c2sc and c2pc instead.

smcp is sometimes needed, because there exist lowercase characters without uppercase mappings, and fonts _may_ provide smallcap variants for these.

**Comment by PeterCon** [comment]
So, in fonts that implement both smcp and c2sc, and with apps that apply this behaviour, how would the Turkish scenario be handled?

* app handles dotted/dotless i uppercasing in a language-aware way
* font's smcp feature (with or without locl) also has TRK handling of dotted/dotless i (in case the app doesn't do the above)

??

**Comment by tiroj** [comment]
Approaches vary, but a common one these days is to perform a TRK langsys substitution in the locl feature up front:

`i -> i.TRK`

where /i.TRK/ is identical to /i/ but follows a different path through the OTL features, so smcp looks something like

```
i -> I.sc
i.TRK -> Idotaccent.sc
dotlessi -> I.sc
```
The other way to do it is to have separate smcp lookups for TRK.

If software is using the buffered case conversion method, the whole point of doing so is that it gets access to Unicode SpecialCasing.txt, which will capture the Turkish casing rules and apply them before c2sc substitutions.

**Comment by tiroj** [comment]
The situation for font makers is that we can't rely on buffered case conversion being used, but we can't ignore that it might be. That's okay for c2sc, because the mappings are quite tidy. It gets more complicated in smcp, because we have to be aware of the langsys specific handling.

**Comment by PeterCon** [comment]
OK: here's a draft revision:

>*Friendly name:* Small Capitals
>
>*Registered by:* Microsoft/Adobe
>
>*Function:* This feature turns <ins>glyphs for </ins>lowercase characters into small capitals. <del>This corresponds to the common SC font layout. </del>It is generally used for display lines set in Large &amp; small caps, such as titles. Forms related to small capitals, such as oldstyle figures, may be included.
>
>> <ins>*Note:* Some languages written with bicameral scripts have special case-mapping behaviors for certain characters. Care is needed by font and application developers to handle these cases correctly.</ins>
>
>*Example:* The user enters text as mixed capitals and lowercase, and gets Large &amp; small cap text.
>
>*Recommended implementation:* <del>The &#39;smcp&#39; table maps lowercase glyphs to the corresponding small-cap forms (GSUB lookup type 1).</del><ins>Glyphs for lowercase characters are mapped to the corresponding small-cap forms (GSUB lookup type 1).</ins> 
>
><ins>Correct handling of case mapping for some languages may require exceptions to be handled using separate language systems. For example, correct handling of Turkish dotted and undotted i could be implemented using a &#39;TRK &#39; language system, with appropriate mappings directly in a lookup for the &#39;smcp&#39; feature or in concert with the &#39;locl&#39; feature. Also, some applications will handle language-specific case mappings by mapping the lowercase characters to appropriate uppercase characters in a temporary buffer and then applying the [&#39;c2sc&#39;](features_ae.md#c2sc) feature. Fonts that implement &#39;smcp&#39; should also implement the &#39;c2sc&#39; feature.</ins>
>
>*Application interface:* <del>For GIDs found in the &#39;smcp&#39; coverage table, the application passes GIDs to the &#39;smcp&#39; table, and gets back new GIDs. Note that applications should treat ß (U+00DF) as a pair of s characters, and that the Turkish dotless i maps to the normal small cap I.</del><ins>Discretionary feature: can be applied to glyph runs based on document markup, user control or other application criteria.</ins>
>
><ins>For best handling of language-specific case mapping behaviors, applications can map lowercase characters to uppercase in a temporary buffer and then apply the [&#39;c2sc&#39;](features_ae.md#c2sc) feature. Lookups for &#39;smcp&#39; should still be applied to characters that do not have an uppercase mapping, or in the event that a font does not support some uppercased characters using the &#39;c2sc&#39; feature.</ins>
>
>*UI suggestion:* This feature should be off by default.
>
>*Script/language sensitivity:* Applies only to bicameral scripts (i.e. those with case differences), such as Latin, Greek, Cyrillic, and Armenian.
>
>*Feature interaction:* This feature may be used in combination with other substitution (GSUB) features, whose results it may override. Also see [&#39;c2sc&#39;](features_ae.md#c2sc).

**Comment by khaledhosny** [comment]
>     4. if the glyph for a character is not supported, and the lowercase of that character is in the original string (i.e., it was not a special-case case mapping), it can fallback to smcp for the lowercase character

That would be nice to do but not required, a font with different `c2sc` coverage then `smcp` is a badly made font, and these workarounds is what keeps people (knowingly or unknowingly) making bad fonts.

> > I think the spec ... should discourage smcp and pcap
> 
> Well, it would be one thing to recommend fonts implement c2sc/c2pc instead. But that would require a broad range of apps to implement special casing as being discussed here. Note that today many content authors would be familiar with selecting entire strings and applying `small caps` formatting knowing that any uppercase letters will remain unaffected. There's no way for an author to achieve small caps except by a `small caps` formatting option.

That is on the application to handle correctly, not unlike many other OpenType features. The idea that case mapping a simple thing that fonts can be trusted to handle is anti-OpenType and more in the realm of AAT or Graphite.

**Comment by PeterCon** [comment]
And here's a related draft revision for the 'c2sc' feature:

>*Application interface:* <del>For GIDs found in the &#39;c2sc&#39; coverage table, the application passes GIDs to the &#39;c2sc&#39; table, and gets back new GIDs.</del><ins>Discretionary feature: can be applied to glyph runs based on document markup, user control or other application criteria. Note that applications may use this feature in an implementation to support the &#39;smcp&#39; feature with language-specific case-mapping logic, in which case the feature is applied automatically by the application based on application of the &#39;smcp&#39; feature. See [&#39;smcp&#39;](features_pt.md#smcp) for additional information.</ins>

**Comment by tiroj** [comment]
> That would be nice to do but not required, a font with different c2sc coverage then smcp is a badly made font, and these workarounds is what keeps people (knowingly or unknowingly) making bad fonts.

See previous comment about smcp for characters without uppercase mapping. This may not be limited to alphabetic characters, e.g. numerals, punctuation, or symbols may have smallcap variant or aligning glyphs, and these may occur in c2sc or smcp as the designer thinks fit.

When making the Brill types, I needed to take into account that caseless IPA characters might occur in running heads in Brill publications, so provided smallcap variants for lots of characters without uppercase equivalents.

So I'd say a tidy smallcap algorithm using case conversion + c2sc should also include smcp.

**Comment by tiroj** [comment]
Peter, I think it is confusing to say e.g. c2sc 'is applied automatically by the application based on application of the 'smcp' feature'. What we're talking about is application interaction at a higher level, i.e. the smallcap function in the app, and how it applies OTL features. So it isn't the case that the smcp is being in some way explicitly invoked by the user but this is instead being handled by the app using case conversion plus c2sc, but that the app has a smallcap function which, when invoked, performs a series of steps involving case conversion and c2sc and smcp features.

If the smcp feature is explicitly invoked by the user, e.g. by using the low level CSS tag, then I would expect the smcp feature lookups to be applied directly.

**Comment by PeterCon** [comment]
>Peter, I think it is confusing to say e.g. c2sc 'is applied automatically by the application based on application of the 'smcp' feature'...

Yup, good point. Revising...

**Comment by PeterCon** [comment]
Revised draft for 'c2sc':

>*Application interface:* <del>For GIDs found in the &#39;c2sc&#39; coverage table, the application passes GIDs to the &#39;c2sc&#39; table, and gets back new GIDs.</del><ins>Discretionary feature: can be applied to glyph runs based on document markup, user control or other application criteria. Note that applications may use this feature in an implementation to support the &#39;smcp&#39; feature with language-specific case-mapping logic, in which case the feature is applied automatically by the application based on small-cap formatting being applied to text. See [&#39;smcp&#39;](features_pt.md#smcp) for additional information.</ins>

Revision to draft for 'smcp' adding references to Unicode:

>> <ins>*Note:* Some languages written with bicameral scripts have special case-mapping behaviors for certain characters. Care is needed by font and application developers to handle these cases correctly. See *The Unicode Standard*, “5.18 Case Mappings”, for more information.</ins>
>
>...
>
><ins>For best handling of language-specific case mapping behaviors, applications can map lowercase characters to uppercase in a temporary buffer and then apply the [&#39;c2sc&#39;](features_ae.md#c2sc) feature. The uppercase mapping can make use of Unicode special-casing data in the Unicode Character Database ([SpecialCasing.txt](https://unicode.org/Public/UNIDATA/SpecialCasing.txt)). Lookups for &#39;smcp&#39; should still be applied to characters that do not have an uppercase mapping, or in the event that a font does not support some uppercased characters using the &#39;c2sc&#39; feature.</ins>

**Comment by PeterCon** [comment]
Sorry, that draft for c2sc didn't really address the review feedback. New draft:

>*Application interface:* <del>For GIDs found in the &#39;c2sc&#39; coverage table, the application passes GIDs to the &#39;c2sc&#39; table, and gets back new GIDs.</del><ins>Discretionary feature: can be applied to glyph runs based on document markup, user control or other application criteria. Note that applications may use this feature in an implementation to support small-cap formatting applied to text with language-specific case-mapping logic. See [&#39;smcp&#39;](features_pt.md#smcp) for additional information.</ins>

**Comment by PeterCon** [comment]
And similar revision to the 'smcp' draft:

><ins>For best handling of language-specific case mapping behaviors, applications can implement small-cap formatting by mapping lowercase characters to uppercase in a temporary buffer and then applying the [&#39;c2sc&#39;](features_ae.md#c2sc) feature. The uppercase mapping can make use of Unicode special-casing data in the Unicode Character Database ([SpecialCasing.txt](https://unicode.org/Public/UNIDATA/SpecialCasing.txt)). Lookups for &#39;smcp&#39; should still be applied to characters that do not have an uppercase mapping, or in the event that a font does not support some uppercased characters using the &#39;c2sc&#39; feature.</ins>

**Comment by PeterCon** [comment]
Draft revision for 'pcap':

>*Function:* Some fonts contain an additional size of capital letters, shorter than the regular smallcaps and whimsically referred to as petite caps. Such forms are most likely to be found in designs with a small lowercase x-height, where they better harmonise with lowercase text than the taller smallcaps (for examples of petite caps, see the Emigre type families Mrs Eaves and Filosofia). This feature turns <ins>glyphs for </ins>lowercase characters into petite capitals. Forms related to petite capitals, such as specially designed figures, may be included.
>
...
>
>> <ins>*Note:* Some languages written with bicameral scripts have special case-mapping behaviors for certain characters. Care is needed by font and application developers to handle these cases correctly. See the [&#39;smcp&#39;](#smcp) feature for more information.</ins>
>
> ...
>*Recommended implementation:* The &#39;pcap&#39; table maps lowercase glyphs to the corresponding petite cap forms (GSUB lookup type 1).
>
><ins>Correct handling of case mapping for some languages may require exceptions to be handled using separate language systems. Also, some applications may handle language-specific case mappings by mapping the lowercase characters to appropriate uppercase characters in a temporary buffer and then applying the [&#39;c2pc&#39;](features_ae.md#c2pc) feature. Fonts that implement &#39;pcap&#39; should also implement the &#39;c2pc&#39; feature. See the [&#39;smcp&#39;](#smcp) feature for more information.</ins>
>
>*Application interface:* <del>For GIDs found in the &#39;pcap&#39; coverage table, the application passes GIDs to the &#39;pcap&#39; table, and gets back new GIDs. Petite cap substitutions should follow language rules for smallcap ([&#39;smcp&#39;](#smcp)) substitutions.</del><ins>Discretionary feature: can be applied to glyph runs based on document markup, user control or other application criteria.</ins>
>
><ins>For best handling of language-specific case mapping behaviors, applications can implement petite-cap formatting by mapping lowercase characters to uppercase in a temporary buffer and then applying the [&#39;c2pc&#39;](features_ae.md#c2pc) feature. See the [&#39;smcp&#39;](#smcp) feature for more information.</ins>
>
>...

**Comment by PeterCon** [comment]
And draft revision for 'c2pc':

>*Application interface:* <del>For GIDs found in the &#39;c2pc&#39; coverage table, the application passes GIDs to the &#39;c2pc&#39; table, and gets back new GIDs.</del><ins>Discretionary feature: can be applied to glyph runs based on document markup, user control or other application criteria. Note that applications may use this feature in an implementation to support petite-cap formatting applied to text with language-specific case-mapping logic. See [&#39;pcap&#39;](features_pt.md#pcap) and [&#39;smcp&#39;](features_pt.md#smcp) for additional information.</ins>

**Comment by PeterCon** [comment]
Draft revisions made to 'c2pc', 'c2sc', 'pcap', 'smcp' as described above, for next version.

**Comment by khaledhosny** [comment]
> > That would be nice to do but not required, a font with different c2sc coverage then smcp is a badly made font, and these workarounds is what keeps people (knowingly or unknowingly) making bad fonts.
> 
> See previous comment about smcp for characters without uppercase mapping. This may not be limited to alphabetic characters, e.g. numerals, punctuation, or symbols may have smallcap variant or aligning glyphs, and these may occur in c2sc or smcp as the designer thinks fit.

`c2sc` can’t include mapping for unicameral characters?

**Comment by tiroj** [comment]
Sometimes, one wants to apply smallcap only to lowercase letters, leaving the uppercase characters full size. This is a fairly common typographic styling. This is the primary reason why c2sc and smcp were spec'd as different features, so there would be an easy way for software to apply either lowercase-to-smallcaps or all-to-smallcaps as separate functions. Having the two features enables font makers to make design decisions about what they want to be transformed with each function, e.g. whether they want the ampersand to take a smallcap form when lowercase letters are styled as smallcaps or only when caps are, and that decision may vary depending on the nature of the design, taking into account e.g. x-height size.
