### ISSUE TITLE
[cmap] Unicode code space doesn’t extend to U+1FFFFF

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#617]
The description of cmap format 8 contains the statement: “Since the Unicode code space extends only to U+1FFFFF...”

This is incorrect; the Unicode code space only extends to U+10FFFF.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86923ff4-2b60-9144-e2b4-77cdb36fd698
* Version Independent ID: ea221e53-f51a-8233-3c0b-d416e5360623
* Content: [cmap - Character To Glyph Index Mapping Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap)
* Content Source: [typographydocs/opentype/spec/cmap.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cmap.md)
* Product: **typography**

**Comment by PeterCon** [comment]
Fixed for next version:

>If a font contains Unicode supplementary-plane characters (U+10000 to U+10FFFF), then it’s likely that it will also include Unicode BMP characters (U+0000 to U+FFFF) as well. Hence, there is a need to map a mixture of 16-bit and 32-bit character codes. A simplifying assumption is made: namely, that there are no 32-bit character codes which share the same first 16 bits as any 16-bit character code. (Since the Unicode code space extends only to <del>U+1FFFFF</del><ins>U+10FFFF</ins>, a potential conflict exists only for characters U+0000 to U+001F, which are non-printing control characters.) This means that the determination as to whether a particular 16-bit value is a standalone character code or the start of a 32-bit character code can be made by looking at the 16-bit value directly, with no further information required.

**Comment by dscorbett** [comment]
Since the Unicode code space extends to U+10FFFF, the potential conflicts are only in the range U+0000 to U+0010, not the range U+0000 to U+001F.

**Comment by PeterCon** [comment]
Fixed.
