### ISSUE TITLE
PCLT discouragement

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#618]
This sentence
> The PCLT table is strongly discouraged for OpenType™ fonts with TrueType outlines.

is underspecified and can be interpreted in multiple ways. Is it *encouraged* for font files with CFF outlines? But I can only find it in font files with TrueType outlines, so perhaps it should be interpreted the other way: i.e. that it's *prohibited* in CFF outlines and also discouraged in TT outline fonts? Should it just be blanket discouraged everywhere?

(What we mean by "discouraged" is also worth thinking about, but perhaps a separate issue.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d1e2f091-5f77-212d-00e6-634a2e0bbc03
* Version Independent ID: 96873917-b737-0f8e-e7ee-97e2fba125e5
* Content: [PCLT - PCL 5 Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/pclt)
* Content Source: [typographydocs/opentype/spec/pclt.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/pclt.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by sairuspatel** [comment]
PCLT is not a table that’s ever been required or recommended for use with OT-CFF or OT-CFF2 fonts.

**Comment by PeterCon** [comment]
Proposed revisions for next version:

><del>The PCLT table is strongly discouraged for OpenType™ fonts with TrueType outlines.</del><ins>Use of the PCLT table in OpenType fonts is strongly discouraged.</ins> Extra information on many of these fields can be found in the *HP PCL 5 Printer Language Technical Reference Manual* available from Hewlett-Packard Boise Printer Division.

**Comment by ctrlcctrlv** [comment]
Why is it discouraged? Some of us have PCL5 printers. Will it break anything? This seems less explanatory than before…?
