### ISSUE TITLE
Only supported in version 1 'gasp'

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#619]
Version 1 is the only version defined in the spec these days, so these sentences are redundant.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1a2cf4e2-f582-0747-6e9a-dfddc6b187a3
* Version Independent ID: efa5dfa1-6f3c-ff49-aba2-d2b0ff8eef2c
* Content: [gasp — Grid-fitting And Scan-conversion Procedure Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/gasp)
* Content Source: [typographydocs/opentype/spec/gasp.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gasp.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Version 1 was introduced in OT 1.5, adding those two flags. Mentioned in the change log, but not in the gasp chapter.

**Comment by PeterCon** [comment]
Proposed change for the next version: add the following at the end of the introduction, before the `'gasp' Table Formats` heading.

><ins>Two versions of the &#39;gasp&#39; table have been defined: both versions use the same formats, except that two new flags were defined in version 1, as documented below. All new fonts and applications should use version 1.</ins>
