### ISSUE TITLE
No concrete information about reordering

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#62]
The “Reordering characters” section does not say which characters need reordering. I think the only one that Uniscribe reorders is U+0F3F TIBETAN SIGN MAR TSHES.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afaf5060-fd0d-2b4c-7555-e3d81ccafe24
* Version Independent ID: 06c7f355-4cd9-4d0c-188b-4d65d4a5b406
* Content: [Creating and Supporting OpenType Fonts for Tibetan Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/tibetan)
* Content Source: [typographydocs/script-development/tibetan.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/tibetan.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by xadxura** [comment]
This spec is deprecated. Tibetan shaping is now handled by USE.
