### ISSUE TITLE
hdmx DeviceRecords "for format 0"?

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#621]
[Enter feedback here]

This clause

> Each DeviceRecord *for format 0* looks like this.

is probably redundant when no other "formats" are defined. It's not even clear what a "format" is here - does it mean hdmx table version?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4696c9e-e34d-71cd-391b-900eb2d2df1a
* Version Independent ID: 415f8087-1bae-4b27-8646-1620f1e3cade
* Content: [hdmx - Horizontal Device Metrics - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/hdmx)
* Content Source: [typographydocs/opentype/spec/hdmx.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/hdmx.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Draft revisions for next version:

><del>Each DeviceRecord for format 0 looks like this.</del><ins>The DeviceRecord format is as follows:</ins>
>
>*<del>Device Record</del><ins>DeviceRecord</ins>*
