### ISSUE TITLE
'curs' should be required for some scripts

### ISSUE THREAD

**Issue by PeterCon** [MicrosoftDocs/typography-issues#622]
The feature description currently states:

>UI suggestion: This feature could be made active or inactive by default, at the user’s preference.

User discretion might be OK for scripts that don't require cursive connection, but it should not be discretionary for scripts like Arabic that require cursive joining behaviour for correct display of text.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4da11419-0864-96ff-7f67-296680843fc1
* Version Independent ID: 1d46dac1-d559-ce3e-2f6f-f47cf8cd9e0f
* Content: [Registered features, a-e - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae)
* Content Source: [typographydocs/opentype/spec/features_ae.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_ae.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Proposed revisions for next version:

>*Function:* In cursive scripts like Arabic, this feature <del>cursively positions adjacent glyphs</del><ins>is used to position adjacent glyphs for correct cursive connections</ins>.
>
>*Example:* In Arabic, the Meem followed by a Reh are cursively positioned by overlapping the exit point of the Meem on the entry point of the Reh.
>
>*Recommended implementation:* <del>The</del><ins>Lookup tables for the</ins> &#39;curs&#39; <del>table provides</del><ins>feature provide</ins> entry and exit points (x,y) for glyphs to be cursively positioned (GPOS lookup type 3).
>
>*Application interface:* <del>For GIDs located in the coverage table, the application gets back positioning point locations for the preceding and following glyphs.</del><ins>In recommended usage, this feature triggers positioning adjustments that are required for correct display of cursively-connecting scripts. It should be applied in the appropriate contexts, as determined by script-specific processing requirements. It should also be applied for other scripts for which cursive styles can optionally be used.</ins>
>
>*UI suggestion:* <del>This feature could be made active or inactive by default, at the user’s preference.</del><ins>Control of this feature should not normally be exposed to the user.</ins>
>
>*Script/language sensitivity:* <del>Can be used in any cursive script.</del><ins>Used primarily for Arabic and other cursively-connecting scripts. May also be used for other scripts for which cursive styles can optionally be used.</ins>

**Comment by tiroj** [comment]
The curs feature shouldn't be limited to nominally 'cursive' script shaping, since cursive attachment connection between letters may be a feature of specific styles or individual type designs for virtually any writing system. There are, for example, plenty of styles of cursive Latin script, including designs in which OTL cursive attachment between letters is a benefit because of a bouncing baseline.

Generalised, cursive attachment lookups provide the same capability for spacing glyphs as mark attachment provides for non-spacing glyphs, _even glyphs that do not graphically connect_ (e.g. in an Arabic font, the curs feature may be used to attach a word initial alif to sit beside a lam whose height is determined by connection to following letters, even though the alif and the lam do not graphically connect). Having a feature like curs that can safely be presumed to be active for any script, in the same way as mark and mkmk, and as provided in USE, provides flexibility to font makers.

**Comment by PeterCon** [comment]
Revised draft:

>*Function:* <del>In cursive scripts like Arabic, this feature cursively positions adjacent glyphs</del><ins>This feature is used to position adjacent glyphs for cursive connections</ins>.
>
>*Example:* In Arabic, the Meem followed by a Reh are cursively positioned by overlapping the exit point of the Meem on the entry point of the Reh.
>
>*Recommended implementation:* <del>The</del><ins>Lookup tables for the</ins> &#39;curs&#39; <del>table provides</del><ins>feature provide</ins> entry and exit points (x,y) for glyphs to be cursively positioned (GPOS lookup type 3).
>
>*Application interface:* <del>For GIDs located in the coverage table, the application gets back positioning point locations for the preceding and following glyphs.</del><ins>In recommended usage, this feature triggers positioning adjustments that are required for correct display of fonts that implement cursive joining behavior. It should always be applied.</ins>
>
>*UI suggestion:* <del>This feature could be made active or inactive by default, at the user’s preference.</del><ins>Control of this feature should not normally be exposed to the user.</ins>
>
>*Script/language sensitivity:* <del>Can be used in any cursive script.</del><ins>Used primarily for Arabic and other cursively-connecting scripts, and also any other scripts for which cursive styles can optionally be used.</ins>
