### ISSUE TITLE
Problems with the section on Tibetan word analysis

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#63]
> There are two other forms of tseg having special functions (U+0F34, U+oFD2).

“tseg” should be “tsheg” and “U+oFD2” should be “U+0FD2”.

> Syllable boundaries occur after any tsheg or non-word-forming character (character ∉ L).

This definition of “non-word-forming character” ignores vowels and modifiers, implying that, for example, ⟨ཨོཾ⟩ has two syllables.

> A syllable boundary is also a word boundary, except in case that the tsheg or other character non-breaking:

This sentence is ungrammatical. It is also misleading: Tibetan text need not follow this convention, but may use U+0F0B for all tshegs.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afaf5060-fd0d-2b4c-7555-e3d81ccafe24
* Version Independent ID: 06c7f355-4cd9-4d0c-188b-4d65d4a5b406
* Content: [Creating and Supporting OpenType Fonts for Tibetan Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/tibetan)
* Content Source: [typographydocs/script-development/tibetan.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/tibetan.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by xadxura** [comment]
This spec is deprecated. Tibetan is now shaped with USE.
