### ISSUE TITLE
Clarify "all other features are optional"

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#640]
In the [Language System Table](https://docs.microsoft.com/en-us/typography/opentype/spec/chapter2#language-system-table) section, after describing the requiredFeatureIndex field, the following statement is made:

>All other features are optional.

This needs clarification as it seems to conflict with the description of many features in the feature registry as required for particular scripts.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb42967-20ca-9270-4572-65315127fcc5
* Version Independent ID: 1fa413f1-71cf-ac2a-0999-70dd5d8ac4cd
* Content: [OpenType layout common table formats - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/chapter2)
* Content Source: [typographydocs/opentype/spec/chapter2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/chapter2.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Proposed revision for next version:

><ins>All other features are considered optional with respect to the general requirements for processing the Language System table.</ins>
>
>> <ins>*Note:* Applications may treat certain features as required in certain contexts, regardless of whether a feature is referenced using the requiredFeatureIndex field. In particular, applications may treat certain features as required for correct layout of certain Unicode characters or scripts. Such higher-level requirements are outside the scope of this specification.</ins>
>
><del>All other features are optional. </del>For each optional feature, a zero-based index value references a record (FeatureRecord) in the FeatureRecord array, which is stored in a Feature List table (FeatureList). The feature indices themselves (excluding the ReqFeatureIndex) are stored in arbitrary order in the FeatureIndex array. The FeatureCount specifies the total number of features listed in the FeatureIndex array.

**Comment by PeterCon** [comment]
I'm not sure what the original motivation and thinking was, but I'm not aware of anything that has ever used it. Perhaps it could be deprecated.
