### ISSUE TITLE
'YCR ' should be mapped only to "crk"

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#645]
The tag 'YCR ' (Y-Cree) should be mapped to "crk" (Plains Cree). It should not be mapped to "cre" (Cree). This is because Y-Cree is a subset of Cree, not a synonym of Cree.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662c6f54-f90c-52ed-dca2-0f0a0a49fee5
* Version Independent ID: 6aa33924-d45e-60c3-a9fd-e317ff662993
* Content: [Language system tags - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags)
* Content Source: [typographydocs/opentype/spec/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
It's certainly plausible that the intent of 'YCR ' was to cover the "y dialect" Cree varieties. But IIUC that would mean those varieties in which proto-form \*l has a "y" reflex; and that would include Plains Cree (crk), but also Northern East Cree (crl) and Southern East Cree (crj).

**Comment by PeterCon** [comment]
Revised iso 639 mapping, for next version:

><del>cre</del><ins>crj, crk, crl</ins>
