### ISSUE TITLE
Add characteristics of the SVG table to intro section

### ISSUE THREAD

**Issue by sairuspatel** [MicrosoftDocs/typography-issues#646]
Adobe would like to propose this note that would be helpful for font designers when deciding which color format to go for. (The start of the COLR table does make its own statement of advantage by saying it is “compatible with existing text engines and easy to support with current OpenType font files”, so it’s appropriate for SVG to do the same, though to be balanced we also note below the possible downsides of SVG.)
  
The Introductory paragraph of the SVG table spec currently says:
 
"OpenType provides various formats for color fonts, one of which is the SVG table. The SVG table provides the benefits of supporting scalable color graphics using the Scalable Vector Graphics markup language, a vector graphics file format that is widely used on the Web and that provides rich graphics capabilities, such as gradients." 

We propose adding to the end of that:
 
[[
Note:

- SVG allows for raster artwork in addition to vectors, and for combining vector and raster graphics within the same glyph.
- A single SVG glyph contains all its multi-colored parts; it is an integrated piece of artwork. Users browsing an application’s glyph selection interface for an OT-SVG font can readily recognize and directly select the desired glyph. With the COLR table, each colored fragment is its own separate glyph and will thus be presented separately in an unfiltered display of all glyphs in the font.
- The conservation of the number of glyphs with the SVG table is also beneficial for fonts with a large number of glyphs that are nearing the 64K glyph limit, for example a pan-CJK font to which multi-color emoji glyphs need to be added.
- An SVG glyph will be larger in size than a COLR or sbix representation (if an equivalent representation were possible); compression or subsetting of the font could help.
- The SVG table does not support variability currently.

]]

**Comment by PeterCon** [comment]
Proposed draft for next version;

>OpenType provides various formats for color fonts, one of which is the SVG table. The SVG table provides the benefits of supporting scalable color graphics using the Scalable Vector Graphics markup language, a vector graphics file format that is widely used on the Web and that provides rich graphics capabilities, such as gradients.
>
><ins>Compared to the other color formats, the SVG table also provides certain other benefits:</ins>
>
>* <ins>SVG allows for raster artwork as well as vectors, and also allows for combining raster and vector elements in a color glyph. The other formats allow for one or the other, but not both.</ins>
>* <ins>The SVG description for a color glyph is a complete, integrated piece of artwork; no additional glyphs are required for the SVG description. In the COLR table, however, a color glyph may require components that have separate glyph IDs. In applications that allow users to browse and select specific glyphs in a font, the user may be presented with extraneous glyphs for components in the case of fonts using the COLR table, but not in the case of the SVG table.</ins>
>* <ins>The conservation of 16-bit glyph IDs when using the SVG table, in comparison with the COLR table, is also beneficial for fonts that support a large number of characters.</ins>
>
><ins>There are certain trade-offs, however. File sizes are often larger when using the SVG table than for the other color formats. Also, glyph outlines used in the COLR table can be variable (in a variable font) and can also be hinted, whereas these capabilities are not supported with the SVG table.</ins>

**Comment by PeterCon** [comment]
>That sounds like a documentation for application(s) limitation in the spec, 

I think this is a fair critique. There can be various reasons why a font has extra glyphs. This is also all commentary on the spec, and I think it's best to limit the amount of commentary. So, I'll consolidate the second and third bullets:

>* <ins>The SVG description for a color glyph is a complete, integrated piece of artwork; no additional glyphs are required for the SVG description. In the [COLR table](colr.md), however, a color glyph may require components that have separate glyph IDs. The conservation of 16-bit glyph IDs when using the SVG table, in comparison with the COLR table, may be beneficial for fonts that support a large number of characters.</ins>

**Comment by sairuspatel** [comment]
This is why our proposal specifically said “unfiltered” display (that detail was obscured in Peter’s rewrite). In several Adobe apps, the Glyphs panel has for many years provided by default an unfiltered or unprocessed grid of all glyphs. Yes, that can be a lot, and so the user can then choose various interesting filters or subsets on that glyph grid from a popup, e.g. “Extended Latin A”, or “Standard Ligatures”, or, possibly in the future “Composed Colr Glyphs”.

Also, I don’t see anything in the spec that prevents layer glyphs from being valid, standalone glyphs as well in the font, and not merely “extra” or “behind the scenes” glyphs which no user is going to want to see. That, combined with the fact that only a small minority of the glyphs in the font could be COLR (say, just for the emoji in a Japanese font), makes it clear that even if COLR glyphs are displayed composed in multi-color, the layer glyphs must also be displayed separately in a see-all-glyphs grid.

A see-all-glyphs grid is certainly not unique to Adobe flagship apps; rather, it is a pattern commonly seen in font production tools as well, one in which a raw or unfiltered display of all glyphs in the font is presented. Yes, it’s a given that the app could provide other filters as well, which is why the qualifier “unfiltered” was specified. Elaborating on what is meant by ”unfiltered” should satisfy the concern.

The spec does have various places which talk extensively about application and user interface design e.g. the various flavors of menu names, and the STAT table. The UI advantage of a user being able to more readily access an SVG glyph from an unfiltered display of all glyphs is a small but important benefit that we think it would be helpful to include. Thanks for considering it.

**Comment by khaledhosny** [comment]
Direct glyph id entry is an anti-feature and should not be discouraged by featuring it prominently in the spec. It is unportable (across different fonts or different versions of the same font), inaccessible (mapping the glyph id to a character is a guess at best and can fail in many situations), and has limited usefulness in many scripts (it is unusable in Arabic, for example, unless one composes whole words manually using glyph ids).

Unfiltered glyph display is pretty much and Adobe feature, and there are too many ways an OpenType font can make it useless. Unless you suggests adding a note to multiple substitutions, for example, saying they can make such glyph display useless.

The spec being bad in many placing is not a justification for making it even worse.

**Comment by sairuspatel** [comment]
Khaled, thanks for the feedback. There is no mention of glyph ID _entry_ in the wording. I certainly agree with your point that entering glyph IDs and expecting proper text to be stored in the backing store is problematic. That's not what's being talked about here, much less promoted.

_Displaying_ all glyph IDs is the pattern we're talking about. Font tools do it (e.g. `tx -pdf -0 ...` in the AFDKO). Some online font catalogs do it, so folks can _see_ all glyphs in the font. (It's one of many details that have been interesting enough that various font catalogs have made it available, just like a listing of the various flavors of family names in the font, including the problematic 4-face Windows family name + style links.) These glyph palettes aren't used to enter glyphs, much less try to convert them as text. They are for displaying glyph repertoire.

**Comment by sairuspatel** [comment]
In Adobe's original proposal above, based on Khaled's feedback, we propose changing the wording:

"Users browsing an application’s glyph selection interface for an OT-SVG font can readily recognize and directly select the desired glyph."

to:

"Users browsing a display of an OT-SVG font’s glyph repertoire can readily recognize and directly identify the multi-colored glyphs."

**Comment by PeterCon** [comment]
As mentioned above, I'm inclined to limit the amount commentary. And, as I mentioned earlier, there are other situations that can give rise to extraneous glyphs that can clutter a glyph selection UI.  For example, here's a selection of glyphs from a Telugu font:

![image](https://user-images.githubusercontent.com/12788502/95947054-aa6c0100-0da2-11eb-8f94-03ef48ed6089.png)

If this were about an especially significant decision criterion for choosing one color format over another, it might be worth mentioning. But I doubt this is what would drive decisions to use SVG vs. COLR vs. sbix or cbdt.

**Comment by sairuspatel** [comment]
Yes, a facility (various examples given in the thread above) which displayed all glyphs in the font would by definition show the glyphs in the Telugu example. That’s what would indeed be expected in a “show all glyphs“ request.

(Perhaps irrelevant now to the proposal, but since it was questioned above as an “anti-feature,” let me offer that there are very much important use cases for inputting by visual glyph selection in an authoring app, e.g. in creating illustrations for tutorials on the various stages of text shaping or COLR mechanics; or creating a glyph grid for a type specimen book, poster, or catalog; or creating a kanji handwriting tutorial with stroke order. Loss of portability across fonts is an acceptable limitation in these situations, as it would be also for any advanced typesetting in which stylistic features or alternate selections are employed.)
