### ISSUE TITLE
Missing ISO 639 codes for Chin

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#647]
The language system tag 'QIN ' should have the following ISO 639 codes added to its list: [biu](https://en.wikipedia.org/wiki/ISO_639:biu), [cek](https://en.wikipedia.org/wiki/ISO_639:cek), [cfm](https://en.wikipedia.org/wiki/ISO_639:cfm), [ckn](https://en.wikipedia.org/wiki/ISO_639:ckn), [clj](https://en.wikipedia.org/wiki/ISO_639:clj), [clt](https://en.wikipedia.org/wiki/ISO_639:clt), [csj](https://en.wikipedia.org/wiki/ISO_639:csj), [csv](https://en.wikipedia.org/wiki/ISO_639:csv), [cth](https://en.wikipedia.org/wiki/ISO_639:cth), [gnb](https://en.wikipedia.org/wiki/ISO_639:gnb), [hmr](https://en.wikipedia.org/wiki/ISO_639:hmr), [hra](https://en.wikipedia.org/wiki/ISO_639:hra), [lus](https://en.wikipedia.org/wiki/ISO_639:lus), [mwq](https://en.wikipedia.org/wiki/ISO_639:mwq), [pkh](https://en.wikipedia.org/wiki/ISO_639:pkh), [ral](https://en.wikipedia.org/wiki/ISO_639:ral), [rnl](https://en.wikipedia.org/wiki/ISO_639:rnl), [rtc](https://en.wikipedia.org/wiki/ISO_639:rtc), [sch](https://en.wikipedia.org/wiki/ISO_639:sch), [shl](https://en.wikipedia.org/wiki/ISO_639:shl), [smt](https://en.wikipedia.org/wiki/ISO_639:smt), [vap](https://en.wikipedia.org/wiki/ISO_639:vap), [weu](https://en.wikipedia.org/wiki/ISO_639:weu), [zyp](https://en.wikipedia.org/wiki/ISO_639:zyp).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662c6f54-f90c-52ed-dca2-0f0a0a49fee5
* Version Independent ID: 6aa33924-d45e-60c3-a9fd-e317ff662993
* Content: [Language system tags - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags)
* Content Source: [typographydocs/opentype/spec/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
What criteria for inclusion are you using?

**Comment by PeterCon** [comment]
Since it's unclear what the original intent was (and chances are the original intent was vague), and because it's not clear whether there are any relevant _typographic_ distinctions to be made, it's unclear how to be definitive.

Given HAL, removing flm from QIN seems reasonable. And given current classifications wrt rnl, not adding it to QIN also makes sense. 

You didn't include cey or pub. Any particular reasons? (I'm inclined to include those.)

**Comment by PeterCon** [comment]
Proposed revision for next version:

><del>bgr, cnh, cnw, czt, sez, tcp, csy, ctd, flm, pck, tcz, zom, cmr, dao, hlt, cka, cnk, mrh, cbl, cnb, csh</del><ins>bgr, biu, cek, cey, cfm, cbl, cka, ckn, clj, clt, cmr, cnb, cnh, cnk, cnw, csh, csj, csv, csy, ctd, cth, czt, dao, gnb, hlt, hmr, hra, lus, mrh, mwq, pck, pkh, pub, ral, rnl, rtc, sch, sez, shl, smt, tcp, tcz, vap, weu, zom, zyp</ins>

**Comment by dscorbett** [comment]
"cey" was already covered by #204. "pub" is Purum, which I mentioned at the end of my last comment. Do you consider Purum’s situation to be different from those of Kharam and Darlong?

**Comment by PeterCon** [comment]
Sorry, overlooked that last comment.

Ethnologue and Glottolog agree that pub is Kuki-Chin but not Northwestern Kuki-Chin.

**Comment by dscorbett** [comment]
You wrote “given current classifications wrt rnl, not adding it to QIN also makes sense”, but in the 1.8.4 beta, "rnl" in mapped to 'QIN '. Was that intentional?

**Comment by PeterCon** [comment]
No, I don't think so.

I'm wondering if rnl should be removed also from HAL?

**Comment by dscorbett** [comment]
Maybe it should. If you do remove it, also remove flm, because flm was deprecated and split into cfm and rnl, so any localization appropriate for flm should also be appropriate for rnl.

**Comment by PeterCon** [comment]
Done.
