### ISSUE TITLE
Nuqta, not "nukta"

### ISSUE THREAD

**Issue by getsnoopy** [MicrosoftDocs/typography-issues#649]
The name of the dot underneath some characters to incorporate foreign sounds is canonically spelled _nuqta_, not "nukta". The word itself is written with a nuqta (नुक़्ता), so it's ironic to have it be spelled "nukta" (नुक्ता). Please fix all the places on the page where it's spelled "nukta".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c1a0129-e23f-c785-89bc-25fb41b378c0
* Version Independent ID: b2a39f6a-94ed-b3ff-effb-17b2cc31b9e1
* Content: [Developing OpenType Fonts for Devanagari Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/devanagari)
* Content Source: [typographydocs/script-development/devanagari.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/devanagari.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
While _nuqta_ is the preferred romanisation, the Unicode Standard uses NUKTA consistently, and the OT spec follows this.

**Comment by PeterCon** [comment]
As mentioned, the specs describe implementation for Unicode text, and the name of the Unicode character, U+039C, is DEVANAGARI SIGN NUKTA.

https://www.unicode.org/charts/PDF/U0900.pdf
