### ISSUE TITLE
typo: missing space

### ISSUE THREAD

**Issue by schriftgestalt** [MicrosoftDocs/typography-issues#655]
There is a space missing in `fontsthat` (third paragraph in "Vertical Origin and Advance Height").

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0d85443a-e993-c018-410f-0ce03cfe9217
* Version Independent ID: 99b6d55e-c3fd-c3df-d6b5-451efd14bdb0
* Content: [vmtx — Vertical metrics table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec184beta/vmtx)
* Content Source: [typographydocs/opentype/otspec184beta/vmtx.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec184beta/vmtx.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Fixed. Thanks!
