### ISSUE TITLE
Typo: “a contextual substitutions”

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#656]
>_Recommended implementation:_ The default glyph for a vowel jamo is mapped into an alternate form required for conjoining in a syllable (GSUB lookup type 1, or a contextual substitutions that references a type 1 lookup).

“substitutions” should be “substitution”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a9e057b6-f1b1-c5ae-62ee-0529957f73b7
* Version Independent ID: 603e17b6-5d93-b5e9-3c8b-3075f6398830
* Content: [Registered features, u-z (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec184beta/features_uz)
* Content Source: [typographydocs/opentype/otspec184beta/features_uz.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec184beta/features_uz.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Fixed. Thanks.
