### ISSUE TITLE
Typo: “theletter”

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#657]
> _Example:_ In the formula <img src="https://docs.microsoft.com/en-us/typography/opentype/otspec184beta/images/abc.png" alt="Letter a with level 1 superscript b and level 2 superscript c">, the glyph for the letter b will be substituted with a script level 1 variant, and the glyph for theletter c _will be substituted with a script level 2 variant._

“theletter” should be “the letter”. Also, the end of the sentence need not be italicized.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c116360-ddbf-3768-3331-5cb3a2b5572c
* Version Independent ID: b5a581db-40db-77df-157e-c85b6e435033
* Content: [Registered features, p-t (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec184beta/features_pt)
* Content Source: [typographydocs/opentype/otspec184beta/features_pt.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec184beta/features_pt.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Fixed. Thanks!

**Comment by dscorbett** [comment]
Is the italicization intentional?
