### ISSUE TITLE
Missing ISO 639 codes for Banda

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#658]
The language system tag BAD0 (Banda) corresponds to the ISO 639 code bad. Banda is a language family, so the codes for its members should be listed too: [bbp](https://glottolog.org/resource/languoid/id/west2458), [bfl](https://glottolog.org/resource/languoid/id/band1345), [bjo](https://glottolog.org/resource/languoid/id/mids1243), [bpd](https://glottolog.org/resource/languoid/id/band1343), [bqk](https://glottolog.org/resource/languoid/id/band1342), [gox](https://glottolog.org/resource/languoid/id/gobu1238), [kuw](https://glottolog.org/resource/languoid/id/kpag1238), [liy](https://glottolog.org/resource/languoid/id/band1344), [lna](https://glottolog.org/resource/languoid/id/lang1318), [lnl](https://glottolog.org/resource/languoid/id/sout2787), [mnh](https://glottolog.org/resource/languoid/id/mono1270), [nue](https://glottolog.org/resource/languoid/id/ngun1266), [nuu](https://glottolog.org/resource/languoid/id/ngbu1241), [tor](https://glottolog.org/resource/languoid/id/togb1241), [yaj](https://glottolog.org/resource/languoid/id/band1348), [zmz](https://glottolog.org/resource/languoid/id/mban1263).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31fa774c-1048-54de-7334-b9e8665f2815
* Version Independent ID: 3502af1f-112a-038b-6ee5-1f7f21018586
* Content: [Language system tags (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec184beta/languagetags)
* Content Source: [typographydocs/opentype/otspec184beta/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec184beta/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Changed in 1.8.4 preview.
