### ISSUE TITLE
Missing ISO 639 codes for Ijo

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#659]
The language system tag 'IJO ' (Ijo languages) corresponds to the ISO 639 code ijo. The codes for its members should be listed too: [iby](https://glottolog.org/resource/languoid/id/iban1261), [ije](https://glottolog.org/resource/languoid/id/bise1238), [ijn](https://glottolog.org/resource/languoid/id/kala1381), [ijs](https://glottolog.org/resource/languoid/id/sout2774), [nkx](https://glottolog.org/resource/languoid/id/nkor1239), [okd](https://glottolog.org/resource/languoid/id/okod1238), [okr](https://glottolog.org/resource/languoid/id/kiri1254), [orr](https://glottolog.org/resource/languoid/id/orum1241). ([ijc](https://glottolog.org/resource/languoid/id/izon1238) is already listed.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31fa774c-1048-54de-7334-b9e8665f2815
* Version Independent ID: 3502af1f-112a-038b-6ee5-1f7f21018586
* Content: [Language system tags (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec184beta/languagetags)
* Content Source: [typographydocs/opentype/otspec184beta/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec184beta/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Changed in 1.8.4 preview.
