### ISSUE TITLE
Missing ISO 639 codes for Tamashek

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#660]
The language system tag 'TMH ' (Tamashek) corresponds to the ISO 639 code tmh. Tamashek a.k.a. Tuareg is a macrolanguage, so the codes for its individual languages should be listed too: [taq](https://glottolog.org/resource/languoid/id/tama1365), [thv](https://glottolog.org/resource/languoid/id/taha1241), [thz](https://glottolog.org/resource/languoid/id/taya1257), [ttq](https://glottolog.org/resource/languoid/id/tawa1286).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31fa774c-1048-54de-7334-b9e8665f2815
* Version Independent ID: 3502af1f-112a-038b-6ee5-1f7f21018586
* Content: [Language system tags (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec184beta/languagetags)
* Content Source: [typographydocs/opentype/otspec184beta/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec184beta/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Changed for 1.8.4
