### ISSUE TITLE
Confused mappings for 'AKA ' and 'TWI '

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#661]
The language system tag 'AKA ' (Akan) is mapped to the ISO 639 code "aka". 'TWI ' (Twi) is mapped to both "aka" and "twi". Twi is a dialect of Akan; it is odd for the more specific language system tag to map to the more generic ISO 639 code. I recommend removing the "aka" mapping from 'TWI '. I recommend adding mappings to 'AKA ' for [fat](https://glottolog.org/resource/languoid/id/fant1241) and [twi](https://glottolog.org/resource/languoid/id/twii1234), the two dialects that have codes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31fa774c-1048-54de-7334-b9e8665f2815
* Version Independent ID: 3502af1f-112a-038b-6ee5-1f7f21018586
* Content: [Language system tags (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec184beta/languagetags)
* Content Source: [typographydocs/opentype/otspec184beta/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec184beta/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
>Twi is a dialect of Akan...

So TWI implies aka. (Of course, the inverse implication, aka -> TWI, wouldn't be valid.)

The registry page doesn't say that the "corresponding ISO 639" should be treated as mappings in one direction only. But if there's an expectation in any case that people need to do some 639 homework, perhaps there may be less risk of confusion if the row for TWI mention only twi and not aka.

As for the entry for AKA, why add fat and twi when there are separate tags FAT and TWI?

(Btw, this is a goofy case in which ISO 639-1 has a code for a dialect.)

**Comment by dscorbett** [comment]
Currently, this page maps from language system tags of greater scope to ISO 639 codes of narrower scope. For example, Slavey includes North Slavey and South Slavey, so 'SLA ' is mapped to both "scs" and "xsl", whereas neither 'SCS ' nor 'SSL ' is mapped to "den". Why should Akan and Twi be the sole exception?

**Comment by PeterCon** [comment]
>Why should Akan and Twi be the sole exception?

You're right: this shouldn't be an exception.

**Comment by PeterCon** [comment]
Changed for 1.8.4. 

Also added a note to capture that principle of  LS -> 639 going to equal or narrower scope, not broader scope.
