### ISSUE TITLE
ISO 639 code "mly" is deprecated

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#662]
The mapping of 'MLY ' to "mly" was added in the 1.8.4 beta. I recommended removing "mly". That code [was deprecated](https://iso639-3.sil.org/sites/iso639-3/files/change_requests/2007/2007-183.pdf) as not clearly referring to any particular language or group of languages.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31fa774c-1048-54de-7334-b9e8665f2815
* Version Independent ID: 3502af1f-112a-038b-6ee5-1f7f21018586
* Content: [Language system tags (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec184beta/languagetags)
* Content Source: [typographydocs/opentype/otspec184beta/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec184beta/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Hmm... That was added in the same change that was done for #274. Not sure now why it was added, but agree to drop it.

**Comment by PeterCon** [comment]
Changed for 1.8.4
