### ISSUE TITLE
Missing ISO 639 codes for Bamileke

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#663]
The language system tag 'BML ' (Bamileke) should correspond to the ISO 639 collection code [bai](https://glottolog.org/resource/languoid/id/bami1239) and to these individual language codes: [bbj](https://glottolog.org/resource/languoid/id/ghom1247), [bko](https://glottolog.org/resource/languoid/id/kwaa1265), [byv](https://glottolog.org/resource/languoid/id/medu1238), [fmp](https://glottolog.org/resource/languoid/id/fefe1239), [jgo](https://glottolog.org/resource/languoid/id/ngom1272), [nla](https://glottolog.org/resource/languoid/id/ngom1271), [nnh](https://glottolog.org/resource/languoid/id/ngie1241), [nnz](https://glottolog.org/resource/languoid/id/ndan1241), [nwe](https://glottolog.org/resource/languoid/id/ngwe1238), [xmg](https://glottolog.org/resource/languoid/id/meng1264), [ybb](https://glottolog.org/resource/languoid/id/yemb1246).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31fa774c-1048-54de-7334-b9e8665f2815
* Version Independent ID: 3502af1f-112a-038b-6ee5-1f7f21018586
* Content: [Language system tags (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec184beta/languagetags)
* Content Source: [typographydocs/opentype/otspec184beta/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec184beta/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Ethnologue and Glottolog differ wrt classification of byv: Ethnologue puts it in a sister node of the hierarchy:

Niger-Congo, Atlantic-Congo, Volta-Congo, Benue-Congo, Bantoid, Southern, Wide Grassfields, Narrow Grassfields, Mbam-Nkam, `Nun`

Not

Niger-Congo, Atlantic-Congo, Volta-Congo, Benue-Congo, Bantoid, Southern, Wide Grassfields, Narrow Grassfields, Mbam-Nkam, `Bamileke`

**Comment by PeterCon** [comment]
Interestingly, Ethnologue lists one of the alternate names as "Bamileke-Medumba".

**Comment by PeterCon** [comment]
Changes for 1.8.4.
