### ISSUE TITLE
Missing ISO 639 codes for Nahuatl

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#665]
The language system tag 'NAH ' (Nahuatl) corresponds to the ISO 639 code nah. Nahuatl is a language family, so the codes for its members should be listed too: [azd](http://glottolog.org/glottolog?iso=azd), [azn](http://glottolog.org/glottolog?iso=azn), [azz](http://glottolog.org/glottolog?iso=azz), [naz](http://glottolog.org/glottolog?iso=naz), [nch](http://glottolog.org/glottolog?iso=nch), [nci](http://glottolog.org/glottolog?iso=nci), [ncj](http://glottolog.org/glottolog?iso=ncj), [ncl](http://glottolog.org/glottolog?iso=ncl), [ncx](http://glottolog.org/glottolog?iso=ncx), [ngu](http://glottolog.org/glottolog?iso=ngu), [nhc](http://glottolog.org/glottolog?iso=nhc), [nhe](http://glottolog.org/glottolog?iso=nhe), [nhg](http://glottolog.org/glottolog?iso=nhg), [nhi](http://glottolog.org/glottolog?iso=nhi), [nhk](http://glottolog.org/glottolog?iso=nhk), [nhm](http://glottolog.org/glottolog?iso=nhm), [nhn](http://glottolog.org/glottolog?iso=nhn), [nhp](http://glottolog.org/glottolog?iso=nhp), [nhq](http://glottolog.org/glottolog?iso=nhq), [nht](http://glottolog.org/glottolog?iso=nht), [nhv](http://glottolog.org/glottolog?iso=nhv), [nhw](http://glottolog.org/glottolog?iso=nhw), [nhx](http://glottolog.org/glottolog?iso=nhx), [nhy](http://glottolog.org/glottolog?iso=nhy), [nhz](http://glottolog.org/glottolog?iso=nhz), [nlv](http://glottolog.org/glottolog?iso=nlv), [npl](http://glottolog.org/glottolog?iso=npl), [nsu](http://glottolog.org/glottolog?iso=nsu), [nuz](http://glottolog.org/glottolog?iso=nuz).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31fa774c-1048-54de-7334-b9e8665f2815
* Version Independent ID: 3502af1f-112a-038b-6ee5-1f7f21018586
* Content: [Language system tags (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec184beta/languagetags)
* Content Source: [typographydocs/opentype/otspec184beta/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec184beta/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Changes for 1.8.4
