### ISSUE TITLE
Missing ISO 639 codes for Karen

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#666]
The language system tag 'KRN ' (Karen) corresponds to the ISO 639 code kar. Karen is a language family, so the codes for its members should be listed too: [blk](http://glottolog.org/glottolog?iso=blk), [bwe](http://glottolog.org/glottolog?iso=bwe), [eky](http://glottolog.org/glottolog?iso=eky), [ghk](http://glottolog.org/glottolog?iso=ghk), [jkm](http://glottolog.org/glottolog?iso=jkm), [jkp](https://glottolog.org/resource/languoid/id/paku1238), [kjp](http://glottolog.org/glottolog?iso=kjp), [kjt](http://glottolog.org/glottolog?iso=kjt), [ksw](http://glottolog.org/glottolog?iso=ksw), [kvl](http://glottolog.org/glottolog?iso=kvl), [kvq](http://glottolog.org/glottolog?iso=kvq), [kvt](http://glottolog.org/glottolog?iso=kvt), [kvu](http://glottolog.org/glottolog?iso=kvu), [kvy](http://glottolog.org/glottolog?iso=kvy), [kxf](http://glottolog.org/glottolog?iso=kxf), [kxk](http://glottolog.org/glottolog?iso=kxk), [kyu](http://glottolog.org/glottolog?iso=kyu), [pdu](http://glottolog.org/glottolog?iso=pdu), [pwo](http://glottolog.org/glottolog?iso=pwo), [pww](http://glottolog.org/glottolog?iso=pww), [wea](http://glottolog.org/glottolog?iso=wea).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31fa774c-1048-54de-7334-b9e8665f2815
* Version Independent ID: 3502af1f-112a-038b-6ee5-1f7f21018586
* Content: [Language system tags (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec184beta/languagetags)
* Content Source: [typographydocs/opentype/otspec184beta/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec184beta/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Changed for 1.8.4.
