### ISSUE TITLE
Basque language system, EUQ: why add ISO 639 ID euq?

### ISSUE THREAD

**Issue by PeterCon** [MicrosoftDocs/typography-issues#667]
The language system tag EUQ for Basque was added in OT 1.5 (2008). The ISO 639 data was first added in OT 1.6 (2009), and for the Basque entry the ISO 639 ID listed was eus, which is included in 639-3 and is also the "T" identifier for Basque in 639-2.

ISO 639-5 was published in 2008 and includes the collection ID euq for "Basque (family)". This is a bit unusual since Basque is a language isolate with no associated language family commonly recognized among linguists.

When the Basque language system tag was registered, it's unclear why EUQ was chosen for the tag and not EUS, given the previously-existing ISO 639-2/-3 ID eus.

At any rate, for OT 1.8.4, the current draft proposes adding the 639 ID euq in the entry for EUQ. Presumably that's because it would generally seem appropriate to list a 639 ID xyz for a tag XYZ whenever there is a correspondence. In this case, however, it's not clear that listing euq is appropriate: 

- Language system tags tend to be created for specific languages more so than language families. If EUQ corresponds to the specific language Basque, then the 639 column should list the individual language ID (equal scope), not a collection ID (broader scope).
- In this particular case, there really isn't any concept of a language *family*. The inclusion of "Basque (family)" in 639-5 appears to be intended to have there be genetic collections in part 5 that cover every individual language in parts 1 and 2. (639-5 also includes jpx apparently for this reason.)

So, remove euq from the 639 data for EUQ?

@dscorbett: What do you think?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31fa774c-1048-54de-7334-b9e8665f2815
* Version Independent ID: 3502af1f-112a-038b-6ee5-1f7f21018586
* Content: [Language system tags (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec184beta/languagetags)
* Content Source: [typographydocs/opentype/otspec184beta/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec184beta/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by dscorbett** [comment]
I think removing "euq" is reasonable.

**Comment by PeterCon** [comment]
Changed for 1.8.4
