### ISSUE TITLE
Missing ISO 639 codes for Berber

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#669]
The language system tag 'BBR ' (Berber) should correspond to the ISO 639 collection code [ber](https://glottolog.org/resource/languoid/id/berb1260) and to these individual language codes: [auj](http://glottolog.org/glottolog?iso=auj), [cnu](http://glottolog.org/glottolog?iso=cnu), [gha](http://glottolog.org/glottolog?iso=gha), [gho](http://glottolog.org/glottolog?iso=gho), [grr](http://glottolog.org/glottolog?iso=grr), [jbe](http://glottolog.org/glottolog?iso=jbe), [jbn](http://glottolog.org/glottolog?iso=jbn), [kab](http://glottolog.org/glottolog?iso=kab), [mzb](http://glottolog.org/glottolog?iso=mzb), [oua](http://glottolog.org/glottolog?iso=oua), [rif](http://glottolog.org/glottolog?iso=rif), [sds](http://glottolog.org/glottolog?iso=sds), [shi](http://glottolog.org/glottolog?iso=shi), [shy](http://glottolog.org/glottolog?iso=shy), [siz](http://glottolog.org/glottolog?iso=siz), [sjs](http://glottolog.org/glottolog?iso=sjs), [swn](http://glottolog.org/glottolog?iso=swn), [taq](http://glottolog.org/glottolog?iso=taq), [tez](http://glottolog.org/glottolog?iso=tez), [thv](http://glottolog.org/glottolog?iso=thv), [thz](http://glottolog.org/glottolog?iso=thz), [tia](http://glottolog.org/glottolog?iso=tia), [tjo](http://glottolog.org/glottolog?iso=tjo), [tmh](http://glottolog.org/glottolog?iso=tmh), [ttq](http://glottolog.org/glottolog?iso=ttq), [tzm](http://glottolog.org/glottolog?iso=tzm), [zen](http://glottolog.org/glottolog?iso=zen), [zgh](http://glottolog.org/glottolog?iso=zgh).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31fa774c-1048-54de-7334-b9e8665f2815
* Version Independent ID: 3502af1f-112a-038b-6ee5-1f7f21018586
* Content: [Language system tags (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec184beta/languagetags)
* Content Source: [typographydocs/opentype/otspec184beta/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec184beta/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
I note that one of the "individual" languages is actually a 639-3 macrolanguage.

Changed for 1.8.4.
