### ISSUE TITLE
'TIB ' is mapped to ISO 639-2/B "tib"

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#671]
The language system tag 'TIB ' (Tibetan) is mapped to the ISO 639-2/B code "tib".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31fa774c-1048-54de-7334-b9e8665f2815
* Version Independent ID: 3502af1f-112a-038b-6ee5-1f7f21018586
* Content: [Language system tags (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec184beta/languagetags)
* Content Source: [typographydocs/opentype/otspec184beta/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec184beta/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Changed for 1.8.4.
