### ISSUE TITLE
Missing ISO 639 codes for creoles and pidgins

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#672]
The language system tag 'CPP ' corresponds to the ISO 639 codes crp, cpe, cpf, and cpp. The codes for individual creoles and pidgins should also be listed.

English-based (cpe)

* [afs](http://glottolog.org/glottolog?iso=afs)
* [aig](http://glottolog.org/glottolog?iso=aig)
* [bah](http://glottolog.org/glottolog?iso=bah)
* [bis](http://glottolog.org/glottolog?iso=bis)
* [bjs](http://glottolog.org/glottolog?iso=bjs)
* [bzj](http://glottolog.org/glottolog?iso=bzj)
* [bzk](http://glottolog.org/glottolog?iso=bzk)
* [cpi](http://glottolog.org/glottolog?iso=cpi)
* [djk](http://glottolog.org/glottolog?iso=djk)
* [fpe](http://glottolog.org/glottolog?iso=fpe)
* [gcl](http://glottolog.org/glottolog?iso=gcl)
* [gpe](http://glottolog.org/glottolog?iso=gpe)
* [gul](http://glottolog.org/glottolog?iso=gul)
* [gyn](http://glottolog.org/glottolog?iso=gyn)
* [hwc](http://glottolog.org/glottolog?iso=hwc)
* [icr](http://glottolog.org/glottolog?iso=icr)
* [jam](http://glottolog.org/glottolog?iso=jam)
* [kri](http://glottolog.org/glottolog?iso=kri)
* [kww](http://glottolog.org/glottolog?iso=kww)
* [lir](http://glottolog.org/glottolog?iso=lir)
* [ngm](http://glottolog.org/glottolog?iso=ngm)
* [njt](http://glottolog.org/glottolog?iso=njt)
* [pcm](http://glottolog.org/glottolog?iso=pcm)
* [pih](http://glottolog.org/glottolog?iso=pih)
* [pis](http://glottolog.org/glottolog?iso=pis)
* [rop](http://glottolog.org/glottolog?iso=rop)
* [srm](http://glottolog.org/glottolog?iso=srm)
* [srn](http://glottolog.org/glottolog?iso=srn)
* [svc](http://glottolog.org/glottolog?iso=svc)
* [tch](http://glottolog.org/glottolog?iso=tch)
* [tcs](http://glottolog.org/glottolog?iso=tcs)
* [tgh](http://glottolog.org/glottolog?iso=tgh)
* [tpi](http://glottolog.org/glottolog?iso=tpi)
* [trf](http://glottolog.org/glottolog?iso=trf)
* [vic](http://glottolog.org/glottolog?iso=vic)
* [wes](http://glottolog.org/glottolog?iso=wes)

French-based (cpf)

* [acf](http://glottolog.org/glottolog?iso=acf)
* [cks](http://glottolog.org/glottolog?iso=cks)
* [crs](http://glottolog.org/glottolog?iso=crs)
* [gcf](http://glottolog.org/glottolog?iso=gcf)
* [gcr](http://glottolog.org/glottolog?iso=gcr)
* [hat](http://glottolog.org/glottolog?iso=hat)
* [kmv](http://glottolog.org/glottolog?iso=kmv)
* [lou](http://glottolog.org/glottolog?iso=lou)
* [mfe](http://glottolog.org/glottolog?iso=mfe)
* [rcf](http://glottolog.org/glottolog?iso=rcf)
* [scf](http://glottolog.org/glottolog?iso=scf)
* [tas](http://glottolog.org/glottolog?iso=tas)

Portuguese-based (cpp)

* [aoa](http://glottolog.org/glottolog?iso=aoa)
* [cri](http://glottolog.org/glottolog?iso=cri)
* [fab](http://glottolog.org/glottolog?iso=fab)
* [idb](http://glottolog.org/glottolog?iso=idb)
* [kea](http://glottolog.org/glottolog?iso=kea)
* [mcm](http://glottolog.org/glottolog?iso=mcm)
* [mzs](http://glottolog.org/glottolog?iso=mzs)
* [pap](http://glottolog.org/glottolog?iso=pap)
* [pov](http://glottolog.org/glottolog?iso=pov)
* [pre](http://glottolog.org/glottolog?iso=pre)
* [tmg](http://glottolog.org/glottolog?iso=tmg)
* [tvy](http://glottolog.org/glottolog?iso=tvy)
* [vkp](http://glottolog.org/glottolog?iso=vkp)

Dutch-based

* [brc](http://glottolog.org/glottolog?iso=brc)
* [dcr](http://glottolog.org/glottolog?iso=dcr)
* [jvd](http://glottolog.org/glottolog?iso=jvd)
* [pey](http://glottolog.org/glottolog?iso=pey)
* [skw](http://glottolog.org/glottolog?iso=skw)

Malay-based

* [abs](http://glottolog.org/glottolog?iso=abs)
* [bew](http://glottolog.org/glottolog?iso=bew)
* [bpl](http://glottolog.org/glottolog?iso=bpl)
* [bpq](http://glottolog.org/glottolog?iso=bpq)
* [ccm](http://glottolog.org/glottolog?iso=ccm)
* [goq](http://glottolog.org/glottolog?iso=goq)
* [lrt](http://glottolog.org/glottolog?iso=lrt)
* [max](http://glottolog.org/glottolog?iso=max)
* [mbf](http://glottolog.org/glottolog?iso=mbf)
* [mfp](http://glottolog.org/glottolog?iso=mfp)
* [mkn](http://glottolog.org/glottolog?iso=mkn)
* [msi](http://glottolog.org/glottolog?iso=msi)
* [pea](http://glottolog.org/glottolog?iso=pea)
* [pmy](http://glottolog.org/glottolog?iso=pmy)
* [sci](http://glottolog.org/glottolog?iso=sci)
* [xmm](http://glottolog.org/glottolog?iso=xmm)

Other

* [bxo](http://glottolog.org/glottolog?iso=bxo)
* [cbk](http://glottolog.org/glottolog?iso=cbk)
* [ccl](http://glottolog.org/glottolog?iso=ccl)
* [chn](http://glottolog.org/glottolog?iso=chn)
* [dep](http://glottolog.org/glottolog?iso=dep)
* [fng](http://glottolog.org/glottolog?iso=fng)
* [gac](http://glottolog.org/glottolog?iso=gac)
* [gib](http://glottolog.org/glottolog?iso=gib)
* [hca](http://glottolog.org/glottolog?iso=hca)
* [hmo](http://glottolog.org/glottolog?iso=hmo)
* [ihb](http://glottolog.org/glottolog?iso=ihb)
* [kcn](http://glottolog.org/glottolog?iso=kcn)
* [mod](http://glottolog.org/glottolog?iso=mod)
* [mud](http://glottolog.org/glottolog?iso=mud)
* [nag](http://glottolog.org/glottolog?iso=nag)
* [nef](http://glottolog.org/glottolog?iso=nef)
* [onx](http://glottolog.org/glottolog?iso=onx)
* [oor](http://glottolog.org/glottolog?iso=oor) (maybe)
* [pga](http://glottolog.org/glottolog?iso=pga)
* [pln](http://glottolog.org/glottolog?iso=pln)
* [pml](http://glottolog.org/glottolog?iso=pml)
* [sta](http://glottolog.org/glottolog?iso=sta)
* [uln](http://glottolog.org/glottolog?iso=uln)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 31fa774c-1048-54de-7334-b9e8665f2815
* Version Independent ID: 3502af1f-112a-038b-6ee5-1f7f21018586
* Content: [Language system tags (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec184beta/languagetags)
* Content Source: [typographydocs/opentype/otspec184beta/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec184beta/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Changed for 1.8.4
