### ISSUE TITLE
'legal' vs. 'valid'

### ISSUE THREAD

**Issue by lemzwerg** [MicrosoftDocs/typography-issues#675]
There are two occurrences of 'legal' on the 'cmap' page that should be replaced with 'valid', which is both more concise and more understandable for non-English speakers.

Ditto for 'illegal' vs. 'invalid'.

Some other pages are also affected.

**Comment by PeterCon** [comment]
Changes made in these pages for 1.8.4:
* cff2charstr
* cmap
* ltsh
* prep
* tt_instructing_glyphs
* tt_instructions
