### ISSUE TITLE
[Data types] Time zone missing from LONGDATETIME specification

### ISSUE THREAD

**Issue by NorbertLindenberg** [MicrosoftDocs/typography-issues#677]
The description of the LONGDATETIME data type fails to specify the time zone of the base time, 12:00 midnight, January 1, 1904.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a1bda96-a268-b684-6cea-9b0c7be6f24e
* Version Independent ID: 36485fec-f05d-3984-6da8-ff2dd2799041
* Content: [OpenType font file - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otff#font-tables)
* Content Source: [typographydocs/opentype/spec/otff.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otff.md)
* Product: **typography**

**Comment by PeterCon** [comment]
Changed for 1.8.4—see <https://docs.microsoft.com/en-us/typography/opentype/otspec184beta/delta/otff.html>.

**Comment by NorbertLindenberg** [comment]
The new verbiage,

> LONGDATETIME values should be in Coordinated Universal Time (UTC), and UTC can be assumed when a value in a font is read.

is too vague for a specification. In [specification language](https://tools.ietf.org/html/rfc2119), "should" means "that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications must be understood and carefully weighed before choosing a different course". For LONGDATETIME, I have a  really hard time imagining circumstances in which using a non-standard time zone could be beneficial. And "can be assumed" just means nothing at all.

The specification of the `head` table describes the `created` and `modified` as "Number of seconds since 12:00 midnight that started January 1st 1904 in GMT/UTC time zone". That’s clear and concise and should work for LONGDATETIME itself. Of course, the `head` table description then drops the ball on "signed"...

**Comment by PeterCon** [comment]
A problem to work around is that the TT and OT specs have underspecified the type in this regard for 30 years.

However, the only uses of the type are in the head table, and it was updated in OT 1.7 to specify UTC. So, on that basis, it seems reasonable to state that where LONGDATETIME is declared. I'll make that change shortly.

>Of course, the head table description then drops the ball on "signed"...

Not sure what that's referring to.

**Comment by PeterCon** [comment]
OTFF page updated.

**Comment by NorbertLindenberg** [comment]
>> Of course, the head table description then drops the ball on "signed"...
> Not sure what that's referring to.

In the Data Types section, LONGDATETIME is described as a "signed 64-bit integer". In the head table specification, only "64-bit integer" is used, leaving it open whether the type is signed or unsigned.

**Comment by PeterCon** [comment]
Ah! Fixed that. (The type shouldn't get declared in two places.) Thanks.
