### ISSUE TITLE
Improve ClearType

### ISSUE THREAD

**Issue by mjarsky** [MicrosoftDocs/typography-issues#68]
I would like to see much better rendering of type in Windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bf2300b8-71e0-a6fe-b12f-f47b2b9564c1
* Version Independent ID: e771c103-3be0-7747-0084-be7bdef7bf63
* Content: [Microsoft ClearType - Typography](https://docs.microsoft.com/en-us/typography/cleartype/)
* Content Source: [typographydocs/cleartype/index.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/cleartype/index.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by PeterCon** [comment]
This is product feedback, not a doc issue. For Windows 10, please provide this feedback using the Feedback Hub.

**Comment by PiotrGrochowski** [comment]
You can get much better rendering of type in Windows by disabling ClearType.

**Comment by PeterCon** [comment]
@PiotrGrochowski: This is product feedback, not a doc issue. For Windows 10, please provide this feedback using the Feedback Hub.
