### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by Mohkokunkku** [MicrosoftDocs/typography-issues#681]
Hello folks!

Its a little bit difficult to find clear information about Font Licensing. 

We have a .Net Core based web application that runs in Linux container. Application converts .docx files to .pdf files with a support of Aspose.Word library. The result .pdf-file ain´t looking 100% like original .docx file mostly because of Linux font-set. 

Is it ok to copy Microsoft Fonts to this Linux container in use that our .pdf documents would look more like original .docx files?

**Comment by alib-ms** [comment]
Hi, 
Please have a look at the [font-faq](https://docs.microsoft.com/en-us/typography/fonts/font-faq) page.

**Comment by Mohkokunkku** [comment]
Hello, 

I have read this many times but maybe it is little bit difficult to decode this kind of text with my english. 

If I am right it is okay to add Microsoft Fonts to Linux Docker because we are embedding them to documents?

**Comment by FontBoss** [comment]
Hi, I am not familiar with this technology. I'm assuming "Linux Docker" runs on Windows as moving the fonts to a Linux machine or server is not permitted. If Linux Docker creates individual document files or PDFs with fonts embedded within them then this might be allowed. If it just bundles up files for redistribution then that is not allowed. The only allowed distribution of the fonts is when they are embedded within document files, even then there are restrictions.

**Comment by PeterCon** [comment]
Unless it is Linux Subsystem for Windows running in a Windows operating system environment, the Linux environment would constitute a different operating system and would not be covered by the Windows EULA.
