### ISSUE TITLE
nirmala

### ISSUE THREAD

**Issue by sanatoda** [MicrosoftDocs/typography-issues#682]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6e5c1c5b-7906-5a2b-714b-d49a71d69069
* Version Independent ID: 4959c5ab-fd37-bd98-337d-418ceb6bcb5f
* Content: [Nirmala UI font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/nirmala-ui)
* Content Source: [typographydocs/font-list/nirmala-ui.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/nirmala-ui.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
I am sorry, but there is no comments in your message.
