### ISSUE TITLE
Two ebdt.htm entries in 1.8.4 change log

### ISSUE THREAD

**Issue by sairuspatel** [MicrosoftDocs/typography-issues#684]
OT 1.8.4 change log has 2 listing of ebdt.htm. Combine them into one, as with other files.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1246c6a8-e7ce-4fd4-a36a-d1ba16e96972
* Version Independent ID: 8a238a07-c34f-724e-2ca5-cd2a77354c91
* Content: [OpenType specification change log (OpenType 1.8.4) (delta) - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec184beta/changes)
* Content Source: [typographydocs/opentype/otspec184beta/changes.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec184beta/changes.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Fixed. Thanks.
