### ISSUE TITLE
post table version 2.0 documentation does not adequately describe the data and how to parse it

### ISSUE THREAD

**Issue by Pomax** [MicrosoftDocs/typography-issues#686]
The post table version 2 documentation on https://docs.microsoft.com/en-ca/typography/opentype/spec/post#version-20 has several issues that prevent it from making it clear how to parse this table.

The field specification for all fields that are unique to this table is:

Type | Name | Description
-- | -- | --
uint16 | numGlyphs | Number of glyphs (this should be the same as numGlyphs in 'maxp' table).
uint16 | glyphNameIndex[numGlyphs]. | This is not an offset, but is the ordinal number of the glyph in 'post' string tables.
int8 | names[numberNewGlyphs] | Glyph names with length bytes [variable] (a Pascal string).

This table has three issues:

1. `glyphNameIndex`'s description is odd: an array is not an offset, so there's text missing (what is meant is that the values in the array are not to be treated as offsets, but represent array indices). Additionally, "the ordinal number of the glyph in 'post' string tables" talks about "string tables", which are not a thing ("string table" does not occur anywhere else in the post table documentation): can this be rewritten to a concise description of what `glyphNameIndex` really is?
2. the `numberNewGlyphs` value has no meaning: it is not defined anywhere, it is not described in plain text anywhere, and appears to be the only occurrence of that word not just on the page, but any page in the opentype documentation: what is this value? i.e. where can it be looked up, or which values can it be derived from?
3. what does "Glyph names with length bytes " mean? Either `length` is the value encoded in `names` (in which case: where does that glyph's string data actually start so that `length` bytes can be read from that position) or `length` for each glyph name has to come from somewhere else (in which case: where?)

Furthermore, the description uses terminology that does not reflect how to actually use the table just given:

>This font file contains glyphs not in the standard Macintosh set, or the ordering of the glyphs in the font file differs from the standard Macintosh set. The glyph name array maps the glyphs in this font to name index. If the name index is between 0 and 257, treat the name index as a glyph index in the Macintosh standard order. If the name index is between 258 and 65535, then subtract 258 and use that to index into the list of Pascal strings at the end of the table. Thus a given font may map some of its glyphs to the standard glyph names, and some to its own names.

The first sentence in this paragraph is fine.

>The glyph name array maps the glyphs in this font to name index.

This sentence is not fine: what is the "glyph name array"? The naming authority is the above table, so either this is `glyphNameIndex`, or `names`. If it's `names` then this sentence is still curious because it doesn't (`names` does not map glyphs to name index, `glyphNameIndex` does). If it is `glyphNameIndex` then the term "glyph name array" is misleading at best.

Can this sentence be rewritten to something precise, using the field names as specified in the data structure table?

>  If the name index is between 0 and 257, treat the name index as a glyph index in the Macintosh standard order

this sentence is fine, but it feels like we're missing an entire section that explains the `glyphNameIndex`: if we have a glyphid of, say, 4, do we simply access `glyphNameIndex[4]` to get the associated index, or do we need to add/subtract some fixed value _before_ we run the lookup?

>  If the name index is between 258 and 65535, then subtract 258 and use that to index into the list of Pascal strings at the end of the table.

This sentence is not precise enough, and should be updated so that "the list of Pascal strings at the end of the table" is replaced by "the `names` array". It has not been stated that `names` constituted the end of the table anywhere, and future versions (if there ever are any) could invalidate this sentence. Directly referring to `names` solves two problems with this sentence.

> Thus a given font may map some of its glyphs to the standard glyph names, and some to its own names.

This sentence feels out of place here, and is probably better moved to the start of the section on version 2, made part of the explanation of why the version 2 post table exist.

Finally, it would help this part of the documentation a lot if an example were specified on how to concretely look up a glyph's name in this table, because right now this text seems of much lower quality than the rest of the spec, and as someone who's trying to implement post table name lookups, this text appears not to explain the actual data structure, and how to use it.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c682af48-1252-0ffc-c6d7-c73130b2a690
* Version Independent ID: ed9e6d48-434b-ab0c-2fdf-e2700cde9cb2
* Content: [post — PostScript Table specification - Typography](https://docs.microsoft.com/en-ca/typography/opentype/spec/post)
* Content Source: [typographydocs/opentype/spec/post.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/post.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Good feedback. This is the last day of the beta review period for OT 1.8.4, so fixes may need to wait for OT 1.9. But I'll review.

**Comment by PeterCon** [comment]
@Pomax  I've prepared draft revisions for OT 184. If you could review right away, that would be helpful. You can find the beta content [here](https://docs.microsoft.com/en-us/typography/opentype/otspec184beta/ot184beta). Thanks

**Comment by Pomax** [comment]
Nice!

Some observations:

- For the sentence about indices between 0 and 257, that probably needs "inclusive", and might be good to link the words "Macintosh glyph name" to the page with that list (is that part of OpenType these days? If not, that might be an external link to Apple's old docs)
- the string format explanation is perfect!

**Comment by PeterCon** [comment]
>probably needs "inclusive"

Adding.

>might be good to link the words "Macintosh glyph name" to the page with that list

That's mentioned, with link provided, in the previous section.

**Comment by Pomax** [comment]
ah, right, so it is
