### ISSUE TITLE
spec index is missing a link to the change log

### ISSUE THREAD

**Issue by Pomax** [MicrosoftDocs/typography-issues#687]
It looks like "change log" in "Updates to this specification are noted in the change log." is not hyperlinked to the actual change log

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2690ef79-7c15-86fa-58bb-500e4f5a9b94
* Version Independent ID: 12a633e1-c7b9-87ad-fd11-1bc4d12bcbb2
* Content: [OpenType specification - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/)
* Content Source: [typographydocs/opentype/spec/index.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/index.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Fixed for [OT 1.8.4](https://docs.microsoft.com/en-us/typography/opentype/otspec184beta/ot184beta)
