### ISSUE TITLE
Possible typo in GPOS description in OpenType specification

### ISSUE THREAD

**Issue by scymtym** [MicrosoftDocs/typography-issues#688]
In the OpenType specification, in the description of the GPOS table, the first sentence of the "Mark-To-Ligature Attachment Positioning Format 1: Mark-to-Ligature Attachment" subsection reads:

> The MarkLigPosFormat1 subtable begins with a format identifier (posFormat) and two offsets (markCoverageOffset, **baseCoverageOffset**) to Coverage tables that list all the mark glyphs (markCoverage) and Ligature glyphs (ligatureCoverage) referenced in the subtable.

Based on the surrounding text and in particular the table "MarkLigPosFormat1 Subtable", I believe the highlighted word should be "ligatureCoverageOffset".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f748ff4-44a6-6395-e0ce-d249b8c9541b
* Version Independent ID: b80d0359-5657-632b-29e8-142c06902001
* Content: [GPOS — Glyph Positioning Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/gpos)
* Content Source: [typographydocs/opentype/spec/gpos.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gpos.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Thanks. Fixed for OT version 1.8.4.
