### ISSUE TITLE
Devanagari glyphs $0956 and $0957 attach erratically to any Base Glyphs in Word 2016, Word 2019, office 365

### ISSUE THREAD

**Issue by advaita56** [MicrosoftDocs/typography-issues#689]
[
1. Bug1 in OPENTYPE Devanagari scripts “dev” or “dev2”
2. Using Microsoft Word 2016, 2019, Office 365 on Windows 7 and Windows 10
3. Font Sanskrit2020.otf https://sourceforge.net/projects/advaita-sharada-font/files/Devanagari/
4. Devanagari Unicode Block $0900 to $097F
a)	glyphs $0956, $0957 cannot be anchored or precisely positioned for any combination using GPOS / GSUB. 
b)	The geometric shape $25CC keeps getting displayed for certain combinations.
5. Whereas glyph $0952 can be accurately positioned and attached and the geometric shape $25CC is never in the way.
6. Using Microsoft Word 2010 on Windows 7 the glyphs $0956 and $0957 do get attached. The geometric shape is not displayed. However the anchor positioning does not work.
]
---
[bug1 in OpenType Devanagari script.docx](https://github.com/MicrosoftDocs/typography-issues/files/5552514/bug1.in.OpenType.Devanagari.script.docx)
[bug1 in OpenType Devanagari script.pdf](https://github.com/MicrosoftDocs/typography-issues/files/5552515/bug1.in.OpenType.Devanagari.script.pdf)

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 194a6d3c-4137-46e9-3a4b-44b990200986
* Version Independent ID: a0c8e788-5228-aa28-670e-3ba1ac3faecd
* Content: [Creating and supporting OpenType fonts for the Universal Shaping Engine - Typography](https://docs.microsoft.com/en-us/typography/script-development/use)
* Content Source: [typographydocs/script-development/use.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/use.md)
* Product: **typography**
* GitHub Login: @Anglass
* Microsoft Alias: **anglass**

**Comment by alib-ms** [comment]
The Unicode characters U+0956 and U+0957 are Kashmiri vowel signs, not Vedic marks, so the reason they are being treated as invalid in most of these combinations is because they are appearing with another vowel sign. I think the shaping engine treats as invalid more than a single vowel sign applied to the same base.

**Comment by alib-ms** [comment]
Wondering if intended to use the Kashmiri vowel sign U+0956 or a similar looking Yajurvedic sign: U+1CD8?

**Comment by advaita56** [comment]
Thanks for this Observation.

Yes we intended to use Yajurvedic sign: U+1CD8 (and not the Kashmiri vowel
signs, which shouldn't combine in this manner).

Jai Gurudev

**Comment by alib-ms** [comment]
thanks, can we close this issue?

**Comment by advaita56** [comment]
Yes. Please close this issue regarding  Devanagari glyphs $0956 and $0957.
Thank You.
Jai Gurudev

**Comment by alib-ms** [comment]
For the following string 
०᳐१᳑२᳒३᳓४᳔५᳕६᳖७᳗८᳘९᳟
OS:Windows 10 
Font:"Sanskrit Text"
Application: Microsoft Word
![image](https://user-images.githubusercontent.com/36778811/99707583-81015d80-2a51-11eb-94ef-9823e11bbec1.png)

Application: Notepad 
![image](https://user-images.githubusercontent.com/36778811/99707537-6c24ca00-2a51-11eb-95a2-9fdbac7d47b6.png)

I am curious what the above string looks like for you using Windows 10 and Word/Notepad with Sanskrit Text font.
