### ISSUE TITLE
Typo: "fundementals"

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#69]
The sidebar misspells “fundamentals” as “fundementals”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8c1e0369-7235-11e6-d1ef-f0a57fca7588
* Version Independent ID: 78d6c664-b275-f986-5374-c3d01ef3ccb2
* Content: [TrueType fundamentals - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/ttch01)
* Content Source: [typographydocs/opentype/spec/ttch01.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/ttch01.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Fixing.
