### ISSUE TITLE
VTT download link broken

### ISSUE THREAD

**Issue by tiroj** [MicrosoftDocs/typography-issues#694]
The download link for VTT goes to a 404 page saying the download is no longer available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3adae675-e33d-0a22-98fd-25a77f2b723c
* Version Independent ID: 3dc9a5cc-4380-056c-848d-48567ecca83c
* Content: [Microsoft Visual TrueType (VTT) - Typography](https://docs.microsoft.com/en-us/typography/tools/vtt/)
* Content Source: [typographydocs/tools/vtt/index.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/tools/vtt/index.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Thank you for letting us know. Will post an update soon. 

Thanks,
Ali

**Comment by paullinnerud** [comment]
Thanks, this should be fixed now.
