### ISSUE TITLE
[CPAL] paletteTypes—what if neither flag set for all palettes?

### ISSUE THREAD

**Issue by ctrlcctrlv** [MicrosoftDocs/typography-issues#697]
Does this mark the entire table invalid or should this be interpreted as unknown usability on different backgrounds? Section could use clarification in this regard. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 446bcdab-0883-6d30-b5ed-0d04262ff820
* Version Independent ID: cdf10ecc-926a-a992-fb71-67213ea8113f
* Content: [CPAL — Color Palette Table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/cpal)
* Content Source: [typographydocs/opentype/spec/cpal.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cpal.md)
* Product: **typography**

**Comment by PeterCon** [comment]
If no flags are set for any palette, then there's no need for a font compiler to create the array (paletteTypesArrayOffset can be set to 0). But when reading a font, if there is an array but no flags are set for any entry, then that should be interpreted as unspecified usability on different backgrounds.
