### ISSUE TITLE
Typo: "Scipt"

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#7]
The top box in otlch1_fig1i.gif is labeled “Scipt” instead of “Script”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5b15ab9e-86c5-f6e0-0145-f9de77c60141
* Version Independent ID: 0ebe3dec-cc24-b6a4-01b8-73bfdb79a71a
* Content: [Advanced typographic tables - OpenType Layout - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/ttochap1)
* Content Source: [typographydocs/opentype/spec/ttochap1.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/ttochap1.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Thanks. The same image appears in OTL Common Tables Formats, and it looks like the typo originally existed in both chapters and was corrected a long time ago in that other chapter, but not in the OTL Overview chapter. Thanks. This will be corrected in the next version.

**Comment by PeterCon** [comment]
Hmmm... I did fix this, but somehow it didn't merge. Trying again.
