### ISSUE TITLE
akhn: mismatch between list and description friendly name

### ISSUE THREAD

**Issue by tiroj** [MicrosoftDocs/typography-issues#700]
In the list on this page, the `akhn` feature is identified as ‘Akhand’, whereas in the feature description the friendly name is given as ‘Akhands’. I believe the latter is correct.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b624d059-5498-9f87-7be3-8ab01aaf3b89
* Version Independent ID: cc92acc8-d227-09e4-a1eb-140d185308e5
* Content: [Registered features (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/featurelist)
* Content Source: [typographydocs/opentype/spec/featurelist.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/featurelist.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
