### ISSUE TITLE
Hiragana and Katakana have the same script tag, intentional?

### ISSUE THREAD

**Issue by fschutt** [MicrosoftDocs/typography-issues#704]
I've noticed that both Hiragana and Katakana have `kana` as their tag, is this intentional or a documentation error?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49c1efc4-e864-0727-9663-7cec0ec4d9f1
* Version Independent ID: 36ec4396-b9cb-cba9-1582-d8400296d249
* Content: [Script tags (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/scripttags)
* Content Source: [typographydocs/opentype/spec/scripttags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/scripttags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
This is intentional. It's assumed there's never a reason to organize layout data (e.g., GPOS features) for Hiragana separate from Katakana.
