### ISSUE TITLE
Remove "current version" note from OT 1.8.3

### ISSUE THREAD

**Issue by sairuspatel** [MicrosoftDocs/typography-issues#705]
Re: "OpenType 1.8.3 (current version)"
Please remove the current version notation (1.8.4 is the current version).
Thanks.
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3446b0e9-288e-734c-52d0-a72068de3064
* Version Independent ID: 764c8071-e525-4631-b4a7-e696bc82b652
* Content: [Archive of OpenType versions - Typography](https://docs.microsoft.com/en-us/typography/opentype/opentypeversions)
* Content Source: [typographydocs/opentype/OpenTypeVersions.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/OpenTypeVersions.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Oops!

**Comment by PeterCon** [comment]
Fixed
