### ISSUE TITLE
Clarify how coordinate rounding works in variations

### ISSUE THREAD

**Issue by Lorp** [MicrosoftDocs/typography-issues#706]
In [OpenType Font Variations Overview: Coordinate Scales and Normalization](https://docs.microsoft.com/en-us/typography/opentype/spec/otvaroverview#coordinate-scales-and-normalization), we read that “implementations must observe the following [7] requirements”. Point number 7 includes the note:

> It is recommended that … any rounding be done at the last point before a value is used

There is undesirable non-specifity about the meaning of “any rounding” (which rounding? is it required?) and “a value is used” (used by a renderer? used by an end user?). I recommend that this clause is expanded into its own point 8.

Given the rounding to 2.14 and 16.16 that is also taking place, it would be useful (if that is the intention) to specify that rounding means rounding to integral glyph coordinates in FUnits.

It seems to be an assumption, though I don’t think it is stated explicitly, that all instances should be faithfully representable – at least in terms of their glyph outlines – as static fonts.

Now, TrueType-flavour fonts require integer glyph coordinates, so it probably makes sense to require that instances derived from TrueType-flavour variable fonts use integer coordinates. It would be good to check whether all common implementations perform this rounding.

On the other hand, non-variable CFF2 fonts do not require integer coordinates, so glyph coordinates in instances made from CFF2 fonts may not need to be rounded. Again, it would be useful to check implementations for actual practice.

**Comment by PeterCon** [comment]
I'm not sure what change in the spec might be appropriate to address the "undesirable specificity".

>which rounding? is it required?

The guidance being given is for calculation of normalized instance values, and then point 7 touches on "subsequent calculations — calculation of interpolation scalars or accumulation of scaled delta values". No rounding is required during those calculations, though an implementation might have implementation-specific reasons for rounding at some point between when the normalized instance vector is calculated and when derivative values (a varied contour point coordinate, a varied ascender value...) are "used". The only case I know of in which rounding would be _required_ would be if calculating an instance value for some item and then passing that through an API or representing it in some data format that constrains precision (e.g., requires integers). Exporting a derived instance font using TrueType outlines would be an example.

But is anything needed in the spec to clarify this?

**Comment by Lorp** [comment]
Thanks for this. Since I created the issue (2020), I’ve realized that (some, maybe all) rasterizers intentionally do *not* produce integer outline coordinates in instantiated outlines. This presumably also applies to MVAR, GPOS and metrics.

I wonder if this non-requirement should be communicated better, perhaps in [OpenType Font Variations Overview](https://learn.microsoft.com/en-us/typography/opentype/spec/otvaroverview), since in many places there is the clear idea is that an instance behaves exactly like a single static font (which at least in the TrueType world, requires integer coordinates). It would be useful to confirm whether all common rasterizers behave the same way in this respect.

**Comment by PeterCon** [comment]
Since there are questions, I've drafted an additional note in the OTVar Overview chapter providing some clarification. I don't think the spec should get into documenting what different implementations do, but it can call out that differences can occur.

See [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
