### ISSUE TITLE
Glyph deletion in Multiple Substitution Format 1

### ISSUE THREAD

**Issue by justvanrossum** [MicrosoftDocs/typography-issues#707]
The section _Multiple Substitution Format 1_ says:

"The use of multiple substitution for deletion of an input glyph is prohibited. The glyphCount value must always be greater than 0."

However, in [this old Mozilla issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1128658) I read:
- that Uniscribe allows it
- that there are fonts out there that use it
- that HarfBuzz was changed to allow it

Shouldn't the OT spec lift this limitation then?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34e7df21-eb35-19ab-3573-e075872e5d3b
* Version Independent ID: 4656a3f9-95ea-15cc-25ed-6eccf7adf370
* Content: [GSUB — Glyph Substitution Table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/gsub#CS)
* Content Source: [typographydocs/opentype/spec/gsub.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gsub.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by khaledhosny** [comment]
Reported earlier https://github.com/MicrosoftDocs/typography-issues/issues/673

**Comment by justvanrossum** [comment]
Oops, thanks.
