### ISSUE TITLE
Inconsistency

### ISSUE THREAD

**Issue by lemzwerg** [MicrosoftDocs/typography-issues#71]
In

https://docs.microsoft.com/en-us/typography/opentype/spec/glyf#glyph-headers

I can read

numberOfContours: “If the number of contours is greater than or equal to zero, this is a simple glyph.  If negative, this is a composite glyph — the value -1 should be used for composite glyphs.”

However, in

https://docs.microsoft.com/en-us/typography/opentype/spec/glyf#simple-glyph-description

there is

“This is the table information needed if numberOfContours is greater than zero, [...]”

It seems to me that the latter explanation is incorrect, since it doesn't cover the case of a space glyph (i.e., numberOfContours=0) that contains bytecode to adjust phantom points.  It should be thus changed to

“This is the table information needed if numberOfContours is greater than or equal to zero, [...]”

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2a9a6a1-a9b9-0864-8982-322da821389e
* Version Independent ID: a42612e3-dc1d-f980-fe4a-4880d1fd0086
* Content: [glyf - Glyf data table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/glyf)
* Content Source: [typographydocs/opentype/spec/glyf.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/glyf.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Fixed as OpenType 1.8.3 erratum.
