### ISSUE TITLE
Graphics State Summary chapter

### ISSUE THREAD

**Issue by fmun** [MicrosoftDocs/typography-issues#710]
The "Graphics State Summary" page (https://docs.microsoft.com/en-us/typography/opentype/spec/tt_graphics_state) mentions the following TrueType instructions that do not exist:

SHE, SCE0, SCE1, SCE3, SCES

Probably the following instructions are meant instead: SHZ, SZP0, SZP1, SZP2, SZPS

Furthermore, zone pointers are called "gep0", "gep1", and "gep2", whereas in the "TrueType Instruction Set" chapter, zone pointers are called "zp0", "zp1", and "zp2".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b8f3ce77-c18f-1036-ccc3-0de8c9354055
* Version Independent ID: 60e1d2a3-664c-ebc9-e6f2-4d7f201c0bed
* Content: [Graphics State Summary (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/tt_graphics_state)
* Content Source: [typographydocs/opentype/spec/tt_graphics_state.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/tt_graphics_state.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Thanks. Fixing for OT 1.9.

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
