### ISSUE TITLE
how to download the font? where to find the sanskrit font? 

### ISSUE THREAD

**Issue by dybhatia** [MicrosoftDocs/typography-issues#711]
how to download the font? where to find the sanskrit font? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1198929e-67b2-8442-c623-7e1325712c6a
* Version Independent ID: 47fa7093-96e1-effa-2157-f07d00e2d7c4
* Content: [Sanskrit Text font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/sanskrit-text)
* Content Source: [typographydocs/font-list/Sanskrit-Text.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/Sanskrit-Text.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
The Sanskrit Text font ships with Windows 10, but is an optional download. It is included in the Devanagari Supplemental Fonts package. This is normally downloaded and installed automatically if you activate relevant language support in Windows, but you can also get the font using the following steps:

1. Click **Start > Settings**.
2. In Settings, click **Apps**, click **Apps & features**, and then click **Optional features**.
3. If you don't see **Devanagari Supplemental Fonts** in the list of installed features, click the plus sign (+) to add a feature.
4. Select **Devanagari Supplemental Fonts** in the list, and then click **Install**.

**Comment by dybhatia** [comment]
Thanks John.
It shows I have them installed. But I don't know how to use them in word or power point.
When I select the font in word, it still continues to type in English.

**Comment by tiroj** [comment]
Ah. You need to activate a Devanagari keyboard. The Sanskrit Text font uses Unicode encoding of Devanagari and Latin characters, so each supported language requires its own keyboard layout.

Click **Start > Settings**.
In Settings, click **Time & Language**, then click **Language**.
Under **Preferred Language** click **+** to add the language you want to use.
Click on the language, and then click **Options**, then under Keyboards click **+** to add a keyboard.

As I recall, there isn't a specific keyboard for Sanskrit, so I use the Hindi one. The different keyboards will show up in your Windows taskbar, usually at the lower right of the screen:

![image](https://user-images.githubusercontent.com/5614500/103300111-fd714f80-49b2-11eb-880d-467c25af5930.png)

**Comment by dybhatia** [comment]
Thanks. That worked.
There is lot of information on how to install the fonts but very less on how to use/enable the fonts.
The one below should be added to online docs. Very helpful

[cid:image003.png@01D6E0FF.8EFB8960]

[cid:image002.png@01D6E0FF.8EF10210]

**Comment by alib-ms** [comment]
Thank you John.
