### ISSUE TITLE
Formatting mistake

### ISSUE THREAD

**Issue by potasiyam** [MicrosoftDocs/typography-issues#712]
in https://docs.microsoft.com/en-us/typography/script-development/bengali#shape-glyph-sequences-gsub-processing
`Apply feature_'akhn'_ to substitute`, it has no spaces before and after `_` which breaks formating. Should be `Apply feature _'akhn'_  to substitute`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c254a65e-1b44-8a56-0f53-13badf120a10
* Version Independent ID: a61fab42-a0ff-c5a6-50eb-3d0bdd7c8d75
* Content: [Developing OpenType Fonts for Bengali Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/bengali)
* Content Source: [typographydocs/script-development/bengali.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/bengali.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Fixed.
