### ISSUE TITLE
U+0442 (Cyrillic Small Letter Te) is wrong in Segoe Print

### ISSUE THREAD

**Issue by mrlacey** [MicrosoftDocs/typography-issues#715]
This font has the wrong glyph for U+0442. It should contain the Cyrillic small letter `Te` but looks more like a small letter `Em`/`m`.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0a0d88d-aa67-8e2d-6dba-0022ad9b0456
* Version Independent ID: d243579c-6aa6-4ff3-f376-6536388b21fe
* Content: [Segoe Print font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/segoe-print)
* Content Source: [typographydocs/font-list/segoe-print.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/segoe-print.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
This is the normal cursive writing form of the Cyrillic lowercase _т_, which resembles a Latin lowercase _m_. This form is not only appropriate for a cursive script typeface like Segoe Script, but is also a common form in italic fonts.

**Comment by vlevantovsky** [comment]
> This is the normal cursive writing form of the Cyrillic lowercase т
As a native Russian speaker and Cyrillic calligraphy sufferer (calligraphy was a mandatory subject in elementary school and we were required to write with fountain pen), I concur. See also https://en.wikipedia.org/wiki/Russian_cursive

**Comment by mrlacey** [comment]
> > This is the normal cursive writing form of the Cyrillic lowercase т
> 
> As a native Russian speaker and Cyrillic calligraphy sufferer (calligraphy was a mandatory subject in elementary school and we were required to write with fountain pen), I concur. See also https://en.wikipedia.org/wiki/Russian_cursive

Thanks for enlightening me. I was struggling to believe such an error had existed for so long without being noticed previously.
