### ISSUE TITLE
Typo: “the the”

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#717]
There are three instances of “the the”. Each should be “the”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb42967-20ca-9270-4572-65315127fcc5
* Version Independent ID: 1fa413f1-71cf-ac2a-0999-70dd5d8ac4cd
* Content: [OpenType layout common table formats (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/chapter2)
* Content Source: [typographydocs/opentype/spec/chapter2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/chapter2.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Fixed. Also searched across the rest of OT 1.8.4. and fixed other occurrences in hmtx and dsig. (Silent edits.)
