### ISSUE TITLE
Traditional Cursive Font

### ISSUE THREAD

**Issue by harecubed** [MicrosoftDocs/typography-issues#72]
It would be great if Windows still had access to a traditional cursive font like the original Script font in Windows v3.x.  All of the current cursive fonts don't accurately display the correct uppercase G.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d43be991-71e4-56f0-fec0-df35d187a0b8
* Version Independent ID: 3ba72d0d-49d0-b525-5a0d-fbe56aa9329c
* Content: [About Microsoft Typography - Typography](https://docs.microsoft.com/en-us/typography/about)
* Content Source: [typographydocs/about.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/about.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by PeterCon** [comment]
This is not a documentation issue. Please submit feedback for Windows 10 using the Feedback Hub app.
