### ISSUE TITLE
Consolas

### ISSUE THREAD

**Issue by field-mint** [MicrosoftDocs/typography-issues#722]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bebad8df-b4dd-251d-f63c-630239cf0bcd
* Version Independent ID: 81bc3207-d7c1-6b93-bd22-47771348961a
* Content: [Consolas font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/consolas)
* Content Source: [typographydocs/font-list/consolas.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/consolas.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Closing as there is no feedback in this opened issue.
