### ISSUE TITLE
Variation of glyph bounding box is not discussed

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#724]
Within the 'glyf' table, each glyph description has a header that includes xMin, etc. values for the glyph bounding box:

>Note that the bounding rectangle from each character is defined as the rectangle with a lower left corner of (xMin, yMin) and an upper right corner of (xMax, yMax). These values are obtained directly from the point coordinate data for the glyph, comparing all on-curve and off-curve points. Phantom points computed by the rasterizer are not relevant. Note that the bounding box defined by control points is guaranteed to contain the outline, but might not be tight to the outline.

These glyph-specific values are distinct from the similar xMin, etc. fields in the 'head' table, which take extrema across all glyphs. 

It appears that there isn't anywhere in the OT spec that discusses variation of the bounding box in a variable font. The 'gvar' table does not provide deltas for these directly; it only provides deltas for contour points and the TT rasterizer phantom points. 

The implication for run-time implementations _appears_ to be that, if bounding box info is needed, the application should process the derived point data for a given instance to obtain the extrema. But perhaps that depends on what might be assumed by font-authoring implementations: Do they...

* Write xMin, etc. values for the glyph outline data without considering any 'gvar' deltas?
* Write xMin, etc. values for the glyph after taking 'gvar' deltas into consideration?

(My guess would be that the former is what any font authoring tools do.)

It seems to me that the spec should have _some_ discussion of this.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2a9a6a1-a9b9-0864-8982-322da821389e
* Version Independent ID: a42612e3-dc1d-f980-fe4a-4880d1fd0086
* Content: [glyf - Glyf data table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/glyf)
* Content Source: [typographydocs/opentype/spec/glyf.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/glyf.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by TrueTyper** [comment]
I agree that run-time implementations should be responsible for processing the derived point data for a given instance to obtain the extrema. I know of no tools that take 'gvar' deltas into account for these values, nor IMO should they.

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
