### ISSUE TITLE
Multiple SFNT tables with the same tag

### ISSUE THREAD

**Issue by lemzwerg** [MicrosoftDocs/typography-issues#727]
It seems to me that multiple SFNT tables with the same tag are allowed.  Is it an omission that this is not forbidden?  Or am I missing something?

I could imagine that an SFNT font contains, say, three tables with the name 'XXXX' that isn't used otherwise.  However, a font with three 'glyf' tables doesn't make sense to me...

Note that I'm not talking about OpenType Collections.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6a1bda96-a268-b684-6cea-9b0c7be6f24e
* Version Independent ID: 36485fec-f05d-3984-6da8-ff2dd2799041
* Content: [OpenType font file (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otff)
* Content Source: [typographydocs/opentype/spec/otff.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otff.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by B-starboy** [comment]
> It seems to me that multiple SFNT tables with the same tag are allowed.  Is it an omission that this is not forbidden?  Or am I missing something?
> 
> 
> 
> I could imagine that an SFNT font contains, say, three tables with the name 'XXXX' that isn't used otherwise.  However, a font with three 'glyf' tables doesn't make sense to me...
> 
> 
> 
> Note that I'm not talking about OpenType Collections.
> 
> 
> 
> ---
> 
> #### Document Details
> 
> 
> 
> ⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*
> 
> 
> 
> * ID: 6a1bda96-a268-b684-6cea-9b0c7be6f24e
> 
> * Version Independent ID: 36485fec-f05d-3984-6da8-ff2dd2799041
> 
> * Content: [OpenType font file (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otff)
> 
> * Content Source: [typographydocs/opentype/spec/otff.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otff.md)
> 
> * Product: **typography**
> 
> * GitHub Login: @PeterCon
> 
> * Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
