### ISSUE TITLE
Hadassah friedlaeder

### ISSUE THREAD

**Issue by MadelyneCarrillo** [MicrosoftDocs/typography-issues#728]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1fd980c7-ca28-6e00-58d5-6e5d46ec8021
* Version Independent ID: 2dc6f4ee-5dc1-82c9-05fd-dd5cdcafe878
* Content: [Hadassah Friedlaender font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/hadassah-friedlaender)
* Content Source: [typographydocs/font-list/Hadassah-Friedlaender.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/Hadassah-Friedlaender.md)
* Product: **typography**
* GitHub Login: @nihar
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Closing the issue as there were no comments.
