### ISSUE TITLE
Add content docs

### ISSUE THREAD

**Issue by davelab6** [MicrosoftDocs/typography-issues#73]
Readme says,

> Currently the Microsoft Typography content docs are held in a private repo and are not accepting public contributions.

I would love to see the OT spec text itself be available in markdown on GitHub, so that the community can help provide improvements and context.

**Comment by v-nihar** [comment]
Closing as be design.

**Comment by alerque** [comment]
This issue needs to be revisited. By _not_ doing this by design Microsoft is putting the lie to the "Microsoft loves Open Source" marketing mantra.
