### ISSUE TITLE
Verdana font is shown incorrectly for some letter with the diacritics signs (web)

### ISSUE THREAD

**Issue by kaganer** [MicrosoftDocs/typography-issues#731]
Verdana font is shown incorrectly for some letters with the diacritics signs (e.g. in extended Cyrillic) - in the web browsers working on WebKit.
This is used in some Wikipedia editions in some regional languages of Russia (Altai, Udmurt, Ingush etc.)

See test html code:
`<html>`
`<p style="font-family: 'Verdana',sans-serif;">Verdana: `
`Тӧс бӱк`
`</p>`
`<p style="font-family: sans-serif;">sans-serif: `
`Тӧс бӱк`
`</p>`
`</html>`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9307bce0-42fe-44fe-e4ef-08905c80c82e
* Version Independent ID: 795973a5-be24-c2ee-48de-2d0421dcdbad
* Content: [Verdana font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/verdana)
* Content Source: [typographydocs/font-list/verdana.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/verdana.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
Cyrillic character coverage in Verdana and Georgia is limited to Slavic languages plus a small number of major central Asian languages.
