### ISSUE TITLE
fix typo required.

### ISSUE THREAD

**Issue by hermet** [MicrosoftDocs/typography-issues#734]
benarrower -> *be narrower

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dab084d-cb51-49c6-ab01-569c9792f69b
* Version Independent ID: c32c2bea-b245-a741-0e0f-3ca33e06c2de
* Content: [TrueType hinting - Typography](https://docs.microsoft.com/en-us/typography/truetype/hinting)
* Content Source: [typographydocs/truetype/hinting.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/truetype/hinting.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Issue has been fixed.
