### ISSUE TITLE
Typo: "case senstive"

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#74]
“case senstive” should be “case-sensitive”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7982ac71-0e79-40ed-11ce-1a42674ad14f
* Version Independent ID: b3d4ac02-0d14-a9fd-b76e-9883796a0309
* Content: [svg - Scalable vector graphics table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/svg)
* Content Source: [typographydocs/opentype/spec/svg.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/svg.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by v-nihar** [comment]
Closing as Fixed.
