### ISSUE TITLE
Missing ISO 639 codes for Sutu

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#742]
The language system tag 'SXT ' is currently associated with the ISO 639 code ngo. It should be associated with the ISO 639 codes ngo, xnj, and xnq because [ngo was split into xnj and xnq](https://iso639-3.sil.org/request/2020-018).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662c6f54-f90c-52ed-dca2-0f0a0a49fee5
* Version Independent ID: 6aa33924-d45e-60c3-a9fd-e317ff662993
* Content: [Language system tags (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags)
* Content Source: [typographydocs/opentype/spec/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Registry page updated.
