### ISSUE TITLE
Tahoma incorrectly displays ♡ (U+2661) as ≡

### ISSUE THREAD

**Issue by rampaa** [MicrosoftDocs/typography-issues#743]
Tahoma incorrectly displays ♡ as ≡.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 36b9d23a-b110-648e-afab-917f5f511bb4
* Version Independent ID: 8ae47820-ce61-0597-7a94-ac2684867c40
* Content: [Tahoma font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/tahoma)
* Content Source: [typographydocs/font-list/tahoma.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/tahoma.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
Confirmed bug: GID 3832 is encoded as U+2661, but has incorrect visual appearance.

U+2661 is part of a set of symbol characters representing playing card suits. It seems that this set is only partially supported in Tahoma.

These are encoded and displayed correctly:
U+2260 ♠ BLACK SPADE SUIT
U+2663 ♣ BLACK CLUB SUIT
U+2665 ♥ BLACK HEART SUIT
U+2666 ♦  BLACK DIAMOND SUIT

This is encoded but displayed incorrectly:
U+2661 ♡ WHITE HEART SUIT

These are not supported at at in Tahoma:
U+2662 ♢ WHITE DIAMOND SUIT
U+2664 ♤ WHITE SPADE SUIT
U+2667 ♧ WHITE CLUB SUIT

If I had to guess, I would say that perhaps the white heart was added to the Tahoma glyph set by mistake, then it was realised that the other white card suit characters were not included, so the heart was replaced by a fallback glyph appearance, but one that confusingly does not correspond to the .notdef glyph in the Tahoma font. Based on the glyph ordering, I suspect the full set of the black card suit characters was added in more recent version of the font.

**Comment by tiroj** [comment]
Note: GitHub and some other environments will emojify the black card suit characters, displaying the heart and diamond as red.

**Comment by rampaa** [comment]
Where can I get Tahoma v7.01+ to try it out? It doesn't seem to be available through Windows Update, Microsoft Download Center or Windows Store.

**Comment by alib-ms** [comment]
It is available in Windows 11, version 22H2 [Build 22621](https://blogs.windows.com/windows-insider/2022/05/11/announcing-windows-11-insider-preview-build-22621/) available in the Release Preview Channel for [Windows Insider Program for Business](https://insider.windows.com/en-us/for-business/) participants.

**Comment by alib-ms** [comment]
Fixed.
