### ISSUE TITLE
Script name 'yi ' is incorrect, needs two blanks

### ISSUE THREAD

**Issue by smuehlst** [MicrosoftDocs/typography-issues#744]
In the second paragraph it says:

> All tags are four-character strings composed of a limited set of ASCII characters;

But the script tag 'yi ' is only three characters long, as there is only a single blank character present after 'yi'. The correct script tag is 'yi  ' with two blanks. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49c1efc4-e864-0727-9663-7cec0ec4d9f1
* Version Independent ID: 36ec4396-b9cb-cba9-1582-d8400296d249
* Content: [Script tags (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/scripttags)
* Content Source: [typographydocs/opentype/spec/scripttags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/scripttags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterConstable** [comment]
The issue here is that whitespace in HTML is collapsed by default. So the multiple spaces get collapsed by browsers to a single space.

**Comment by smuehlst** [comment]
How about using two non-breaking spaces &amp;nbsp;? When I copy the following string from Chrome and paste it through a hex dump then there are two spaces:

'yi&nbsp;&nbsp;'

    $ xxd
    'yi  '
    00000000: 2779 6920 2027 0a                        'yi  '.

**Comment by PeterConstable** [comment]
Where you paste is probably a factor. If I copy the string in your comment and then paste into Notepad, it ends up with U+0020. But when I copy (from either Edge or Safari) and then paste into Word or Outlook, what's pasted is U+00A0.

**Comment by smuehlst** [comment]
Do you get one or two U+0020/U+00A0?

Maybe a footnote is better then. But it should be clarified somehow, as at least I was confused by this.

**Comment by PeterConstable** [comment]
Two. Agreed that it's a valid issue. I'm just pondering what the best fix is. Maybe nbsp with a footnote.

**Comment by PeterCon** [comment]
Fixed, erratum published.

**Comment by Lorp** [comment]
To avoid undesirable no-break space characters, a better solution may be CSS `white-space: pre-wrap;` which is designed for exactly this case. Consecutive spaces remain visible and the copy/pasted text would be normal spaces. All OpenType 4-letter tags like this would be assigned a CSS class including this property, e.g. `".ot-tag"`.

**Comment by PeterConstable** [comment]
For all content on microsoft.docs, the source is markdown, and any custom styling is stripped. I have no control over the CSS used, else I would have considered that.
