### ISSUE TITLE
format 0 should not be suggested for Unicode encodings

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#748]
The section for platformID 0 says this:

>Encoding ID 3 should be used in conjunction with 'cmap' subtable formats 0, 4 or 6.

(This information was introduced in OT 1.6 in the 'name' chapter.)

But encoding ID 3 for platform 0 is Unicode 2.0 BMP. Suggesting that format 0 can be used for platform 0 encoding 3 makes no sense: Unicode encoding requires a 16-bit format.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86923ff4-2b60-9144-e2b4-77cdb36fd698
* Version Independent ID: ea221e53-f51a-8233-3c0b-d416e5360623
* Content: [cmap - Character To Glyph Index Mapping Table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap)
* Content Source: [typographydocs/opentype/spec/cmap.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cmap.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
