### ISSUE TITLE
Typo in OS/2 docs

### ISSUE THREAD

**Issue by ln-north** [MicrosoftDocs/typography-issues#752]
In https://docs.microsoft.com/en-us/typography/opentype/spec/os2#version-3

> Although new fields were not added beyond those in version 2, the specification of certain fields was revised to reflect changes in Uniode 3.2. 

`Uniode` => `Unicode`

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ae9457c-0d3d-c137-588b-81d54a086f07
* Version Independent ID: 658c6d22-b9d1-1007-9cdb-6898911c9c75
* Content: [OS/2 - OS/2 and Windows metrics table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/os2)
* Content Source: [typographydocs/opentype/spec/os2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/os2.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Thanks. Fixed.
