### ISSUE TITLE
Clarification of state persistence.

### ISSUE THREAD

**Issue by bungeman** [MicrosoftDocs/typography-issues#757]
There are bytecode instructions which can alter persistent state. In addition to the Graphics State and the many instructions which affect it, WS writes to the storage area; WCVTP, WCVTF, and DELTAC1-3 to write to the control value table; IDEF defines instructions; and FDEF defines functions. The obvious intention is to modify this persistent state in the font and CVT programs which are the font and size specific prelude to any glyph program. However, should a glyph program attempt to change any of this state such changes should not persist after that glyph program is finished. This is somewhat hinted at in the documentation, but this is not always explicitly stated. If any persistent state is modified and not reverted, the font may hint differently depending on the order of running glyph programs or even on the number of times each glyph program is run.

The documentation for the Graphics State is actually quite explicit and states "When value of a state variable is changed by instructions associated with a particular glyph, it will hold only for that glyph."

The current documentation does address FDEF stating that "A function definition can appear only in the Font Program or the CVT program". A glyph program can call functions defined in a font program or CVT program; it is assumed that the intent of this statement is that it is an error for the glyph program to call a function defined in the font or CVT program which itself attempts to use FDEF. However, it is possible to also interpret this to mean that the FDEF instruction should not appear in the glyph program itself but may still appear in the complete glyph program if it appears in a function previously defined. If so, then such functions should be temporary and disappear upon completion of the glyph program.

The current documentation for IDEF is that "IDEFs should be defined in the Font Program or the CVT Program." This seems to imply that IDEFs can appear in the glyph program (but of course may not redefine existing IDEFs). This would imply that any IDEFs defined in the course of a glyph program's execution should disappear upon completion of the glyph program. If they do not, then the first glyph program executed would "win" potentially causing the font to hint differently depending on the order the glyphs are hinted.

However for WS (storage area), WCVTP, WCVTF, and DELTAC1-3 (CVT values) there is no guidance. It would be helpful if the "Managing the Storage Area" and "Managing the Control Value Table" sections explicitly stated that any writes while running the glyph program will not persist after the glyph program is finished.

The specification of the Graphics State is fine and can stay as-is. The specification of FDEF and IDEF should clarify that they must not be used in the course of executing a glyph program (or alternatively that they can be used but any such definitions are temporary). The specification for the storage area and control value table should note that any writes while executing the glyph program are temporary.

Note that FreeType recently [changed to behave as proposed](https://gitlab.freedesktop.org/freetype/freetype/-/merge_requests/23). This seems to be the least surprising behavior. That FreeType did not already behave in this manner was discovered when a font in the wild was discovered to use WCVTP in a function defined in the font program called from the glyph program. This glyph under certain circumstances would produce different results when loaded multiple times with hinting due to the CVT change persisting past the end of the glyph program.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb69554-e257-e483-2e26-7f04fdf44fd8
* Version Independent ID: d560a11c-2ac5-1abc-7165-453c3a9618c8
* Content: [TrueType Instruction Set (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/tt_instructions)
* Content Source: [typographydocs/opentype/spec/tt_instructions.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/tt_instructions.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **alib**

**Comment by bungeman** [comment]
As was brought up in separate discussion, the underspecified persistence of state seems to perhaps have been used by some older fonts in order to deliberately modify outlines each time they were processed. The effect could be used for varying the outlines subtly (like in a handwriting font), semi-randomly (like in a grunge font), or in many other ways. However, this doesn't work well with caches (causing the outline not to be re-hinted each time it is drawn) or even shaping (hinted advance width while shaping may be different from the hinted advance when drawing that result much later).

Most of these uses can now be done more deterministically by using shaping to do glyph substitution or explicit use of variations. It seems better to specify hinting to be deterministic.

**Comment by PeterCon** [comment]
The changes in FreeType diverge from past FT behavior and from other implementations, though I understand concerns. That FT change presents a risk of breaking compatibility with existing fonts and content (e.g. PDF), though a mitigating consideration is that, even for implementations that permit values written in a glyph program, glyph caching hinder fonts ways in which fonts might make use of that.

Note that composite glyphs are a special case: in MS implementations, when a composite is rasterized, the glyph programs for components are always run, regardless of whether those glyphs (when used as standalone simple glyphs) were previously processed and results cached. There certainly could be fonts (e.g., CJK fonts) that have composites in which a component writes a CVT value to be read when the composite's glyph program is run. For that reason, MS's view is that FT should still permit that communication from a component glyph's font program and the composite font program.

With this issue in mind, several changes are proposed for OT 1.9. (The following show the changes along with other editorial changes.)

In the TT Instruction Set chapter:

* Revise the description for FDEF:
  >Marks the start of a function definition. The argument f is a number that uniquely identifies this function. A function definition can appear only in the Font Program or the CVT program<ins>; attempts to invoke the FDEF instruction within a glyph program will result in an error</ins>. Functions may not exceed 64K in size<ins>.</ins>

* Revise the description for IDEF:
  > Begins the definition of an instruction. The instruction definition terminates when at ENDF, which is encountered in the instruction stream. Subsequent executions of the opcode popped will be directed to the contents of this instruction definition (IDEF). IDEFs <del>should</del><ins>must</ins> be defined in the Font Program or the CVT Program<ins>; attempts to invoke the IDEF instruction within a glyph program will result in an error</ins>. An IDEF affects only undefined opcodes. If the opcode in question is already defined, the interpreter will ignore the IDEF. This is to be used as a patching mechanism for future instructions. Instructions may not exceed 64K in size.

In the TT Fundamentals chapter:

* Revise the paragraph in the Font Program section:
  >The <del>Font Program</del><ins>font program is stored in the [&#39;fpgm&#39;](fpgm.md) table of a font and</ins> consists of a set of instructions that is executed once, the first time a font is accessed by an application. It is used to create function definitions (FDEFs) and instruction definitions (IDEFs). Functions and instructions defined in the <del>Font Program can be used elsewhere in the font file.</del><ins>font program may be used in the control value program or in glyph programs. Functions and instructions defined in the font program may also be re-defined in the control value program.</ins>

* Revise the first two paragraphs in the CVT Program section (and revise the section heading):
  > ### The <del>CVT Program</del><ins>control value program</ins>
  >
  >The <del>CVT Program</del><ins>control value program</ins> is <ins>stored in the [&#39;prep&#39;](prep.md) table of a font and consists of </ins>a <del>sequence of TrueType</del><ins>set of</ins> instructions executed every time the point size or transformation <del>change</del><ins>changes</ins>. It is used to make font wide changes <ins>in the Control Value Table </ins>rather than to manage individual glyphs.<del> The CVT Program is used to establish the values in the Control Value Table.</del>
  >
  ><del>The purpose of the Control Value Table or CVT is to simplify the task of maintaining consistency when instructing a font. It is a numbered list of values that</del><ins>The Control Value Table, or CVT, is a numbered list of values used to simplify the task of maintaining consistency across glyphs when instructing a font. The CVT is initialized from the font’s &#39;cvt &#39; table, and then managed using instructions in the control value program. (See Managing the Control Value Table.) Entries in the CVT</ins> can be referenced by either of two indirect instructions (MIRP and MIAP). CVT entries can be used to store values that need to be the same across a number of glyphs in a font. For example an instruction might refer to a CVT entry whose purpose is to regularize stem weights across a font.

* Add two paragraphs at the end of the CVT Program section:
  > <ins>The control value program may also be used to set Graphics State variables (see [The Graphics State](#the-graphics-state) below.) The control value program can determine whether such changes to Graphics State variables will be visible to glyph programs using the [INSTCTRL](tt_instructions.md#instruction-execution-control) instruction.</ins>
  >
  ><ins>The control value program may also be used to define functions or instructions, or to re-define functions or instructions defined in the Font Program. The most recent definition of a given function or instruction is used in subsequent glyph programs. If a function or instruction is first defined in a Font Program, later re-defined in the control value program, but not re-defined again when the control value program is run on another scale or transform change, the re-definition from the earlier control value program run is used.</ins>

* After the Graphics State section, add a new section:
  > ### <ins>Glyph programs and persistence</ins>
  >
  ><ins>Glyph programs may write values in the storage area or the CVT. Implementations may persist storage or CVT values set in a glyph program after the glyph program has ended, allowing those values to be used in other glyph programs. Implementations may also opt not to do this; that is, when a glyph program ends, implementations may reset storage and CVT variables to their earlier values before that glyph program was run. Also note that implementations can cache the results after a glyph program is run. For these reasons, font developers should not assume that values set when a glyph program is run can be used to affect glyphs that are subsequently displayed by an application (for example, to simulate gradual degradation of a typewriter ribbon).</ins>
  >
  ><ins>Composite glyphs require special consideration in this regard. When a composite glyph is processed, implementations should process component glyphs, including running their glyph programs, rather than relying on previously cached results for the component glyphs. Also, storage and CVT values in the glyph program of a component glyph should be available to the composite glyph program, even if the implementation does not otherwise persist these values after the glyph program is run when the glyph is used alone as a simple glyph.</ins>

**Comment by PeterCon** [comment]
After further discussion with GregH, some additional revisions proposed to more completely cover the topic of persistence.

* In the Using instructions section, add the following paragraph:
  > <ins>The interpreter stack is cleared for each run of a font program, control value program, or glyph program.</ins>

* At the end of the CVT Program section, add one more paragraph (after the other two new paragraphs):
  > <ins>Every time the control value program is run, the zone 0 (the “twilight zone”) contour data is initialized to 0s. (See Zones in the Instructing TrueType Glyphs chapter for details regarding zone 0.)</ins>

* In the Storage Area section, add sentences in the first paragraph:
  >The interpreter also maintains a Storage Area consisting of a portion of memory that can be used for temporary storage of data from the interpreter stack. <ins>Values can be written in the storage area by the font program, the control value program, or glyph programs. Values written by the font program can be used in the control value program or glyph programs. Similarly, values written in the control value program can be used in glyph programs. See [Glyph programs and persistence](#glyph-programs-and-persistence) regarding values written in glyph programs. </ins>Instructions exist that make it possible to read the values of stored data and to write new values to storage. Storage locations range from 0 to n-1 where n is the value established in the maxStorage entry in the maxProfile table of the font file. Values are <del>32 </del><ins>32-</ins>bit numbers

* In the newly-added Glyph programs and persistence section, revise the first paragraph and insert an additional paragraph after it. The complete section addition is as follows:
  > ### <ins>Glyph programs and persistence</ins>
  >
  ><ins>Glyph programs may write values in the storage area or the CVT. Implementations may persist storage or CVT values set in a glyph program after the glyph program has ended, allowing those values to be used in other glyph programs, or (for storage values only) in subsequent runs of the control value program. Implementations may also opt not to do this; that is, when a glyph program ends, implementations may reset storage and CVT variables to their earlier values before that glyph program was run. Also note that implementations can cache the results after a glyph program is run. For these reasons, font developers should not assume that values set when a glyph program is run can be used to affect glyphs that are subsequently displayed by an application (for example, to simulate gradual degradation of a typewriter ribbon).</ins>
  >
  ><ins>A glyph program may change contour data in zone 0 (the “twilight zone”). These values should always persist until the next time the control value program is run.</ins>
  >
  ><ins>Composite glyphs require special consideration in this regard. When a composite glyph is processed, implementations should process component glyphs, including running their glyph programs, rather than relying on previously cached results for the component glyphs. Also, storage and CVT values in the glyph program of a component glyph should be available to the composite glyph program, even if the implementation does not otherwise persist these values after the glyph program is run when the glyph is used alone as a simple glyph.</ins>

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
