### ISSUE TITLE
Clarification of overflow handling in instance calculation

### ISSUE THREAD

**Issue by PeterCon** [MicrosoftDocs/typography-issues#758]
This proposed draft for OT 1.9 includes additional text to address #751. The following text is added; the portion that pertains to overflow is highlighted.

>In calculation of scalars (S, AS) and of interpolated values (scaledDelta, netAjustment, interpolatedValue), at least 16 fractional bits of precision should be maintained. Rounding should be done only when the final result is used, and may retain greater fractional bit-depth than that of the data type of the item to which deltas are applied. When scaled deltas are applied to a default value, the possibility of overflow exists. The integer bit-depth used in calculation must be at least that of the data type of the item to which deltas are applied; for example, at least 16 integer bits when applying scaled deltas to an FWORD value. **If overflow in the implementation-internal representation occurs, saturation arithmetic must be used; values must not wrap from maximum to minimum values, or vice versa. The final result should be clamped to the range of the data type of the item to which deltas are applied;** for example, [-32768, 32767] for an FWORD value.

Comments are invited.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ce0a830-13fd-cbc7-37b4-36b77745a97c
* Version Independent ID: 78280596-7e83-153d-36db-7038b31a442e
* Content: [OpenType Font Variations overview (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec190alpha/otvaroverview)
* Content Source: [typographydocs/opentype/otspec190alpha/otvaroverview.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec190alpha/otvaroverview.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by reli-msft** [comment]
One interesting case may be _overflowing the intermediate (partial) sum_. Consider a scalar with 30000 "base" value then a +30000 delta and -30000 delta, the sum does not overflow but the _intermediate_ sum (60000) overflows, and if all summation is done in saturating flavor, this result will be considered strange. In my personal idea, all the intermediate summation should be performed in wrap-around flavor, and perform one saturation at the end.

**Comment by PeterConstable** [comment]
Good point. For your example—a large +ve delta paired by a large -ve delta—wrapping would end up with an expected result; but wrapping would lead to discontinuities in any other case of overflow. I think you're right: that intermediate calculations *should* use sufficient bit-depth to avoid overflow, regardless of what happens in relation to the final result.

I've revised wording to accommodate your comment.

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
