### ISSUE TITLE
apostrophe bug

### ISSUE THREAD

**Issue by ziel5122** [MicrosoftDocs/typography-issues#76]
apostrophes (') appear as question marks (?)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c29cd56a-2ece-7acf-da8d-ba22131a6db6
* Version Independent ID: 48c52cb0-062f-7777-1fde-bde9369d1a85
* Content: [Georgia font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/georgia#feedback)
* Content Source: [typographydocs/font-list/georgia.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/georgia.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by ziel5122** [comment]
![screen shot 2018-08-28 at 5 40 48 pm](https://user-images.githubusercontent.com/14335217/44758497-9cd35e80-aae9-11e8-932e-51bd540684a5.png)

**Comment by fitojb** [comment]
When fixing this issue, make sure you use [typographic apostrophes](https://practicaltypography.com/apostrophes.html), of course. 😁

**Comment by v-nihar** [comment]
Closing as fixed.
