### ISSUE TITLE
Typo: "is has"

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#761]
Typo: should be "it has".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3213e236-1ddb-592a-4060-1877d45f48d7
* Version Independent ID: 05b50516-8461-48f3-c849-ef150c0a8038
* Content: [wdth design-variation axis tag (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_wdth)
* Content Source: [typographydocs/opentype/spec/dvaraxistag_wdth.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/dvaraxistag_wdth.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Already fixed.
