### ISSUE TITLE
TupleRecord type?

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#763]
The shared tuples array is described as:

Type | Name | Description
-- | -- | --
TupleRecord | sharedTuples[sharedTupleCount] | Array of tuple records shared across all glyph variation data tables.

What is the `TupleRecord` type? I can't see it defined anywhere. Should this be `Tuple`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 446bcdab-0883-6d30-b5ed-0d04262ff820
* Version Independent ID: cdf10ecc-926a-a992-fb71-67213ea8113f
* Content: [gvar — Glyph Variations Table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/gvar)
* Content Source: [typographydocs/opentype/spec/gvar.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gvar.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
