### ISSUE TITLE
FWord capitalization

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#764]
The post table has

FWord | underlinePosition | This is the suggested distance of the top of the underline from the baseline (negative values indicate below baseline).The PostScript definition of this FontInfo dictionary key (the y coordinate of the center of the stroke) is not used for historical reasons. The value of the PostScript key may be calculated by subtracting half the underlineThickness from the value of this field.
-- | -- | --
FWord | underlineThickness | Suggested values for the underline thickness. In general, the underline thickness should match the thickness of the underscore character (U+005F LOW LINE), and should also match the strikeout thickness, which is specified in the OS/2 table.

The correct data type is

FWORD | int16 that describes a quantity in font design units.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c682af48-1252-0ffc-c6d7-c73130b2a690
* Version Independent ID: ed9e6d48-434b-ab0c-2fdf-e2700cde9cb2
* Content: [post — PostScript Table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/post)
* Content Source: [typographydocs/opentype/spec/post.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/post.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by B-starboy** [comment]
That'll work

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
