### ISSUE TITLE
Is the description of radicalDegreeBottomRaisePercent correct?

### ISSUE THREAD

**Issue by kevinbarabash** [MicrosoftDocs/typography-issues#766]
The MathML spec describes the positioning of the alphabetic baseline of the radical index (degree) in the following way (from [3.3.3.3 Root with index](https://mathml-refresh.github.io/mathml-core/#root-with-index)):
> The alphabetic baseline of B is aligned with the alphabetic baseline. The alphabetic baseline of the index is shifted away from the line-under edge by a distance of RadicalDegreeBottomRaisePercent × the *block size* of B + the line-descent of the index's margin box.

According to the diagram in the section the "block size" is the descender + ascender of the radical symbol + a small bit of padding on top.

The OpenType spec description:
> Height of the bottom of the radical degree, if such is present, in proportion to the *ascender* of the radical sign. Suggested: 60%.

It seems like these two explanations of how `radicalDegreeBottomRaisePercent` should be applied to determine the baseline of the index (degree) don't agree.

I've tested the MathML rendering in Chrome with a few different OpenType fonts and the index appears to be positioned correctly.  Is it possible that the description of `radicalDegreeBottomRaisePercent` in the OpenType spec is incorrect?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0076fd2-52b0-2989-3142-fd9e456b9514
* Version Independent ID: 4aef8fa3-2ad3-7933-5a77-0a7473e66112
* Content: [MATH - The mathematical typesetting table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/math#mathconstants-table)
* Content Source: [typographydocs/opentype/spec/math.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/math.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
Further investigation of possibly related issues:
https://github.com/stipub/stixfonts/issues/206#issuecomment-827168105

It does seem as if different environments are interpreting this and perhaps other aspects of radical handling differently. The MS MathFont tool displays things nicely, but results in apps—including MS Word—are not as in the tool.

**Comment by PeterCon** [comment]
@tiroj @khaledhosny Can you clarify exactly what discrepency you observe between the MATH spec and behaviour in Word? Is it that the spec wording has "ascender of the radical sign" rather than "height of the radical sign?

@khaledhosny mentioned the "bounding box height of the radical glyph", which seems like it would not include the MathConstants.radicalExtraAscender value. The MathML spec refers to "the block of B" which, IIUC, would include RadicalExtraAscender.

**Comment by khaledhosny** [comment]
> @tiroj @khaledhosny Can you clarify exactly what discrepency you observe between the MATH spec and behaviour in Word? Is it that the spec wording has "ascender of the radical sign" rather than "height of the radical sign?

Yes.


> @khaledhosny mentioned the "bounding box height of the radical glyph", which seems like it would not include the MathConstants.radicalExtraAscender value. The MathML spec refers to "the block of B" which, IIUC, would include RadicalExtraAscender.

Word does not seem to include RadicalExtraAscender in the calculation. Firefox and Chrome do not seem to include it either.

**Comment by PeterCon** [comment]
Draft change for OT 1.9.1:

>Height of the bottom of the radical degree, if such is present, in proportion to the <del>ascender</del><ins>height (ascender + descender)</ins> of the radical sign. Suggested: 60%.

See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by khaledhosny** [comment]
Looks good, thanks!

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue. Closing.
