### ISSUE TITLE
UTF for Unicode encoding unspecified

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#768]
I know that:

> Language-tag strings stored in the naming table must be encoded in UTF-16BE

and I also know that:

> All naming table strings for the Windows platform (platform ID 3) must be encoded in UTF-16BE. Strings for the Macintosh platform (platform ID 1) use platform-specific single- or double-byte encodings.

but for Platform ID=0, I only know that:

> 3 | Unicode 2.0 and onwards semantics, Unicode BMP only

This does not actually specify the UTF to be used for encoding Unicode-platform data in the name table. (Yes, I know it's UTF16-BE, but the spec should say so.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc5a9d9-70e1-97b3-6926-c176e1a2401d
* Version Independent ID: 1afb0f5b-d1a7-7d69-d175-a5c9382b74be
* Content: [name - Naming table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/name)
* Content Source: [typographydocs/opentype/spec/name.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/name.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Rev'ing page for OT 1.9. 

While working on this, I discovered that some early CJK fonts used platform 3 with CJK encoding IDs, but encoded the strings inconsistently: UTF-16BE for Latin strings, but legacy CJK code page for the CJK strings (name records all having the same encodingID).

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
