### ISSUE TITLE
ROUND_XY_TO_GRID description is inadequate

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#769]
I don't really know what this means:

Mask | Name | Description
-- | -- | --
0x0002 | ARGS_ARE_XY_VALUES | Bit 1: If this is set, the arguments are signed xy values; otherwise, they are unsigned point numbers.
0x0004 | ROUND_XY_TO_GRID | Bit 2: *For the xy values if the preceding is true*.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2a9a6a1-a9b9-0864-8982-322da821389e
* Version Independent ID: a42612e3-dc1d-f980-fe4a-4880d1fd0086
* Content: [glyf - Glyf data table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/glyf)
* Content Source: [typographydocs/opentype/spec/glyf.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/glyf.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by moyogo** [comment]
The Apple TrueType spec says "If set, round the xy values to grid; if not set do not round xy values to grid (relevant only to bit 1 is set)"

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
