### ISSUE TITLE
dfd

### ISSUE THREAD

**Issue by erickalejandro1996** [MicrosoftDocs/typography-issues#770]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ea00eecc-6816-77be-6d53-a910e47d279e
* Version Independent ID: df6b0b98-073d-84bc-0f94-8e579aa0ebbb
* Content: [Berlin Sans FB font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/berlin-sans-fb)
* Content Source: [typographydocs/font-list/berlin-sans-fb.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/berlin-sans-fb.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
No feedback. Closing the issue.
