### ISSUE TITLE
Please add more Arial weights on Microsoft Windows

### ISSUE THREAD

**Issue by RodneyAraujo** [MicrosoftDocs/typography-issues#771]
Hello, I have a suggestion: Can you add the following Arial weight styles to complement Regular, Italic, Bold, Bold Italic, Black and Black Italic font styles on Microsoft Windows?
Arial Light
Arial Light Italic
Arial Medium
Arial Medium Italic
Arial Extra Bold
Arial Extra Bold Italic
Arial Condensed Light
Arial Condensed Regular
Arial Condensed Bold
Arial Condensed Extra Bold

Thanks.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 97746b9a-3055-8530-b613-22de7432fd56
* Version Independent ID: 3e86494e-e566-78f3-b43a-312b44c3964a
* Content: [Arial font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/arial)
* Content Source: [typographydocs/font-list/arial.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/arial.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by RodneyAraujo** [comment]
> Thank you for the feedback. Adding all these weights will further increase the font footprint in the product, this is not very desirable. Perhaps a variable version of the Arial font family will be a better solution. I will pass your feedback to the feature team. I noticed fonts.com offers additional weights, this might be an option for someone wanting to have additional weights.

@alib-ms Okay. Thank you for the solution of implementing a variable version of all Arial fonts in Microsoft Windows 10. It is a good idea.

**Comment by alib-ms** [comment]
For now I am closing this issue as Arial Nova font family is available from store as an alternative. Thank you for your feedback.

**Comment by RodneyAraujo** [comment]
> For now I am closing this issue as Arial Nova font family is available from store as an alternative. Thank you for your feedback.

@alib-ms I don't like so much the Arial Nova font, but it not have medium, semibold and black weights apart of the light, regular, and bold weights that it have. Could you inform to MS Typography team and Monotype if they can create more Arial Nova Weights in normal and condensed to be added on MS Windows?
