### ISSUE TITLE
Typo in Imre Reiner

### ISSUE THREAD

**Issue by zwouter** [MicrosoftDocs/typography-issues#773]
Imre Reiner is spelled as "Imr? Reiner" for some reason

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 10f752bc-83eb-1539-9001-623fe191f986
* Version Independent ID: e02c84df-d7dd-c6b0-b317-3d62c8780757
* Content: [Matura MT Script Capitals font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/matura-mt-script-capitals)
* Content Source: [typographydocs/font-list/matura-mt-script-capitals.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/matura-mt-script-capitals.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
It appears as expected for me. Closing (no repro).
