### ISSUE TITLE
Please add more Times New Roman Weights on Microsoft Windows

### ISSUE THREAD

**Issue by RodneyAraujo** [MicrosoftDocs/typography-issues#774]
Hello, I have a suggestion: Can you add the following Times New Roman weight styles to complement Regular, Italic, Bold, Bold Italic font styles on Microsoft Windows?
Times New Roman Medium
Times New Roman Medium Italic
Times New Roman Semi Bold
Times New Roman Semi Bold Italic
Times New Roman Extra Bold
Times New Roman Condensed Regular
Times New Roman Condensed Italic
Times New Roman Condensed Bold

Thanks.

**Comment by alib-ms** [comment]
Thank you for the feedback. Adding new weights increases font footprint and getting an approval for this is not an easy task.

**Comment by RodneyAraujo** [comment]
@alib-ms I prefer that this mentioned Times New Roman weights can be added to Windows as a variable font.
