### ISSUE TITLE
How many subtables in an Extension?

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#776]
The specification for ExtensionSub and ExtensionPos is somewhat confused as to how many extension subtables are stored within the lookup.

The description of the table structure suggests one extension subtable:

 Type |  Name | Description 
--- | --- | ---
Offset32 | extensionOffset | Offset to **the** extension subtable.

(And reading this, I only see a way to store a single extension subtable.)

But the following description says:

> **All subtables** in a LookupType 7 lookup must have the same extensionLookupType. All offsets within the extension **subtables** are set in the usual way...
> * Proceed as though **each extension subtable** referenced by extensionOffset 

Which suggests more than one is possible.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34e7df21-eb35-19ab-3573-e075872e5d3b
* Version Independent ID: 4656a3f9-95ea-15cc-25ed-6eccf7adf370
* Content: [GSUB — Glyph Substitution Table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/gsub#lookuptype-7-extension-substitution)
* Content Source: [typographydocs/opentype/spec/gsub.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gsub.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
