### ISSUE TITLE
CFF2: blend has incorrect value for number of arguments

### ISSUE THREAD

**Issue by QuantumDeveloper** [MicrosoftDocs/typography-issues#777]
I want to implement CFF2 parser for my own font engine.

First of all, I read MSDN docs [here](https://docs.microsoft.com/en-us/typography/opentype/spec/cff2#variations) and I know that last argument for blend operator says how many arguments we must take. This is real values for the operator, which will go after blend.

But while parsing font AdobeVFPrototype from https://github.com/adobe-fonts/adobe-variable-font-prototype I found that value in last operand does not correspond to count of operands that should be present for the certain operator. For example: Glyph id 15:

**rmoveto** always has only 2 operands and not more. not less, but blend says it has only 1 operand. Here is real numbers from my parser: 150, -13, 3, -3, 0, 0, 0, **1**

So, here we have 1 as number of operands for rmoveto, which is incorrect, but this is not all. The most interesting part is with **xxcurveto** operators.

For example, here is blend arguments for **vhcurveto** for Glyph id 18: -70, 0, 3, 0, 0, 0, 1, -70, -1, -71, -2, -70, -2, -1, 0, 0, 0, **1**

And again incorrect number of arguments. for **vhcurveto** operator there should be at last 4 operands.

But... Fontlab somehow parse this font correctly and even display it also correctly.
![image](https://user-images.githubusercontent.com/6085009/119706223-5a8a0800-be62-11eb-8bcf-ed8a9b4aebec.png)

So, obviously, I am doing something wrong, but according to docs, everything is ok. 
Maybe, someone can help me to understand what I am missing?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8f3f1db1-b1f0-587c-0dbe-9e090b32c5d9
* Version Independent ID: 49bd6461-28c0-a133-77b1-617b8f2f5dab
* Content: [CFF2 - Compact font format version 2 table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/cff2#10-font-dict-index-font-dicts-and-fdselect)
* Content Source: [typographydocs/opentype/spec/cff2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cff2.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Thanks for filing this issue. Adobe are responsible for this section of the OpenType spec; I've asked them for clarifications.

**Comment by Lorp** [comment]
The *n* of blend does not need to be the same as the number of values consumed by the subsequent operator. Rather, after processing the blends, the stack must be left in a good state for the subsequent operator. Consider an example where, though we know rmoveto works on stack[0] and stack[1], only stack[1] requires blending. Then *n* is 1 (not 2) and only stack[1] will be blended to a new value, leaving 2 arguments on the stack (the old stack[0] and the popped and pushed stack[1]) ready for rmoveto. Note that blend requires at least *n* * (*k*+1) + 1 arguments on the stack, where *n* is the topmost argument, and *k* is the number of regions in the current variation store.

**Comment by Elzianor** [comment]
@Lorp Thank you very much! It was not that obvious when reading the docs :) Now all seems to be parsing correctly.

**Comment by Lorp** [comment]
Glad to hear it helped. I was scratching my head over the spec for a while myself!

**Comment by josh-hadley** [comment]
Thanks @Lorp for answering this. Speaking for Adobe, I can confirm that this is correct. @PeterCon, given @Elzianor's confusion over this, perhaps it would be useful to add Laurence's description to the spec as clarifying text for future implementors.

**Comment by Lorp** [comment]
Thanks for the confirmation. I’m happy for the text to migrate to the spec.

**Comment by vlevantovsky** [comment]
There is still an opportunity to make this correction part of the OFF AMD2 text, but it needs to be proposed for review/discussion as part of the AHG process (either via the email list or as a [new issue on MPEG/OFF Github](https://github.com/MPEGGroup/OpenFontFormat/issues)
