### ISSUE TITLE
Typo in opsz axisdescription

### ISSUE THREAD

**Issue by tiroj** [MicrosoftDocs/typography-issues#779]
> _Suggested programmatic interactions:_ Applications may choose to select an optical-size variant automatically based on the **displayedtext** size.

Should be ‘displayed text’.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3061e37e-08cf-d8be-345c-7f762521b910
* Version Independent ID: 9314da1d-dd1c-5730-ca08-a5b30ad7213f
* Content: [opsz design-variation axis tag (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_opsz)
* Content Source: [typographydocs/opentype/spec/dvaraxistag_opsz.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/dvaraxistag_opsz.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Thanks. Fixed.
