### ISSUE TITLE
[OpenType] Language System Tags for languages using U+0192 as a letter

### ISSUE THREAD

**Issue by moyogo** [MicrosoftDocs/typography-issues#781]
U+0192 LATIN SMALL LETTER F WITH HOOK ƒ is often designed as a florin symbol that is not letter-like (italic in upright styles, on the baseline, or at figure-height) which is problematic for the languages that use it as a lowercase letter with its uppercase U+0191 LATIN CAPITAL LETTER F WITH HOOK Ƒ.

It would be useful to have language systems tags for all the languages where a letter-like glyph should be used instead, so that glyph could be selected by default or with optional features.

The OpenType Language System Tags registry, as of 1.8.4, only has the Language System Tag for Ewe 'EWE' <tt>ewe</tt> (more than 4 million speakers). The following tags could be added:
|Language System|Language System Tag|Corresponding ISO 639 ID (if applicable)
|--|--|--|
| Avatime | AVN | [avn](https://iso639-3.sil.org/code/avn) |
| Lelemi| LEF | [lef](https://iso639-3.sil.org/code/lef) |
| Waci Gbe | WCI| [wci](https://iso639-3.sil.org/code/wci) |

**Comment by tiroj** [comment]
Since the florin symbol is now of historical use only, a good recommendation to font makers would be to prioritise the fhook letter form unless known that a character set will remain limited to European language support.

**Comment by PeterCon** [comment]
Added.
