### ISSUE TITLE
"FWord" should be "FWORD"

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#783]
For consistency with https://docs.microsoft.com/en-us/typography/opentype/spec/otff, use "FWORD".

Similarly, "F2Dot14" should be "F2DOT14".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2a9a6a1-a9b9-0864-8982-322da821389e
* Version Independent ID: a42612e3-dc1d-f980-fe4a-4880d1fd0086
* Content: [glyf - Glyf data table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/glyf)
* Content Source: [typographydocs/opentype/spec/glyf.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/glyf.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
