### ISSUE TITLE
Typo in abvm

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#786]
"UI suggestion: Control of the feature should not generall be exposed to the user."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4da11419-0864-96ff-7f67-296680843fc1
* Version Independent ID: 1d46dac1-d559-ce3e-2f6f-f47cf8cd9e0f
* Content: [Registered features, a-e (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae)
* Content Source: [typographydocs/opentype/spec/features_ae.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_ae.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by simoncozens** [comment]
(Edited to remove the fix, as you "are not accepting public contributions.")

**Comment by PeterCon** [comment]
Also fixing other instances.

**Comment by PeterCon** [comment]
Thanks; fixed (commit pending).
