### ISSUE TITLE
Missing word in fin3

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#789]
"Function: Used to Alaph glyphs..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fb16259e-1f7c-4e96-02b8-f692eb3e77e7
* Version Independent ID: eab1b2c5-0209-ccdf-b898-bbc5b5dbbe0f
* Content: [Registered features, f-j (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/features_fj)
* Content Source: [typographydocs/opentype/spec/features_fj.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_fj.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Thanks; fixed (commit pending).
