### ISSUE TITLE
Copy-paste error in dnom

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#790]
>  Recommended implementation; Glyphs for figures (digits) and related characters (grouping or decimal separators) are mapped to corresponding *numerator* glyphs in the font (GSUB lookup type 1).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4da11419-0864-96ff-7f67-296680843fc1
* Version Independent ID: 1d46dac1-d559-ce3e-2f6f-f47cf8cd9e0f
* Content: [Registered features, a-e (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae)
* Content Source: [typographydocs/opentype/spec/features_ae.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_ae.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
