### ISSUE TITLE
Can't find any discussion or `1.9-LABEL`

### ISSUE THREAD

**Issue by ChiefMikeK** [MicrosoftDocs/typography-issues#791]
> Share via Feedback is invited on proposed changes for version 1.9. Feedback should be submitted using the feedback mechanism, with a feedback link at the bottom of each page. All feedback will appear as issues in the [MicrosoftDocs/typography-issues](https://github.com/MicrosoftDocs/typography-issues) GitHub repository, and can be discussed there.

- The feedback & disscussion link should go to `milestone:"OpenType 1.9"` vice linking to all open tickets.  
`https://github.com/MicrosoftDocs/typography-issues/milestones` 
- Please add an additional labels for [DISCUSSION](https://github.com/MicrosoftDocs/typography-issues/labels/DISCUSSION) and **`1.9`**
- `https://github.com/MicrosoftDocs/typography-issues/labels/DISCUSSION`
- Also Discussion and Issues can be added on separate drop-tabs if enabled in the repo.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 78d1fc69-7a53-e149-90df-d62d7458775d
* Version Independent ID: 1e426bf0-4775-0be5-7c0a-f5f78911bedb
* Content: [OpenType 1.9 Alpha Review - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec190alpha/ot190alpha)
* Content Source: [typographydocs/opentype/otspec190alpha/ot190alpha.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec190alpha/ot190alpha.md)
* Product: **typography**
* GitHub Login: @pconstable
* Microsoft Alias: **pconstable**

**Comment by PeterCon** [comment]
There's no mechanism for this repo to automatically assign milestones or labels to issues. Issues related to the OT spec will be reviewed, and labels and milestone applied when triaging work for completing the OT 1.9 revision.
