### ISSUE TITLE
No download link

### ISSUE THREAD

**Issue by philipamour** [MicrosoftDocs/typography-issues#794]
Can't find download link

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d3c2a6fb-3005-b23b-bc83-f8046b852851
* Version Independent ID: f5d0fbf0-990b-7b3d-0c4a-bd4b51c8532e
* Content: [Segoe UI font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/segoe-ui)
* Content Source: [typographydocs/font-list/segoe-ui.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/segoe-ui.md)
* Product: **typography**
* GitHub Login: @nihar
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
See the [Licensing and redistribution info](https://docs.microsoft.com/en-us/typography/font-list/segoe-ui#licensing-and-redistribution-info) section of the page.

**Comment by philipamour** [comment]
> See the [Licensing and redistribution info](https://docs.microsoft.com/en-us/typography/font-list/segoe-ui#licensing-and-redistribution-info) section of the page.

How do you expect designers who are mainly on macOS to design Windows apps?

**Comment by PeterCon** [comment]
@philipamour See [Design toolkits and samples for Windows apps](https://docs.microsoft.com/en-us/windows/apps/design/downloads/).
