### ISSUE TITLE
KAW (Kawi or "Old Javanese") missing

### ISSUE THREAD

**Issue by mekkablue** [MicrosoftDocs/typography-issues#797]
For proper Javanese (and also Balinese) OT feature code, we may need a possibility to reference [Kawi (Old Javanese)](https://en.wikipedia.org/wiki/Kawi_language), ISO language code `KAW`. Can this be added to the list of registered languages?

TIA, Fadhl & Rainer

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662c6f54-f90c-52ed-dca2-0f0a0a49fee5
* Version Independent ID: 6aa33924-d45e-60c3-a9fd-e317ff662993
* Content: [Language system tags (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags)
* Content Source: [typographydocs/opentype/spec/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Added.
