### ISSUE TITLE
Why Urdu Typesetting make my urdu text weird. 

### ISSUE THREAD

**Issue by awaischorahi** [MicrosoftDocs/typography-issues#798]
I want to use Microsoft Urdu Typesetting but it make my some of words like this distort & space. I tried Times new roman it works fine but i want to use Urdu typesetting font. I tried Jameel noori nastaleeq but i got result same as i get earlier. Kindly please tell me why i am getting this issue. tried Ms Word 2016 & also 2013. 
![Capture](https://user-images.githubusercontent.com/36324342/124473980-68b03a00-ddb9-11eb-9169-9ab016217fe4.PNG)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e49c0a80-1bad-7a41-fb6d-4ee348c38339
* Version Independent ID: bce9a14c-4ec8-be80-5b98-fcca4ae43ee7
* Content: [Urdu Typesetting font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/urdu-typesetting)
* Content Source: [typographydocs/font-list/urdu-typesetting.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/urdu-typesetting.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by awaischorahi** [comment]
@PeterCon Can you help me in this? why Urdu type setting separate & put a space between two characters.I tried few other custom Urdu fonts, I got same result. but its work fine in Times new roman. Also i tried in  Android Ms Word I got same result there too.

**Comment by PeterCon** [comment]
@awaischorahi Can you please provide a txt file containing a sample text and also image files (e.g. PNG) or PDF that shows the incorrect display you currently see, but also what you expect as a correct result. Thanks.

**Comment by awaischorahi** [comment]
[File.docx](https://github.com/MicrosoftDocs/typography-issues/files/6765782/File.docx)
![result](https://user-images.githubusercontent.com/36324342/124506120-6c0ceb00-dde4-11eb-863d-4876a790fafb.PNG)
I attach the file & result image. Please help me in this & fix it as soon as you can.

**Comment by awaischorahi** [comment]
[Uploading error & expected result file.pdf…]()
I have attached the PDF file where i explain a little bit more about it. Kindly check it & also see expected result that i want. Thanks

**Comment by tiroj** [comment]
The Urdu Typesetting font only supports a subset of Arabic script characters needed for Urdu language text. The character ٸ U+0678 ARABIC LETTER HIGH HAMZA YEH is not included, so what you are seeing here is fallback to a glyph from a different font, which then does not shape correctly because the glyph processing run is broken.

**Comment by awaischorahi** [comment]
@tiroj Thanks for your reply, Then what should I do now? How can i fix it or will Microsoft team will handle this? How can i get my expected result as i sent in picture or PDF. Thanks

**Comment by tiroj** [comment]
I can’t speak for Microsoft’s plans, but my understanding is that the Urdu Typesetting font was only ever intended to be used for Urdu language text, and that U+0678 is not a character in the standard Urdu orthography. So I doubt that they would add this character unless it were necessary for some form of Urdu text.

It might be helpful if you explain why you want to use this character, for what language, and what it’s role is in the writing of that language.

**Comment by awaischorahi** [comment]
This is part of Urdu language we used it in many times and for the combination of different words. we used it in daily life. This is mandatory part of urdu. See برائے its also contain that character. This is a example we used it in our daily life. How can i request Microsoft team to add this or fix it?

**Comment by tiroj** [comment]
The character in برائے is U+0626 ARABIC LETTER YEH WITH HAMZA ABOVE. That is a different character than the one that is causing problems in your document, which is U+0678 ARABIC LETTER HIGH HAMZA YEH. Both these characters are forms of yeh with a hamza above, but the position of the hamza differs.

If you change the encoding of the word in your document to use U+0626—which is indeed a standard Urdu character—it should display correctly in the Urdu Typesetting font: عائشہ

![image](https://user-images.githubusercontent.com/5614500/124523169-c7ba8280-ddaa-11eb-9957-6cf781ceccc1.png)

**Comment by awaischorahi** [comment]
Yes this برائے is a different word but it contains a character of "yeh" ٸ this makes words weird and goes separate to other. I don't know how can i do encoding in Ms Word. Sorry I am not sure of it but if i do should i have to encode it where ever i use this ٸ.
I tried Naskh it was working fine few days back but now it has also the same problem with it. This ٸ goes separate or glyph. I think there is a bug in Ms Word or glyph processing is broken.
Note: Ms Word Android app also have the same problem because its can't fetch the font data correctly.

**Comment by B-starboy** [comment]
Thanks for your information about the issue. I am not sure what to do about it at this time , but I am looking into this.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by awaischorahi** [comment]
@B-starboy Thanks I am waiting for it.

**Comment by awaischorahi** [comment]
@PeterCon Is there any progress about this issue?

**Comment by tiroj** [comment]
There are two yeh with hamza characters in the Unicode Standard:

U+0626 ARABIC LETTER YEH WITH HAMZA ABOVE
U+0678 ARABIC LETTER HIGH HAMZA YEH

The first of these, U+0626, is a character in the Urdu orthography and appears on Urdu keyboards:
<img width="599" alt="Screenshot 2021-07-06 at 9 48 53 AM" src="https://user-images.githubusercontent.com/5614500/124638264-9b9d1100-de3f-11eb-995b-af9977601802.png">
When written in isolated or final form, the hamza sign is placed over the left tip of the letter.

The second of these, U+0678, is _not_ a character in the Urdu orthography and does not appear on Urdu keyboards, but is similar enough to the Urdu letter that it might be mistaken for it by some users and incorrectly input into Urdu text using e.g. copy/paste, onscreen character pickers, or non-Urdu or atypical keyboard layouts. In contrast to the Urdu character, in the isolated form of the  U+0678 character, the hamza is placed high over the _right_ side of the letter. This character is occurs in the Arabic-script orthographies of some Turkic languages, e.g. the Kazakh alphabet, in which it represents a near-close near-front unrounded vowel /ɪ/.

Although they look similar—or identical in initial or medial position—, these characters belong to different writing systems and represents entirely different sounds in those writing systems.

**Comment by awaischorahi** [comment]
@tiroj Thank you so much for well explained. You provide me a very good information. I really didn't know about it. Now at least i figured why i get that issue. can you please tell me which Urdu Keyboard you have used. If you have any download link it would be good & please guide me if i use this ٸ U+0678 yeh which font would be good for me or any other suggestion would be great too. Thanks again

**Comment by PeterCon** [comment]
@awaischorahi On Windows 10, when you add Urdu to your language settings (either Urdu (India) or Urdu (Pakistan)), the normal Windows Urdu keyboard layout will be enabled. The Shift state for the 6th key from the left on the bottom row (same key as N on a US-QWERTY layout) will generate U+0626.

You should not be using U+0678 for Urdu. In fact, that character really shouldn't be used for any language, and the code charts for the next version of Unicode are being revised to indicate that use is discouraged. See [the Unicode 14.0 beta chart for Arabic block](https://www.unicode.org/charts/PDF/Unicode-14.0/U140-0600.pdf)

**Comment by awaischorahi** [comment]
@PeterCon Thank you so much. I think i got the answer. Special thanks for both of you @tiroj and @PeterCon
