### ISSUE TITLE
Typo: “PaintTransformed”

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#799]
In colr_transform_glyph_gradient.png and colr_transform_glyph_transform_gradient.png, the first box is labeled “PaintTransformed”, which is a typo for “PaintTransform”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a0df445-4e69-2a2e-5faf-c3f75524d5e6
* Version Independent ID: 29369443-3d5b-92bc-c5b6-aab193f8ee12
* Content: [COLR - Color Table (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec190alpha/colr)
* Content Source: [typographydocs/opentype/otspec190alpha/colr.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec190alpha/colr.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Thanks; fixed.
