### ISSUE TITLE
batangche

### ISSUE THREAD

**Issue by badebayo** [MicrosoftDocs/typography-issues#80]
batangche download

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e2059473-4e13-0128-b802-587a6d128868
* Version Independent ID: 3ee80b59-b8a2-6060-bbd3-1228c10ff2e2
* Content: [BatangChe font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/batangche)
* Content Source: [typographydocs/font-list/batangche.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/batangche.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment]
Closing As Fixed
