### ISSUE TITLE
Avenir LT Pro regular font

### ISSUE THREAD

**Issue by nidhisinghjat** [MicrosoftDocs/typography-issues#800]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e7594f27-c747-e1e3-a667-bbe005d5d455
* Version Independent ID: edb2bd58-2c3b-5737-07f0-e4e1d07fc202
* Content: [Avenir Next LT Pro - Typography](https://docs.microsoft.com/en-us/typography/font-list/avenirnextltpro)
* Content Source: [typographydocs/font-list/AvenirNextLTPro.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/AvenirNextLTPro.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
There was no message.

**Comment by alib-ms** [comment]
No comments/feedback were added.
