### ISSUE TITLE
[OpenType] Language System Tags for Haida, Heiltsuk, Kwakiutl and Tlingit

### ISSUE THREAD

**Issue by moyogo** [MicrosoftDocs/typography-issues#801]
Please add a language system tag for Haida macrolanguage (ISO 639-3: hai), including Northern Haida (ISO 639-3: hdn) and Southern Haida (ISO 639-3: hax), a tag for Heiltsuk (ISO 639-3: hei), a tag for Kwakiutl (ISO 639-3: kwk) and a tag for Tlingit (ISO 639-3: tli).

Some orthographies Haida and Tlingit use a special casing pair for g̱ or ɢ̱ and G̱. If one wants to use ɢ̱ and G̱, there needs to be Haida or Tlingit specific casing features.

Heiltsuk and Kwakiutl use lambda and lambda with stroke, λ and ƛ. As there is no Latin lambda and there is no Latin capital lambda with stroke in Unicode, it would be useful to allow language specific features for these languages.

Because the Language System Tag 'HAI' is already defined for 'Haitian (Haitian Creole)' (ISO 639-3: hat), I suggest using 'HAI0' for Haida.

|Language System|Language System Tag|Corresponding ISO 639 ID (if applicable)
|--|--|--|
| Haida | HAI0 | [hai](https://iso639-3.sil.org/code/hai), [hax](https://iso639-3.sil.org/code/hax), [hdn](https://iso639-3.sil.org/code/hdn) |
| Heiltsuk | HEI | [hei](https://iso639-3.sil.org/code/hei)
| Kwakiutl | KWK | [kwk](https://iso639-3.sil.org/code/kwk)
| Tlingit | TLI | [tli](https://iso639-3.sil.org/code/tli)

**Comment by tiroj** [comment]
Kwakʼwala may be preferred term for Kwakuitl language.

**Comment by PeterConstable** [comment]
Looking at https://www.umista.ca/pages/kwakwakawakw to confirm how they spell the language name. They actually aren't consistent:

* U+02BC after a vowel
* U+0313 for some instances of k̓, but U+02BC for other instances
* U+0315 for t̕

(It's also too bad the Web font they use—Muli—doesn't actually support the characters they need.)

**Comment by PeterCon** [comment]
The requested tags have been added to the registry.
