### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by sawtawkalu** [MicrosoftDocs/typography-issues#802]
I installed Myanmar text font but i can not type it in Burmese or Karen it just appear in Eng so what is the issue? i try to reinstall it and the Keyboard still does not work. Is keyboard needed for the font as well? most of other font i installed, they all work for the language.

**Comment by tiroj** [comment]
The Myanmar Text font uses standard Unicode encoding of Myanmar characters. If you are getting English characters when typing, that means that your keyboard is inputing the ANSI 8-bit subset of Unicode, not correct Unicode Myanmar characters. 

You will need to install and activate a Unicode Myanmar keyboard driver. There are a number of options for this, including third-party keyboard layouts, but I suggest starting with the Windows language pack for Burmese. This web page has good general information on adding language support in Windows 10:
https://www.digitalcitizen.life/change-display-language-windows-10-english-another-language/
Note that you can either add a new language to be your default input and display language (which will localise the user interface), or just add a new keyboard driver, spelling dictionary, etc.

**Comment by alib-ms** [comment]
Information for managing the input and display language settings in Windows 10 is posted [here](https://support.microsoft.com/en-us/windows/manage-the-input-and-display-language-settings-in-windows-10-12a10cb4-8626-9b77-0ccb-5013e0c7c7a2).

**Comment by PeterCon** [comment]
I assume the issue was not having a Myanmar keyboard installed. Closing.
