### ISSUE TITLE
Consider providing permanent links to TrueType Instruction Set.

### ISSUE THREAD

**Issue by crlf0710** [MicrosoftDocs/typography-issues#803]
The opentype iso standard contains the following normative reference:

TrueType Instruction Set, http://www.microsoft.com/typography/otspec/ttinst.htm

This link quickly become outdated now. The newest url is: 
https://docs.microsoft.com/en-us/typography/opentype/spec/tt_instructions

I wonder if it makes sense to make this somehow a permanent link that can be updated overtime. Or make this a normative publication somehow. It would also be nice if a PDF version is provided.

**Comment by alib-ms** [comment]
Thank you for letting us know. I will submit a request to get the URL redirected. I will update when this is done.

**Comment by alib-ms** [comment]
Fixed. Old URL http://www.microsoft.com/typography/otspec/ttinst.htm now redirects to https://docs.microsoft.com/en-us/typography/opentype/spec/tt_instructions.
