### ISSUE TITLE
Feature Scripts

### ISSUE THREAD

**Issue by Derrekito** [MicrosoftDocs/typography-issues#81]
I'm completely new to font design/scripting. This documentation has been the most useful information on OpenType fonts I've been able to locate anywhere. However, providing .fea script boilerplate examples would go a long way toward helping the community. For example, after reading the JSTF section I'm not certain how to define a JSTF table. Perhaps the following is correct?

table JSTF {  
} JSTF;

And are values such as jstfScriptCount supposed to be explicitly defined in the .fea file? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b691a267-906d-cafb-2f9e-4dadc8691427
* Version Independent ID: 41170219-4e78-137d-9382-2d06039a4e8c
* Content: [JSTF — Justification Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/jstf#jstf-header)
* Content Source: [typographydocs/opentype/spec/jstf.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/jstf.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by PeterCon** [comment]
Hi, Derrekito. Your question pertains to use of tools for creating fonts, not to the OpenType spec itself. You should post your question to a forum that focuses on the tools you're using.
