### ISSUE TITLE
Wrong letter case

### ISSUE THREAD

**Issue by LineGap** [MicrosoftDocs/typography-issues#811]
This is in reference to https://docs.microsoft.com/en-us/typography/opentype/spec/recom

Most of these comments pertain to the wrong letter case being used for several of the terms.  The letter case should be consistent with how the term appears in the table where it originates.

ISSUE #1.  Under the section titled Macintosh.
Immediately below the Macintosh-OpenType metrics comparison table, the following expression appears:
"The suggested BTBD = ascent + descent + leading"

The terms ascent and descent are not in the table and either need to be defined or the words ascent and descent changed to ascender and descender (both lowercase) to be consistent with Macintosh metrics.  The change will make this expression consistent with the one appearing in the section titled Windows which uses the Windows metrics.

ISSUE #2.  Under the section titled Macintosh.
The first sentence is using the terms Ascender and Descender, but Apple uses lowercase for both terms, as seen in the Macintosh-OpenType metrics comparison table.  To avoid using the capital letter for Ascender which begins the sentence, recommend the first sentence be changed to:

"The terms ascender and descender are metrics defined by Apple and are not to be confused…"

ISSUE #3.  Under the section titled Making Them Match
The expression shown is using the wrong letter case for three of its terms.  The expression should read:
lineGap >= (yMax - yMin) - (ascender - descender)

Also, this section should indicate where these terms originate like what was done in some other sections on this page where the terms origination is not readily apparent.  For example, add a statement like the one below that is similar to one elsewhere:

"The lineGap, ascender and descender values are from the 'hhea' table, and the yMax and yMin are values from the 'head' table."

Or (which is preferred), add the table name as a prefix, as was done elsewhere:

hhea.lineGap >= (head.yMax – head.yMin) - (hhea.ascender – hhea.descender)

ISSUE #4.  Under the section titled Windows.
In the Windows-OpenType metrics comparison table, the following expression appears:
"MAX(0, LineGap - ((usWinAscent + usWinDescent) - (Ascender - Descender)))"

The terms LineGap, Ascender and Descender are the wrong letter case.  The expression should read:
"MAX(0, lineGap - ((usWinAscent + usWinDescent) - (ascender - descender)))"

Also, the last sentence should be changed to the proper case too:
"The lineGap, ascender, and descender values are from the 'hhea' table."

An aside.
The MAX(0) function is not defined, and although most mathematicians and programmers may be familiar with the function, I doubt many others would be.  In any case, it is redundant since the following statement already appears below it.
"It should be clear that the “external leading” can never be less than zero."
Furthermore, there are many other terms in the standard that have limited ranges, and they do not have functions limiting their range.  Thus, you can omit the Max function altogether and simply state:
lineGap - ((usWinAscent + usWinDescent) - (ascender - descender)))

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95e88b53-d670-0240-422c-72748258ab2a
* Version Independent ID: b5fff1ee-cf03-e424-a2dc-aee58e0429e4
* Content: [Recommendations for OpenType Fonts (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/recom)
* Content Source: [typographydocs/opentype/spec/recom.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/recom.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
For OT 1.9, a revision of the entire BTBD section is proposed, replacing the current content (including the Windows and Mac sub-sections) with the following:

## Baseline to Baseline Distances

The OS/2 table fields [sTypoAscender](os2.md#stypoascender), [sTypoDescender](os2.md#stypodescender), and [sTypoLineGap](os2.md#stypolinegap) free applications from Macintosh- or Windows-specific metrics which are constrained by backward compatibility requirements. See [above]() for recommendations regarding those values. The following discussion <del>only </del>pertains to the platform-specific metrics.

In early TrueType implementations on Windows and Macintosh platforms, different font values were used for line height metrics:

* Macintosh: the ascender, descender and lineGap values in the [&#39;hhea&#39;](hhea.md) table.
* Windows GDI: the [usWinAscent](os2.md#uswinascent) and [usWinDescent](os2.md#uswindescent) values in the OS/2 table.

In the GDI TEXTMETRIC structure, metric values for TrueType fonts were set as follows:

| GDI metric | OpenType metric |
| - | - |
| tmHeight | usWinAscent - usWinDescent |
| tmAscent | usWinAscent |
| tmDescent | usWinDescent |
| tmInternalLeading | usWinAscent + usWinDescent - unitsPerEm |
| tmExternalLeading | MAX(0, (hhea.ascender - hhea.descender + hhea.lineGap) - (usWinAscent + usWinDescent)) |

In addition, the usWinAscent and usWinDescent values were used to set a clip rectangle: in on-screen display, any portions of glyphs extending beyond these limits could be clipped.

In addition to these early platform implementations, different applications and text-layout engines (including newer Windows and Macintosh platforms) can use different logic to determine a default baseline-to-baseline distance using the various metric fields in the &#39;hhea&#39; or OS/2 tables. This has made it challenging for font developers to create fonts with predictable behavior when used in a wide range of applications. The following recommendations might be useful to increase likelihood of consistent behavior in different applications:

* Set sTypoAscender and sTypoDescender such that (sTypoAscender - sTypoDescender) = unitsPerEm.
* Set the USE_TYPO_METRICS flag (bit 7) in the [fsSelection](os2.md#fsselection) field of the OS/2 table.
* Set hhea.ascender = sTypoAscender, hhea.descender = sTypoDescender, and hhea.lineGap = sTypoLineGap.
* Set usWinAscent and usWinDescent such that (usWinAscent + usWinDescent) = (sTypoAscender - sTypoDescender + sTypoLineGap).

The following is alternative guidance that might also be useful:

* Set the USE_TYPO_METRICS flag (bit 7) in the fsSelection field of the OS/2 table.
* Set hhea.ascender = usWinAscent = sTypoAscender.
* Set hhea.descender = -usWinDescent = sTypoDescender.
* Set hhea.lineGap and sTypoLineGap to 0.

With either guidance, if the font requires applications to use a larger clipping rectangle, then usWinAscent and usWinDescent values can be set to larger values, though different behavior will be seen in applications that set line spacing using sTypo* values (as recommended) versus applications that set line spacing using the usWin* values.

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
