### ISSUE TITLE
head Table Clarifications

### ISSUE THREAD

**Issue by LineGap** [MicrosoftDocs/typography-issues#812]
This is in reference to
https://docs.microsoft.com/en-us/typography/opentype/spec/head

Issue #1.  The terms xMin, yMin, xMax, and yMax all have the same description.
"For all glyph bounding boxes (Glyphs without contours are ignored.)"

Yet, each term has a different meaning.  Using the same statement for all four terms does not describe what is different.  Since the terms are closely related to one another, recommend that the statement be replaced with a link or a note directing the reader to the following text placed below the table.

"A glyph's bounding box is the smallest rectangle aligned with the axes of the glyph's X-Y coordinate system where all four sides touch the edges of the glyph.  The box encloses the entire glyph and no more.  On the other hand, the font bounding box is the smallest rectangle that can enclose all the glyphs' bounding boxes with their origins aligned.  Glyphs without contours are ignored.  

The xMin is the distance from the origin to the left side of the font bounding box, and the xMax is the distance from the origin to the right side of the font bounding box.  Similarly, the yMin is the distance from the origin to the bottom of the font bounding box, and the yMax is the distance from the origin to the top of the font bounding box."

Issue #2.  The description for the term unitsPerEm provides a range of values, but does not describe the meaning of the term or how it is used.  Recommend a statement be added in the description that describes the purpose of the unitsPerEm.  For instance, something along the lines of:

"The unitsPerEm determine the granularity of the em square which is used by an application in determining the physical dimensions of type."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3ee780c-6509-ae67-2223-7c0468dc745c
* Version Independent ID: 907dff3d-e18f-e9c9-3ff6-7cf7f05aa7be
* Content: [head - Font header table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/head)
* Content Source: [typographydocs/opentype/spec/head.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/head.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Proposed changes for OT 1.9:

For issue 1:

* Descriptions for xMin, etc. in the table revised as follows:
  > <del>For</del><ins>Minimum x coordinate across</ins> all glyph bounding boxes.<del> (Glyphs without contours are ignored.)</del>

* Add a paragraph after the table:
  > A glyph’s bounding box is the smallest rectangle that contains all of the glyph’s control points. (See the ['glyf'](https://docs.microsoft.com/en-us/typography/opentype/spec/glyf#glyph-headers) table chapter for more information.) The xMin, yMin, xMax and yMax values provide a bounding box that will contain all glyphs from the font. Glyphs without contours are ignored.

For issue 2: add a paragraph after the table:

> The unitsPerEm value determines the granularity of the font’s coordinate grid at which coordinates can be specified for visual elements such as outline control points or mark-attachment anchor positions. See the [TrueType Fundamentals](https://docs.microsoft.com/en-us/typography/opentype/spec/ttch01#funits-and-the-grid) chapter for more information.

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
