### ISSUE TITLE
[OpenType] Language System Tags for languages using Tamil script

### ISSUE THREAD

**Issue by bobh0303** [MicrosoftDocs/typography-issues#819]
[NLCI Tamil script fonts](https://github.com/nlci/taml-font-thiruvalluvar/releases/) use the following Language System Tags that should be added to the OpenType Layout Tag registry:

| Language System | Language System Tag | Corresponding ISO 639 ID |
|----|----|----|
| Betta Kurumba | XUB | xub |
| Irula | IRU | iru |
| Jennu Kurumba | XUJ | xuj |
| Wayanad  Chetti | CTT | ctt |

All of the above proposed Language System Tags match their corresponding ISO 639-3 codes.

**Comment by PeterCon** [comment]
The requested tags have been added to the registry.
