### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by PeterCon** [MicrosoftDocs/typography-issues#82]
Typos in Example 4:
PPairSet -&gt; PairSet
&quotPo&quot -&gt; "Po"
TPairSet -&gt; PairSet

These typos are in every version back to (at least) 1.4.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3f748ff4-44a6-6395-e0ce-d249b8c9541b
* Version Independent ID: b80d0359-5657-632b-29e8-142c06902001
* Content: [GPOS — Glyph Positioning Table - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/gpos)
* Content Source: [typographydocs/opentype/spec/gpos.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gpos.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by v-nihar** [comment]
Closing as Fixed.
