### ISSUE TITLE
[OpenType] Language System Tags for languages using Arabic script

### ISSUE THREAD

**Issue by bobh0303** [MicrosoftDocs/typography-issues#820]
SIL Arabic fonts [Scheherazade New](http://software.sil.org/scheherazade) and [Harmattan](http://software.sil.org/harmattan) use the following Language System Tag that should be added to the OpenType Layout Tag registry:

| Language System | Language System Tag | Corresponding ISO 639 ID |
|----|----|----|
| Rohingya | RHG | rhg |

The proposed Language System tag matches the corresponding ISO 639-3 code.

**Comment by PeterCon** [comment]
The requested tag has been added to the registry.
