### ISSUE TITLE
No way to download font

### ISSUE THREAD

**Issue by frankvg** [MicrosoftDocs/typography-issues#822]
Offers a great description of the font I need. Just no way to make it work.  Word 365 has the font, but I want to use it in other Windows 10 programs.  it's not listed in my Windows 10 Fonts.  So how to download it?  There should be an easy-to-select way to add it to your Windows.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c629c9b-d28b-aa25-5344-376a3dd28b2e
* Version Independent ID: 991734e0-5210-6a12-f671-1c0b07d11e58
* Content: [Mangal font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/mangal)
* Content Source: [typographydocs/font-list/mangal.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/mangal.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by kenmcd** [comment]
Mangal is included in the free Devanagari Supplemental Fonts package. 
This is normally downloaded and installed automatically if you activate relevant language support in Windows, but you can also get the font using the following steps:
  1.  Click Start > Settings.
  2.  In Settings, click Apps, click Apps & features, and then click Optional features.
  3.  If you don't see Devanagari Supplemental Fonts in the list of installed features, click the plus sign (+) to add a feature.
  4.  Select Devanagari Supplemental Fonts in the list, and then click Install.

**Comment by frankvg** [comment]
Thanks!  That worked!

Best regards,

Frank.
