### ISSUE TITLE
Tables unreadable

### ISSUE THREAD

**Issue by pgundlach** [MicrosoftDocs/typography-issues#824]
Please use `valign="top"` on your HTML tables. They are hard to read with the default (`valign="middle"`).
This applies to all pages in the OpenType spec.

<img width="345" alt="valign" src="https://user-images.githubusercontent.com/209434/132338865-0c8f6de1-d0c8-45c7-910b-ffc350347a8c.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8d3d5b8-059a-613d-8666-80438ebd7aa7
* Version Independent ID: 6a0f2873-97c3-833c-45e4-340ea96667a0
* Content: [GDEF — Glyph Definition Table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/gdef#feedback)
* Content Source: [typographydocs/opentype/spec/gdef.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gdef.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
@pgundlach :  I don't see the same result you show in the screenshot you provided. I've tried different browsers on both Mac and Windows, and see clear column separation and top-aligned cells.

![image](https://user-images.githubusercontent.com/12788502/133846130-71b788ae-a577-46b2-9b4a-3b6f407101dc.png)

Perhaps when you were viewing the page the stylesheets weren't getting loaded?

If you continue to have the same issue, please provide more details.

**Comment by pgundlach** [comment]
I see that it works in all browsers tested except for  Safari version 14.1.2 (14611.3.10.1.5) on macOS 10.14.6 (18G9323). It works on the current macOS (Big Sur) Safari.

With the current Safari, the overall page looks different. I have made sure that no ad blocker is in the way.

<img width="1412" alt="browser" src="https://user-images.githubusercontent.com/209434/133880601-c1767922-71e5-4b76-bd75-96d986f0ec98.png">
