### ISSUE TITLE
Feedback button does not work on Safari / macOS

### ISSUE THREAD

**Issue by pgundlach** [MicrosoftDocs/typography-issues#825]
The feedback button does not work on Safari / macOS. Nothing happens when I click on the feedback button. It works on Chrome.

Safari Version 14.1.2 (14611.3.10.1.5)
macOS version 10.14.6 (18G9323)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e8d3d5b8-059a-613d-8666-80438ebd7aa7
* Version Independent ID: 6a0f2873-97c3-833c-45e4-340ea96667a0
* Content: [GDEF — Glyph Definition Table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/gdef#feedback)
* Content Source: [typographydocs/opentype/spec/gdef.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/gdef.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
@pgundlach : I can't reproduce this issue: the feedback button works for me in Safari on macOS v11.6.

**Comment by pgundlach** [comment]
Likely related to #824 - the current macOS 11 works fine here as well.
