### ISSUE TITLE
Can MathVariants.horizGlyphCoverageOffset be NULL?

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#828]
Both Linux Libertine O and LinLibertine_R contain NULL values for MathVariants.horizGlyphCoverageOffset. This makes sense, because MathVariants.horizGlyphCount is zero. But the spec doesn't explicitly say that these coverage offsets may be NULL - and it *does* say explicitly that *other* coverage offsets may be NULL. I think this is probably a spec omission, but it may be a non-conforming font.

(Found because the OpenType parser in SILE just tripped over these fonts.)

cc @khaledhosny, @alerque.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f0076fd2-52b0-2989-3142-fd9e456b9514
* Version Independent ID: 4aef8fa3-2ad3-7933-5a77-0a7473e66112
* Content: [MATH - The mathematical typesetting table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/math)
* Content Source: [typographydocs/opentype/spec/math.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/math.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by khaledhosny** [comment]
I think Behdad will tell you [all offsets can NULL](https://github.com/khaledhosny/ots/issues/172).

Cc @fred-wang

**Comment by PeterCon** [comment]
Re MathVariants.horizGlyphCoverageOffset, I'd say that it's valid for that to be NULL: that would simply mean there are no horizontal growth variants. The spec could be updated to call out that this may be NULL.

>all offsets can be NULL

A parser may need to anticipate null offsets (rather than fail), and in some cases NULL offsets are well formed and valid. But clearly in some cases a NULL offset results in an invalid font. E.g., a ttc header with a NULL table directory offset won't be valid. (If nothing else, fonts within the collection can't have sfntVersion = 'ttcf'.) I'm not sure that the spec needs to call out in every case what is valid, but am open to suggestions.

**Comment by PeterCon** [comment]
After further investigation and discussion with implementers, I'll reverse what I said regarding this coverage offset.

One implementation might assume that all offsets can be NULL, but that doesn't mean that all implementations would make the same assumption. There's no significant advantage to using NULL for a coverage offset if there are no covered glyphs: it saves only four bytes of data.

It might have been reasonable to allow for NULL offsets to coverage tables if that principle had been established from the beginning of OpenType Layout. But that wasn't done. There may be different opinions on whether that was unfortunate, but either way that's "water under the bridge". Today, we have to assume that some implementations expect non-NULL offsets to these coverage tables (and, in fact, such do exist), and so require that font data have non-NULL offsets even if the <dir>GlyphCount field is 0. Else, an implementation may begin reading what it assumes to be a coverage table, and get garbage, including conflicting glyph count fields (which would it believe?).

So, the MATH spec indicates that some offset fields may be NULL, but not other offset fields. Font parsers can be defensive, anticipating NULL offsets in the latter cases, but font compilers really should not ("must not") generate data with NULL offsets in those cases.

I can consider adding some language to that effect.

**Comment by fred-wang** [comment]
So IIRC other tables (e.g. GSUB) contain CoverageOffset? I don't have preference on this, but I think we should just try to be consistent.

**Comment by PeterCon** [comment]
No fields for offsets to coverage tables in GSUB or GPOS are spec'd as allowing NULL.

**Comment by PeterCon** [comment]
For OT 1.9 the following is a proposed addition to The OpenType Font File chapter at the end of the [Data Types](https://docs.microsoft.com/en-us/typography/opentype/spec/otff#data-types) section.

>In some cases, fields for subtable offsets are documented as permitting NULL values when the given subtable is optional. For example in the [BASE table header](https://docs.microsoft.com/en-us/typography/opentype/spec/base#base-header), the horizAxisOffset and vertAxisOffset fields may be NULL, meaning that either subtable (or both) is optional. A NULL subtable offset always indicates that the given subtable is not present. Applications should never interpret a NULL offset value as the offset to subtable data. For cases in which subtable offset fields are not documented as permitting NULL values, font compilers must include a subtable of the indicated format, even if it is a header stub without further data (for example, a [coverage](https://docs.microsoft.com/en-us/typography/opentype/spec/chapter2#coverage-table) table with no glyph IDs). Applications parsing font data should, however, anticipate non-conformant font data that has a NULL subtable offset where only a non-NULL value is expected.

**Comment by simoncozens** [comment]
I’ve never really been keen on the fact that the spec - which is really a description of the on-disk representation of the font file - refers to NULLs anyway. There’s no such thing as a NULL byte, just zeros.

**Comment by PeterCon** [comment]
@simoncozens Valid critique. Spec has been that way for decades, though, so I think there's not a priority to change that.

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
