### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by PeterCon** [MicrosoftDocs/typography-issues#83]
Under OpenType 1.7: "htmx.htm" should be "hmtx.htm"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 58ee5664-1103-604f-752f-428d42acef99
* Version Independent ID: 8583ef1a-b9f7-ee4d-5fb1-13544b65b63a
* Content: [OpenType specification change log - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/changes)
* Content Source: [typographydocs/opentype/spec/changes.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/changes.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by v-nihar** [comment]
Closing as Fixed
