### ISSUE TITLE
Updated links for Adobe CFF and Type2 Charstring specification PDFs

### ISSUE THREAD

**Issue by josh-hadley** [MicrosoftDocs/typography-issues#832]
The PDFs for Adobe Technical Note #5176 and #5177 (as mentioned in the first paragraph of this page) have updated links:
 - #5176: https://adobe-type-tools.github.io/font-tech-notes/pdfs/5176.CFF.pdf
 - #5177: https://adobe-type-tools.github.io/font-tech-notes/pdfs/5177.Type2.pdf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 17b4d28b-40cc-986c-e84c-e106317c413e
* Version Independent ID: b6b21260-0114-3f2c-c9d3-2c8eb81f2e72
* Content: [CFF - Compact font format table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/cff)
* Content Source: [typographydocs/opentype/spec/cff.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cff.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
The existing links pointing at adobe.com appear to still work, and the docs appear to be identical (PDFs copied as is to GitHub). Will the old links be getting killed?

**Comment by josh-hadley** [comment]
Yes, the old links will be getting killed (they were supposed to be nuked a while ago, actually, which was the reason for moving them to GitHub).

**Comment by vlevantovsky** [comment]
@josh-hadley 
These links are official references as part of the ISO OFF standard. There is a document Adobe submitted to ISO a while back (like, a decade ago) where they promised to always maintain these documents public and to never take the links down. Since the ISO standard is archived in the PDF format, the older versions cannot be updated, and the links there must remain live. Redirecting them to a new location is fine, but the original link should not be dead (like it's the case now for http://partners.adobe.com/public/developer/en/font/5176.CFF.pdf)

**Comment by josh-hadley** [comment]
@vlevantovsky thanks for that info. Any chance you have a reference to that agreement that I could remind our link-maintaining people about? I'll see about getting that dead one re-directed. I'm now concerned that there might be others that need the same treatment.

**Comment by vlevantovsky** [comment]
> Any chance you have a reference to that agreement that I could remind our link-maintaining people about?

I don't have a copy of that document but it is called "Reference Explanatory Report" and is a standard form for any outside technical document that is included by reference as part of an ISO Standard. I believe two different forms were submitted - once (way back in 2003) when the OpenType specification was included as an external reference in MPEG-4 part 18, and the updated form, when the OT was submitted as a contribution that formed the basis for ISO Open Font Format (MPEG-4 part 22).

**Comment by josh-hadley** [comment]
OK thanks, I'll see if I can chase that up with folks here. In the meantime, I've submitted that broken URL (and the same for its companion T2Char which I assume is also broken) to our team that manages redirects. They should have it restored soon.

**Comment by PeterConstable** [comment]
If a redirect will be set up for the older URL so that it will continue to work, then it's probably better not to change what's used in the OT spec to avoid differences between OT and OFF.

**Comment by josh-hadley** [comment]
@PeterCon I agree -- although the OT Spec is already different from OFF (OT Spec uses `http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/font/pdfs/...` whereas OFF uses `http://partners.adobe.com/public/developer/en/font/...`). So maybe the task here is to switch the OTSpec to use the same URLs as the OFF (_after_ I get the redirects sorted on my end, because the OFF links are still broken).

I apologize for the churn on this -- I did not realize the extent of this seemingly innocent change!

**Comment by PeterCon** [comment]
@josh-hadley @vlevantovsky I'm wondering how I should be handling this in the OT spec. The OT spec currently has these links:

* http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/font/pdfs/5176.CFF.pdf
* http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/font/pdfs/5177.Type2.pdf

These links appear in two pages of the OT spec: 
* [home page](https://docs.microsoft.com/en-us/typography/opentype/spec/)
* [CFF](https://docs.microsoft.com/en-us/typography/opentype/spec/cff)

The [CFF2](https://docs.microsoft.com/en-us/typography/opentype/spec/cff2) page also reference these (and a third note) but already has a link to <https://adobe-type-tools.github.io/font-tech-notes/>.

Vlad, for minimizing content diffs between OT and OFF, does it matter what links the OT spec uses? (I don't think it's a concern to edit the links in the online OT spec.)

Josh: What's the status on getting redirects for the older URLs?

**Comment by josh-hadley** [comment]
> Josh: What's the status on getting redirects for the older URLs?

Redirects have been (re-)established for
http://partners.adobe.com/public/developer/en/font/5176.CFF.pdf 
and
http://partners.adobe.com/public/developer/en/font/5177.Type2.pdf

to
https://adobe-type-tools.github.io/font-tech-notes/pdfs/5176.CFF.pdf
and
https://adobe-type-tools.github.io/font-tech-notes/pdfs/5177.Type2.pdf

So OFF should once again work. As to what OTSpec does about this: I also don't think it's a concern to have different URLs, so pointing directly to the redirected destination seems fine to me.

**Comment by vlevantovsky** [comment]
Great, thank you Josh! Just to confirm that checked both links and they do work.

> Vlad, for minimizing content diffs between OT and OFF, does it matter what links the OT spec uses? (I don't think it's a concern to edit the links in the online OT spec.)

OFF Bibliography section is using links to partners.adobe.com. I don't think it matters what links are used in OT spec for as long as they point to (and/or are resolved to bring users to) the right place. Josh and I have been working together to make sure that the "static" links exist and are redirected to the right physical storage location if and when it changes - for as long as this works it might be best to simply use partners.adobe.com as "static links".

**Comment by PeterConstable** [comment]
@josh-hadley What about links to 5902? Currently the OT spec is using this:

<https://wwwimages2.adobe.com/content/dam/acom/en/devnet/font/pdfs/5902.AdobePSNameGeneration.pdf>

I'm not sure what OFF has. That is currently working; will it have a redirect? Or is there a redirect for a URL at partners.adobe.com?

**Comment by vlevantovsky** [comment]
> I'm not sure what OFF has. That is currently working; will it have a redirect? Or is there a redirect for a URL at partners.adobe.com?

The OFF text currently has the same link in the Bibliography section. I agree we would be better off if all references are maintained under one "redirect" roof at partners.adobe.com - would be much easier for users and maintainers alike.

**Comment by josh-hadley** [comment]
I'm not able to determine whether 5902.AdobePSNameGeneration.pdf was ever under the "partners" umbrella. If there's desire to have both OFF and OTSpec reference everything under that subdomain (even if it never was there previously), I can see about putting in some additional redirect requests. I agree that having both standards reference "<something>.adobe.com" consistently is probably a good thing.

OFF has one additional "wwwimages" one that should probably get the same treatment: https://wwwimages2.adobe.com/content/dam/acom/en/devnet/font/pdfs/5015.Type1_Supp.pdf

**Comment by vlevantovsky** [comment]
It would be ideal to convert all Adobe external references to a single hosting location under partners.adobe.com (as it's currently the case) or "<something>.adobe.com" for as long as it's consistent and all redirects are properly maintained.

**Comment by jwr12135** [comment]
The links in the current documentation to the Adobe technical notes do not seem to work at all right now. They just show "Page not found".

**Comment by PeterConstable** [comment]
@josh-hadley The links to partners.adobe.com appear to be redirecting now to adobe-type-tools.github.io. Can I go ahead and close this?

**Comment by PeterCon** [comment]
These have been fixed.
