### ISSUE TITLE
In the maxp spec, include CFF2 in fonts that use Format 0.5

### ISSUE THREAD

**Issue by Lorp** [MicrosoftDocs/typography-issues#833]
[Enter feedback here]

"Fonts with CFF data" should read "Fonts with CFF or CFF2 data"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a6f198f8-04dd-6617-1a83-35065b2a9ad9
* Version Independent ID: dea9fd4f-3a60-fa9a-e7c2-cf9c0f04bd50
* Content: [maxp - Maximum Profile table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/maxp)
* Content Source: [typographydocs/opentype/spec/maxp.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/maxp.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
