### ISSUE TITLE
[question] Is a base mapping required for non-default UVS entries?

### ISSUE THREAD

**Issue by josh-hadley** [MicrosoftDocs/typography-issues#838]
Regarding [format 14/UVS subtables](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#format-14-unicode-variation-sequences): the examples seem to assume that Unicodes referenced for non-default UVS mappings will have an explicit (non-zero) mapping in the base Unicode cmap subtable(s). But there doesn't seem to be any actual _requirement_ for this and in fact, some current implementations seem to handle this unusual case without trouble (NOTE: the behavior of _default_ UVS mappings does seem to imply a requirement for a base mapping; this question is only about _non-default_ UVS entries).

My question is: should it be considered valid for non-default mappings in a UVS subtable to reference Unicodes that aren't present in a base Unicode subtable?

Regardless of the answer: I think it might be helpful to add a clarifying note to this part of the spec as the presence of UVS entries is important in understanding which Unicodes a font supports.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86923ff4-2b60-9144-e2b4-77cdb36fd698
* Version Independent ID: ea221e53-f51a-8233-3c0b-d416e5360623
* Content: [cmap - Character To Glyph Index Mapping Table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#format-14-unicode-variation-sequences)
* Content Source: [typographydocs/opentype/spec/cmap.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cmap.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Proposed addition at the end of the Default UVS section:

>All code points listed in the ranges[] array should have corresponding entries in a Unicode 'cmap' subtable. Applications should take precautions in case this is not true in some fonts, however.

Proposed addition at the end of the Non-default UVS section:

>Typically, code points listed in the uvsMappings[] array will have corresponding entries in a Unicode 'cmap' subtable. This is not required, however. For example, it might not be the case if a font is intended for use with content in which a given Unicode character only occurs in a variation sequence.

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
