### ISSUE TITLE
Clarify table requirements for variable fonts

### ISSUE THREAD

**Issue by josh-hadley** [MicrosoftDocs/typography-issues#847]
To some extent this is actually clarifying what a “variable font” is. With the addition of Feature Variations to the spec, it’s possible to have a ‘glyf’-based font with no ‘gvar’, or a CFF-based font (not CFF2) that is “variable” solely through the ‘fvar’ + GSUB (or GPOS) Feature Variations.

The [wording of the spec](https://docs.microsoft.com/en-us/typography/opentype/spec/otvaroverview#variation-data-tables-and-miscellaneous-requirements) currently requires a ‘gvar’ for TrueType-based (‘glyf’) fonts containing an ‘fvar’. Similarly it requires a ‘CFF2’ table for CFF-based fonts containing an ‘fvar’. Given that variability can come solely from Feature Variations, it seems this spec requirement could be relaxed or re-worded to allow for TrueType-based variable fonts to omit the ‘gvar’ table, and allow CFF-based variable fonts to use a ‘CFF ‘ table.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 41ea55ee-53f0-15da-1819-6dbbd9ae0e51
* Version Independent ID: 5746bf07-2094-52b3-3285-dadc590006c7
* Content: [OpenType Font Variations overview (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otvaroverview#variation-data-tables-and-miscellaneous-requirements)
* Content Source: [typographydocs/opentype/spec/otvaroverview.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otvaroverview.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
I might be inclined to identify several different categories of fonts that are variable in ‘and/or’ terms: design variable fonts, feature variable fonts, colour variable fonts. A font might involve multiple kinds of variation, but a font that implements only one kind of variation would still be a variable font.

**Comment by PeterCon** [comment]
I'm glad this issue was raised: it makes sense to me that some update to this page should be made in OT 1.9 given the introduction of COLR v1. Having given more thought, I think it would be reasonable to say that variable fonts have an fvar table with one or more design axis that can be used to vary _some_ aspect of the visual appearance. That could set a reasonable level of expectation for users. So, perhaps only feature variations are used; or perhaps there's no gvar but there is an HVAR table to adjust advance widths; or perhaps only COLR. And if some font claims to be variable (has fvar and STAT) but users can't detect any visual change, then that would be a matter between the font vendor and their customer.

Thinking back... Back in fall 2016, did Adam Twardoch implement a demo font that had an fvar table but only used it in conjunction with feature variations?

**Comment by Lorp** [comment]
Indeed, that’ll be Zinzin

https://github.com/twardoch/varfonts-ofl/blob/master/ZinzinVF-OFL

**Comment by josh-hadley** [comment]
Great discussion folks :-) I raised this because the question of conformance came up with a private implementation and people were questioning the table requirements for a font much like Zinzin.

> it would be reasonable to say that variable fonts have an fvar table with one or more design axis that can be used to vary some aspect of the visual appearance

Yes, that's the meat of what I was after with this.

> if some font claims to be variable (has fvar and STAT) but users can't detect any visual change, then that would be a matter between the font vendor and their customer

This seems reasonable to me. I think such fonts will probably be unusual and uncommon -- but it shouldn't be prohibited.

**Comment by PeterCon** [comment]
Proposed revisions for OT 1.9:

* Paragraph inserted after the second figure:
  >Typically, variable fonts will vary the design of glyph outlines. In general, however, potentially any aspect of the visual appearance may vary. For example, a font could vary line height metrics or appearance of gradients in color glyphs rather than (or in addition to) glyph outlines.

* Paragraph inserted after the following paragraph ("A variable font includes...")
  >Every axis allows for a continuous range of instance-selection values, and typically there will be continuous variation in appearance for a given axis. In some cases, however, appearance can vary in discrete steps as the axis setting is changed. For example, an axis could trigger substitution to different alternate glyphs for discrete sub-ranges of axis values.

* In the paragraph beginning, "As different variation instances of a font are selected...", revise the first two sentences that are currently worded assuming that outlines must vary:
> As different variation instances of a font are selected, various items of data within a font can be adjusted accordingly. For example, a 'glyf' table can provide the default outline of a given glyph, but the outline can be adjusted in some manner to reflect different design variations. ...

In the section, Variation Data Tables and Miscellaneous Requirements:

* Insert bulleted item at the end of the list after the first paragraph:
  > * Gradient placement and color stop offsets, color alpha values, and transformations for color glyphs in the COLR table.

* Added paragraph after "Two tables are required in all variable fonts" and the following bulleted list:
  > A variable font must contain some other variation-related data, according to the ways in which the design varies, but no other specific type of variation-related data is required in all variable fonts.

* Revise the following two paragraphs that currently indicate that outline variation (using gvar or CFF2) is required:
  > If a variable font has TrueType outlines in a 'glyf' table, the outline variation data can be provided in the glyph variations ('gvar') table. Variation data for CVT values can be provided in the optional CVT variations ('cvar') table.
  >
  > If a variable font has PostScript-style outlines in a Compact Font Format 2.0 (CFF2) table, the CFF2 table itself can also contain the associated variation data.

* Added paragraph before the final two paragraphs of that section:
  > In a color font using the COLR table, variation data can be included in the COLR table, as needed, for variable items in color glyph descriptions.

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
