### ISSUE TITLE
Are not both 'lfbd' and 'rtbd' features deprecated?

### ISSUE THREAD

**Issue by tnake** [MicrosoftDocs/typography-issues#853]
'opbd' was marked as DEPRECATED, whereas 'lfbd' and 'rtbd' features are not deprecated.
The descriptions of 'lfbd' and 'rtbd' say that 'this is applied to sequences automatically by applications when the 'opbd' feature is used, and direct user control is not required'.
So, I think that since 'opbd' feature was deprecated and 'lfbd' and 'rtbd' will not be called by 'opbd' feature, then 'lfbd' and 'rtbd' features should be deprecated.
Or, can 'lfbd' and/or 'rtbd' features apply discretionally with way that I'm not aware of things?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61a9106c-ca98-1891-2c00-ace78615994f
* Version Independent ID: 0feefbc8-23a7-5bc8-76dc-0a336a1c7968
* Content: [Registered features, k-o (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ko)
* Content Source: [typographydocs/opentype/spec/features_ko.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/features_ko.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Thanks for pointing out that 'lfbd' and 'rtbd' still mention being "called by the Optical Bounds ('opbd') feature". That should have been removed.

As for deprecating 'lfbd' and 'rtbd', that was discussed together with discussion of deprecation of 'opbd', and it was decided to deprecate only 'opbd'. See https://github.com/MicrosoftDocs/typography-issues/issues/578#issuecomment-694550390.

**Comment by tnake** [comment]
Thank you for reply to my comment.
And I apologize that I didn't read that discussion that why only was 'obpd' deprecated.
In addition, I could make sense that why 'lfbd' and  'rtbd' is marked as 'Discretionary feature'.

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
