### ISSUE TITLE
Typo(which is within 'Format 10: Trimmed array').

### ISSUE THREAD

**Issue by tnake** [MicrosoftDocs/typography-issues#854]
The description of 'Format 10: Trimmed array' starts with text that is 'Subtable format 8 was designed'.
I think that this format number is 10, not 8.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86923ff4-2b60-9144-e2b4-77cdb36fd698
* Version Independent ID: ea221e53-f51a-8233-3c0b-d416e5360623
* Content: [cmap - Character To Glyph Index Mapping Table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap)
* Content Source: [typographydocs/opentype/spec/cmap.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cmap.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
