### ISSUE TITLE
Add script tags for Unicode 14

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#855]
The following scripts have been added in Unicode 14, but don't yet have tags in the OpenType Layout script tag registry:

| Script | Unicode / ISO 15924 ID | proposed tag |
| - | - | - |
| Cypro-Minoan | Cpmn | 'cpmn' |
| Old Uyghur | Ougr | 'ougr' |
| Tangsa | Tnsa | 'tnsa' |
| Toto | Toto | 'toto' |
| Vithkuqi | Vith | 'vith' |

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49c1efc4-e864-0727-9663-7cec0ec4d9f1
* Version Independent ID: 36ec4396-b9cb-cba9-1582-d8400296d249
* Content: [Script tags (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/scripttags)
* Content Source: [typographydocs/opentype/spec/scripttags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/scripttags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
