### ISSUE TITLE
yeazure

### ISSUE THREAD

**Issue by CushKing** [MicrosoftDocs/typography-issues#856]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 42a267ba-0319-1eb6-107c-470db82a78f1
* Version Independent ID: 3dd42d43-7f3b-2219-87e6-6be6ef6d3fea
* Content: [Blackadder ITC font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/blackadder-itc#blackadder-itc)
* Content Source: [typographydocs/font-list/blackadder-itc.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/blackadder-itc.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
There's no actionable feedback here, so closing.
