### ISSUE TITLE
ConditionFormat1 fields have uppercased names

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#857]
This is what a ConditionFormat1 table looks like:

Type | Name | Description
-- | -- | --
uint16 | Format | Format, = 1
uint16 | AxisIndex | Index (zero-based) for the variation axis within the 'fvar' table.
F2DOT14 | FilterRangeMinValue | Minimum value of the font variation instances that satisfy this condition.
F2DOT14 | FilterRangeMaxValue | Maximum value of the font variation instances that satisfy this condition.

This is pretty much unique in terms of naming convention, where all other subtable fields have a lower camel case name. Departing from the norm draws attention to itself, so is it purposeful (in which case, what's the purpose?) or an oversight?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1cb42967-20ca-9270-4572-65315127fcc5
* Version Independent ID: 1fa413f1-71cf-ac2a-0999-70dd5d8ac4cd
* Content: [OpenType layout common table formats (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/chapter2)
* Content Source: [typographydocs/opentype/spec/chapter2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/chapter2.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Oversight. I've tried to bring consistency in naming in recent versions. It's a large spec, and this got missed.

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
