### ISSUE TITLE
Typo in description of `wordDeltaCount`

### ISSUE THREAD

**Issue by lemzwerg** [MicrosoftDocs/typography-issues#860]
`s/(wordDeltaCount && WORD_DELTA_COUNT_MASK)/(wordDeltaCount & WORD_DELTA_COUNT_MASK)/`

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: aedc12a3-7116-0160-7b97-e6657f14e89a
* Version Independent ID: aedc12a3-7116-0160-7b97-e6657f14e89a
* Content: [OpenType Font Variations Common Table Formats (OpenType 1.9) - Typography](https://docs.microsoft.com/de-de/typography/opentype/otspec190/otvarcommonformats)
* Content Source: [typographydocs/opentype/otspec190/otvarcommonformats.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec190/otvarcommonformats.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Fixed in beta.

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
