### ISSUE TITLE
Typo in describing Windows encoding IDs

### ISSUE THREAD

**Issue by lemzwerg** [MicrosoftDocs/typography-issues#862]
`s/Tranditional/Traditional/`

---
#### Dokumentdetails

⚠ *Bearbeiten Sie diesen Abschnitt nicht. Er ist für die Verknüpfung von docs.microsoft.com zum GitHub-Artikel erforderlich.*

* ID: 57e5ebcf-592a-887b-acac-2428c0879b1c
* Version Independent ID: 57e5ebcf-592a-887b-acac-2428c0879b1c
* Content: [name - Naming table (OpenType 1.9) - Typography](https://docs.microsoft.com/de-de/typography/opentype/otspec190/name)
* Content Source: [typographydocs/opentype/otspec190/name.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec190/name.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Thanks.

**Comment by PeterCon** [comment]
Fixed in beta.

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
