### ISSUE TITLE
Web rights to Georgia font

### ISSUE THREAD

**Issue by gfinlay01** [MicrosoftDocs/typography-issues#863]
We manage font licensing for the publisher Conde Nast. Recently when we select the licensing tab on the Microsoft Typography page we are sent to Fonts.com, Monotype's website. When did Monotype gain control of web licensing for this Microsoft font and does that control extend to all other Microsoft fonts as well?

Thank you.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c29cd56a-2ece-7acf-da8d-ba22131a6db6
* Version Independent ID: 48c52cb0-062f-7777-1fde-bde9369d1a85
* Content: [Georgia font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/georgia#licensing-and-redistribution-info)
* Content Source: [typographydocs/font-list/georgia.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/georgia.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
In general, Microsoft does not directly license fonts outside of the applications and operating systems that include them. Microsoft established an outbound licensing program for Microsoft font IP in partnership with Ascender Corp in ~2009, and then the license was transferred to Monotype when they acquired Ascender Corp. The programs extend to all Microsoft fonts with few exceptions.
