### ISSUE TITLE
What is 'jamo' for?

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#864]
What is the script tag 'jamo' for? How does it differ from 'hang'? The Hangul script development page only mentions 'hang', implying that 'jamo' is unused and that an itemizer should put jamo characters in 'hang' items.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49c1efc4-e864-0727-9663-7cec0ec4d9f1
* Version Independent ID: 36ec4396-b9cb-cba9-1582-d8400296d249
* Content: [Script tags (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/scripttags)
* Content Source: [typographydocs/opentype/spec/scripttags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/scripttags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by kenmcd** [comment]
Don't know if this is a specific answer, but it may be helpful.
I ran across "jamo" while trying to figure-out what certain OpenType features actually do.
I found the jamo OpenType features in fonts which support Korean: Source Han Sans K, MS Malgun Gothic, etc.
It appears these "jamo" forms are an older style of Korean script.

Some links I saved:

ljmo - Leading Jamo Forms
https://docs.microsoft.com/en-us/typography/opentype/spec/features_ko#tag-ljmo
tjmo - Trailing Jamo Forms
https://docs.microsoft.com/en-us/typography/opentype/spec/features_pt#tag-tjmo
vjmo - Vowel Jamo Forms
https://docs.microsoft.com/en-us/typography/opentype/spec/features_uz#tag-vjmo

Hangul Jamo (Unicode block)
https://en.wikipedia.org/wiki/Hangul_Jamo_(Unicode_block)
Which includes this: _"specifically syllables that are not used in standard modern Korean."_

Hangul consonant and vowel tables
https://en.wikipedia.org/wiki/Hangul_consonant_and_vowel_tables

List of Hangul jamo
https://en.wikipedia.org/wiki/List_of_Hangul_jamo

So, hope that points in the right direction.

**Comment by tiroj** [comment]
I think this was a mistake in the early years of OT: the distinct script tag was derived from the distinct Unicode block rather than reflecting the Unicode script property of the characters. JAMO should probably be deprecated, but it would be worth checking with Korean font makers and shaping engines to confirm that it isn’t actually used.

**Comment by PeterCon** [comment]
Indeed, fonts for Old Hangul that use conjoining jamo characters should be implemented using the 'hang' script tag, not 'jamo'.

**Comment by PeterCon** [comment]
Added remarks about 'jamo' in the [OT 1.9 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec190/ot190beta).

**Comment by dscorbett** [comment]
The remark “Fonts supporting conjoining jamo characters should use 'hang'” sounds like it means “Fonts should not use 'jamo'”. Is that what it means? If so, I think it should be worded more strongly. If not, it should explain under what circumstances a font should use 'jamo'.

**Comment by PeterCon** [comment]
Revised the beta content per David's comments.

**Comment by dscorbett** [comment]
> Fonts supporting Unicode conjoining jamo characters should use 'hang', not 'jamo'.

This explains when _not_ to use 'jamo' but it does not explain what 'jamo' actually _is_ for. Could it be for non-conjoining jamo characters, or for precomposed jamo sequences (syllable blocks)? I think the answer is that 'jamo' has no use for any purpose, but the documentation does not say that.

**Comment by PeterCon** [comment]
Updated again.

Btw, you're welcome to propose text.

**Comment by dscorbett** [comment]
I think the new text is clear.

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
