### ISSUE TITLE
Seedocs.microsoft.com

### ISSUE THREAD

**Issue by thiwatx33** [MicrosoftDocs/typography-issues#866]
This is an exampleyes    [Dwarfs: There and Back Again

A basic idle game made wih JS. Won JS13K 2022at 8th place and 2th place in mobile category. ￼

Installation

Install dependencies.

npm install 

Build a compact version in both build and electronapp folders.

./build.sh 

Generating an Electron app

￼ Enter to the electronapp folder.

cd electronapp 

Install dependencies.

npm install 

Contributors

Original Author: Msvalikov

Contributor: Yutyo {Skip to content lee-dohm / atom-style-tweaks Public Code Issues 35 Pull requests 27 Actions Projects Security Insights atom-style-tweaks/mix.exs @dependabot dependabot Bump credo from 1.4.0 to 1.5.6 … 4 contributors 166 lines (159 sloc) 4.26 KB defmodule AtomTweaks.Mixfile do use Mix.Project

def project do [ app: :atom_tweaks, version: "0.1.0", name: "Atom Tweaks", homepage_url: "https://www.atom-tweaks.com", source_url: "https://github.com/lee-dohm/atom-style-tweaks", elixir: "~> 1.9", elixirc_paths: elixirc_paths(Mix.env()), compilers: [:phoenix, :gettext] ++ Mix.compilers(), build_embedded: Mix.env() == :prod, start_permanent: Mix.env() == :prod, aliases: aliases(), deps: deps(), docs: docs(), test_coverage: [tool: ExCoveralls, test_task: "test"], preferred_cli_env: [ coveralls: :test, "coveralls.html": :test, "coveralls.travis": :test ] ] end

def application do [ mod: { AtomTweaks.Application, [] }, extra_applications: [:logger] ] end

Specifies which paths to compile per environment.

defp elixirc_paths(:test), do: ["lib", "test/support"] defp elixirc_paths(_), do: ["lib"]

defp deps do [ # Full dependencies {:cmark, "~> 0.8"}, {:ex_debug_toolbar, "~> 0.5"}, {:gettext, "~> 0.11"}, {:jason, "~> 1.1"}, {:navigation_history, "~> 0.2"}, {:oauth2, "~> 2.0.0"}, {:phoenix_ecto, "~> 3.0"}, {:phoenix_html, "~> 2.6"}, {:phoenix_octicons, "~> 0.6"}, {:phoenix_pubsub, "~> 1.0"}, {:phoenix_slime, "~> 0.13.0"}, {:phoenix, "~> 1.4.6"}, {:plug_cowboy, "~> 2.0"}, {:plug_ribbon, "~> 0.2"}, # Required for ex_debug_toolbar {:poison, "~> 3.0"}, {:postgrex, ">= 0.0.0"}, {:sentry, "~> 7.2.0"}, {:timex, "~> 3.1"},

# Dev dependencies {:credo, "~> 1.5.6", only: [:dev, :test], runtime: false}, {:dotenv, "~> 3.0.0", only: :dev}, {:ex_doc, "~> 0.16", only: [:dev, :test], runtime: false}, {:ex_machina, "~> 2.0", only: :test}, {:excoveralls, "~> 0.6", only: :test}, {:faker_elixir_octopus, "~> 1.0", only: :test}, {:floki, "~> 0.23.0", only: [:dev, :test]}, {:html_entities, "~> 0.4.0", only: [:dev, :test]}, {:phoenix_live_reload, "~> 1.0", only: :dev}, {:pseudoloc, "~> 0.2", only: [:dev, :test]}, {:uuid, "~> 1.1", only: [:dev, :test]} ] 

end

defp aliases do [ "ecto.setup": ["ecto.create", "ecto.migrate", "run priv/repo/seeds.exs"], "ecto.ci": ["ecto.create", "ecto.migrate"], "ecto.reset": ["ecto.drop", "ecto.setup"], translate: ["gettext.extract", "gettext.merge priv/gettext", "pseudoloc priv/gettext"] ] end

defp docs do [ main: "readme", extras: [ "CODE_OF_CONDUCT.md", "CONTRIBUTING.md", "README.md": [ filename: "readme", title: "README" ], "LICENSE.md": [ filenam basic Information about[<?xml version="1.0" encoding="UTF-8"?><rss version="2.0" xmlns:content="http://purl.org/rss/1.0/modules/content/"> <channel> <title>https://beta.groups.io/g/docs</title> <link>https://beta.groups.io/g
    [
wait

public final void wait(long timeout, int nanos) throws InterruptedException

Causes the current thread to wait until another thread invokes the notify() method or the notifyAll() method for this object, or some other thread interrupts the current thread, or a certain amount of real time has elapsed.

This method is similar to the wait method of one argument, but it allows finer control over the amount of time to wait for a notification before giving up. The amount of real time, measured in nanoseconds, is given by:

1000000*timeout+nanos

In all other respects, this method does the same thing as the method wait(long) of one argument. In particular, wait(0, 0) means the same thing as wait(0).

The current thread must own this object's monitor. The thread releases ownership of this monitor and waits until either of the following two conditions has occurred:

Another thread notifies threads waiting on this object's monitor to wake up either through a call to the notify method or the notifyAll method.

The timeout period, specified by timeout milliseconds plus nanos nanoseconds arguments, has elapsed.

The thread then waits until it can re-obtain ownership of the monitor and resumes execution.

As in the one argument version, interrupts and spurious wakeups are possible, and this method should always be used in a loop:

synchronized (obj) { while (<condition does not hold>) obj.wait(timeout, nanos); ... // Perform action appropriate to condition } This method should only be called by a thread that is the owner of this object's monitor. See the notify method for a description of the ways in which a thread can become the owner of a monitor.

Parameters:timeout - the maximum time to wait in milliseconds.nanos - additional time, in nanoseconds range 0-999999.Throws:IllegalArgumentException - if the value of timeout is negative or the value of nanos is not in the range 0-999999.IllegalMonitorStateException - if the current thread is not the owner of this object's monitor.InterruptedException - if any thread interrupted the current thread before or while the current thread was waiting for a notification. The interrupted status of the current thread is cleared when this exception is thrown.

wait

public final void wait() throws InterruptedException

Causes the current thread to wait until another thread invokes the notify() method or the notifyAll() method for this object. In other words, this method behaves exactly as if it simply performs the call wait(0).

The current thread must own this object's monitor. The thread releases ownership of this monitor and waits until another thread notifies threads waiting on this object's monitor to wake up either through a call to the notify method or the notifyAll method. The thread then waits until it can re-obtain ownership of the monitor and resumes execution.

As in the one argument version, interrupts and spurious wakeups are possible, and this method should always be used in a loop:

synchronized (obj) { while (<condition does not hold>) obj.wait(); ... // Perform action appropriate to condition } This method should only be called by a thread that is the owner of this object's monitor. See the notify method for a description of the ways in which a thread can become the owner of a monitor.

Throws:IllegalMonitorStateException - if the current thread is not the owner of the object's monitor.InterruptedException - if any thread interrupted the current thread before or while the current thread was waiting for a notification. The interrupted status of the current thread is cleared when this exception is thrown.See Also:notify(), notifyAll()

finalize

protected void finalize() throws Throwable

Called by the garbage collector on an object when garbage collection determines that there are no more references to the object. A subclass overrides the finalize method to dispose of system resources or to perform other cleanup.

The general contract of finalize is that it is invoked if and when the JavaTM virtual machine has determined that there is no longer any means by which this object can be accessed by any thread that has not yet died, except as a result of an action taken by the finalization of some other object or class which is ready to be finalized. The finalize method may take any action, including making this object available again to other threads; the usual purpose of finalize, however, is to perform cleanup actions before the object is irrevocably discarded. For example, the finalize method for an object that represents an input/output connection might perform explicit I/O transactions to break the connection before the object is permanently discarded.

The finalize method of class Object performs no special action; it simply returns normally. Subclasses of Object may override this definition.

The Java programming language does not guarantee which thread will invoke the finalize method for any given object. It is guaranteed, however, that the thread that invokes finalize will not be holding any user-visible synchronization locks when finalize is invoked. If an uncaught exception is thrown by the finalize method, the exception is ignored and finalization of that object terminates.

After the finalize method has been invoked for an object, no further action is taken until the Java virtual machine has again determined that there is no longer any means by which this object can be accessed by any thread that has not yet died, including possible actions by other objects or classes which are ready to be finalized, at which point the object may be discarded.

The finalize method is never invoked more than once by a Java virtual machine for any given object.

Any exception thrown by the finalize method causes the finalization of this object to be halted, but is otherwise ignored.

Throws:Throwable - the Exception raised by this method

**Comment by PeterCon** [comment]
Not related to this repo: closing.
