### ISSUE TITLE
Sylfaen font - IPA phonetic characters

### ISSUE THREAD

**Issue by smhewitt** [MicrosoftDocs/typography-issues#869]
[Enter feedback here]
Why was Sylfaen font never completed with, for instance, IPA Phonetic symbols, as originally planned? 
This would be wonderful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fa224fe9-0171-7dc6-c828-5455c3a70ea9
* Version Independent ID: 3e141e15-d316-effd-e62c-cee223d18fea
* Content: [Sylfaen - Typography](https://docs.microsoft.com/en-us/typography/font-list/sylfaen)
* Content Source: [typographydocs/font-list/sylfaen.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/sylfaen.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
[Dupilicate of #870]
