### ISSUE TITLE
The EULA of MS YaHei Fonts

### ISSUE THREAD

**Issue by latrikcoasler** [MicrosoftDocs/typography-issues#87]
近日我方收到北大方正律师函提示我的公司广告、网站和网页上使用了由其设计的“微软雅黑”字体，北大方正认为我们的商业使用“微软雅黑”未经其授权，故要求我们付费。对此，作为最终使用者的我们想知道，微软系统自带或我们在微软官方网站下载的“微软雅黑”字体的是否可以“嵌入”到我的广告、方案和设计中，并使用在网页上。

---
#### 文档详细信息

⚠ *请勿编辑此部分。 docs.microsoft.com ➟ GitHub 问题链接必须具有此部分。*

* ID: 887c10e0-63c5-06d9-38fc-3c844c0d308d
* Version Independent ID: fbc7a8c5-a8bd-611d-0758-1b56e5d5a03a
* Content: [Microsoft YaHei font family - Typography](https://docs.microsoft.com/zh-cn/typography/font-list/microsoft-yahei#feedback)
* Content Source: [typographydocs/font-list/microsoft-yahei.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/microsoft-yahei.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment]
We have an FAQ that should answer your questions.

https://docs.microsoft.com/en-us/typography/fonts/font-faq
