### ISSUE TITLE
meta table : slng contents?

### ISSUE THREAD

**Issue by tiroj** [MicrosoftDocs/typography-issues#877]
Should `slng` entries include ScriptLangTags that are in the `dlng` entries? or only ScriptLangTags that are supported but not those for which the font is primarily designed? i.e. is `slng` intended to be a superset of designed for and supported scripts/languages?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8f6ed4e-64e4-2176-f903-c2778419d391
* Version Independent ID: bb311713-0340-4c84-180d-b0016a18fefe
* Content: [meta — Meta table (OpenType 1.8.4) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/meta)
* Content Source: [typographydocs/opentype/spec/meta.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/meta.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
[Original issue edited to fix markdown. Maybe this makes more sense now?]

**Comment by PeterCon** [comment]
Intent was that `slng` should provide a superset of `dlng`. That's worth clarifying.

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
