### ISSUE TITLE
Segoe UI Emoji font doc page should reflect the new Win11 design

### ISSUE THREAD

**Issue by andrew-z** [MicrosoftDocs/typography-issues#878]
The documentation page shows the screenshot that features old (Win10) design of Segoe UI emoji font. In Win11, the new font was serviced using 11C servicing (servicing date: 11/22) - the page should reflect that. 

https://blogs.windows.com/windowsexperience/2021/11/22/express-yourself-with-new-emoji-now-available-in-windows-11/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a897815e-652e-d4ae-8f3d-979ee1ec0fcb
* Version Independent ID: 575e9a80-3e10-d850-eea7-d3c921779f82
* Content: [Segoe UI Emoji font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/segoe-ui-emoji)
* Content Source: [typographydocs/font-list/Segoe-UI-Emoji.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/Segoe-UI-Emoji.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Thanks, I have updated the page with new image.
