### ISSUE TITLE
About the right of embeding the MS YaHei fonts into docs.

### ISSUE THREAD

**Issue by latrikcoasler** [MicrosoftDocs/typography-issues#88]
what's the meaning of "embed fonts in content as permitted by the embedding restrictions in the fonts; and when printing content, temporarily download them to a printer or other output device." displayed in the license of MS YaHei fonts.

Is that right including commercial use of embedding fonts in contents. Cause we what to use this fonts to design our company's logo, website and kinds of advertisement.

**Comment by v-nihar** [comment]
We have an FAQ that should answer your questions.

https://docs.microsoft.com/en-us/typography/fonts/font-faq
