### ISSUE TITLE
More Burmese minority language tag requests

### ISSUE THREAD

**Issue by simoncozens** [MicrosoftDocs/typography-issues#880]
* The Tai Laing language has typographic variants of certain letters, such as MYANMAR LETTER SHAN A, and different expected shaping behaviour for tone marks. (See [UTN-11](https://www.unicode.org/notes/tn11/UTN11_4.pdf) p51ff) A language tag is needed to activate this behaviour. The ISO language tag is `tle`.
* Old Burmese requires additional ligature forms, as detailed in [UTN-11](https://www.unicode.org/notes/tn11/UTN11_4.pdf) p27. The ISO language tag is `obr`.
* Geba Karen (ISO tag `kvq`) has Karenic shaping requirements (triangular medial wa, dots on the left, etc.).

**Comment by dscorbett** [comment]
“kvq” is listed as corresponding to the language system tag 'KRN ' (Karen). Does it have specific shaping requirements that warrant a new tag?

**Comment by PeterCon** [comment]
@simoncozens 

I'm not sure where you got `tle` as the ISO language tag. That is a deprecated ID that had been used to denote a language of Kenya "Markwet" (since merged into another entry). The ID for Tai Laing is `tjl`.

Can you comment on dscorbett's question wrt `kvq` and 'KRN '?

**Comment by simoncozens** [comment]
I got “tle” from p51 of UTN11 - we actually use TJL in the font, but after rereading UTN1. I thought we’d got it wrong. Apparently we haven’t!

@ohbendy, do we actually need to do anything special for Geba?

**Comment by ohbendy** [comment]
Keep the critical thinking hat on when dealing with UTN11. I try to corroborate every detail from several sources. Page 27 is not clear what it means by 'unique ligatures'. Does it mean they occur only in Old Burmese? Or the shape is somehow special? Neither of those is correct, the two conjuncts with ṣa and repha are Sanskrit and there's nothing special about a subjoined ṭa. So I don't know what it's getting at.

At any rate, Old Burmese doesn't require any special shaping. 

The scant sources I have for Geba show the triangular medialWa, but no indication of where the dotbelow sits if there's another belowmark. Until/unless we find evidence to the contrary, I'd keep it consistent with S'gaw.

And yes TJL for Tai Laing. The preferred endonym is ShanNi.

**Comment by PeterCon** [comment]
For now, then, it sounds like only 'TJL ' should be added in the language system tag registry.

**Comment by PeterCon** [comment]
Addressed in [OpenType 1.9](https://docs.microsoft.com/en-us/typography/opentype/spec/). Closing.
