### ISSUE TITLE
Clarify the behavior when applying deltas from an IVS IVD with `LONG_WORDS` bit CLEARED to a Fixed (16.16) value

### ISSUE THREAD

**Issue by reli-msft** [MicrosoftDocs/typography-issues#882]
When applying deltas from an ItemVariationData subtable in an ItemVariationStore with `LONG_WORDS` bit being cleared to a Fixed (16.16) value, what should happen? Should this delta apply to the _integral part_, or the delta is directly applied to the underlying integral representation (`int32`) of this Fixed?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc38f55-a142-6d66-fc68-1bb6e6e9ed56
* Version Independent ID: 0665d6f2-4150-1977-4fd6-91c50c226ed9
* Content: [OpenType Font Variations Common Table Formats - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otvarcommonformats)
* Content Source: [typographydocs/opentype/spec/otvarcommonformats.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otvarcommonformats.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
The spec currently states,

>When scaled deltas are applied to Fixed values, the Fixed value is treated like a 32-bit integer. (In this sense, the delta and the Fixed value can be viewed as integer values in units of 1/65536ths.)

Does that not provide the answer to your question?

**Comment by PeterCon** [comment]
Without further feedback, I assume the current wording as noted above is sufficiently clear. Closing.
