### ISSUE TITLE
INSTCTRL *can* be used in the `glyf` table, too

### ISSUE THREAD

**Issue by lemzwerg** [MicrosoftDocs/typography-issues#883]
The documentation says
```
INSTCTRL[ ] can only be executed in the CVT program.
```
However, this is not correct; the [ClearType description of `INSTCTRL`](https://docs.microsoft.com/en-us/typography/cleartype/truetypecleartype#instctrl) says something else.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9eb69554-e257-e483-2e26-7f04fdf44fd8
* Version Independent ID: d560a11c-2ac5-1abc-7165-453c3a9618c8
* Content: [TrueType Instruction Set (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/tt_instructions)
* Content Source: [typographydocs/opentype/spec/tt_instructions.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/tt_instructions.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
That old article isn't completely accurate, but it is on this point. Will draft a revision.

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by lemzwerg** [comment]
Thanks.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
