### ISSUE TITLE
Tw Cen MT - File Names and Styles incorrect

### ISSUE THREAD

**Issue by kenmcd** [MicrosoftDocs/typography-issues#884]
@alib-ms 

Currently it appears there are 7 fonts available from this family (in cloud fonts).

**File name** list shows 10 files - 3 of which are duplicates.
Tcm_____.ttf  - Regular 
Tcb_____.ttf   - Bold
Tcbi____.ttf   - Bold Italic
Tcmi____.ttf  - Italic
Tcm_____.ttf  - Regular (duplicate)
Tcmi____.ttf   - Italic (duplicate)
Tccm____.ttf  - Condensed Regular
Tccb____.ttf   - Condensed Bold
Tcceb.ttf       -  Condensed Extra Bold 
Tccm____.ttf  - Condensed Regular (duplicate)

Remove the three duplicates and the file names are correct.

**Styles & Weights** list shows 6 styles - 2 of which are not available
Tw Cen MT
Tw Cen MT Bold
Tw Cen MT Bold Italic
Tw Cen MT Italic
Tw Cen MT Medium           - (not available in cloud fonts)
Tw Cen MT Medium Italic  - (not available in cloud fonts)

And the following 3 styles are not listed (but are correctly in the file list)
Tw Cen MT Condensed
Tw Cen MT Condensed Bold
Tw Cen MT Condensed Extra Bold

Add these 3 styles (and remove the 2 Mediums) to make the Styles list correct.

The **Style & Weight examples** show 3 different Medium fonts.
Tw Cen MT Medium
Tw Cen MT Medium Italic
Tw Cen MT Condensed Medium

Which application supplied these Medium fonts?
I did not find them in Office 2003 thru 2021.
So how did they end up in this list?
Thanks!

Note: The Cloud Fonts list appears to show the correct 7 fonts (name and file name).
Or should the 3 Medium styles be added to make 10?

UPDATE: I found the three Medium fonts in Publisher 98.

ANOTHER UPDATE: OK, I finally figured-out what happened.
The Medium fonts got renamed - taking the "Medium" out of the name.
They are now the Regular fonts.

So to prevent confusion for the currently available cloud fonts, 
the above changes should be made.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 75a5230f-2c4d-c16e-3ea6-cef7afe2f743
* Version Independent ID: 8110c516-3426-e595-9495-04ae3debe2cd
* Content: [Tw Cen MT font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/tw-cen-mt)
* Content Source: [typographydocs/font-list/tw-cen-mt.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/tw-cen-mt.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Thank you for letting me know. Office currently only ships 
Tw Cen MT	Tcm_____.ttf
Tw Cen MT Bold	Tcb_____.ttf
Tw Cen MT Bold Italic	Tcbi____.ttf
Tw Cen MT Italic	Tcmi____.ttf
Tw Cen MT Condensed	Tccm____.ttf
Tw Cen MT Condensed Bold	Tccb____.ttf
Tw Cen MT Condensed Extra Bold	Tcceb.ttf

I will make the corrections.

**Comment by kenmcd** [comment]
OK. Great.
That also matches what is installed with Office 2019.
Thanks.

**Comment by alib-ms** [comment]
Hi @kenmcd, I have updated the [Tw Cen MT font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/tw-cen-mt) page.

**Comment by kenmcd** [comment]
Looks good now!
Closing.
