### ISSUE TITLE
'prep' and compound glyphs

### ISSUE THREAD

**Issue by lemzwerg** [MicrosoftDocs/typography-issues#886]
The documentation of 'prep' starts as follows

> The Control Value Program consists of a set of TrueType instructions that will be executed
> whenever the font or point size or transformation matrix change and before each glyph is
> interpreted.

The wording 'each glyph' is unfortunate, I think, and should be reformulated.  In particular, the sentence could be interpreted as if 'prep' must be executed again and again before running a glyph program, which is not the case.

Besides that, it should be mentioned that 'prep' doesn't get re-executed if a component of a composite glyph gets scaled – AFAIK, the top-level parent's CVS values are used for all compound elements.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9a2eefb9-8105-5af1-1a85-8837e4ecc6b5
* Version Independent ID: b47a191a-32d4-476f-6a8f-c98221f24fde
* Content: [prep - Control value program table (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/prep)
* Content Source: [typographydocs/opentype/spec/prep.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/prep.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by lemzwerg** [comment]
Thanks.  It seems there are a few typos on https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/delta/prep_delta.html

* can used → can be used
* Maybe: font wide → font-wide (but I'm not a native speaker)
* Something appears wrong to me with the sentence starting with "The CV Program is not re-executed ..." – at least I don't understand it :-) – but I can't say what it is.

**Comment by PeterCon** [comment]
Thanks for catching that. Fixed.

**Comment by PeterCon** [comment]
Further small revision based on input from GregH.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
