### ISSUE TITLE
Broken link for BCP47

### ISSUE THREAD

**Issue by tiroj** [MicrosoftDocs/typography-issues#889]
The meta table spec includes an external link to BCP47 at 

http://tools.ietf.org/html/bcp47

but that returns an ‘Object not found!’ error.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8f6ed4e-64e4-2176-f903-c2778419d391
* Version Independent ID: bb311713-0340-4c84-180d-b0016a18fefe
* Content: [meta — Meta table (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/meta)
* Content Source: [typographydocs/opentype/spec/meta.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/meta.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by kenmcd** [comment]
For me that link redirects to: https://www.rfc-editor.org/info/bcp47

**Comment by tiroj** [comment]
Hmm. Interesting: if I click the link as a pasted it into the issue, then it redirects as @kenmcd says. If I clicked the link in the [ScriptLangTag Values](https://docs.microsoft.com/en-us/typography/opentype/spec/meta#scriptlangtag-values) section of the meta table specification page, it did not redirect this morning but does now. Perhaps the issue is on the IETF server end.

**Comment by vlevantovsky** [comment]
The redirect doesn't work for me either. I think the issue here may be due to the redirect going from the unsecured http://tools.ietf.org/html/bcp47 to secure page https://www.rfc-editor.org/info/bcp47. Anyway, I think it's time to update that link in both OT and OFF.

**Comment by PeterConstable** [comment]
I think the /info/ link would be best to use.

**Comment by PeterCon** [comment]
Since BCP 47 is an important reference for understanding the design, I've handled this as an erratum and have corrected the URL in OT 1.9.

The use of http rather than https appears to have been the root case, but the /info/ URL is preferred (recommended in IETF's guidance for RFC editors).
