### ISSUE TITLE
Add langsys tag for Nunavik Inuktitut

### ISSUE THREAD

**Issue by tiroj** [MicrosoftDocs/typography-issues#893]
Inuktitut as written in Nunavik (northern Quebec) shows a fairly consistent preference for the form of syllable-final NG (U+1595). In this illustration, the left form is the Nunavut/NYT form (also the form shown in the Unicode chart), and the form on the right is the Nunavik form.

![image](https://user-images.githubusercontent.com/5614500/149596294-9211f376-d2ba-4fca-aba4-6fa6a30a1004.png)

In order to provide locale-particular access to the latter via the OTL locl feature, we request addition to the registry of a Nunavik-specific langsys tag. [We do not feel it is necessary to add two tags to distinguish Nunavut/NYT from Nunavik, but instead suggest that the existing INU tag can be interpreted as the former.

Suggested tag (but open to other ideas):

**Inuktitut, Nunavik  INUQ**  

I am unsure what to suggest for the ISO 639 identity: ‘ike’ is identified as Eastern Canadian Inuktitut, but I think that is a general term that covers all Canadian forms of Inuktitut as distinct from related languages of Alaska and Siberia.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662c6f54-f90c-52ed-dca2-0f0a0a49fee5
* Version Independent ID: 6aa33924-d45e-60c3-a9fd-e317ff662993
* Content: [Language system tags (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/languagetags)
* Content Source: [typographydocs/opentype/spec/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
Kevin King, via email, suggests INUK as tag, to avoid possible association of INUQ with Western Inuktitut ‘Inunniaqtun’ language (which uses Latin script orthography).

**Comment by PeterCon** [comment]
Is there documentation anywhere reasonably stable that could be referenced?

**Comment by PeterCon** [comment]
>I am unsure what to suggest for the ISO 639 identity: ‘ike’ is identified as Eastern Canadian Inuktitut, but I think that is a general term that covers all Canadian forms of Inuktitut as distinct from related languages of Alaska and Siberia.

In ISO 639, 'iku' is a "macrolanguage" entity that encompasses 'ike' ("Easter Canadian Inuktitut") and 'ikt' ("Innuinaqtun"). The description in Ethnologue for 'ike' describes the geographic range as Nunavut, Northern Quebec, Labrador and Newfoundland. The description for 'ikt' gives a range from the NW coast of Hudson Bay westward into NW Territories.

So, IIUC, the corresponding ISO 639 IDs listed should include 'iku' and 'ike', or perhaps only 'ike'.

Eastern Canadian Inuktitut
--


and 'ikt'.

**Comment by PeterCon** [comment]
The proposed tag 'INUK' seems reasonable and doesn't conflict with any existing tags.

**Comment by tiroj** [comment]
I will try to find references. I spotted the variant form in the Euphemia UCAS glyph set, so asked Ross Mills to identify it. Independently, Kevin King confirmed what Ross said, that the form was used in Nunavik, and noted that it was pretty standard in publications he had seen from that region.

**Comment by PeterConstable** [comment]
A further thought on the tag: 'IKE ' is not currently used for anything. If we think that target for usage corresponds to ISO 639 'ike', is there any reason no to use 'IKE ' as the tag?

**Comment by tiroj** [comment]
ISO 639 ‘ike’ refers to all of Canadian Eastern Inuktitut, which is all the variants of Inuktitut that use syllabics (as distinct from western 'ikt' ("Innuinaqtun") which is written in Latin script). So IKE doesn’t work to distinguish specifically Nunavik.

**Comment by PeterConstable** [comment]
So, not encompassing usage in Newfoundland/Labrador or Nunavut. OK.

But then if it's narrower than 'ike', it's that all the more narrow relative to 'iku'. The description "Nunavik Inuktitut" seems fine, but rather than a qualification of 'INU ' ("Inuktitut") (i.e., appending "K"), it makes me wonder if a tag that is adding qualification to 'ike' might be better; e.g., 'IKEN'? 

(Of course, that could raise the question whether 'IKE ' should also be listed.)

**Comment by tiroj** [comment]
> (Of course, that could raise the question whether 'IKE ' should also be listed.)

Well, from an OTL perspective, the distinction between Eastern Canadian Inuktitut and Innuinaqtun is made at the script level, so doesn’t need to be made at the langsys level. This is another situation where ISO language tags do not map cleanly on to the OpenType Layout model. So the existing OTL INU langsys tag can be applied to either or both the cans and latn script tags, and what we need to capture the _writing system_ distinction for Nunavik is a variant of that.

**Comment by PeterCon** [comment]
INUK has been added to the registry.
