### ISSUE TITLE
Minor typo on TTF cmap page

### ISSUE THREAD

**Issue by nico** [MicrosoftDocs/typography-issues#898]
https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#unicode-platform-platform-id--0 says "In particular, binary search is optimal when the number of entries as a power of two." It should say "In particular, binary search is optimal when the number of entries is a power of two." (i.e. s/ as / is /).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86923ff4-2b60-9144-e2b4-77cdb36fd698
* Version Independent ID: ea221e53-f51a-8233-3c0b-d416e5360623
* Content: [cmap - Character To Glyph Index Mapping Table (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap)
* Content Source: [typographydocs/opentype/spec/cmap.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cmap.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Fixed (silent update). Thanks for reporting.
