### ISSUE TITLE
cmap entrySelector formula is wrong

### ISSUE THREAD

**Issue by nico** [MicrosoftDocs/typography-issues#899]
https://docs.microsoft.com/en-us/typography/opentype/spec/cmap#unicode-platform-platform-id--0 says:

"""Log2 of the maximum power of 2 less than or equal to numTables (log2(searchRange/2), which is equal to floor(log2(numTables)))"""

That's incorrect. `numTables` is from a completely different section. It should say "…, which is equal to floor(log2(segCount))".

(Just plug the formula for `searchRange` into `(log2(searchRange/2)` to verify.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 86923ff4-2b60-9144-e2b4-77cdb36fd698
* Version Independent ID: ea221e53-f51a-8233-3c0b-d416e5360623
* Content: [cmap - Character To Glyph Index Mapping Table (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/cmap)
* Content Source: [typographydocs/opentype/spec/cmap.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/cmap.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterConstable** [comment]
This typo was introduced as a copy/paste error while making the description of these fields consistent with the description for the similar fields in the font [Table Directory](https://docs.microsoft.com/en-us/typography/opentype/spec/otff#table-directory). It is, of course, a technical error, and an erratum will be posted to correct this.

Thanks for reporting it.

**Comment by PeterCon** [comment]
Erratum published with fix in OT 1.9. Because of the serious nature of the error, I also backported the fix to OT 1.8.4.

**Comment by PeterCon** [comment]
#1000 is a duplicate of this issue. (Erratum fix in 1.9 somehow wasn't picked up for 1.9.1 alpha.)
