### ISSUE TITLE
Vertically centered cells make tables confusing

### ISSUE THREAD

**Issue by Lorp** [MicrosoftDocs/typography-issues#901]
Like several other tables in the spec, the table on this page is difficult to read because of vertical centering of cells. See the attached image, where a blank line in the the **fontDirectionHint** description means the first part of it appears to be part of the **lowestRecPPEM** definition. Can the style sheet be adjusted so that cells are by default top-aligned? Also, grey cell borders would be useful.

![Screenshot 2022-01-26 at 16 10 44](https://user-images.githubusercontent.com/587440/151202155-1670df2f-281b-4532-8d1e-8e4361677a78.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3ee780c-6509-ae67-2223-7c0468dc745c
* Version Independent ID: 907dff3d-e18f-e9c9-3ff6-7cf7f05aa7be
* Content: [head - Font header table (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/head#feedback)
* Content Source: [typographydocs/opentype/spec/head.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/head.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
How are you viewing it? 

The formatting is controlled by the styling for docs.microsoft.com overall, but the table cells already are top aligned with rows separated by a gray border. Here's a snippet for how the table appears in Safari:

![image](https://user-images.githubusercontent.com/12788502/151214950-ede2b0bb-fee2-4abd-a7c9-9cbc5195d35d.png)

**Comment by Lorp** [comment]
Indeed it’s fine when I try Firefox and Chrome. It seems Safari 14.1.2 on macOS 10.14.6 does not receive the correct CSS. The computed CSS properties in the inspector lack the desired solid border and top alignment. The screen grabs show Safari’s properties, then Chrome.

<img width="266" alt="CSS computed properties Safari 14 1 2" src="https://user-images.githubusercontent.com/587440/151217736-3890c9a6-092e-440a-888d-429542c85130.png">

![CSS computed properties Chrome 97 0 4692 71](https://user-images.githubusercontent.com/587440/151217672-57ca80c9-2d99-4e12-a850-9728adc3562e.png)

**Comment by PeterCon** [comment]
This isn't something I have any direct control over, but I'm trying to find someone for the docs.microsoft.com sites who can look at this.

**Comment by PeterCon** [comment]
It didn't repro for me in Safari 15.2, and doesn't repro now in Safari 15.6.1. I wasn't able to find someone who could investigate, but am not inclined to spend time when it doesn't repro on newer versions of Safari or in other browsers. Closing.
