### ISSUE TITLE
Minor issues around WE_HAVE_INSTRUCTIONS

### ISSUE THREAD

**Issue by nico** [MicrosoftDocs/typography-issues#904]
Three issues:

1. ~~`if (flags & WE_HAVE_INSTR){` is outside the `MORE_COMPONENTS` do/while loop. It should be inside it (after the scale reading) (…I think?).~~ (See comment below)

2. The "Component Glyph Flags" table calls the flag `WE_HAVE_INSTRUCTIONS`. The pseudocode should match that and use `WE_HAVE_INSTRUCTIONS` instead of `WE_HAVE_INSTR`.

3. The text after the "Component Glyph Flags" lacks a description of the `WE_HAVE_INSTRUCTIONS` bit (all other bits are described).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2a9a6a1-a9b9-0864-8982-322da821389e
* Version Independent ID: a42612e3-dc1d-f980-fe4a-4880d1fd0086
* Content: [glyf - Glyf data table (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/glyf)
* Content Source: [typographydocs/opentype/spec/glyf.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/glyf.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by nico** [comment]
Actually, I think point 1 is incorrect. The table says "Bit 8: Following the last component are instructions for the composite character.".

It could be clearer which component this bit needs to be set on. Do they follow if they're set for any component? Is this bit only looked at for the last component?

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.
