### ISSUE TITLE
What is 'math' for?

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#906]
'math' is defined as “Mathematical Alphanumeric Symbols”. However, [the MATH table documentation](https://docs.microsoft.com/en-us/typography/opentype/spec/math) says it is “used for features in math layout”, implying that it is not just for alphanumeric symbols. What is the true scope of 'math'? Does it have any use outside of MATH?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49c1efc4-e864-0727-9663-7cec0ec4d9f1
* Version Independent ID: 36ec4396-b9cb-cba9-1582-d8400296d249
* Content: [Script tags (OpenType 1.9 delta) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/scripttags)
* Content Source: [typographydocs/opentype/spec/scripttags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/scripttags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
The ‘math’ script tag is used by the math layout handler, and I believe the way that works is a bit different than the usual OTL script path mechanism. While the usual process is to itemise character scope across a run of text by script property, the ‘math’ script is applied to everything within a math zone (i.e. something indentified as an equation at a higher level, not derived from script properties). A lot of what the registered features used by the math layout handler apply affects Unicode Mathematical Alphanumeric Symbols, but also Latin and Greek characters, combining marks, and other symbols.

The math script tag can be interpreted as a kind of escape mechanism, by which character occuring in a math zone get different handling than they would in a normal text zone.

I think identification of the ‘math’ script tag with Unicode Mathematical Alphanumeric Symbols is a misapplication of the script tag -> script property paradigm, and probably needs some kind of annotation to clarify actual scope and use.

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
