### ISSUE TITLE
'head': are bearing values in 'hmtx' (and 'vmtx'?) ignored if bit 1 of `flags` is set?

### ISSUE THREAD

**Issue by lemzwerg** [MicrosoftDocs/typography-issues#907]
While working on [a FreeType issue](https://gitlab.freedesktop.org/freetype/freetype/-/issues/998) I noticed that [Ben's testfonts](https://github.com/MicrosoftDocs/typography-issues/files/5209365/color-font.zip) `colorheads.ttf` and `colorheads-lsb.ttf` contain identical lsb values.  However, only font `colorheads-lsb.ttf` sets bit 1 in the 'head' table.  Looking at the CoreText rendering results (the first image in the mentioned FreeType issue) it seems that `colorheads.ttf` ignores lsb values completely.

This makes me wonder whether this is official behaviour: What exactly happens if bit 1 is set but the 'hmtx' table contain non-zero lsb values?  Is it then necessary to ignore lsb values even if they are present?

Ditto for 'vmtx' (which is probably not affected by bit 1 because the specification only talks about the 'left sidebearing point').

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f3ee780c-6509-ae67-2223-7c0468dc745c
* Version Independent ID: 907dff3d-e18f-e9c9-3ff6-7cf7f05aa7be
* Content: [head - Font header table (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/head)
* Content Source: [typographydocs/opentype/spec/head.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/head.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
@lemzwerg Do the details about positioning in the ['sbix'](https://docs.microsoft.com/en-us/typography/opentype/spec/sbix#glyph-data) chapter provide clarification on this? (LSB has no effect if there is no glyph outline.)

**Comment by lemzwerg** [comment]
No, it doesn't.  This is a different issue.  I understand how 'sbix' works, however, the 'head' table is generic, which means that the information in this table is to be applied to all available tables, not only 'sbix'.

What I want is a clarification for bit one of the 'flags' field in the 'head' table, for example, "If the font provides LSB values, they are ignored."  Or maybe a recommendation: "Since LSB values are ignored if this flag is set, it is recommended to not provide any LSB data in the 'htmx' table."

BTW, I would still like to know whether this flag has (by extension) any relation to the 'vmtx' table.

**Comment by PeterCon** [comment]
@lemzwerg Why would LSB data be ignored or not provided?

>Bit 1: Left sidebearing point at x=0 (relevant only for TrueType rasterizers) — see the note below regarding variable fonts.

The left sidebearing point — aka phantom point 1 — is the point of reference from which left sidebearing distance is measured. The hmtx chapter provides this relationship between pp1, lsb and xMin:

> pp1 = xMin - lsb

You need at least two. If head.flags bit 1 is set, then pp1 is provide (= 0), and so it's true that xMin and lsb are redundant. 

But there's no way "to not provide _any_ LSB data in the 'htmx' table" as there must be maxp.numGlyphs lsb values provided in 'hmtx'. Moreover, the spec states,

>In a variable font with TrueType outlines, the left side bearing for each glyph must equal xMin, and bit 1 in the flags field of the 'head' table must be set.

So, it's not clear to me what clarification is needed?

**Comment by lemzwerg** [comment]
> @lemzwerg Why would LSB data be ignored or not provided?

My main concern are invalid fonts, or rather, fonts that are at fringe of being invalid.

> But there's no way "to not provide _any_ LSB data in the 'htmx' table" as there must be maxp.numGlyphs lsb values provided in 'hmtx'.

My bad, I mean 'non-zero LSB values'.

> So, it's not clear to me what clarification is needed?

As mentioned above: you have a font, bit 1 is set, and you have non-zero LSB values: what happens with these values?  I simply suggest to mention that they are ignored.  Maybe you feel this is redundant information, but IMHO it's better to be a little more explicit than not – it doesn't really hurt to add those few words, and it also helps avoid to rely on any implicit conclusions.

**Comment by PeterCon** [comment]
I think you're confusing per-glyph lsb values with the placement of the _left sidebearing point_. In this equation,

>pp1 = xMin - lsb

the intent of bit 1 pertains to pp1, not to lsb.

So, it would be not at all surprising to have a font with bit 1 set and to have many (most?) glyphs with non-zero lsb values. When bit 1 is set, the only constrain on lsb values is that, for each glyph, lsb should be equal to xMin.

**Comment by PeterCon** [comment]
Btw, GregH mentioned to me that MS's rasterizer never checked bit 1. In that case, both lsb from hmtx and xMin from glyf are needed for each glyph to determine the placement of the left sidebearing phantom point.

**Comment by lemzwerg** [comment]
Doh...  Thanks for the correction.

Well, if even I as the FreeType maintainer get confused, I think all those points you've mentioned should be somehow incorporated.  Greg's note is the icing on top of the cake, of course :-)

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

I made edits in the head and tt_instructing_glyphs pages.

**Comment by lemzwerg** [comment]
Thanks!

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
