### ISSUE TITLE
Suggession to improve font

### ISSUE THREAD

**Issue by 9425848586** [MicrosoftDocs/typography-issues#909]
When we type Mangal font and want to write द्वारा in Mangal font it does not come like द्वारा when we write in Microsoft word it produces द् वारा without space. Therefore it may be ensured that when द्वारा is written in the microsoft word, whe it get typed. Similarly द्य when it is typed in the word it comes as द् य that is also required to be amended. 
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c629c9b-d28b-aa25-5344-376a3dd28b2e
* Version Independent ID: 991734e0-5210-6a12-f671-1c0b07d11e58
* Content: [Mangal font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/mangal)
* Content Source: [typographydocs/font-list/mangal.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/mangal.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Hi,

Mangal was edited to disable the traditional ligatures for these conjuncts to horizontal, decomposed rendering. This was done in response to feedback, 
![image](https://user-images.githubusercontent.com/36778811/177659231-82be0214-77ba-4a06-99f7-502af9745faa.png)

**Comment by alib-ms** [comment]
There is disagreement among Hindi users, though, regarding the preferred rendering of retroflex conjuncts for Hindi. A lot of people grew up with typewriter and 8-bit digital font encodings that always displayed these with explicit halant, and we have encountered people who complain about the Nirmala UI defaults and prefer the decomposed Mangal sequences. 

Microsoft Office added Mangal Pro. Mangal Pro displays stacked conjunct forms as the default experience.
![image](https://user-images.githubusercontent.com/36778811/177660141-42ee79d4-5719-40dc-8aeb-0a7a58078b3b.png)

**Comment by alib-ms** [comment]
Feel free to reopen if you have further questions.
