### ISSUE TITLE
Typo - Spaces

### ISSUE THREAD

**Issue by sevenpix** [MicrosoftDocs/typography-issues#91]
A few spaces are missing. For example:

imagequality. -> image quality
thescreen. -> the screen
shapeproduced. -> shape produced
andundistorted. -> and undistorted

They are mostly at the end of paragraphes.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0dab084d-cb51-49c6-ab01-569c9792f69b
* Version Independent ID: c32c2bea-b245-a741-0e0f-3ca33e06c2de
* Content: [TrueType hinting - Typography](https://docs.microsoft.com/en-us/typography/truetype/hinting#feedback)
* Content Source: [typographydocs/truetype/hinting.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/truetype/hinting.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by v-nihar** [comment]
Closing as Fixed
