### ISSUE TITLE
'name' table: nameId 13 dictates linguistic style, which is out of scope of this spec

### ISSUE THREAD

**Issue by Lorp** [MicrosoftDocs/typography-issues#910]
In the entry for name ID 13, we read “This field should be written in plain language, not legalese.” Advising implementors on the linguistic style of a legal agreement (over which they probably have no control) seems well beyond the scope of the spec. Legalese is not clearly differentiated from “plain language” anyway. I propose removing the sentence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc5a9d9-70e1-97b3-6926-c176e1a2401d
* Version Independent ID: 1afb0f5b-d1a7-7d69-d175-a5c9382b74be
* Content: [name - Naming table (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/name)
* Content Source: [typographydocs/opentype/spec/name.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/name.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by Lorp** [comment]
Good point about ‘License’ and ‘License Description’ being potentially different things. Indeed a way to provide simple anchor text (e.g. “Standard Tiro Typeworks license”) to be used in conjunction with the license URL would be useful, though if the field sometimes contains an entire license agreement, this would be impractical to assume in any UI.

Another deficiency with these license field specifications is that no guidance is given as to how they should be populated if the font is to be provided under various different licenses both now and in the future. This is surely a very common case, and probably omitting the fields entirely would be the best choice. Other than this last point, I like your updated text.

**Comment by tiroj** [comment]
If multiple licenses apply, then certainly having only a single license URL name ID is a problem, although that is a case where name ID 13 becomes useful in terms of being able to identify multiple licenses and even include additional URLs as text.

[Our build process uses config files to write custom name table entries for different packages, which can include different license descriptions, e.g. for the Tiro commercial vs Brill non-commercial distribution packages for the Brill fonts. This is typical of what we put in our retail fonts:

> Use of this font is governed by the terms of the applicable License Agreement and limitations stated in the Order Summary provided at the time of license purchase. The font may not be used without a valid License Agreement, or in a way that exceeds the limitations stated in the Order Summary.

]

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
