### ISSUE TITLE
[OS/2] Size fields should be uint16, not int16

### ISSUE THREAD

**Issue by Lorp** [MicrosoftDocs/typography-issues#911]
All these fields, as well as [*underlineThickness*](https://docs.microsoft.com/en-us/typography/opentype/spec/post#underlineThickness) in the post table, should be uint16, not int16, since negative sizes are meaningless. (The correct type is already used for the optical point size fields.) Of course, correct typing helps implementations to catch font errors.

int16	[ySubscriptXSize](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#ysubscriptxsize)	
int16	[ySubscriptYSize](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#ysubscriptysize)	
...  
int16	[ySuperscriptXSize](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#ysuperscriptxsize)	
int16	[ySuperscriptYSize](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#ysuperscriptysize)	
...  
int16	[yStrikeoutSize](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#ystrikeoutsize)	
...   
uint16	[usLowerOpticalPointSize](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#lps)	
uint16	[usUpperOpticalPointSize](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#ups)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ae9457c-0d3d-c137-588b-81d54a086f07
* Version Independent ID: 658c6d22-b9d1-1007-9cdb-6898911c9c75
* Content: [OS/2 - OS/2 and Windows metrics table (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#ystrikeoutsize)
* Content Source: [typographydocs/opentype/spec/os2.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/os2.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
These were signed from the beginning since (for whatever reason) the implementation in OS/2 used signed values. Conceptually unsigned would make sense, but changing now could potentially lead to fonts with large values that overflow existing implementations. The best remedy would be to add a recommendation that values be greater than zero.

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
