### ISSUE TITLE
COLR v1 spec needs clarification about alpha

### ISSUE THREAD

**Issue by niklasb-ms** [MicrosoftDocs/typography-issues#914]
In the OpenType 1.9 COLR table spec, the "Colors an solid color fills" section includes the following wording:

"In the formats added for COLR version 1, color references include a palette entry index and a separate alpha value within the COLR structure . . . The alpha value in the COLR structure is multiplied into the alpha value given in the CPAL color entry."

The last sentence above refers specifically to a "CPAL color entry," but if the palette entry index is 0xFFFF the text foreground color is used instead of a CPAL entry. The specification is silent as to whether the alpha value within the COLR table is ignored in this case, or is multiplied into the text foreground color. I think it should be the latter, and suggest adding the following sentence after the ones quoted above:

"If the palette entry index is 0xFFFF, the alpha value in the COLR structure is multiplied into the alpha value of the text foreground color."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be879f46-c026-4a9d-1156-a3c98ae8f429
* Version Independent ID: 28be1ce2-e487-b652-632f-e4dc5bb17f42
* Content: [COLR - Color Table (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/colr?source=docs)
* Content Source: [typographydocs/opentype/spec/colr.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/colr.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
