### ISSUE TITLE
Gurmukhi numerals?

### ISSUE THREAD

**Issue by manisingh9** [MicrosoftDocs/typography-issues#920]
how to put gurmukhi numerals?
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cd91da07-ca53-6679-d0e4-92176a354211
* Version Independent ID: 9dd20ffe-a3b3-8092-fa16-ce53b115ddc8
* Content: [Developing OpenType Fonts for Gurmukhi Script - Typography](https://docs.microsoft.com/en-us/typography/script-development/gurmukhi)
* Content Source: [typographydocs/script-development/gurmukhi.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/script-development/gurmukhi.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Can you please clarify your question? 
If you want to add Gurmukhi numerals to your document, you can do so via the [touch keyboard](https://support.microsoft.com/en-us/windows/get-to-know-the-touch-keyboard-004f3d67-855b-27f0-6f7c-d5145f691181).
