### ISSUE TITLE
Broken link to Adobe Technical Note #5902

### ISSUE THREAD

**Issue by DanTypeNetwork** [MicrosoftDocs/typography-issues#925]
The link to the PDF for Adobe Technical Note #5902 is broken. The file is now located at https://adobe-type-tools.github.io/font-tech-notes/pdfs/5902.AdobePSNameGeneration.pdf

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9bc5a9d9-70e1-97b3-6926-c176e1a2401d
* Version Independent ID: 1afb0f5b-d1a7-7d69-d175-a5c9382b74be
* Content: [name - Naming table (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/name)
* Content Source: [typographydocs/opentype/spec/name.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/name.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Should be fixed now.
