### ISSUE TITLE
Example 5: unclear wording "include a table"

### ISSUE THREAD

**Issue by mekkablue** [MicrosoftDocs/typography-issues#932]
In [example 5](https://docs.microsoft.com/en-gb/typography/opentype/spec/stat#example-5-a-family-comprised-of-a-non-italic-variable-font-plus-an-italic-variable-font), it says:

> …the first font would also **include a table** to reflect...

And a bit below:

> The second font would **include a table** to reflect the italic attribute…

1. The word ‘table’ may be confusing, consider ‘Axis Value Table’, or ‘Axis Value Table entry’.
2. Consider specifying the Axis Value Table _format._ I guess it is 3 and 1, respectively, but it should say so explicitly in the example.

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6dac86fb-3792-6630-ade2-32bfc4bba93a
* Version Independent ID: 9de5c023-f363-3e42-43c9-eac7793c8eaa
* Content: [STAT — Style Attributes Table (OpenType 1.9) - Typography](https://docs.microsoft.com/en-gb/typography/opentype/spec/stat)
* Content Source: [typographydocs/opentype/spec/stat.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/stat.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
