### ISSUE TITLE
Suggest note clarifying how deltas are applied to F2DOT14 and FIXED values

### ISSUE THREAD

**Issue by niklasb-ms** [MicrosoftDocs/typography-issues#933]
Per common table formats, the correct behavior is to add deltas to F2DOT14 by treating it as a 16-bit integer, and similarly for FIXED. This is not obvious to someone not intimately familiar with the spec, so a note in the relevant parts of the COLR table spec would be helpful.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be879f46-c026-4a9d-1156-a3c98ae8f429
* Version Independent ID: 28be1ce2-e487-b652-632f-e4dc5bb17f42
* Content: [COLR - Color Table (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/colr)
* Content Source: [typographydocs/opentype/spec/colr.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/colr.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
