### ISSUE TITLE
No option to add fonts "Manage optional features".

### ISSUE THREAD

**Issue by ChrisBertrandIndus** [MicrosoftDocs/typography-issues#934]
I don't see any option to add fonts in the Settings panel "Manage optional features".
Windows 10 pro 21H2 FR 64 bits

> Any of these [Feature On Demand (FOD)](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/features-on-demand-v2--capabilities) packages can also be installed manually via Settings. To add font packages manually, select the Start button, and then select Settings > Apps > Apps & features > Manage optional features.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0c0610f6-7c7b-b771-e635-84663af729db
* Version Independent ID: 50a9b23c-733c-c934-95dc-0bbd5d502fea
* Content: [Font List Windows 10 - Typography](https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list#-pan-european-supplemental-fonts)
* Content Source: [typographydocs/fonts/Windows_10_Font_List.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/fonts/Windows_10_Font_List.md)
* Product: **typography**
* GitHub Login: @nihar
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Select Start --> Settings --> Apps 
Under Apps and features, Click the link to Optional features --> Click + Add a feature.

**Comment by ChrisBertrandIndus** [comment]
Yes, thank you. Your details help.
