### ISSUE TITLE
ahmad 

### ISSUE THREAD

**Issue by mohmadmm** [MicrosoftDocs/typography-issues#935]
[اكتب ملاحظاتك هنا]

---
#### تفاصيل المستند

⚠ *تجنب تحرير هذا القسم. مطلوب لـ docs.microsoft.com ➟ ربط مشكلة GitHub.*

* ID: d43be991-71e4-56f0-fec0-df35d187a0b8
* Version Independent ID: 3ba72d0d-49d0-b525-5a0d-fbe56aa9329c
* Content: [About Microsoft Typography - Typography](https://docs.microsoft.com/ar-sa/typography/about)
* Content Source: [typographydocs/about.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/about.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
No notes/feedback were posted.
