### ISSUE TITLE
"Download PDF" links to OpenType 1.8.3 Spec

### ISSUE THREAD

**Issue by NSGod** [MicrosoftDocs/typography-issues#937]
Maybe I'm missing something, but the `Download PDF` link in the lower left corner of the page (https://docs.microsoft.com/en-us/typography/opbuildpdf/toc.pdf?branch=live) seems to link to a PDF of the OpenType 1.8.3 spec. Is there one available for the 1.9 spec, or am I out of luck?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2690ef79-7c15-86fa-58bb-500e4f5a9b94
* Version Independent ID: 12a633e1-c7b9-87ad-fd11-1bc4d12bcbb2
* Content: [OpenType specification (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/)
* Content Source: [typographydocs/opentype/spec/index.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/index.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Got this fixed.
