### ISSUE TITLE
VarStore explanations for deltas to F2DOT14 suggest clipping

### ISSUE THREAD

**Issue by drott** [MicrosoftDocs/typography-issues#939]
> When applying scaled deltas to an F2DOT14 value, the F2DOT14 value is treated like a 16-bit integer. (In this sense, the delta and the F2DOT14 value can be viewed as integer values in units of 1/16384ths.) If the context in which the F2DOT14 is used constrains the valid range for the default value, then any variations by applying deltas are clipped to that range.

In other parts of the spec the intention is more clearly stated that internal representations should be high enough to handle deltas resulting in effective values that are outside the range of the original data type. In the example of F2DOT14 (for example for angles in COLRv1), I understand from those separate parts of the spec that the deltas should allow moving those to values that are outside the `F2DOT14` range.

Here, the text 

> If the context in which the F2DOT14 is used constrains the valid range for the default value, then any variations by applying deltas are clipped to that range.

may be read as the fact that the F2DOT14 data type is used for COLRv1 angles means constraining its value range to the range of F2DOT14 and values should be clipped to it, after applying the deltas. 

I suggest to fix this ambiguity.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc38f55-a142-6d66-fc68-1bb6e6e9ed56
* Version Independent ID: 0665d6f2-4150-1977-4fd6-91c50c226ed9
* Content: [OpenType Font Variations Common Table Formats (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otvarcommonformats)
* Content Source: [typographydocs/opentype/spec/otvarcommonformats.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otvarcommonformats.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Some thoughts related to this: For certain variable items, deltas could yield a result < 0 that wouldn't make any sense. E.g., MVAR could for some instances yield OS/2.ySubscriptXSize < 0, or post.underlineThickness < 0.

**Comment by PeterCon** [comment]
Further thoughts: 

In COLR, VarColorIndex.alpha is F2DOT14 and is variable, but alpha does need to be constrained to [0, 1]. On the other hand, PaintVarSweepGradient.startAngle is also F2DOT14 and variable, but doesn't need to be constrained.

In the case of VarColorIndex.alpha, the text calls out that that value needs to be clamped, but this is not called out in some other cases involving variable alpha.

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
