### ISSUE TITLE
Oauth clean

### ISSUE THREAD

**Issue by jonjnegroguinea** [MicrosoftDocs/typography-issues#94]
[Escriba sus comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 95e88b53-d670-0240-422c-72748258ab2a
* Version Independent ID: b5fff1ee-cf03-e424-a2dc-aee58e0429e4
* Content: [Recommendations for OpenType Fonts - Typography](https://docs.microsoft.com/es-es/typography/opentype/spec/recom#base-table)
* Content Source: [typographydocs/opentype/spec/recom.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/recom.md)
* Product: **windows**
* GitHub Login: @PeterCon
* Microsoft Alias: **PeterCon**

**Comment by v-nihar** [comment]
Closing.
