### ISSUE TITLE
Item Variation Store: wrong expression is given for the size of each mapping entry

### ISSUE THREAD

**Issue by Lorp** [MicrosoftDocs/typography-issues#941]
In the section [_Associating Target Items to Variation Data_](https://docs.microsoft.com/en-us/typography/opentype/spec/otvarcommonformats#associating-target-items-to-variation-data) an incorrect expression is given for the size of each mapping entry, due to apparent confusion over operator precedence in C-like languages. The bit shift needs to happen before the addition, thus requires parentheses.

Please replace:

> The size of each mapping entry is ((entryFormat & mapEntrySizeMask) >> 4 + 1).

with:

> The size of each mapping entry is ((entryFormat & mapEntrySizeMask) >> 4) + 1.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc38f55-a142-6d66-fc68-1bb6e6e9ed56
* Version Independent ID: 0665d6f2-4150-1977-4fd6-91c50c226ed9
* Content: [OpenType Font Variations Common Table Formats (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otvarcommonformats#associating-target-items-to-variation-data)
* Content Source: [typographydocs/opentype/spec/otvarcommonformats.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otvarcommonformats.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
The wrong reading seems unlikely (there's no other point in having "4 + 1"), but doesn't hurt to be clearer. Will fix in the next version.

**Comment by Lorp** [comment]
If I’m anything to go by, implementors will copy and paste the expression into their code and wonder why it doesn't work!

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
