### ISSUE TITLE
Incorrect glyph mapping for "counterclockwise arrows button" emoji

### ISSUE THREAD

**Issue by fluffy-critter** [MicrosoftDocs/typography-issues#944]
Ever since the November 2021 update, the Windows 11 emoji font renders "[counterclockwise arrows button](https://emojipedia.org/counterclockwise-arrows-button/)" as equivalent to "[end arrow](https://emojipedia.org/end-arrow/)". The appropriate glyph for "counterclockwise arrows button" appears to still be in the font.

**Comment by alib-ms** [comment]
Thank you for letting us know. This issue has been fixed in the version 1.35 or higher.
