### ISSUE TITLE
COLR: ColorIndex and VarColorIndex are not used

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#949]
The ColorStop, VarColorStop, PaintSolid and PaintVarSolid formats don't use the ColorIndexRecord and VarColorIndex record formats as members, though it seems like they could, and the note that follows (Var)PaintSolid seems to assume that they do.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: be879f46-c026-4a9d-1156-a3c98ae8f429
* Version Independent ID: 28be1ce2-e487-b652-632f-e4dc5bb17f42
* Content: [COLR - Color Table (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/colr)
* Content Source: [typographydocs/opentype/spec/colr.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/colr.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterConstable** [comment]
In a [commit on July 12, 2021](https://github.com/googlefonts/colr-gradients-spec/commit/641f7f6070a90e07fc2b29a91691a605e7c7e6fa), ColorIndex and VarColorIndex were dropped from the OFF draft. But some of the details were overlooked when incorporating that into OT 1.9 drafts.

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
