### ISSUE TITLE
Microsoft fonts for commercial use

### ISSUE THREAD

**Issue by snoix** [MicrosoftDocs/typography-issues#95]
We are an online publishing company, and I try to find information on if we can use the fonts provided by Word 2013 for our journals. We wish to convert it to PDF file and put the PDF online and readers can download it for free. 

Do we need a specific license for doing this? The legal terms are so vague and I can't find the license agreement anywhere. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d43be991-71e4-56f0-fec0-df35d187a0b8
* Version Independent ID: 3ba72d0d-49d0-b525-5a0d-fbe56aa9329c
* Content: [About Microsoft Typography - Typography](https://docs.microsoft.com/en-us/typography/about#feedback)
* Content Source: [typographydocs/about.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/about.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by alib-ms** [comment]
I apologize that your feedback was never addressed here. I understand that it can be frustrating when your concerns are not addressed in a timely manner. However, I hope that the [FAQ ](https://learn.microsoft.com/en-us/typography/fonts/font-faq) will be helpful in addressing your question. It contains useful information about fonts and their usage.
As your original post was made some time ago, I am going to close this matter for now. However, please don't hesitate to reach out and reopen this issue if you have any further questions or concerns.
Thank you for your feedback and patience.
