### ISSUE TITLE
Restrictions when using a home, student, or non-commercial license

### ISSUE THREAD

**Issue by lefhya** [MicrosoftDocs/typography-issues#953]
In the FAQ they say that when you’re not using a home, student, or non-commercial use license you don’t have restrictions.

But about when you HAVE one of this licenses? What are the terms of use then?

I found that the FAQ doesn’t answer that in a clear way. 

Does anybody know the terms?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ea5ad39-ec78-af12-1479-e3def2c62723
* Version Independent ID: 4c9dbe2a-0d30-42fe-34be-38053fcf5c4e
* Content: [Font redistribution FAQ - Typography](https://docs.microsoft.com/en-us/typography/fonts/font-faq)
* Content Source: [typographydocs/fonts/font-faq.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/fonts/font-faq.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
You probably want to review the Windows license [here](https://www.microsoft.com/en-us/useterms/).

**Comment by alib-ms** [comment]
I hope the link I shared with you gives you the information you were looking for, therefore, I am closing this issue. Please feel free to reopen if you need additional information.
