### ISSUE TITLE
wrong shape -" Arial Unicode MS " (Devnagri) font

### ISSUE THREAD

**Issue by pcm8081** [MicrosoftDocs/typography-issues#958]
The shape of the word is wrong
word =  शृंगार (Devnagri =Arial Unicode MS)

![2022-08-08_001001](https://user-images.githubusercontent.com/100966712/183306156-5d1dfc68-1a07-4002-a632-fc56ce6312ed.png)

--

</body>
</html>
word (शृंगार)which 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e542900f-429c-499a-be33-06ed008076fc
* Version Independent ID: b7e1af17-8a49-ab34-9dc4-686adc66a357
* Content: [Arial Unicode MS font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/arial-unicode-ms)
* Content Source: [typographydocs/font-list/arial-unicode-ms.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/arial-unicode-ms.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
The Arial Unicode MS is no longer offered with Microsoft products. This typeface use ship with Office. However, Office removed this font from their font offering quite a few years ago. If you like to see this corrected in the Arial Unicode font file then you will need to contact Monotype.

**Comment by alib-ms** [comment]
Closing the issue upon no further follow up questions from @pcm8081.
