### ISSUE TITLE
wrong shape -"Sanskrit text " (Devnagri) font

### ISSUE THREAD

**Issue by pcm8081** [MicrosoftDocs/typography-issues#959]
The shape of the word is wrong

word = क्या , क्यों, क्योंकि (Devnagri  )
[
![sans text](https://user-images.githubusercontent.com/100966712/183307195-16b93f4c-858c-4443-9bf8-73013fbcf965.png)
](url)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1198929e-67b2-8442-c623-7e1325712c6a
* Version Independent ID: 47fa7093-96e1-effa-2157-f07d00e2d7c4
* Content: [Sanskrit Text font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/sanskrit-text)
* Content Source: [typographydocs/font-list/Sanskrit-Text.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/Sanskrit-Text.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
This is not wrong, it is just a different style of ligature within the Sanskrit manuscript tradition. If you prefer the linear half form presentation, you can force this in the Sanskrit Text font by inserting the Zero-Width Joiner formatting control character (U+000D) after the halant.

This is how the test word appears with the default ligature, top, and with ZWJ inserted to force the half form of क, bottom:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/5614500/183484836-abad15cc-1d1b-42af-be3d-de3b21d7bbac.png">

**Comment by alib-ms** [comment]
Thank you @tiroj for the reply. Dear @pcm8081, please feel free to reopen the issue if you have follow-up thoughts on this matter. I think this is by design.
