### ISSUE TITLE
wrong shape - "Mangal"  (Devnagri) font 

### ISSUE THREAD

**Issue by pcm8081** [MicrosoftDocs/typography-issues#960]
The Shape of word is wrong.
word = शृंगार,विद्या,यद्यपि,विद्यालय 
![mangal](https://user-images.githubusercontent.com/100966712/183307872-3c0ea622-8445-4093-b0e2-f386dd742ff5.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6c629c9b-d28b-aa25-5344-376a3dd28b2e
* Version Independent ID: 991734e0-5210-6a12-f671-1c0b07d11e58
* Content: [Mangal font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/mangal)
* Content Source: [typographydocs/font-list/mangal.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/mangal.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
As I recall, earlier versions of Mangal included more traditional ligatures for conjuncts involving retroflex consonants, but these were disabled in response to feedback from some users and some unfortunate recommendations of the Bureau of Indian Standards regarding use of explicit halant in modern Hindi.

**Comment by alib-ms** [comment]
The conjuncts such as श्‍व, श्‍ल, and श्‍‍न are predominantly used in contemporary Hindi. This was also accepted as Standard by the Hindi Spelling Committee of Govt of India. This is widely used by all Hindi Newspapers and Hindi Fonts developed by various private companies. Therefore, the recommendation was to update the default behavior with conjunct like श्‍व.

**Comment by alib-ms** [comment]
Dear @pcm8081, please feel free to reopen the issue if you have follow-up thoughts on this matter.
