### ISSUE TITLE
wrong shape - " Utsaah " (Devnagri) font

### ISSUE THREAD

**Issue by pcm8081** [MicrosoftDocs/typography-issues#961]
The Shape of word is wrong.
word = शृंगार
![uttash](https://user-images.githubusercontent.com/100966712/183308217-be1ff423-8117-48a9-b7c0-736b4c3d9174.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc6a119f-0f2b-9e28-6d46-9c790d3ccb03
* Version Independent ID: e041cf6b-2f79-1c44-c5d6-a47229b3331e
* Content: [Utsaah font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/utsaah)
* Content Source: [typographydocs/font-list/utsaah.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/utsaah.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
This is not a wrong shape.

There is a traditional ligature form, which is what you see in Nirmala UI and Sanskrit Text, etc. In some fonts, this consonant+vowel combination is not given a ligature but instead represented as a base letter plus the vowel sign below, which is what you see in Kokila and some other fonts. Some users are going to insist that the traditional form should be used, while others are content with the simplified display. We can add both forms in the font, one as default and other possibly as a stylistic form. The challenge would how do users will find the stylistic form?

**Comment by alib-ms** [comment]
Dear @pcm8081, please feel free to reopen the issue if you have follow-up thoughts on this matter. I think this is by design.
