### ISSUE TITLE
Be consistent in formatting of "ItemVariationStore" structure name

### ISSUE THREAD

**Issue by Lorp** [MicrosoftDocs/typography-issues#963]
There are multiple ways that ItemVariationStore is written on this page:

* ItemVariationStore (4x)
* itemVariationStore (2x)
* item variation store (25x, with case variations when at start of sentence and in headings)

I recommend we standardize on **ItemVariationStore** to be consistent with the general structure naming convention of the spec. There are also occurrences in various other tables that should be updated.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8cc38f55-a142-6d66-fc68-1bb6e6e9ed56
* Version Independent ID: 0665d6f2-4150-1977-4fd6-91c50c226ed9
* Content: [OpenType Font Variations Common Table Formats (OpenType 1.9) - Typography](https://docs.microsoft.com/en-us/typography/opentype/spec/otvarcommonformats)
* Content Source: [typographydocs/opentype/spec/otvarcommonformats.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otvarcommonformats.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Across the OT spec, structures are often referred to in an informal way, as in the case here "item variation store" (with sentence case variants). But structures are all given a formal, symbolic name and references should be consistent. So the two instances of "itemVariationStore" should be corrected.

**Comment by Lorp** [comment]
Understood about informal references (though when Item Variation Store is Title Cased it takes on an air of formality).

Same applies to ItemVariationData (which is sometimes written itemVariationData).

**Comment by PeterCon** [comment]
In the otvarcommonformats page, "Item Variation *" only occurs in headings. Not going to change that.

**Comment by PeterCon** [comment]
I thought this would be a very easy fix, but it turned out that the issue also occurred (and in greater numbers) in several of the OTL-related chapters.

**Comment by PeterCon** [comment]
See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
