### ISSUE TITLE
Allow usWidthClass valid values greater than 9.

### ISSUE THREAD

**Issue by fabiocaccamo** [MicrosoftDocs/typography-issues#964]
Hello!

Together with [@JeremieHornus](https://github.com/JeremieHornus), we're encountering some limitations instantiating a variable font having some instances with the `width` percentage value greater than the max valid value allowed for the `usWidthClass` *(value 9 / 200% / "Ultra-expanded" as defined in the [documentation](https://docs.microsoft.com/en-us/typography/opentype/spec/os2#uswidthclass))*.

This happens because `fontmake` clamps the max value to `9` *(on all instances different where width exceeds 200%)* for having an explicit mapping between legacy `OS2.usWidthClass` and Variable Font's `wdth` axis. 

We already started discussing this in a [fontmake issue](https://github.com/googlefonts/fontmake/issues/926).

### The main proposals are these:

- Support `usWidthClass` valid values greater than `9` (this would be backward compatible).
- All values (except value `5` / 100% / "Normal") shouldn't be linked directly to a precise `%` value (eg. for a particular font the value `9` could mean 300% width).

**Comment by PeterCon** [comment]
IIUC, you have a variable font with a width axis that can extend beyond 200, and then are generating instance fonts for instances with wdth > 200?

Why not simply set usWidthClass in those instances to 9? What wouldn't work if you were to do that?

**Comment by fabiocaccamo** [comment]
Exactly.

The `usWidthClass` value is set by `fontmake`. The problem is that instances with `width = 200` and instances with `width > 200` have the same `usWidthClass` value as if they would have the same identical width.

**Comment by PeterCon** [comment]
But what wouldn't work if two generated instance fonts had the same usWidthClass?

**Comment by fabiocaccamo** [comment]
On our (new to come soon) web shop, we display each family static fonts grouped/sorted by `usWeightClass`, `usWidthClass` and `italicAngle`, so these three are very useful informations we extract from the static fonts that we instantiate automatically from the variable ones.

**Comment by PeterCon** [comment]
The OS/2.usWeightClass spec is around 30 years old. There are likely to be very many implementations in the wild that assume that these values fall in the range 1 to 9. I think changing this now would be very risky.

As an alternative, you could generate instance fonts with a STAT table and specify wdth values there. Then, for your UI, you could use information from the STAT table, if present, to determine how to sort in UI. This is exactly the kind of scenario the STAT table is intended for, and it was designed to supersede the limitations of legacy parts of the spec, like OS/2 fields.
