### ISSUE TITLE
Please clarify whether VOLT will *convert* legacy encoded text into Unicode when new font file is created with correct Unicode points

### ISSUE THREAD

**Issue by kaanchan** [MicrosoftDocs/typography-issues#966]
We have a corpus of Devanagari text using a legacy font (APS_C_DV_Priyanka.ttf). I have in the process of converting the legacy encoded text to Unicode. Reading through a number of online docs, I still don't get if VOLT has the ability to read legacy encoded text and *convert* it to Unicode or if it more specifically provides a way to update a legacy font so that it can be used with Unicode encoded text. 

I guess the question is essentially: do I still need to find a way to convert the original legacy-encoded Devanagari text to Unicode Devnagari and then run an update VOLT font to view the text so it appears the same or does VOLT offer a way to take the original text and produce Unicode encoded text from the updated rules?

https://docs.microsoft.com/en-us/typography/develop/convert-a-devangarai-font-to-unicode-otl

> So, suppose you have a font that was used to print Devanagari in some proprietary encoding. What does it take to convert it to Unicode? Where do I start?

It would be great if the above paragraph were expanded to allay the confusion of those like me and make clear what problem VOLT actually solves at which point it is used to solve it. The problem in my case, and I imagine many of those need to updated legacy fonts is the following:

1. text was typed out using a legacy (Devanagari) font
2. the underlying encoding looks like gibberish (‚ã®ãÄãäØã¶ãã) in other programs and text cannot be searched for in a standard way
3. a script has been created to convert the legacy encoded text to Unicode encoded text so now the orginal text is correctly viewable with Unicode (Devanagari) fonts but not in the original legacy font
4. some tool is used to update the legacy font to the correct Unicode points so that the updated Unicode encoding can now be viewed to look visually the same as the font from the original in step 1

Does VOLT fall into step 4 or can it be used as a tool in step 3 as well?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1eaef1fe-85fe-38d2-53c6-0e3cf5e183d1
* Version Independent ID: a3f17066-d403-2fd2-d90e-2b4d5234fa35
* Content: [Convert a Devanagari font to Unicode / OTL - Typography](https://docs.microsoft.com/en-us/typography/develop/convert-a-devangarai-font-to-unicode-otl)
* Content Source: [typographydocs/develop/convert-a-devangarai-font-to-unicode-otl.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/develop/convert-a-devangarai-font-to-unicode-otl.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
VOLT does not do any encoding conversion.

VOLT can read the cmap table of a font opened in VOLT, provides the ability to change or add Unicode encodings in the VOLT glyph data editing window, and can write a new cmap table (you can specify which platform encodings and formats it should write).

It is possible to manually edit the Unicode mapping for each individual glyph in the VOLT glyph data editing window, but that is very slow and prone to errors. My recommendation is to do the encoding conversion in another, more general font editing tool such as FontLab or Glyphs, or via a cmap table dump/fuse script with TTX. You can probably use the script that you have for text conversion as a basis for glyph encoding conversion in the font, or make a simple name mapping chart.

I use FontLab for this sort of thing, and the easiest method is probably to create a .nam file which is a list mapping Unicode characters to glyph names (I am presuming you want to keep the glyph names in your font; if not, you will also want a .ren file that maps from old names to new names). You can use the .nam file within FontLab to generate new Unicode encodings based on the glyph names. You then export a TTF from FontLab and open it in VOLT.

**Comment by alib-ms** [comment]
Feel free to reopen if you have further questions.

**Comment by kaanchan** [comment]
@tiroj 
> VOLT does not do any encoding conversion.

Thanks for the above and for the suggested process with the alternate softwares you provided. I'll look into those.

@alib-ms 
> Converting previously created Devanagari text using non-Unicode encoded fonts to Unicode encoded text is outside the scope of VOLT.

Got it, thank you.

> You can read more about VOLT here
> [Visual OpenType Layout Tool - Typography | Microsoft Docs](https://docs.microsoft.com/en-us/typography/tools/volt/)

I think I read every post about VOLT there is and was still unclear :). I'll provide some page feedback for a few lines that may be considered for adding to clarify for future searchers like me. The use of "substitution" in a larger workflow that involves lots of substitutions is where I got tripped up. I had no font internals experience until reading up on the topic recently.
