### ISSUE TITLE
INSTRCTRL typo

### ISSUE THREAD

**Issue by Lorp** [MicrosoftDocs/typography-issues#967]
The section headed "INSTRuction execution ConTRoL" has a typo: the R should be lowercase to match the INSTCTRL instruction. There is also an occurrence of "INSTRCTRL[]" in the code example that follows. Likewise that should be "INSTCTRL[]".

https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/tt_instructions#instruction-execution-control

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72f10002-2bdd-f04d-e1aa-201dd8bbcdcf
* Version Independent ID: 72f10002-2bdd-f04d-e1aa-201dd8bbcdcf
* Content: [TrueType Instruction Set (OpenType 1.9.1) - Typography](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/tt_instructions)
* Content Source: [typographydocs/opentype/otspec191alpha/tt_instructions.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/otspec191alpha/tt_instructions.md)
* Product: **typography**
* GitHub Login: @v-nihar
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Thanks for catching that. See the [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
