### ISSUE TITLE
[OpenType] Language System Tag for Uralic Phonetic Alphabet

### ISSUE THREAD

**Issue by moyogo** [MicrosoftDocs/typography-issues#969]
There is a registered [IETF language tag](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) for the Uralic Phonetic Alphabet, just like there are for the International Phonetic Alphabet and the Americanist Phonetic Alphabets.

There are Language System Tags for IPA and APA, there should be one for UPA as well.

For example, phonetic data transcribed with UPA typically uses U+0251 ɑ with a shape different from the typicall IPA form.

|Language System|Language System Tag|Corresponding ISO 639 ID (if applicable)
|--|--|--|
| Phonetic transcription—Uralicist conventions | 'UPPH' |

**Comment by PeterCon** [comment]
See [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
