### ISSUE TITLE
windows 10 is not included in the "Products that supply this font" list

### ISSUE THREAD

**Issue by BartolomeSintes** [MicrosoftDocs/typography-issues#97]
[Escriba sus comentarios aquí]

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: d3c2a6fb-3005-b23b-bc83-f8046b852851
* Version Independent ID: f5d0fbf0-990b-7b3d-0c4a-bd4b51c8532e
* Content: [Segoe UI font family - Typography](https://docs.microsoft.com/es-es/typography/font-list/segoe-ui)
* Content Source: [typographydocs/font-list/segoe-ui.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/segoe-ui.md)
* Product: **windows**
* GitHub Login: @nihar
* Microsoft Alias: **mihar**

**Comment by Porges** [comment]
Also there should be a page for "Segoe UI Historic"

**Comment by fitojb** [comment]
That is true for all the individual font pages—no one includes Windows 10, in any of its versions.

**Comment by alib-ms** [comment]
Fixed.
