### ISSUE TITLE
[OpenType] Language System Tags for Iroquoian languages (Cayuga, etc.)

### ISSUE THREAD

**Issue by moyogo** [MicrosoftDocs/typography-issues#970]
Please add Language System Tags for Cayuga (ISO 639-3: cay), Oneida (ISO 639-3: one), Onondaga (ISO 639-3: ono), Seneca (ISO 639-3: see), Tuscarora (ISO 639-3: tus), Wendat (ISO 639-3: wdt), Wyandot (ISO 639-3: wyn).

The Reg Henry orthography of Cayuga often uses an angular left hook below and an angular modifier glottal stop.
With Unicode, these are usually represented with ogonek letters Ę, ę, Ǫ, ǫ and the single quote ’, the modifier letter apostrophe ʼ, the superscript seven ⁷, or the modifier letter ˀ.

It would be useful to have a language system tag for Cayuga or other Iroquois languages if one wants implement font features for those languages.

|Language System|Language System Tag|Corresponding ISO 639 ID (if applicable)
|--|--|--|
| Cayuga | 'CAY ' | [cay](https://iso639-3.sil.org/code/cay)
| Oneida | 'ONE ' | [one](https://iso639-3.sil.org/code/one)
| Onondaga | 'ONO ' | [ono](https://iso639-3.sil.org/code/ono)
| Seneca | 'SEE ' | [see](https://iso639-3.sil.org/code/see)
| Tuscarora | 'TUS ' | [tus](https://iso639-3.sil.org/code/tus)
| Wendat | 'WDT ' | [wdt](https://iso639-3.sil.org/code/wdt)
| Wyandot | 'WYN ' | [wyn](https://iso639-3.sil.org/code/wyn)

Note that there is a ISO 639-1 code for Iroquaian languages, as well as other Iroquaian languages with ISO 639-3 codes but they are not proposed here.

**Comment by PeterCon** [comment]
If they all follow the same typographic conventions, would it not be useful to have a tag ('IRO '?) for Iroquoian languages?

**Comment by PeterCon** [comment]
See [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by moyogo** [comment]
It's not clear if all Iroquois languages follow the same style for those characters at this point.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
