### ISSUE TITLE
How to type/display शृंगार with Kokila font?

### ISSUE THREAD

**Issue by kaanchan** [MicrosoftDocs/typography-issues#973]
Kokila font is presented on https://learn.microsoft.com/en-us/typography/font-list/kokila as a font "primarily meant for use in displaying Hindi text in documents." One Hindi word we are unable to represent is Kokila in शृंगार, namely the display of the first conjunct (शृं). It shows as श्रृं. 

Current and expected are depicted below:
![image](https://user-images.githubusercontent.com/13602253/190910889-11a49781-8515-430a-b87b-fe0b99f34ea8.png)

The closest I can get is below, which is incorrect:
![image](https://user-images.githubusercontent.com/13602253/190911048-d50b6f03-649a-42d3-91c5-cdfb3c04233c.png)

This thread discusses the issue in greater detail: https://groups.google.com/g/technical-hindi/c/ozHt0UyJ5Aw?pli=1

Is there any solution for displaying शृंगार as per correct/standard Hindi using Kokila font?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3c1df5ef-aecd-50be-593e-f5a8272afdf8
* Version Independent ID: 854fa645-b308-024e-d848-f4577ec1a6f6
* Content: [Kokila font family - Typography](https://learn.microsoft.com/en-us/typography/font-list/kokila)
* Content Source: [typographydocs/font-list/kokila.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/kokila.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
Kokila lacks the special ligature glyph needed to represent the traditional form of this combination.

If adding this ligature, @alib-ms, consider also the ligature with the vocalic r̄ sign, although this would be _very_ rare and specific to Sanskrit:
<img width="511" alt="image" src="https://user-images.githubusercontent.com/5614500/190916667-62aef5d3-bcfe-4cdb-854e-02020771a4a7.png">

**Comment by alib-ms** [comment]
Thank you for the feedback. I have created a work item to add these missing ligatures in the Kokila font family.

**Comment by kaanchan** [comment]
@alib-ms Any idea when a release date for a new version of Kokila font family that includes that work item could be (even if a very non-committal, broad estimate)? Anything I can do to contribute to that effort to accelerate a new release with that work item?

**Comment by tiroj** [comment]
Yes. All the –Ra letters with merged _rakar_ stroke are ligature glyphs, and so would be the special forms with vocalic vowel signs, as in the Sanskrit Text font.

This may be of interest to you. This is the complete set of consonant+vowel special ligatures in the Tiro Devanagari Sanskrit font. Some of these are pretty specific to Sanskrit, so might not be suitable for a font primarily targeting modern Hindi use, but perhaps let Ali know if you think any more of these are missing from Kokila and should be added?
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/5614500/191332280-77161147-0253-458e-9b6f-566633a2c093.png">
/dDa_dSignVocalicR  /dDa_dSignVocalicRr  /dDDa_dSignVocalicR  /dRa_dSignU  /dRa_dSignUu  /dRa_dSignVocalicR  /dRa_dSignVocalicL  /dRa_dSignVocalicRr  /dRa_dSignVocalicLl  /dSha_dSignVocalicR  /dSha_dSignVocalicRr  /dHa_dSignU  /dHa_dSignUu  /dHa_dSignVocalicR  /dHa_dSignVocalicRr  /dHRa_dSignU  /dHRa_dSignUu

**Comment by kaanchan** [comment]
@alib-ms Great to hear! Please let me know if/how I can help with any testing and verifcation.

**Comment by kaanchan** [comment]
> If adding this ligature, @alib-ms, consider also the ligature with the vocalic r̄ sign, although this would be _very_ rare and specific to Sanskrit:

We also work with a large Sankrit corpus. It is often mixed with Hindi, so this would be very useful and complete in implemenation even if rarely used. Thanks for pointing it out @tiroj .

**Comment by alib-ms** [comment]
Quick before and after.  
![image](https://user-images.githubusercontent.com/36778811/222257262-ff454156-b3f3-462b-92df-032b327e04e9.png)

[kaanchan](https://github.com/kaanchan) please share some valid words with both ligatures.

**Comment by kaanchan** [comment]
> kaanchan please share some valid words with both ligatures.

@alib-ms This is what the editing department was able to share immediately:
शृंगार
शृंखला
शृगाल

They could not come up with any words from memory that use the double Ri lagature, but acknowledged it would be a Sankrit use-case. 

We do do a fair bit of Hindu + Sankrit documentation, research, and editing so if/when that scenario arrives, it will be great if Kokila handles it.

I will try and create a list of multiple words for both ligatures over the next few days.

**Comment by alib-ms** [comment]
Thank you, [kaanchan](https://github.com/kaanchan)! Appreciate your help. 
I got the Kokila font family almost completed. As noted above I have added both ligatures. I will also update the Aparajita and Utsaah font families accordingly.

**Comment by tiroj** [comment]
The long ṝ vowel is, so far as I know, non-naturally occurring in Sanskrit phonology, so may never occur in any actual words. It is a sort of theoretical construct that completes the algorithmic models of Sanskrit grammarians.

**Comment by kaanchan** [comment]
@alib-ms 
> [kaanchan](https://github.com/kaanchan) please share some valid words with both ligatures.
Here are some Sanskrit words from [sanskritdictionary.com](https://sanskritdictionary.com/?iencoding=deva&q=%E0%A4%B6%E0%A5%84&lang=sans&action=Search):
अभिविशॄ
अपिशॄ
अवशॄ
निःशॄ
निर्विशॄ
पराशॄ
परिशॄ

It appears to be a full root per Paninian grammar:
![image](https://user-images.githubusercontent.com/13602253/224047148-9b6fb264-0d00-4cfc-b581-7e54f506ea73.png)
Note how the above text had to mix the two forms of ś because their typeface did not support the śṝ combination are now supporting for Kokila!

And here is an example of śṝ (शॄ) rendered in siddhanta-cakravat-webfont. A nice use-case for a font being able to generate this combination.
![image](https://user-images.githubusercontent.com/13602253/224042990-799cdaf2-628a-43e5-91ac-cc022b1d40e4.png)

**Comment by alib-ms** [comment]
To type this word “शृंगार” the user will type the following sequence of characters. 
U+0936 U+0943 U+0902 U+0917 U+093E U+0930
Using the Kokila font, the results: 
![image](https://user-images.githubusercontent.com/36778811/230462219-c2e79ed9-13c9-4b42-b9be-7dbed2393f48.png)
![image](https://user-images.githubusercontent.com/36778811/230462310-c4d1c7ae-7531-4b42-93ed-5b878003177e.png)

No special formatting is needed. input method will be exactly the same only the results will differ from old font vs new font. if you add the Zero Width Joiner then you will not get the ligature form.

**Comment by kaanchan** [comment]
> @alib-ms How will a user be able to input
> ![image](https://user-images.githubusercontent.com/13602253/230151638-f5bffe8d-80a0-442d-a903-8704646b0d4f.png)

Is there any way to input this ligature, in particular? Curious because it says "in source". If so, how can it be done? This question is separate from the new ligature which allows for creating words like shringar.

**Comment by fontdesigner** [comment]
I have Developed a Vedakshar typeface just like metal Typeface 

![Vedakshar Text](https://github.com/MicrosoftDocs/typography-issues/assets/5018438/a9a4f113-290a-4ded-8fb9-4b21207e167d)

**Comment by alib-ms** [comment]
I have resolved the reported issues with our Devanagari fonts. The updated fonts will be included in the upcoming release of Office and the Windows 11 update. If you have any further questions or concerns, please feel free to reopen the issue. I sincerely appreciate your valuable input and feedback. Thank you very much.
