### ISSUE TITLE
Names of 'TUL ' and 'TUM ' are swapped

### ISSUE THREAD

**Issue by dscorbett** [MicrosoftDocs/typography-issues#974]
The names for 'TUL ' and 'TUM ' are swapped. 'TUL ' should be “Tulu”. 'TUM ' should be “Tumbuka”.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 662c6f54-f90c-52ed-dca2-0f0a0a49fee5
* Version Independent ID: 6aa33924-d45e-60c3-a9fd-e317ff662993
* Content: [Language system tags (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/languagetags)
* Content Source: [typographydocs/opentype/spec/languagetags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/languagetags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Wow! That error was introduced in OT 1.8. 'TUL ' is indeed for Tulu, and 'TUM ' is for Tumbuka. Fixing as an erratum in OT 1.9.

**Comment by PeterCon** [comment]
Fixed in OT 1.9.
