### ISSUE TITLE
script tag 'kana' is listed twice

### ISSUE THREAD

**Issue by seehuhn** [MicrosoftDocs/typography-issues#976]
The OpenType script list has two entries for the script tag 'kana'.  The first entry is for "Hiragana", the second for "Katakana".  If this is correct, maybe these two lines should be merged into one?  Or should the script tag for "Hiragana" be 'hira'?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 49c1efc4-e864-0727-9663-7cec0ec4d9f1
* Version Independent ID: 36ec4396-b9cb-cba9-1582-d8400296d249
* Content: [Script tags (OpenType 1.9 delta) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/scripttags)
* Content Source: [typographydocs/opentype/spec/scripttags.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/scripttags.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by tiroj** [comment]
Early in OpenType Layout history, the Unicode Hiragana and Katakana script properties were unified under the `kana` script tag. Given how long this has been the case, and the core functionality of the script tags in determining shaping engine paths, this is something that is unlikely to be changed now. The term kana is used collectively to refer to Hiragana and Katakana, so I think it is probably fine as is: there’s nothing wrong with having a tag that maps to more than one Unicode script (so long as there isn’t a situation in which one would want to implement script-level OTL differences).

**Comment by seehuhn** [comment]
Thanks for the clarification.  I wonder whether it would make sense to make this clear in the documentation, by replacing the current two `kana` lines with one combined line, _e.g._ saying "Japanese scripts (Hiragana+Katakana) - 'kana'"?

**Comment by tiroj** [comment]
The OTL script tag registry is basically a mapping of tags to Unicode script property names, in which respect the current set up is correct. It has the benefit of allowing quick reverse lookups, i.e. finding the tag from the script name as well as the script name from the tag.

**Comment by seehuhn** [comment]
Great, thank you for your patient explanations.
