### ISSUE TITLE
Book antiqua license issues

### ISSUE THREAD

**Issue by iergon** [MicrosoftDocs/typography-issues#979]
hi, i didn't found out, can i use font "Book antiqua" for commercial use, or i needed to buy official licence? and if i need, where i can buy it?

---
#### Сведения о документе

⚠ *Не вносите правки в этот раздел. Это необходимо для связывания страницы сайта learn.microsoft.com с вопросом на GitHub.*

* ID: dbfc5c0c-7705-040b-a9af-cfefbd6616dd
* Version Independent ID: e421be6d-c8ac-6701-64cb-d9744d0227cf
* Content: [Book Antiqua font family - Typography](https://learn.microsoft.com/ru-ru/typography/font-list/book-antiqua)
* Content Source: [typographydocs/font-list/book-antiqua.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/book-antiqua.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by alib-ms** [comment]
Hi [iergon](https://github.com/iergon),

This [FAQ](https://docs.microsoft.com/en-us/typography/fonts/font-faq) should answer your questions - even though it is Windows-centric FAQ and Book Antiqua is typically installed with Office. 

If you need additional rights they can be acquired from our licensing partner Monotype – the contact there is Jacqueline Sutter [jaki@monotype.com](mailto:jaki@monotype.com)
