### ISSUE TITLE
Title Case opsz descriptive name

### ISSUE THREAD

**Issue by davelab6** [MicrosoftDocs/typography-issues#983]
In https://github.com/googlefonts/axisregistry/issues/4 towards the end, Adam helpfully noted there are some editorial inconsistencies in the MS OT & MPEG OFF specs regarding the treatment of casing. 

In https://github.com/googlefonts/axisregistry/pull/89 I am changing the GF axis registry from Sentence case to Title Case for opsz; I worked with the Material Design Guidelines' content strategy folks on this topic earlier this year for the m3 guidelines (https://m3.material.io/styles/typography/fonts) and landed on Title Case, since I believe the axes names are properly Proper Nouns

The original sentence case for opsz comes from the specs' sentence case, and so we would like to upstream this change to the specs.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3061e37e-08cf-d8be-345c-7f762521b910
* Version Independent ID: 9314da1d-dd1c-5730-ca08-a5b30ad7213f
* Content: [opsz design-variation axis tag (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/dvaraxistag_opsz)
* Content Source: [typographydocs/opentype/spec/dvaraxistag_opsz.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/dvaraxistag_opsz.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Sounds good. Note that this won't be prescriptive on what font developers put in their fonts, or what applications show in UI.

See [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
