### ISSUE TITLE
Format numbers; Formats 4(PaintLinearGradient) and 5(PaintVarLinearGradient).

### ISSUE THREAD

**Issue by tnake** [MicrosoftDocs/typography-issues#984]
In the detail descrption for Format 4 and 5(PaintLinearGradient, PaintVarLinearGradient), it says; '**Format 4** allows for variation of color stop positions or of alpha in a variable font; **format 5** provides a more compact representation when variation is not required.'.
Are these format numbers correct? I think that 4 and 5 were swapped over each other by unintentional human error.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: be879f46-c026-4a9d-1156-a3c98ae8f429
* Version Independent ID: 28be1ce2-e487-b652-632f-e4dc5bb17f42
* Content: [COLR - Color Table (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/colr)
* Content Source: [typographydocs/opentype/spec/colr.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/colr.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Thanks for catching. See [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
