### ISSUE TITLE
vhea advanceHeightMax has signed int16 whereas hhea advanceWidthMax has UFWORD (unsiged)

### ISSUE THREAD

**Issue by anthrotype** [MicrosoftDocs/typography-issues#985]
hhea and vhea are supposed to be similar to one another, one for horizontal the other for vertical metrics header respectively.

However the vhea advanceHeightMax is typed as `int16` (`FWORD`?) which means it is supposed to be a _signed_ 16-bit integer
https://learn.microsoft.com/en-us/typography/opentype/spec/vhea

... whereas the hhea advanceWidthMax is typed as `UFWORD` thus unsigned:
https://learn.microsoft.com/en-us/typography/opentype/spec/hhea

Is that intentional? Why is there that difference? Aren't advances always supposed to proceed in the same positive direction (either horizontal or vertical)? A negative andvance would make the text proceed backward.

I noticed that both FontTools and Harfbuzz interpret that field in the vhea as an unsigned 16-bit integer:

https://github.com/fonttools/fonttools/blob/9369edb6a9fa061e40bb5c45c6861e3d565bcdf5/Lib/fontTools/ttLib/tables/_v_h_e_a.py#L15
https://github.com/harfbuzz/harfbuzz/blob/fddeba26e4a0363f7b9ae260ddff2daad6939b34/src/hb-ot-hhea-table.hh#L61

**Comment by anthrotype** [comment]
Interestingly this signed vhea.advanceHeightMax seems to be inherited from the TrueType Reference manual which also has int16:

https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6vhea.html

I still think it doesn't make much sense and OT spec should change to be unsigned for consistency with the hhea.
I don't believe any font deliberately want their advanceHeightMax to be interpreted as a negative integer.

**Comment by PeterCon** [comment]
I don't think it's a good idea to make change a significant format change after the formats have been specified that way for over 25 years (at least TrueType 1.66) if not over 30 years.

I don't think this is the only place in which, by historical accident, two fields that seem like they should be handled the same wrt signed/unsigned are, nonetheless, different.

What would be reasonable, though, would be to use FWORD as the type for appropriate fields in the vhea chapter, rather than int16.

**Comment by PeterCon** [comment]
For #189, signed fields were changed to unsigned, but those were not cases of values measured in design units, but values that inherently could not possibly be negative (numRecords, sizeDeviceRecords).

Hypothetically, one could imagine advanceHeightMax having negative values, except that it's the max of advanceHeight values from the 'vmtx' table, and the type for that field is _unsigned_. In theory, there could be fonts (though maybe not likely) in which the max advanceHeight is > 32,767.

**Comment by PeterCon** [comment]
Given that advanceHeightMax cannot ever be negative, that there's no risk of breaking any existing fonts, and that forward compat risk is low (hypothetical future font could fail in older software, but unlikely), the risk of the proposed change seems manageable.

See [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
