### ISSUE TITLE
[GPOS] Change how PairPos is applied when ValueFormat2 is non-zero

### ISSUE THREAD

**Issue by behdad** [MicrosoftDocs/typography-issues#989]
Currently, the OT spec GPOS section, under PairPos says:

> "valueFormat2 applies to the ValueRecords for the second glyph in each pair. The single ValueFormat field applies to ValueRecords for all second glyphs. If valueFormat2 is set to 0, then the ValueRecords for the second glyph of the pair will be empty, the second glyph is not repositioned, and it becomes the “next” glyph for which a lookup is performed."

This makes it very hard to use valueFormat2 of non-zero. Because if it is, then no pair-positioning will be applied between the second glyph and the glyph after it. Imagine a font that tries to kern the pair "oo" and it wants to split the kern between the two glyphs. It must use both valueFormat1 and valueFormat2; but then in a sequence of "oooooooooooooo", you would get kerning between every other pair only.

This also has implications on kerning in right-to-left scripts. Whereas those scripts can use a simple kerning of just adjusting advance of second glyph, because of this limitation they don't, and instead they adjust both advance and offset of the first glyph instead, which consumes twice the bytes.

So I like to propose changing the specification to always make the second glyph to become the "next" glyph for which the lookup is performed, as currently is the case when valueFormat2 is zero.

Reference:
https://github.com/harfbuzz/harfbuzz/issues/3824
https://github.com/harfbuzz/harfbuzz/pull/3825#issuecomment-1311899482

cc @nedley @PeterCon @jfkthame

**Comment by behdad** [comment]
FWIW, we have seen reports of this misbehavior in actual fonts over the years.

**Comment by behdad** [comment]
> then in a sequence of "oooooooooooooo", you would get kerning between every other pair only.

It's actually worse than that. In a word where every glyph has kerning with "some glyph" in the font, then only every other pair would be kerned.

**Comment by behdad** [comment]
To summarize, IMO, currently ValueFormat2 of non-zero is broken and unreliable for actual use.

**Comment by behdad** [comment]
Note that a similar issue exists with Context lookups; the solution there is to switch to ChainContext and use lookahead instead.

**Comment by behdad** [comment]
Here's a test font. It supports two glyphs `e` and `v`. Both `ev` and `ve` kern, with non-zero valueFormat1 and valueFormat2.

[pairpos.ttf.zip](https://github.com/MicrosoftDocs/typography-issues/files/10006852/pairpos.ttf.zip)

**Comment by behdad** [comment]
In fact, my testing with CoreText with the attached font shows that CoreText implements the behavior I'm proposing in this issue. @nedley can you confirm? In light of that we might change HarfBuzz as well.

**Comment by nedley** [comment]
> @nedley can you confirm?

No, that looks like a bug.

**Comment by PeterCon** [comment]
It's not the case that non-zero valueFormat2 is "is broken and unreliable"; it's just a constraint that non-zero valueFormat2 will advance past both matched input sequence glyphs. 

That, btw, is the normal behaviour for all lookup types; the case of PairPos with valueFormat2 = 0 is the exception:

>A lookup is finished for a glyph after the client has performed the substitution or positioning operation. To move to the “next” glyph, the client skips all the glyphs that participated in the lookup operation: glyphs that were substituted/positioned as well as any other glyphs in the matched input sequence. However, an exception to this rule is made in the case of pair positioning operations (for example,, kerning): the “next” glyph in a sequence may be the second glyph of the input sequence pair, rather than skipping over the entire input sequence. 

This behaviour has been defined this way since OT 1.2 &mdash; over 24 years. While a change could make it possible to do some things that currently wouldn't work, the change could also break an unknown number of fonts, and documents in which they're used, where the current behaviour has been relied upon. This is not a change that should be considered without very careful consideration of back-compat implications.

**Comment by behdad** [comment]
> It's not the case that non-zero valueFormat2 is "is broken and unreliable"; it's just a constraint that non-zero valueFormat2 will advance past both matched input sequence glyphs.

I think both statements can be true at the same time.  For end-users the current behavior is surprising, bordering on broken and unreliable. Kerning seemingly arbitrarily works or doesn't work.

> That, btw, is the normal behaviour for all lookup types; the case of PairPos with valueFormat2 = 0 is the exception:

True. But because of how PairPos operates between two glyphs, it has significant implications here that doesn't have in other cases.  For example, CursivePos reaches out to its previous glyph regardless. The problem we have here is akin to CursivePos only connecting between every other pair of glyphs...

> This is not a change that should be considered without very careful consideration of back-compat implications.

I'm fine closing this as won't-fix. I just wanted to document this and make sure we understand the user implications. The fact that CoreText doesn't implement it came as a surprise discovery.

**Comment by nedley** [comment]
As I said, the CoreText behavior is a bug (and the reasons for it are not worth going into here), but only manifests _for particular PairPos lookups_. Which is all to say, we are fixing the bug and the behavior will once again be to spec.
