### ISSUE TITLE
Alt characters in Times New Roman

### ISSUE THREAD

**Issue by Ruth-E-Shaw** [MicrosoftDocs/typography-issues#99]
I am recreating a number of scientific reports into Times New Roman before the XML conversion. For special characters I am using exclusively Times New Roman characters. HOWEVER, I use a subscript and even a superscript period (.) as in 2.5 (subscript) and I have searched and searched and have not found a subscript, or superscript period.  It is important that my special characters do not lose their formatting, and it is just silly that I cannot find a subscript period. Can you advise? Help? Assist? Make me one?
Many thanks, Ruth Shaw, Senior Typographer and Designer, Cameographics, Belfast Maine 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d43be991-71e4-56f0-fec0-df35d187a0b8
* Version Independent ID: 3ba72d0d-49d0-b525-5a0d-fbe56aa9329c
* Content: [About Microsoft Typography - Typography](https://docs.microsoft.com/en-us/typography/about#feedback)
* Content Source: [typographydocs/about.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/about.md)
* Product: **windows**
* GitHub Login: @mijacobs
* Microsoft Alias: **mijacobs**

**Comment by PiotrGrochowski** [comment]
Unicode unfortunately does not have a superscript full stop or a subscript full stop. Therefore it is impossible to fix this issue.

**Comment by alib-ms** [comment]
I am not aware of a subscript or superscript period in Unicode.
