### ISSUE TITLE
Typo in data type "tableRecord"

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#992]
In the format for TableDirectory, the type for the tableRecords[] field should be "TableRecord".

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6a1bda96-a268-b684-6cea-9b0c7be6f24e
* Version Independent ID: 36485fec-f05d-3984-6da8-ff2dd2799041
* Content: [OpenType font file (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/otff)
* Content Source: [typographydocs/opentype/spec/otff.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/otff.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
See [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
