### ISSUE TITLE
glyph metric values should use FWORD / UFWORD data types

### ISSUE THREAD

**Issue by PeterConstable** [MicrosoftDocs/typography-issues#995]
The correct types are used in the 'hhea' table, but not here.

Same issue applies to the 'vmtx' and 'vhea' tables (see also #985).

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: b569bf16-eea2-0953-3345-024bbd9bd8d4
* Version Independent ID: 5e1b6957-a7c9-fef1-5928-dca56d848565
* Content: [hmtx - Horizontal metrix table (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/hmtx)
* Content Source: [typographydocs/opentype/spec/hmtx.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/hmtx.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
See [OT 1.9.1 alpha](https://docs.microsoft.com/en-us/typography/opentype/otspec191alpha/ot191alpha) for draft revisions addressing this issue.

**Comment by PeterCon** [comment]
This is fixed in OT 1.9.1. See the [OT 1.9.1 beta](https://docs.microsoft.com/en-us/typography/opentype/otspec191/ot191beta) for draft revisions addressing this issue.
