### ISSUE TITLE
RIBBI family model case sensitive?

### ISSUE THREAD

**Issue by moi15moi** [MicrosoftDocs/typography-issues#998]
> Note: When generating family and subfamily names for compatibility with the R/B/I/BI family model, then any subfamily name elements that are not “Regular”, “Bold”, “Italic” or “Oblique” will be moved into the family name.

Does the subfamily name are case sensitive or not?
So, what happen if the subfamily name is "regular"?

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6dac86fb-3792-6630-ade2-32bfc4bba93a
* Version Independent ID: 9de5c023-f363-3e42-43c9-eac7793c8eaa
* Content: [STAT — Style Attributes Table (OpenType 1.9) - Typography](https://learn.microsoft.com/en-us/typography/opentype/spec/stat#axis-value-tables)
* Content Source: [typographydocs/opentype/spec/stat.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/opentype/spec/stat.md)
* Product: **typography**
* GitHub Login: @PeterCon
* Microsoft Alias: **alib**

**Comment by PeterCon** [comment]
Case sensitivity is relevant in string searching or matching. The strings in a font could be lowercase Latin; they could also be in a different language using a script that does not have case. Implementations that re-organize names to fit an R/I/B/BI family model or to fit a WWS family model could search for specific strings like "Regular", though with the STAT table they could also look for certain axis value tables such as one indicating 'wght' = 400, and then find the string referenced by that table. If an implementation does search for specific strings in Latin or another cased script, then it would probably be a good idea to do a case-insensitive search, but that's an implementation decision. The OpenType spec doesn't require implementations to re-organize family & sub-family string elements; it just provides the STAT table format that can be useful for implementations in doing so.

I'll close this at this point. If this hasn't fully answered your question, please re-open with additional clarification.
